Repository stashapp/stash, pull requests merged in 2019-11, with the labels that each got.

#175 Use custom.css in same path as config file
  pkg/manager/config/config.go
Labels: improvement

#176 Fix ffmpeg error output
  pkg/ffmpeg/encoder.go
  pkg/ffmpeg/encoder_marker.go
  pkg/ffmpeg/encoder_scene_preview_chunk.go
  pkg/ffmpeg/encoder_screenshot.go
Labels: bug

#178 Add configurable maximum transcode sizes
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/api/routes_scene.go
  pkg/ffmpeg/encoder_transcode.go
  pkg/manager/config/config.go
  pkg/manager/task_transcode.go
  ui/v2/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2/src/components/Shared/FolderSelect/FolderSelect.tsx
Labels: improvement

#181 Stop tasks and show task progress
  graphql/documents/queries/settings/metadata.graphql
  graphql/documents/subscriptions.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/metadata.graphql
  pkg/api/resolver_query_metadata.go
  pkg/api/resolver_subscription_metadata.go
  pkg/manager/job_status.go
  pkg/manager/manager.go
  pkg/manager/manager_subscription_handler.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_generate_markers.go
  ui/v2/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2/src/core/StashService.ts
Labels: feature, improvement

#179 More performer filter criteria
  graphql/schema/types/filters.graphql
  pkg/models/querybuilder_performer.go
  pkg/models/querybuilder_sql.go
  ui/v2/src/components/list/AddFilter.tsx
  ui/v2/src/models/list-filter/criteria/criterion.ts
  ui/v2/src/models/list-filter/criteria/utils.ts
  ui/v2/src/models/list-filter/filter.ts
Labels: improvement

#174 Performers, Tags and Studio from scene filename
  graphql/documents/queries/scene.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/scene.graphql
  pkg/api/resolver_query_find_scene.go
  pkg/manager/filename_parser.go
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_tag.go
  ui/v2/src/components/scenes/SceneFilenameParser.tsx
  ui/v2/src/components/select/FilterSelect.tsx
  ui/v2/src/core/StashService.ts
  ui/v2/src/index.scss
Labels: improvement

#188 Calculate and print job totals for scan and generate tasks
  pkg/manager/manager_tasks.go
  pkg/manager/task_generate_markers.go
  pkg/manager/task_scan.go
  pkg/manager/task_transcode.go
Labels: feature

#205 Fix panic on import with existing scene
  pkg/manager/task_import.go
Labels: bug

#183 Make sort filter queries for name case insensitive
  pkg/models/querybuilder_sql.go
Labels: bug, improvement

#212 Update cross-compile.sh for new docker tag.
  scripts/cross-compile.sh
Labels: improvement

#215 Fix Windows database.Reset
  pkg/database/database.go
  pkg/manager/task_import.go
Labels: bug

#216 Add develop branch releases and display version tag
  .travis.yml
  graphql/documents/queries/misc.graphql
  graphql/schema/types/version.graphql
  pkg/api/resolver.go
  pkg/api/server.go
  scripts/cross-compile.sh
  ui/v2/src/components/Settings/SettingsAboutPanel.tsx
Labels: feature

#217 Refresh config when paths change
  pkg/api/resolver_mutation_configure.go
  pkg/api/server.go
  pkg/manager/manager.go
Labels: feature

#218 Use justified layout for wall
  ui/v2/package.json
  ui/v2/src/components/Wall/WallItem.tsx
  ui/v2/src/components/Wall/WallPanel.tsx
  ui/v2/src/index.scss
  ui/v2/src/models/justified-layout.d.ts
  ui/v2/yarn.lock
Labels: improvement

#203 Generic performer scrapers
  graphql/documents/queries/scrapers/scrapers.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/scraped-performer.graphql
  graphql/schema/types/scraper.graphql
  pkg/api/resolver.go
  pkg/api/resolver_query_scraper.go
  pkg/manager/config/config.go
  pkg/manager/manager.go
  pkg/scraper/freeones.go
  pkg/scraper/scrapers.go
  ui/v2/src/components/Shared/DetailsEditNavbar.tsx
  ui/v2/src/components/performers/PerformerDetails/Performer.tsx
  ui/v2/src/components/select/FreeOnesPerformerSuggest.tsx
  ui/v2/src/components/select/ScrapePerformerSuggest.tsx
  ui/v2/src/core/StashService.ts
  ui/v2/src/index.scss
Labels: feature

#223 fix builds
  .travis.yml
  scripts/cross-compile.sh
Labels: bug, improvement

#165 Upload pull request builds to transfer.sh
  .travis.yml
  scripts/upload-pull-request.sh
Labels: help wanted, improvement, investigate, question

#190 [WIP] README: Added additional notes to dev install
  README.md
Labels: improvement

#230 Loop and autostart flags. Save interface options
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
  ui/v2/src/components/Settings/SettingsInterfacePanel.tsx
  ui/v2/src/components/Wall/WallItem.tsx
  ui/v2/src/components/scenes/ScenePlayer/ScenePlayer.tsx
  ui/v2/src/hooks/LocalForage.ts
  ui/v2/src/hooks/VideoHover.ts
Labels: feature, improvement

#237 Fix marker page error
  ui/v2/src/components/Wall/WallItem.tsx
Labels: bug

#231 [BUG] Fix previews generation bug
  pkg/ffmpeg/encoder_scene_preview_chunk.go
Labels: bug
