Repository stashapp/stash, pull requests merged in 2019-10, with the labels that each got.

#134 Fix scheme detection when reverse proxy is used
  pkg/api/server.go
Labels: Hacktoberfest, bug

#133 Consider performer aliases when scraping
  pkg/scraper/freeones.go
Labels: Hacktoberfest

#126 fix isMissing date filter
  go.mod
  go.sum
  pkg/models/querybuilder_scene.go
Labels: bug

#136 Make title from file metadata optional
  graphql/documents/queries/settings/metadata.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/metadata.graphql
  pkg/api/resolver_query_metadata.go
  pkg/ffmpeg/ffprobe.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_scan.go
  pkg/models/generated_exec.go
  pkg/models/generated_models.go
  ui/v2/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2/src/core/StashService.ts
  ui/v2/src/core/generated-graphql.tsx
Labels: Hacktoberfest

#137 Allow unsetting of rating, studio, gallery
  pkg/api/resolver_mutation_scene.go
  pkg/manager/task_scan.go
  pkg/models/model_scene.go
  pkg/models/querybuilder_gallery.go
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_sql.go
  ui/v2/src/components/scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2/src/components/scenes/SceneDetails/SceneMarkersPanel.tsx
  ui/v2/src/components/select/FilterSelect.tsx
  ui/v2/src/components/select/ValidGalleriesSelect.tsx
  ui/v2/src/utils/table.tsx
Labels: Hacktoberfest, improvement

#141 Add scene list view
  ui/v2/src/components/scenes/SceneList.tsx
  ui/v2/src/components/scenes/SceneListTable.tsx
Labels: Hacktoberfest, feature, improvement

#140 Reset to first page when changing sort by
  ui/v2/src/hooks/ListHook.tsx
Labels: Hacktoberfest, feature, improvement

#142 Add performer list view.
  ui/v2/src/components/Stats.tsx
  ui/v2/src/components/performers/PerformerList.tsx
  ui/v2/src/components/performers/PerformerListTable.tsx
  ui/v2/src/components/scenes/SceneListTable.tsx
  ui/v2/src/index.scss
Labels: Hacktoberfest, feature, improvement

#85 Basic password security #3
  go.mod
  go.sum
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/api/server.go
  pkg/manager/config/config.go
  ui/v2/src/components/Settings/SettingsConfigurationPanel.tsx
  vendor/golang.org/x/crypto/bcrypt/base64.go
  vendor/golang.org/x/crypto/bcrypt/bcrypt.go
  vendor/golang.org/x/crypto/blowfish/block.go
  vendor/golang.org/x/crypto/blowfish/cipher.go
  vendor/golang.org/x/crypto/blowfish/const.go
  vendor/modules.txt
Labels: Hacktoberfest, feature, improvement, investigate

#143 Freeones fixes
  pkg/scraper/freeones.go
Labels: Hacktoberfest, bug

#145 Scan screens
  pkg/manager/task_scan.go
Labels: Hacktoberfest, improvement

#110 Display hash and build time at startup and in about page
  Makefile
  graphql/documents/queries/misc.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/version.graphql
  pkg/api/resolver.go
  pkg/api/server.go
  scripts/cross-compile.sh
  scripts/getDate.go
  ui/v2/src/components/Settings/SettingsAboutPanel.tsx
  ui/v2/src/core/StashService.ts
Labels: Hacktoberfest, feature, improvement

#109 Generate performer checksum from name instead of image. Use default performer image
  graphql/documents/mutations/performer.graphql
  graphql/documents/mutations/studio.graphql
  graphql/schema/types/performer.graphql
  graphql/schema/types/studio.graphql
  pkg/api/images.go
  pkg/api/resolver_mutation_performer.go
  pkg/api/resolver_mutation_studio.go
  pkg/api/server.go
  pkg/manager/task_import.go
  pkg/models/model_studio.go
  pkg/utils/crypto.go
  static/performer/NoName01.png
  static/performer/NoName02.png
  static/performer/NoName03.png
  static/performer/NoName04.png
  static/performer/NoName05.png
  static/performer/NoName06.png
  static/performer/NoName07.png
  static/performer/NoName08.png
  static/performer/NoName09.png
  static/performer/NoName10.png
  static/performer/NoName11.png
  static/performer/NoName12.png
  static/performer/NoName13.png
  static/performer/NoName14.png
  static/performer/NoName15.png
  static/performer/NoName16.png
  static/performer/NoName17.png
  static/performer/NoName18.png
  static/performer/NoName19.png
  static/performer/NoName20.png
  static/performer/NoName21.png
  static/performer/NoName22.png
  static/performer/NoName23.png
  static/performer/NoName24.png
  static/performer/NoName25.png
  static/performer/NoName26.png
  static/performer/NoName27.png
  static/performer/NoName28.png
  static/performer/NoName29.png
  static/performer/NoName30.png
  static/performer/NoName31.png
  static/performer/NoName32.png
  static/performer/NoName33.png
  static/performer/NoName34.png
  static/performer/NoName35.png
  static/performer/NoName36.png
  static/performer/NoName37.png
  static/performer/NoName38.png
  static/performer/NoName39.png
  static/performer/NoName40.png
Labels: feature, improvement

#151 Add logs to Logs page
  graphql/documents/data/log.graphql
  graphql/documents/queries/misc.graphql
  graphql/documents/subscriptions.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/logging.graphql
  pkg/api/resolver_query_logs.go
  pkg/api/resolver_subscription_logging.go
  pkg/logger/logger.go
  ui/v2/package.json
  ui/v2/src/components/Settings/SettingsLogsPanel.tsx
  ui/v2/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2/src/components/Stats.tsx
  ui/v2/src/core/StashService.ts
  ui/v2/src/index.scss
  ui/v2/yarn.lock
Labels: Hacktoberfest, feature, improvement

#154 Add logging options
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/api/server.go
  pkg/logger/logger.go
  pkg/manager/config/config.go
  pkg/manager/manager.go
  ui/v2/src/components/Settings/SettingsConfigurationPanel.tsx
Labels: Hacktoberfest, improvement, investigate

#159 Remove packr2 go:generate from main #153
  main.go
Labels: bug, improvement

#161 Use wss if origin uses https
  ui/v2/src/core/StashService.ts
Labels: bug

#92 Bulk update scenes
  graphql/documents/mutations/scene.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/scene.graphql
  pkg/api/resolver.go
  pkg/api/resolver_mutation_scene.go
  ui/v2/src/components/list/ListFilter.tsx
  ui/v2/src/components/scenes/SceneCard.tsx
  ui/v2/src/components/scenes/SceneList.tsx
  ui/v2/src/components/scenes/SceneSelectedOptions.tsx
  ui/v2/src/components/select/FilterMultiSelect.tsx
  ui/v2/src/core/StashService.ts
  ui/v2/src/hooks/ListHook.tsx
  ui/v2/src/index.scss
Labels: feature, improvement

#157 Add query options for tags, performers, studios #29
  graphql/schema/types/filters.graphql
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_scene_marker.go
  pkg/models/querybuilder_sql.go
  ui/v2/src/components/Stats.tsx
  ui/v2/src/components/list/AddFilter.tsx
  ui/v2/src/models/list-filter/criteria/criterion.ts
  ui/v2/src/models/list-filter/criteria/performers.ts
  ui/v2/src/models/list-filter/criteria/studios.ts
  ui/v2/src/models/list-filter/criteria/tags.ts
  ui/v2/src/models/list-filter/filter.ts
Labels: Hacktoberfest, improvement

#164 Scene filename to metadata parser
  graphql/documents/mutations/scene.graphql
  graphql/documents/queries/scene.graphql
  graphql/schema/schema.graphql
  pkg/api/resolver_mutation_scene.go
  pkg/api/resolver_query_find_scene.go
  pkg/database/database.go
  pkg/models/querybuilder_scene.go
  ui/v2/src/App.tsx
  ui/v2/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2/src/components/scenes/SceneFilenameParser.tsx
  ui/v2/src/core/StashService.ts
  ui/v2/src/index.scss
Labels: feature

#167 Invalidate specific query results after mutations
  ui/v2/src/core/StashService.ts
Labels: improvement

#169 Check if scenes are in the library path when cleaning
  pkg/manager/task_clean.go
Labels: improvement
