Repository stashapp/stash, pull requests merged in 2019-12, with the labels that each got.

#204 Add scene auto-tagging from filename
  graphql/documents/queries/settings/metadata.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/metadata.graphql
  pkg/api/resolver_query_metadata.go
  pkg/manager/job_status.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_autotag.go
  pkg/manager/task_autotag_test.go
  pkg/models/model_scene.go
  pkg/models/querybuilder_joins.go
  pkg/models/querybuilder_scene.go
  ui/v2/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2/src/components/Shared/DetailsEditNavbar.tsx
  ui/v2/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2/src/components/Tags/TagList.tsx
  ui/v2/src/components/performers/PerformerDetails/Performer.tsx
  ui/v2/src/core/StashService.ts
Labels: feature, investigate

#229 Fix performers/studio/tags not updating in Scene Filename Parser
  ui/v2/src/components/scenes/SceneFilenameParser.tsx
Labels: bug

#241 Fix video.js current time
  ui/v2/src/components/scenes/ScenePlayer/ScenePlayer.tsx
Labels: bug

#242 Marker time input
  ui/v2/src/components/Shared/DurationInput.tsx
  ui/v2/src/components/scenes/SceneDetails/SceneMarkersPanel.tsx
Labels: improvement

#246 Allow pasting image into performer/studio
  ui/v2/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2/src/components/performers/PerformerDetails/Performer.tsx
Labels: feature

#232 Scene ui improvements
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
  ui/v2/src/components/Settings/SettingsInterfacePanel.tsx
  ui/v2/src/components/list/AddFilter.tsx
  ui/v2/src/components/list/ListFilter.tsx
  ui/v2/src/components/scenes/SceneCard.tsx
  ui/v2/src/components/scenes/SceneList.tsx
  ui/v2/src/hooks/ListHook.tsx
  ui/v2/src/index.scss
  ui/v2/src/utils/text.ts
  ui/v2/src/utils/zoom.ts
Labels: improvement

#255 Add Play random button to scenes and scene markers page
  ui/v2/src/components/list/ListFilter.tsx
  ui/v2/src/components/scenes/SceneDetails/Scene.tsx
  ui/v2/src/components/scenes/SceneList.tsx
  ui/v2/src/components/scenes/SceneMarkerList.tsx
  ui/v2/src/components/scenes/ScenePlayer/ScenePlayer.tsx
  ui/v2/src/core/StashService.ts
  ui/v2/src/hooks/ListHook.tsx
Labels: feature

#257 Make top level navbar responsive
  ui/v2/src/App.tsx
  ui/v2/src/components/MainNavbar.tsx
  ui/v2/src/components/Sidebar.tsx
  ui/v2/src/index.scss
Labels: improvement

#256 Change scraper config to yaml
  go.mod
  graphql/documents/queries/scrapers/scrapers.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/scraper.graphql
  pkg/api/resolver_query_scraper.go
  pkg/scraper/config.go
  pkg/scraper/freeones.go
  pkg/scraper/scrapers.go
  pkg/scraper/script.go
  ui/v2/src/components/Shared/DetailsEditNavbar.tsx
  ui/v2/src/components/performers/PerformerDetails/Performer.tsx
  ui/v2/src/core/StashService.ts
Labels: improvement

#259 Make scene metadata from file metadata optional
  graphql/schema/types/metadata.graphql
  pkg/api/resolver_query_metadata.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_scan.go
  ui/v2/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
Labels: improvement

#262 Allow uploading of custom scene covers
  graphql/documents/mutations/scene.graphql
  graphql/schema/types/scene.graphql
  pkg/api/resolver_mutation_scene.go
  pkg/manager/scene_screenshot.go
  ui/v2/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2/src/components/performers/PerformerDetails/Performer.tsx
  ui/v2/src/components/scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2/src/index.scss
  ui/v2/src/utils/image.tsx
Labels: feature

#263 Fix vtt for chapter display in scene players
  pkg/api/routes_scene.go
  pkg/utils/vtt.go
  ui/v2/src/components/scenes/ScenePlayer/ScenePlayer.tsx
Labels: bug

#236 Add scene metadata scraping functionality
  graphql/documents/data/scrapers.graphql
  graphql/documents/queries/scrapers/scrapers.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/scraper.graphql
  pkg/api/resolver_query_scraper.go
  pkg/scraper/config.go
  pkg/scraper/freeones.go
  pkg/scraper/scrapers.go
  pkg/scraper/script.go
  ui/v2/src/components/scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2/src/core/StashService.ts
Labels: feature

#265 Add "Open Random" to performer list
  ui/v2/src/components/performers/PerformerList.tsx
  ui/v2/src/core/StashService.ts
Labels: improvement

#268 jwplayer transcode seek support. Remove video.js
  ui/v2/package.json
  ui/v2/public/jwplayer/jwplayer.controls.js
  ui/v2/public/jwplayer/jwplayer.core.controls.html5.js
  ui/v2/public/jwplayer/jwplayer.core.controls.js
  ui/v2/public/jwplayer/jwplayer.core.controls.polyfills.html5.js
  ui/v2/public/jwplayer/jwplayer.core.controls.polyfills.js
  ui/v2/public/jwplayer/jwplayer.core.js
  ui/v2/public/jwplayer/jwplayer.js
  ui/v2/public/jwplayer/polyfills.webvtt.js
  ui/v2/public/jwplayer/provider.html5.js
  ui/v2/public/jwplayer/vttparser.js
  ui/v2/src/components/scenes/ScenePlayer/ScenePlayer.tsx
  ui/v2/src/components/scenes/helpers.tsx
  ui/v2/yarn.lock
Labels: improvement

#253 Add exclude file from scan feature
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
  pkg/manager/manager_tasks.go
  pkg/manager/manager_tasks_test.go
  ui/v2/src/components/Settings/SettingsConfigurationPanel.tsx
Labels: feature

#272 Fix transcoded video player position
  ui/v2/src/components/scenes/ScenePlayer/ScenePlayer.tsx
Labels: bug

#275 Fixed minor typo bug for scene list thumbnails
  ui/v2/src/components/scenes/SceneListTable.tsx
Labels: bug

#269 Add stash scraper type
  go.mod
  go.sum
  gqlgen.yml
  pkg/api/resolver_query_find_scene.go
  pkg/models/model_scene.go
  pkg/models/model_scraped_item.go
  pkg/scraper/config.go
  pkg/scraper/scrapers.go
  pkg/scraper/stash.go
  ui/v2/src/components/scenes/SceneDetails/SceneEditPanel.tsx
  vendor/github.com/shurcooL/graphql/.travis.yml
  vendor/github.com/shurcooL/graphql/LICENSE
  vendor/github.com/shurcooL/graphql/README.md
  vendor/github.com/shurcooL/graphql/doc.go
  vendor/github.com/shurcooL/graphql/graphql.go
  vendor/github.com/shurcooL/graphql/ident/ident.go
  vendor/github.com/shurcooL/graphql/internal/jsonutil/graphql.go
  vendor/github.com/shurcooL/graphql/query.go
  vendor/github.com/shurcooL/graphql/scalar.go
  vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go
  vendor/modules.txt
Labels: feature

#274 Added exclude patterns support for Clean Task
  pkg/manager/exclude_files.go
  pkg/manager/exclude_files_test.go
  pkg/manager/manager_tasks.go
  pkg/manager/manager_tasks_test.go
  pkg/manager/task_clean.go
  ui/v2/src/components/Settings/SettingsConfigurationPanel.tsx
Labels: improvement
