Repository stashapp/stash, pull requests merged in 2020-07, with the labels that each got.

#642 Scene selection improvements
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Scenes/styles.scss
Labels: improvement

#637 Add keyboard shortcuts
  README.md
  ui/v2.5/package.json
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/Help/Manual.tsx
  ui/v2.5/src/components/Help/styles.scss
  ui/v2.5/src/components/List/AddFilter.tsx
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/MainNavbar.tsx
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerList.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkersPanel.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Scenes/SceneMarkerList.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/docs/en/KeyboardShortcuts.md
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/src/utils/focus.ts
  ui/v2.5/src/utils/index.ts
  ui/v2.5/yarn.lock
Labels: feature

#644 Scrape dialog
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Shared/Modal.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/index.scss
  ui/v2.5/src/utils/editabletext.tsx
Labels: feature

#653 Fix travis not validating UI
  .travis.yml
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
Labels: bug

#641 Add grid view, image to tag
  graphql/documents/data/tag.graphql
  graphql/documents/mutations/tag.graphql
  graphql/documents/queries/misc.graphql
  graphql/documents/queries/tag.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/tag.graphql
  pkg/api/context_keys.go
  pkg/api/resolver_model_tag.go
  pkg/api/resolver_mutation_tag.go
  pkg/api/resolver_query_find_tag.go
  pkg/api/routes_studio.go
  pkg/api/routes_tag.go
  pkg/api/server.go
  pkg/api/urlbuilders/tag.go
  pkg/database/database.go
  pkg/database/migrations/11_tag_image.up.sql
  pkg/logger/logger.go
  pkg/manager/json_utils.go
  pkg/manager/jsonschema/mappings.go
  pkg/manager/jsonschema/tag.go
  pkg/manager/paths/paths_json.go
  pkg/manager/tag.go
  pkg/manager/task_export.go
  pkg/manager/task_import.go
  pkg/models/model_tag.go
  pkg/models/querybuilder_scene_test.go
  pkg/models/querybuilder_sql.go
  pkg/models/querybuilder_tag.go
  pkg/models/querybuilder_tag_test.go
  pkg/models/setup_test.go
  pkg/utils/image.go
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/MainNavbar.tsx
  ui/v2.5/src/components/Scenes/SceneMarkerList.tsx
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/components/Settings/SettingsLogsPanel.tsx
  ui/v2.5/src/components/Tags/TagCard.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagMarkersPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagScenesPanel.tsx
  ui/v2.5/src/components/Tags/TagList.tsx
  ui/v2.5/src/components/Tags/Tags.tsx
  ui/v2.5/src/components/Tags/styles.scss
  ui/v2.5/src/components/Wall/styles.scss
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/docs/en/KeyboardShortcuts.md
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/src/index.scss
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
  ui/v2.5/src/models/list-filter/criteria/utils.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: feature

#657 Fix tag query performance problems
  pkg/manager/config/config.go
  pkg/models/querybuilder_sql.go
  pkg/models/querybuilder_tag.go
  pkg/models/querybuilder_tag_test.go
  ui/v2.5/src/models/list-filter/filter.ts
Labels: bug

#661 Use referer on xpath getImage, apply printHTML to subscraper also
  pkg/scraper/image.go
  pkg/scraper/xpath.go
Labels: improvement

#650 Scan for files with ALLCAPS extensions
  pkg/manager/manager_tasks.go
  ui/v2.5/src/components/Changelog/versions/v030.tsx
Labels: improvement

#666 Support random performer sort
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/models/list-filter/filter.ts
Labels: improvement

#670 Fix performer view width
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
Labels: bug

#672 Generate content for specific scenes
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  graphql/schema/types/metadata.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_mutation_metadata.go
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
  pkg/manager/generator_preview.go
  pkg/manager/generator_sprite.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_generate_gallery_thumbs.go
  pkg/manager/task_generate_markers.go
  pkg/manager/task_generate_preview.go
  pkg/manager/task_generate_sprite.go
  pkg/manager/task_transcode.go
  pkg/models/querybuilder_gallery.go
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_scene_marker.go
  pkg/utils/string_collections.go
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneGenerateDialog.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/GenerateButton.tsx
  ui/v2.5/src/hooks/ListHook.tsx
Labels: feature

#678 Don't show dialog when setting front movie image
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/utils/image.tsx
Labels: bug

#681 Fix FormattedDate timezone bug
  ui/v2.5/src/components/Changelog/Version.tsx
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneDetailPanel.tsx
Labels: bug

#616 Refactor xpath scraper code. Add fixed and map
  go.sum
  pkg/api/resolver_mutation_scraper.go
  pkg/api/resolver_query_scraper.go
  pkg/manager/manager.go
  pkg/scraper/action.go
  pkg/scraper/config.go
  pkg/scraper/freeones.go
  pkg/scraper/image.go
  pkg/scraper/mapped.go
  pkg/scraper/mapped_test.go
  pkg/scraper/scrapers.go
  pkg/scraper/script.go
  pkg/scraper/stash.go
  pkg/scraper/xpath.go
  pkg/scraper/xpath_test.go
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/docs/en/Scraping.md
Labels: improvement

#682 Fix performer card name truncation
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/index.scss
Labels: bug

#609 Transcode stream refactor
  graphql/documents/data/config.graphql
  graphql/documents/data/scene.graphql
  graphql/documents/queries/scene.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/config.graphql
  graphql/schema/types/scene.graphql
  pkg/api/resolver_model_scene.go
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/api/resolver_query_scene.go
  pkg/api/routes_scene.go
  pkg/api/urlbuilders/scene.go
  pkg/ffmpeg/encoder.go
  pkg/ffmpeg/encoder_transcode.go
  pkg/ffmpeg/ffprobe.go
  pkg/ffmpeg/hls.go
  pkg/ffmpeg/stream.go
  pkg/manager/config/config.go
  pkg/manager/scene.go
  pkg/manager/task_transcode.go
  pkg/manager/utils.go
  pkg/utils/byterange.go
  ui/v2.5/public/jwplayer/jwplayer.controls.js
  ui/v2.5/public/jwplayer/jwplayer.core.controls.html5.js
  ui/v2.5/public/jwplayer/jwplayer.core.controls.js
  ui/v2.5/public/jwplayer/jwplayer.core.controls.polyfills.html5.js
  ui/v2.5/public/jwplayer/jwplayer.core.controls.polyfills.js
  ui/v2.5/public/jwplayer/jwplayer.core.js
  ui/v2.5/public/jwplayer/jwplayer.js
  ui/v2.5/public/jwplayer/notice.txt
  ui/v2.5/public/jwplayer/polyfills.intersection-observer.js
  ui/v2.5/public/jwplayer/polyfills.webvtt.js
  ui/v2.5/public/jwplayer/provider.html5.js
  ui/v2.5/public/jwplayer/vttparser.js
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/utils/jwplayer.ts
Labels: improvement

#673 Allow customisation of preview generation
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  graphql/schema/types/metadata.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/api/routes_scene.go
  pkg/ffmpeg/encoder_scene_preview_chunk.go
  pkg/manager/config/config.go
  pkg/manager/generator.go
  pkg/manager/generator_preview.go
  pkg/manager/manager.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_generate_preview.go
  pkg/utils/file.go
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/Scenes/SceneGenerateDialog.tsx
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/index.scss
Labels: improvement

#685 Fix potential sprite generation segfault
  pkg/manager/task_generate_sprite.go
Labels: bug

#686 Fix missing video player poster
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: bug

#689 Fix marker seeking
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: bug

#690 Fix tag delete
  ui/v2.5/src/components/Tags/TagList.tsx
  ui/v2.5/src/core/StashService.ts
Labels: bug
