Repository stashapp/stash, pull requests merged in 2020-08, with the labels that each got.

#695 add non-binary option for gender
  graphql/schema/types/performer.graphql
  ui/v2.5/src/core/StashService.ts
Labels: improvement

#704 Fix scraping error
  pkg/scraper/url.go
Labels: bug

#698 Fix markers not autoplaying
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: bug

#663 Allow adding performer & studio from scenes page
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/core/StashService.ts
Labels: feature

#667 Add oshash support
  graphql/documents/data/config.graphql
  graphql/documents/data/scene-slim.graphql
  graphql/documents/data/scene.graphql
  graphql/documents/mutations/metadata.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/config.graphql
  graphql/schema/types/scene.graphql
  main.go
  pkg/api/migrate.go
  pkg/api/resolver_model_scene.go
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_mutation_metadata.go
  pkg/api/resolver_mutation_scene.go
  pkg/api/resolver_query_configuration.go
  pkg/api/resolver_query_find_scene.go
  pkg/api/routes_scene.go
  pkg/database/database.go
  pkg/database/migrations/12_oshash.up.sql
  pkg/manager/checksum.go
  pkg/manager/config/config.go
  pkg/manager/job_status.go
  pkg/manager/jsonschema/scene.go
  pkg/manager/manager_tasks.go
  pkg/manager/post_migrate.go
  pkg/manager/scene.go
  pkg/manager/task_autotag_test.go
  pkg/manager/task_clean.go
  pkg/manager/task_export.go
  pkg/manager/task_generate_markers.go
  pkg/manager/task_generate_preview.go
  pkg/manager/task_generate_screenshot.go
  pkg/manager/task_generate_sprite.go
  pkg/manager/task_import.go
  pkg/manager/task_migrate_hash.go
  pkg/manager/task_scan.go
  pkg/manager/task_transcode.go
  pkg/models/model_scene.go
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_scene_test.go
  pkg/models/setup_test.go
  pkg/scraper/stash.go
  pkg/utils/oshash.go
  scripts/test_oshash.go
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/components/Settings/styles.scss
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/docs/en/Configuration.md
Labels: feature

#713 Improve oshash collision detection and logging
  pkg/manager/task_scan.go
Labels: improvement

#651 Add plugin tasks
  go.mod
  go.sum
  graphql/documents/mutations/plugins.graphql
  graphql/documents/queries/plugins.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/plugin.graphql
  pkg/api/resolver_mutation_plugin.go
  pkg/api/resolver_query_plugin.go
  pkg/api/server.go
  pkg/api/session.go
  pkg/manager/config/config.go
  pkg/manager/job_status.go
  pkg/manager/manager.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_plugin.go
  pkg/plugin/args.go
  pkg/plugin/common/doc.go
  pkg/plugin/common/log/log.go
  pkg/plugin/common/msg.go
  pkg/plugin/common/rpc.go
  pkg/plugin/config.go
  pkg/plugin/convert.go
  pkg/plugin/examples/README.md
  pkg/plugin/examples/common/graphql.go
  pkg/plugin/examples/goraw/goraw.yml
  pkg/plugin/examples/goraw/main.go
  pkg/plugin/examples/gorpc/gorpc.yml
  pkg/plugin/examples/gorpc/main.go
  pkg/plugin/log.go
  pkg/plugin/plugins.go
  pkg/plugin/raw.go
  pkg/plugin/rpc.go
  pkg/plugin/task.go
  pkg/plugin/util/client.go
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/Help/Manual.tsx
  ui/v2.5/src/components/Settings/Settings.tsx
  ui/v2.5/src/components/Settings/SettingsPluginsPanel.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/docs/en/Plugins.md
  vendor/github.com/natefinch/pie/.gitignore
  vendor/github.com/natefinch/pie/LICENSE
  vendor/github.com/natefinch/pie/README.md
  vendor/github.com/natefinch/pie/doc.go
  vendor/github.com/natefinch/pie/pie.go
  vendor/modules.txt
Labels: feature

#716 Don't play video after failover
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: bug

#718 Fix sprite vtt panic
  pkg/api/routes_scene.go
Labels: bug

#717 Add JSON scrape support
  go.mod
  go.sum
  pkg/scraper/action.go
  pkg/scraper/config.go
  pkg/scraper/json.go
  pkg/scraper/json_test.go
  pkg/scraper/stash.go
  pkg/scraper/url.go
  pkg/scraper/xpath.go
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/docs/en/Scraping.md
  vendor/github.com/tidwall/gjson/.travis.yml
  vendor/github.com/tidwall/gjson/LICENSE
  vendor/github.com/tidwall/gjson/README.md
  vendor/github.com/tidwall/gjson/SYNTAX.md
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/gjson/go.mod
  vendor/github.com/tidwall/gjson/go.sum
  vendor/github.com/tidwall/gjson/logo.png
  vendor/github.com/tidwall/match/.travis.yml
  vendor/github.com/tidwall/match/LICENSE
  vendor/github.com/tidwall/match/README.md
  vendor/github.com/tidwall/match/match.go
  vendor/github.com/tidwall/pretty/.travis.yml
  vendor/github.com/tidwall/pretty/LICENSE
  vendor/github.com/tidwall/pretty/README.md
  vendor/github.com/tidwall/pretty/pretty.go
  vendor/modules.txt
Labels: feature

#709 Implement scraping movies by URL
  gqlgen.yml
  graphql/documents/data/scrapers.graphql
  graphql/documents/queries/scrapers/scrapers.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/scraped-movie.graphql
  graphql/schema/types/scraper.graphql
  pkg/api/resolver_query_scraper.go
  pkg/api/urlbuilders/movie.go
  pkg/models/model_scraped_item.go
  pkg/scraper/action.go
  pkg/scraper/config.go
  pkg/scraper/image.go
  pkg/scraper/json.go
  pkg/scraper/mapped.go
  pkg/scraper/scrapers.go
  pkg/scraper/script.go
  pkg/scraper/stash.go
  pkg/scraper/xpath.go
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieScrapeDialog.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/docs/en/Scraping.md
Labels: feature

#721 Make scene movie number freely editable
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMovieTable.tsx
Labels: improvement

#722 Clear image
  graphql/schema/types/filters.graphql
  pkg/api/images.go
  pkg/api/resolver_mutation_movie.go
  pkg/api/resolver_mutation_performer.go
  pkg/api/resolver_mutation_studio.go
  pkg/api/resolver_mutation_tag.go
  pkg/api/routes_movie.go
  pkg/api/routes_performer.go
  pkg/api/routes_studio.go
  pkg/api/routes_tag.go
  pkg/models/querybuilder_movies.go
  pkg/models/querybuilder_performer.go
  pkg/models/querybuilder_studio.go
  pkg/utils/crypto.go
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Shared/DetailsEditNavbar.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
  ui/v2.5/src/models/list-filter/criteria/utils.ts
  ui/v2.5/src/models/list-filter/filter.ts
Labels: improvement

#711 scraper/mapped: Add feetToCm post process.
  pkg/scraper/mapped.go
  pkg/scraper/mapped_test.go
  pkg/scraper/xpath_test.go
  ui/v2.5/src/docs/en/Scraping.md
Labels: improvement

#732 Fix import performers/movies/studios with no image
  pkg/manager/task_import.go
Labels: bug

#726 UI improvements
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Scenes/EditScenesDialog.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Shared/MultiSet.tsx
  ui/v2.5/src/hooks/ListHook.tsx
Labels: improvement

#742 Upgrade doublestar to v2.0.1
  go.mod
  go.sum
  pkg/manager/generator_sprite.go
  pkg/manager/manager_tasks.go
  vendor/github.com/bmatcuk/doublestar/go.mod
  vendor/github.com/bmatcuk/doublestar/v2/.gitignore
  vendor/github.com/bmatcuk/doublestar/v2/.travis.yml
  vendor/github.com/bmatcuk/doublestar/v2/LICENSE
  vendor/github.com/bmatcuk/doublestar/v2/README.md
  vendor/github.com/bmatcuk/doublestar/v2/UPGRADING.md
  vendor/github.com/bmatcuk/doublestar/v2/doublestar.go
  vendor/github.com/bmatcuk/doublestar/v2/go.mod
  vendor/modules.txt
Labels: bug

#737 Cross compile for armv7/armv8, raise raspi variant to armv6 (only)
  .dockerignore
  .travis.yml
  docker/build/x86_64/Dockerfile
  docker/compiler/Dockerfile
  docker/compiler/Makefile
  scripts/cross-compile.sh
Labels: improvement

#745 SafeMove
  pkg/ffmpeg/encoder.go
  pkg/manager/generator_preview.go
  pkg/manager/generator_sprite.go
  pkg/manager/task_generate_markers.go
  pkg/manager/task_scan.go
  pkg/manager/task_transcode.go
  pkg/utils/file.go
Labels: improvement

#764 Fix scene-card jumping
  ui/v2.5/src/index.scss
Labels: bug

#772 Make travis build and push docker images
  .travis.yml
  docker/ci/x86_64/Dockerfile
  docker/ci/x86_64/README.md
  docker/ci/x86_64/docker_push.sh
Labels: bug

#774 Add cbz to supported extensions as gallery
  pkg/manager/manager_tasks.go
  ui/v2.5/src/components/Changelog/versions/v030.tsx
Labels: improvement

#778 Fix age filtering regression
  pkg/models/querybuilder_performer_test.go
  pkg/models/querybuilder_scene_test.go
  pkg/models/querybuilder_sql.go
  pkg/models/setup_test.go
  ui/v2.5/src/hooks/ListHook.tsx
Labels: bug
