Repository stashapp/stash, pull requests merged in 2020-12, with the labels that each got.

#934 Add support for setting cookies in the scraper
  pkg/scraper/config.go
  pkg/scraper/cookies.go
  pkg/scraper/url.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/docs/en/Scraping.md
Labels: feature

#969 Add missing gallery components
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerGalleriesPanel.tsx
  ui/v2.5/src/components/Settings/SettingsScrapersPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioGalleriesPanel.tsx
Labels: improvement

#978 Fix manual tables
  ui/v2.5/package.json
  ui/v2.5/src/components/Shared/MarkdownPage.tsx
  ui/v2.5/yarn.lock
Labels: bug

#976 Use changesets correctly when updating objects
  graphql/documents/mutations/gallery.graphql
  graphql/documents/mutations/image.graphql
  graphql/documents/mutations/movie.graphql
  graphql/documents/mutations/performer.graphql
  graphql/documents/mutations/scene.graphql
  graphql/documents/mutations/studio.graphql
  graphql/documents/mutations/tag.graphql
  pkg/api/changeset_translator.go
  pkg/api/resolver_mutation_gallery.go
  pkg/api/resolver_mutation_image.go
  pkg/api/resolver_mutation_movie.go
  pkg/api/resolver_mutation_performer.go
  pkg/api/resolver_mutation_scene.go
  pkg/api/resolver_mutation_studio.go
  pkg/api/resolver_mutation_tag.go
  pkg/models/mocks/PerformerReaderWriter.go
  pkg/models/model_performer.go
  pkg/models/performer.go
  pkg/models/querybuilder_performer.go
  pkg/performer/import.go
  pkg/performer/import_test.go
  ui/v2.5/src/components/Galleries/EditGalleriesDialog.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Images/EditImagesDialog.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Scenes/EditScenesDialog.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tagger/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/queries.ts
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/core/StashService.ts
Labels: improvement

#986 Fix studio logo getting nulled when editing a studio
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
Labels: bug

#974 Implement user customizable menu items
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/MainNavbar.tsx
  ui/v2.5/src/components/Settings/Settings.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/CheckboxGroup.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
Labels: improvement

#990 Fix scene gallery selection
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Shared/Select.tsx
Labels: bug

#989 Fix login redirect to remember current page
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/core/createClient.ts
Labels: bug

#996 Add includes/excludes modifiers to path filter
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
Labels: improvement

#1000 Fix broken isMissing filters
  pkg/models/querybuilder_image.go
  pkg/models/querybuilder_performer.go
  pkg/models/querybuilder_scene.go
Labels: bug

#988 Organised flag
  graphql/documents/data/gallery-slim.graphql
  graphql/documents/data/gallery.graphql
  graphql/documents/data/image-slim.graphql
  graphql/documents/data/image.graphql
  graphql/documents/data/scene-slim.graphql
  graphql/documents/data/scene.graphql
  graphql/documents/mutations/gallery.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/gallery.graphql
  graphql/schema/types/image.graphql
  graphql/schema/types/scene.graphql
  pkg/api/resolver_mutation_gallery.go
  pkg/api/resolver_mutation_image.go
  pkg/api/resolver_mutation_scene.go
  pkg/database/database.go
  pkg/database/migrations/16_organized_flag.up.sql
  pkg/gallery/export.go
  pkg/gallery/export_test.go
  pkg/gallery/import.go
  pkg/gallery/import_test.go
  pkg/image/export.go
  pkg/image/export_test.go
  pkg/image/import.go
  pkg/manager/jsonschema/gallery.go
  pkg/manager/jsonschema/image.go
  pkg/manager/jsonschema/scene.go
  pkg/manager/task_autotag.go
  pkg/manager/task_autotag_test.go
  pkg/models/model_gallery.go
  pkg/models/model_image.go
  pkg/models/model_scene.go
  pkg/models/modelstest/sql.go
  pkg/models/querybuilder_gallery.go
  pkg/models/querybuilder_image.go
  pkg/models/querybuilder_scene.go
  pkg/scene/export.go
  pkg/scene/export_test.go
  pkg/scene/import.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Galleries/EditGalleriesDialog.tsx
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Images/EditImagesDialog.tsx
  ui/v2.5/src/components/Images/ImageCard.tsx
  ui/v2.5/src/components/Images/ImageDetails/Image.tsx
  ui/v2.5/src/components/Scenes/EditScenesDialog.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/OrganizedButton.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/locale/en-GB.json
  ui/v2.5/src/locale/en-US.json
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/organized.ts
  ui/v2.5/src/models/list-filter/criteria/utils.ts
  ui/v2.5/src/models/list-filter/filter.ts
Labels: feature

#1004 Fix galleryCreate mutation
  graphql/documents/mutations/gallery.graphql
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/core/StashService.ts
Labels: bug

#827 Add Mouse Click support for the CDP scraper
  pkg/scraper/config.go
  pkg/scraper/url.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/docs/en/Scraping.md
Labels: improvement

#994 Fix integer overflow for scene size on 32bit systems
  graphql/schema/types/stats.graphql
  pkg/api/resolver.go
  pkg/database/database.go
  pkg/database/migrations/17_reset_scene_size.up.sql
  pkg/manager/task_scan.go
  pkg/models/querybuilder_image.go
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_sql.go
  ui/v2.5/src/components/Changelog/versions/v050.md
Labels: bug

#998 Fix scene file name parser update
  pkg/api/changeset_translator.go
  ui/v2.5/src/components/SceneFilenameParser/SceneParserRow.tsx
Labels: bug

#1008 Add gallery wall view, and new lightbox
  ui/v2.5/package.json
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Galleries/GalleryList.tsx
  ui/v2.5/src/components/Galleries/GalleryViewer.tsx
  ui/v2.5/src/components/Galleries/GalleryWallCard.tsx
  ui/v2.5/src/components/Galleries/styles.scss
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Shared/RatingStars.tsx
  ui/v2.5/src/components/Shared/index.ts
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/Lightbox/context.tsx
  ui/v2.5/src/hooks/Lightbox/hooks.ts
  ui/v2.5/src/hooks/Lightbox/index.ts
  ui/v2.5/src/hooks/Lightbox/lightbox.scss
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/src/hooks/index.ts
  ui/v2.5/src/index.scss
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/yarn.lock
Labels: improvement

#1020 Fix performer page lightbox
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
Labels: bug

#1014 Various bugfixes for scene tagger
  pkg/manager/config/config.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Settings/StashBoxConfiguration.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/components/Tagger/Config.tsx
  ui/v2.5/src/components/Tagger/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/Tagger.tsx
  ui/v2.5/src/components/Tagger/constants.ts
  ui/v2.5/src/hooks/LocalForage.ts
  ui/v2.5/src/hooks/index.ts
Labels: bug, improvement
