Repository stashapp/stash, pull requests merged in 2020-05, with the labels that each got.

#526 Add is-missing tags filter
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_scene_test.go
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
Labels: improvement

#496 Add a cache for gallery thumbnails
  go.mod
  go.sum
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  graphql/schema/types/metadata.graphql
  pkg/api/cache_thumbs.go
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_mutation_metadata.go
  pkg/api/resolver_query_configuration.go
  pkg/api/routes_gallery.go
  pkg/api/server.go
  pkg/manager/manager_tasks.go
  pkg/manager/paths/paths_gallery.go
  pkg/manager/task_clean.go
  pkg/manager/task_generate_gallery_thumbs.go
  pkg/manager/task_scan.go
  pkg/models/model_gallery.go
  pkg/models/querybuilder_scene.go
  pkg/utils/file.go
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/GenerateButton.tsx
  vendor/github.com/dustin/go-humanize/.travis.yml
  vendor/github.com/dustin/go-humanize/LICENSE
  vendor/github.com/dustin/go-humanize/README.markdown
  vendor/github.com/dustin/go-humanize/big.go
  vendor/github.com/dustin/go-humanize/bigbytes.go
  vendor/github.com/dustin/go-humanize/bytes.go
  vendor/github.com/dustin/go-humanize/comma.go
  vendor/github.com/dustin/go-humanize/commaf.go
  vendor/github.com/dustin/go-humanize/ftoa.go
  vendor/github.com/dustin/go-humanize/humanize.go
  vendor/github.com/dustin/go-humanize/number.go
  vendor/github.com/dustin/go-humanize/ordinals.go
  vendor/github.com/dustin/go-humanize/si.go
  vendor/github.com/dustin/go-humanize/times.go
  vendor/modules.txt
Labels: feature

#528 Fix edge case preview generation, tweak preview generation preset
  pkg/ffmpeg/encoder_scene_preview_chunk.go
Labels: bug

#534 Make auto tagger matching more flexible
  pkg/manager/task_autotag.go
  pkg/manager/task_autotag_test.go
Labels: bug

#535 Fix 0 undefined library size on empty db
  pkg/models/querybuilder_scene.go
Labels: bug

#533 Add details to is-missing filter
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
Labels: improvement

#541 Fix setting stash directory with spaces
  pkg/api/server.go
Labels: bug

#542 Change builtin freeones scraper to community yml
  pkg/scraper/config.go
  pkg/scraper/freeones.go
  pkg/scraper/scrapers.go
Labels: bug

#549 Fix redirect loops in login, migrate and setup pages
  pkg/api/server.go
Labels: bug

#550 Fix xpath comments text
  pkg/scraper/xpath.go
Labels: bug

#531 Changelog
  ui/v2.5/package.json
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/Version.tsx
  ui/v2.5/src/components/Changelog/styles.scss
  ui/v2.5/src/components/Changelog/versions/index.ts
  ui/v2.5/src/components/Changelog/versions/v010.tsx
  ui/v2.5/src/components/Changelog/versions/v011.tsx
  ui/v2.5/src/components/Changelog/versions/v020.tsx
  ui/v2.5/src/components/Stats.tsx
  ui/v2.5/src/hooks/LocalForage.ts
  ui/v2.5/src/hooks/index.ts
  ui/v2.5/src/index.scss
  ui/v2.5/src/locale/de.json
  ui/v2.5/src/locale/en.json
  ui/v2.5/yarn.lock
Labels: feature

#554 Include scrapers in subdirectories
  pkg/scraper/scrapers.go
Labels: improvement

#555 Add debug logging for xpath scraping
  pkg/scraper/xpath.go
Labels: improvement

#560 Encode pasted images to jpegs
  ui/v2.5/package.json
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/utils/image.tsx
  ui/v2.5/yarn.lock
Labels: improvement

#563 Set performers/tags/studios in parser
  ui/v2.5/src/components/SceneFilenameParser/SceneParserRow.tsx
Labels: bug

#564 Fix sceneTags filter selection
  ui/v2.5/src/components/List/AddFilter.tsx
  ui/v2.5/src/components/Shared/Select.tsx
Labels: bug

#570 Speed up tag count queries
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_scene_marker.go
  pkg/models/querybuilder_scene_marker_test.go
Labels: improvement

#556 Change scrape matching (studio, movies, tag, performers) to case insensitive
  pkg/manager/filename_parser.go
  pkg/manager/task_import.go
  pkg/models/querybuilder_movies.go
  pkg/models/querybuilder_performer.go
  pkg/models/querybuilder_studio.go
  pkg/models/querybuilder_tag.go
  pkg/models/querybuilder_tag_test.go
  pkg/models/setup_test.go
  pkg/scraper/scrapers.go
Labels: improvement

#510 Selectable wall preview type
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  graphql/schema/types/metadata.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_mutation_metadata.go
  pkg/api/resolver_query_configuration.go
  pkg/ffmpeg/encoder_scene_preview_chunk.go
  pkg/ffmpeg/ffprobe.go
  pkg/manager/config/config.go
  pkg/manager/generator_preview.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_generate_preview.go
  pkg/utils/file.go
  ui/v2.5/src/components/Settings/SettingsInterfacePanel.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/GenerateButton.tsx
  ui/v2.5/src/components/Wall/WallItem.tsx
  ui/v2.5/src/components/Wall/WallPanel.tsx
  ui/v2.5/src/components/Wall/styles.scss
Labels: improvement

#580 Fix date rendering for missing date values
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneDetailPanel.tsx
  ui/v2.5/src/utils/text.ts
Labels: bug
