Repository stashapp/stash, pull requests merged in 2020-02, with the labels that each got.

#340 Fix paging not working
  ui/v2/src/hooks/ListHook.tsx
Labels: bug

#335 Fix to avoid creating generated folder inside data folder.
  docker/production/docker-compose.yml
Labels: bug

#334 Add O-counter
  graphql/documents/data/scene-slim.graphql
  graphql/documents/data/scene.graphql
  graphql/documents/mutations/scene.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/scene.graphql
  pkg/api/resolver_mutation_scene.go
  pkg/database/database.go
  pkg/database/migrations/3_o_counter.up.sql
  pkg/models/model_scene.go
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_sql.go
  ui/v2/src/components/scenes/OCounterButton.tsx
  ui/v2/src/components/scenes/SceneCard.tsx
  ui/v2/src/components/scenes/SceneDetails/Scene.tsx
  ui/v2/src/components/scenes/SceneDetails/SceneDetailPanel.tsx
  ui/v2/src/core/StashService.ts
  ui/v2/src/index.scss
  ui/v2/src/models/list-filter/criteria/criterion.ts
  ui/v2/src/models/list-filter/criteria/utils.ts
  ui/v2/src/models/list-filter/filter.ts
  ui/v2/src/utils/icons.tsx
Labels: feature

#345 Prepare for 0.1.0 release
  .travis.yml
  Makefile
  docker/production/x86_64/Dockerfile
  pkg/api/check_version.go
  scripts/cross-compile.sh
  scripts/upload-pull-request.sh
Labels: improvement

#355 Make performer image contain
  ui/v2/src/index.scss
Labels: bug

#350 Fix URL update not reflected in list hook
  ui/v2/src/hooks/ListHook.tsx
  ui/v2/src/models/list-filter/filter.ts
Labels: bug

#343 [Feature] Adding Feature.md/BugFix.md Pull Request Template.
  .github/FUNDING.yml
  .github/PULL_REQUEST_TEMPLATE/BugFix.md
  .github/PULL_REQUEST_TEMPLATE/Feature.md
  docs/CONTRIBUTING.md
Labels: feature, help wanted

#374 Fix panic when version check times out
  pkg/api/check_version.go
Labels: bug

#373 Fix scene selection not working
  ui/v2/src/hooks/ListHook.tsx
Labels: bug
