Repository stashapp/stash, pull requests merged in 2020-03, with the labels that each got.

#387 Use parameter binding for all queries
  pkg/models/querybuilder_gallery.go
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_scene_marker.go
  pkg/models/querybuilder_sql.go
  pkg/models/querybuilder_studio.go
  pkg/models/querybuilder_tag.go
Labels: improvement

#388 Fix performer height filter error
  pkg/models/querybuilder_performer.go
Labels: bug

#370 Add image scraping support
  .gitattributes
  go.mod
  go.sum
  graphql/documents/data/scrapers.graphql
  graphql/schema/types/scraped-performer.graphql
  graphql/schema/types/scraper.graphql
  pkg/models/model_scraped_item.go
  pkg/scraper/image.go
  pkg/scraper/scrapers.go
  pkg/scraper/stash.go
  pkg/scraper/xpath.go
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/index.scss
  ui/v2/src/components/performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2/src/components/scenes/SceneDetails/SceneEditPanel.tsx
  vendor/github.com/jinzhu/copier/Guardfile
  vendor/github.com/jinzhu/copier/License
  vendor/github.com/jinzhu/copier/README.md
  vendor/github.com/jinzhu/copier/copier.go
  vendor/github.com/jinzhu/copier/wercker.yml
Labels: feature

#376 Generate cover image
  graphql/documents/mutations/metadata.graphql
  graphql/documents/mutations/scene.graphql
  graphql/documents/queries/settings/metadata.graphql
  graphql/schema/schema.graphql
  pkg/api/resolver_mutation_metadata.go
  pkg/api/resolver_mutation_scene.go
  pkg/api/resolver_query_metadata.go
  pkg/ffmpeg/encoder_screenshot.go
  pkg/manager/manager_tasks.go
  pkg/manager/screenshot.go
  pkg/manager/task_generate_screenshot.go
  pkg/manager/task_scan.go
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerOperationsPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneOperationsPanel.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/GenerateButton.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagList.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2/src/components/Settings/SettingsTasksPanel/GenerateButton.tsx
  ui/v2/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2/src/components/Tags/TagList.tsx
  ui/v2/src/components/performers/PerformerDetails/PerformerOperationsPanel.tsx
  ui/v2/src/components/scenes/SceneDetails/Scene.tsx
  ui/v2/src/components/scenes/SceneDetails/SceneOperationsPanel.tsx
  ui/v2/src/core/StashService.ts
Labels: feature

#396 Fix marker time setting in v2.5 UI
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkerForm.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkersPanel.tsx
Labels: bug

#395 Fix error when viewing scenes related to objects with illegal characters in name
  .gitattributes
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneOperationsPanel.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/performers.ts
  ui/v2.5/src/models/list-filter/criteria/studios.ts
  ui/v2.5/src/models/list-filter/criteria/tags.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/models/list-filter/types.ts
  ui/v2/src/models/list-filter/criteria/criterion.ts
  ui/v2/src/models/list-filter/criteria/movies.ts
  ui/v2/src/models/list-filter/criteria/performers.ts
  ui/v2/src/models/list-filter/criteria/studios.ts
  ui/v2/src/models/list-filter/criteria/tags.ts
  ui/v2/src/models/list-filter/filter.ts
  ui/v2/src/models/list-filter/types.ts
Labels: bug

#405 Autoassociate galleries to scenes when scanning
  pkg/manager/manager_tasks.go
  pkg/manager/task_scan.go
Labels: feature

#411 Fix random sort not changing seed
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2/src/models/list-filter/filter.ts
Labels: bug

#397 Port Movies UI to v2.5
  .gitignore
  graphql/schema/types/movie.graphql
  pkg/api/resolver_model_movie.go
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/List/AddFilter.tsx
  ui/v2.5/src/components/MainNavbar.tsx
  ui/v2.5/src/components/Movies/MovieCard.tsx
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieScenesPanel.tsx
  ui/v2.5/src/components/Movies/MovieList.tsx
  ui/v2.5/src/components/Movies/Movies.tsx
  ui/v2.5/src/components/Movies/styles.scss
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMoviePanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMovieTable.tsx
  ui/v2.5/src/components/Scenes/SceneListTable.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Shared/DetailsEditNavbar.tsx
  ui/v2.5/src/components/Shared/ImageInput.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Shared/TagLink.tsx
  ui/v2.5/src/components/Stats.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/core/generated-graphql.tsx
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/src/index.scss
  ui/v2.5/src/locale/de.json
  ui/v2.5/src/locale/en.json
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
  ui/v2.5/src/models/list-filter/criteria/movies.ts
  ui/v2.5/src/models/list-filter/criteria/utils.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/models/list-filter/types.ts
  ui/v2.5/src/utils/navigation.ts
  ui/v2.5/src/utils/table.tsx
Labels: feature

#409 Configurable scraper user agent string
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
  pkg/scraper/config.go
  pkg/scraper/image.go
  pkg/scraper/xpath.go
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2/src/components/Settings/SettingsConfigurationPanel.tsx
Labels: improvement

#412 Add modes for performer/tag for bulk scene editing
  graphql/documents/mutations/scene.graphql
  graphql/schema/types/scene.graphql
  pkg/api/resolver_mutation_scene.go
  ui/v2.5/src/components/Scenes/SceneSelectedOptions.tsx
  ui/v2.5/src/components/Shared/MultiSet.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2/src/components/scenes/SceneSelectedOptions.tsx
  ui/v2/src/components/select/FilterMultiSet.tsx
Labels: improvement

#371 Add gender support for performer
  graphql/documents/data/performer-slim.graphql
  graphql/documents/data/performer.graphql
  graphql/documents/mutations/performer.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/performer.graphql
  pkg/api/resolver_model_performer.go
  pkg/api/resolver_mutation_performer.go
  pkg/database/database.go
  pkg/database/migrations/5_performer_gender.down.sql
  pkg/database/migrations/5_performer_gender.up.sql
  pkg/manager/jsonschema/performer.go
  pkg/manager/task_export.go
  pkg/manager/task_import.go
  pkg/models/model_performer.go
  pkg/models/querybuilder_performer.go
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/gender.ts
  ui/v2.5/src/models/list-filter/criteria/utils.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2/src/components/performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2/src/core/StashService.ts
  ui/v2/src/models/list-filter/criteria/criterion.ts
  ui/v2/src/models/list-filter/criteria/gender.ts
  ui/v2/src/models/list-filter/criteria/utils.ts
  ui/v2/src/models/list-filter/filter.ts
Labels: feature
