Repository stashapp/stash, pull requests merged in 2020-09, with the labels that each got.

#781 Allow updating tag name capitalization
  pkg/api/resolver_mutation_tag.go
  pkg/manager/tag.go
Labels: bug

#784 Fix erroneous pending thumbnail on wall items
  ui/v2.5/src/components/Wall/WallItem.tsx
Labels: bug

#802 Persist studio/gallery/marker list filters
  ui/v2.5/src/components/Galleries/GalleryList.tsx
  ui/v2.5/src/components/Scenes/SceneMarkerList.tsx
  ui/v2.5/src/components/Studios/StudioList.tsx
Labels: bug

#792 Library updates
  ui/v2.5/.eslintrc.json
  ui/v2.5/codegen.yml
  ui/v2.5/package.json
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Galleries/Gallery.tsx
  ui/v2.5/src/components/Help/Manual.tsx
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/SceneFilenameParser/SceneFilenameParser.tsx
  ui/v2.5/src/components/SceneFilenameParser/SceneParserRow.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneListTable.tsx
  ui/v2.5/src/components/Settings/Settings.tsx
  ui/v2.5/src/components/Settings/SettingsPluginsPanel.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/core/createClient.ts
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/src/hooks/LocalForage.ts
  ui/v2.5/src/hooks/Toast.tsx
  ui/v2.5/src/index.tsx
  ui/v2.5/src/utils/focus.ts
  ui/v2.5/yarn.lock
Labels: improvement

#793 Update gallery view layout and switch libraries
  ui/v2.5/package.json
  ui/v2.5/src/components/Galleries/Gallery.tsx
  ui/v2.5/src/components/Galleries/GalleryViewer.tsx
  ui/v2.5/src/components/Galleries/styles.scss
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/yarn.lock
Labels: improvement

#807 Fix date timezone bug
  ui/v2.5/src/utils/text.ts
Labels: bug

#804 Hotfix for theme preview bug
  ui/v2.5/src/index.scss
Labels: bug

#795 Add filter country when click the performer flag
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/models/list-filter/criteria/country.ts
  ui/v2.5/src/utils/navigation.ts
Labels: improvement

#799 Add gallery icon in "scene card" and "scene list table"
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneListTable.tsx
Labels: improvement

#800 Add filter on Movie section "Is Missing is scenes"
  pkg/models/querybuilder_movies.go
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
Labels: improvement

#748 Config for stash-box instances
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  graphql/schema/types/stash-box.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/components/Settings/StashBoxConfiguration.tsx
Labels: feature

#803 Add 0.4.0 changelog, convert to md
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/index.ts
  ui/v2.5/src/components/Changelog/versions/v010.md
  ui/v2.5/src/components/Changelog/versions/v011.md
  ui/v2.5/src/components/Changelog/versions/v011.tsx
  ui/v2.5/src/components/Changelog/versions/v020.md
  ui/v2.5/src/components/Changelog/versions/v021.md
  ui/v2.5/src/components/Changelog/versions/v021.tsx
  ui/v2.5/src/components/Changelog/versions/v030.md
  ui/v2.5/src/components/Changelog/versions/v040.md
  ui/v2.5/src/components/Help/Manual.tsx
  ui/v2.5/src/components/Shared/MarkdownPage.tsx
Labels: improvement

#812 Add partial import functionality
  graphql/documents/mutations/metadata.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/metadata.graphql
  pkg/api/resolver_mutation_metadata.go
  pkg/gallery/import.go
  pkg/gallery/import_test.go
  pkg/manager/import.go
  pkg/manager/jsonschema/utils.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_import.go
  pkg/models/gallery.go
  pkg/models/join.go
  pkg/models/json_time.go
  pkg/models/mocks/GalleryReaderWriter.go
  pkg/models/mocks/JoinReaderWriter.go
  pkg/models/mocks/MovieReaderWriter.go
  pkg/models/mocks/PerformerReaderWriter.go
  pkg/models/mocks/SceneMarkerReaderWriter.go
  pkg/models/mocks/SceneReaderWriter.go
  pkg/models/mocks/StudioReaderWriter.go
  pkg/models/mocks/TagReaderWriter.go
  pkg/models/model_movie.go
  pkg/models/model_performer.go
  pkg/models/model_studio.go
  pkg/models/model_tag.go
  pkg/models/movie.go
  pkg/models/performer.go
  pkg/models/querybuilder_movies.go
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_studio.go
  pkg/models/scene.go
  pkg/models/scene_marker.go
  pkg/models/sqlite_date.go
  pkg/models/studio.go
  pkg/models/tag.go
  pkg/movie/import.go
  pkg/movie/import_test.go
  pkg/performer/export_test.go
  pkg/performer/import.go
  pkg/performer/import_test.go
  pkg/scene/import.go
  pkg/scene/import_test.go
  pkg/scene/marker_import.go
  pkg/scene/marker_import_test.go
  pkg/studio/import.go
  pkg/studio/import_test.go
  pkg/tag/import.go
  pkg/tag/import_test.go
  ui/v2.5/package.json
  ui/v2.5/src/components/Changelog/versions/v040.md
  ui/v2.5/src/components/Settings/SettingsTasksPanel/ImportDialog.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/components/Shared/Modal.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/core/createClient.ts
  ui/v2.5/yarn.lock
Labels: feature
