Repository stashapp/stash, pull requests merged in 2020-10, with the labels that each got.

#814 Added ffmpeg/ffprobe permission correction code for linux/osx
  pkg/ffmpeg/downloader.go
Labels: bug

#824 Fix ffmpeg/ffprobe downloads
  pkg/ffmpeg/downloader.go
Labels: bug

#832 Convert scraped movie create data
  ui/v2.5/src/components/Changelog/versions/v040.md
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
Labels: bug

#835 Parent studio link in studio page
  ui/v2.5/src/components/Changelog/versions/v040.md
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
Labels: improvement

#840 Fix filter layout on devices
  ui/v2.5/src/components/List/ListFilter.tsx
Labels: bug

#836 Prevent invalid date tag in video file from aborting scan
  pkg/ffmpeg/ffprobe.go
  pkg/manager/task_scan.go
  pkg/models/json_time.go
  ui/v2.5/src/components/Changelog/versions/v040.md
Labels: bug

#838 Add collapse button to scene page
  ui/v2.5/src/components/Changelog/versions/v040.md
  ui/v2.5/src/components/ScenePlayer/styles.scss
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
Labels: improvement

#834 Path filter for scenes and galleries
  graphql/schema/types/filters.graphql
  pkg/models/querybuilder_gallery.go
  pkg/models/querybuilder_gallery_test.go
  pkg/models/querybuilder_performer.go
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_scene_test.go
  pkg/models/querybuilder_sql.go
  ui/v2.5/src/components/Changelog/versions/v040.md
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/utils.ts
  ui/v2.5/src/models/list-filter/filter.ts
Labels: improvement

#833 Add scraper list page
  ui/v2.5/src/components/Changelog/versions/v040.md
  ui/v2.5/src/components/Settings/Settings.tsx
  ui/v2.5/src/components/Settings/SettingsScrapersPanel.tsx
  ui/v2.5/src/components/Settings/styles.scss
  ui/v2.5/src/core/StashService.ts
Labels: feature

#846 Fix clean and scan bugs
  pkg/image/image.go
  pkg/manager/task_scan.go
Labels: bug

#849 Show static image if wall video missing
  ui/v2.5/src/components/Changelog/versions/v040.md
  ui/v2.5/src/components/Wall/WallItem.tsx
Labels: improvement

#853 Add image-count sorting, and image deletion on gallery deletion
  pkg/api/resolver_mutation_gallery.go
  pkg/models/querybuilder_gallery.go
  ui/v2.5/src/components/Galleries/DeleteGalleriesDialog.tsx
  ui/v2.5/src/components/Shared/Modal.tsx
  ui/v2.5/src/models/list-filter/filter.ts
Labels: improvement

#855 Sort images in galleries by path
  pkg/models/querybuilder_image.go
Labels: bug

#852 Treat empty string columns as missing
  pkg/models/querybuilder_image.go
  pkg/models/querybuilder_performer.go
  pkg/models/querybuilder_scene.go
  ui/v2.5/src/components/Changelog/versions/v040.md
Labels: bug

#858 Add shim for String.prototype.replaceAll
  ui/v2.5/package.json
  ui/v2.5/src/App.tsx
  ui/v2.5/src/globals.d.ts
  ui/v2.5/yarn.lock
Labels: bug

#857 Fix loading issue in galleries and redirect on gallery creation
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryImagesPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/Image.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Shared/ErrorMessage.tsx
  ui/v2.5/src/components/Shared/index.ts
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/core/StashService.ts
Labels: improvement

#864 Persist gallery list state
  ui/v2.5/src/components/Galleries/Galleries.tsx
Labels: bug

#847 Image improvements
  graphql/documents/queries/misc.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/stats.graphql
  pkg/api/resolver.go
  pkg/manager/manager_tasks.go
  pkg/models/querybuilder_gallery.go
  pkg/models/querybuilder_gallery_test.go
  pkg/models/querybuilder_image.go
  pkg/models/querybuilder_image_test.go
  pkg/models/querybuilder_scene.go
  pkg/utils/file.go
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerImagesPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScenesPanel.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Stats.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioImagesPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioScenesPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagImagesPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagScenesPanel.tsx
  ui/v2.5/src/core/performers.ts
  ui/v2.5/src/core/studios.ts
  ui/v2.5/src/core/tags.ts
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
  ui/v2.5/src/models/list-filter/criteria/resolution.ts
  ui/v2.5/src/models/list-filter/criteria/utils.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/utils/text.ts
Labels: improvement

#871 Fix scan issue when encountering invalid symlinks
  go.mod
  go.sum
  pkg/manager/task_scan.go
  pkg/utils/symwalk.go
  vendor/github.com/facebookgo/symwalk/license
  vendor/github.com/facebookgo/symwalk/patents
  vendor/github.com/facebookgo/symwalk/readme.md
  vendor/github.com/facebookgo/symwalk/walk.go
  vendor/modules.txt
Labels: bug

#862 Add gallery scraping
  graphql/documents/data/scrapers.graphql
  graphql/documents/queries/scrapers/scrapers.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/scraper.graphql
  pkg/api/resolver_query_scraper.go
  pkg/models/model_scraped_item.go
  pkg/scraper/action.go
  pkg/scraper/config.go
  pkg/scraper/json.go
  pkg/scraper/mapped.go
  pkg/scraper/scrapers.go
  pkg/scraper/script.go
  pkg/scraper/stash.go
  pkg/scraper/stashbox/graphql/generated_client.go
  pkg/scraper/url.go
  pkg/scraper/xpath.go
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
  ui/v2.5/src/core/StashService.ts
Labels: feature

#841 Make performer name mandatory in graphQL (#273)
  graphql/documents/mutations/performer.graphql
  graphql/schema/types/performer.graphql
  pkg/api/resolver_mutation_performer.go
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
Labels: bug

#875 Use temp redirects for setup
  pkg/api/server.go
Labels: bug

#878 Query url parameters
  pkg/scraper/config.go
  pkg/scraper/json.go
  pkg/scraper/query_url.go
  pkg/scraper/url.go
  pkg/scraper/xpath.go
  ui/v2.5/src/components/Changelog/versions/v040.md
  ui/v2.5/src/docs/en/Scraping.md
Labels: improvement

#880 Fix new performer scraping
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
Labels: bug

#790 Added streaming quality options
  pkg/api/routes_scene.go
  pkg/ffmpeg/stream.go
  pkg/manager/scene.go
  ui/v2.5/src/components/Changelog/versions/v040.md
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: feature

#826 Video filters and transforms
  ui/v2.5/.stylelintrc
  ui/v2.5/src/components/Changelog/versions/v040.md
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneVideoFilterPanel.tsx
  ui/v2.5/src/components/Scenes/styles.scss
Labels: feature

#881 Update freeones scraper
  pkg/scraper/freeones.go
Labels: bug

#889 Wire up Tagger set tags checkbox
  ui/v2.5/src/components/Tagger/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/Tagger.tsx
Labels: bug

#891 Cache generated exclude regex
  pkg/manager/exclude_files.go
  pkg/manager/task_scan.go
Labels: improvement

#879 Add basic i18n implementation
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/locale/en-GB.json
  ui/v2.5/src/locale/en-US.json
  ui/v2.5/src/locale/index.ts
Labels: improvement

#887 Don't set default studio image
  pkg/api/resolver_mutation_studio.go
  ui/v2.5/src/components/Changelog/versions/v040.md
Labels: bug

#905 Fix recursive loop when filtering performer with country is null
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
Labels: bug

#904 Add page sizes up to 1000
  pkg/models/querybuilder_sql.go
  ui/v2.5/src/components/Changelog/versions/v040.md
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/SceneFilenameParser/ParserInput.tsx
Labels: improvement

#907 Fix image thumbnail display
  ui/v2.5/src/components/Images/styles.scss
  ui/v2.5/src/index.scss
Labels: bug

#873 Add selection and export for all list pages
  pkg/gallery/export.go
  pkg/manager/task_export.go
  pkg/models/image.go
  pkg/models/mocks/ImageReaderWriter.go
  pkg/models/mocks/SceneReaderWriter.go
  pkg/models/scene.go
  ui/v2.5/src/components/Changelog/versions/v040.md
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Galleries/GalleryExportDialog.tsx
  ui/v2.5/src/components/Galleries/GalleryList.tsx
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/components/Movies/MovieCard.tsx
  ui/v2.5/src/components/Movies/MovieList.tsx
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Performers/PerformerList.tsx
  ui/v2.5/src/components/Scenes/SceneExportDialog.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Shared/BasicCard.tsx
  ui/v2.5/src/components/Shared/ExportDialog.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/components/Studios/StudioCard.tsx
  ui/v2.5/src/components/Studios/StudioList.tsx
  ui/v2.5/src/components/Tags/TagCard.tsx
  ui/v2.5/src/components/Tags/TagList.tsx
  ui/v2.5/src/core/StashService.ts
Labels: feature
