Repository stashapp/stash, pull requests merged in 2020-04, with the labels that each got.

#421 Fix to allow scene to be removed when attached to a movie
  pkg/models/querybuilder_scene.go
Labels: bug

#431 Make ethnicity freetext and fix freeones ethnicity panic
  pkg/scraper/freeones.go
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2/src/components/performers/PerformerDetails/PerformerDetailsPanel.tsx
Labels: improvement

#429 [Feature] Add image count to gallery list
  ui/v2.5/src/components/Galleries/GalleryList.tsx
  ui/v2/src/components/Galleries/GalleryList.tsx
Labels: feature

#435 Fix movie filter on v2.5 UI
  ui/v2.5/src/hooks/ListHook.tsx
Labels: bug

#432 Add scene rating to scene filename parser
  .gitattributes
  pkg/manager/filename_parser.go
  ui/v2.5/src/components/SceneFilenameParser/ParserField.ts
  ui/v2.5/src/components/SceneFilenameParser/ParserInput.tsx
  ui/v2.5/src/components/SceneFilenameParser/SceneFilenameParser.tsx
  ui/v2.5/src/components/SceneFilenameParser/SceneParserRow.tsx
  ui/v2.5/src/components/SceneFilenameParser/styles.scss
  ui/v2.5/src/index.scss
  ui/v2/src/components/scenes/SceneFilenameParser.tsx
Labels: improvement

#384 Add detection of container/video_codec/audio_codec compatibility for live file streaming or transcoding
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/api/routes_scene.go
  pkg/database/database.go
  pkg/database/migrations/6_scenes_format.up.sql
  pkg/ffmpeg/encoder_transcode.go
  pkg/ffmpeg/ffprobe.go
  pkg/ffmpeg/media_detection.go
  pkg/manager/config/config.go
  pkg/manager/jsonschema/scene.go
  pkg/manager/task_export.go
  pkg/manager/task_import.go
  pkg/manager/task_scan.go
  pkg/manager/task_transcode.go
  pkg/manager/utils.go
  pkg/models/model_scene.go
  pkg/models/querybuilder_scene.go
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2/src/components/Settings/SettingsConfigurationPanel.tsx
Labels: improvement

#446 Delete marker preview on marker change or delete
  pkg/api/resolver_mutation_scene.go
  pkg/manager/scene.go
Labels: bug

#449 Prefer modified performer image over scraped one
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
Labels: improvement

#453 Don't redirect login to migrate page
  pkg/api/server.go
Labels: bug

#447 Performer and Movie UI fixes and improvements
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkerForm.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel.tsx
  ui/v2.5/src/components/Shared/DurationInput.tsx
  ui/v2.5/src/utils/duration.ts
  ui/v2.5/src/utils/editabletext.tsx
  ui/v2.5/src/utils/index.ts
  ui/v2.5/src/utils/table.tsx
  ui/v2.5/src/utils/text.ts
Labels: improvement

#448 Include gender in performer scraper results
  graphql/documents/data/scrapers.graphql
  graphql/schema/types/scraped-performer.graphql
  graphql/schema/types/scraper.graphql
  pkg/models/model_scraped_item.go
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/core/StashService.ts
Labels: bug

#465 Fix studio edit name
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
Labels: bug

#461 Fix tag creation
  ui/v2.5/src/components/Shared/Select.tsx
Labels: bug

#459 Fix log population
  ui/v2.5/src/components/Settings/SettingsLogsPanel.tsx
Labels: bug

#460 Add slim endpoints for entities to speed up filters
  graphql/documents/queries/misc.graphql
  graphql/schema/schema.graphql
  pkg/api/resolver_query_find_movie.go
  pkg/api/resolver_query_find_performer.go
  pkg/api/resolver_query_find_studio.go
  pkg/api/resolver_query_find_tag.go
  pkg/database/database.go
  pkg/database/migrations/7_performer_optimization.up.sql
  pkg/models/querybuilder_movies.go
  pkg/models/querybuilder_performer.go
  pkg/models/querybuilder_studio.go
  pkg/models/querybuilder_tag.go
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMovieTable.tsx
  ui/v2.5/src/components/Shared/Select.tsx
Labels: improvement

#482 Don't error in IsStreamable resolver
  pkg/api/resolver_model_scene.go
Labels: bug

#476 Restore movie/studio data on edit cancel
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieScenesPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/utils/editabletext.tsx
Labels: bug

#458 Add Studio to movie and fix movie schema
  go.sum
  graphql/documents/data/movie.graphql
  graphql/documents/mutations/movie.graphql
  graphql/documents/queries/movie.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/movie.graphql
  graphql/schema/types/scene.graphql
  pkg/api/migrate.go
  pkg/api/resolver_model_movie.go
  pkg/api/resolver_model_scene.go
  pkg/api/resolver_mutation_movie.go
  pkg/api/resolver_mutation_scene.go
  pkg/api/resolver_query_find_movie.go
  pkg/database/database.go
  pkg/database/functions.go
  pkg/database/migrations/8_movie_fix.up.sql
  pkg/manager/jsonschema/movie.go
  pkg/manager/jsonschema/scene.go
  pkg/manager/task_export.go
  pkg/manager/task_import.go
  pkg/models/model_joins.go
  pkg/models/model_movie.go
  pkg/models/querybuilder_joins.go
  pkg/models/querybuilder_movies.go
  ui/v2.5/src/components/Movies/MovieCard.tsx
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMovieTable.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/models/list-filter/filter.ts
Labels: bug

#488 Include scene o-counter in import/export
  pkg/manager/jsonschema/scene.go
  pkg/manager/task_export.go
  pkg/manager/task_import.go
  pkg/models/querybuilder_scene.go
  ui/v2.5/src/components/Scenes/SceneCard.tsx
Labels: bug

#477 Move image with cover.jpg in name to first place in Galleries
  pkg/models/model_gallery.go
Labels: improvement

#489 Clean missing galleries
  pkg/manager/exclude_files.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_clean.go
  pkg/models/querybuilder_gallery.go
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
Labels: bug

#491 Add random male performer image
  pkg/api/images.go
  pkg/api/resolver_mutation_performer.go
  static/performer_male/noname_male_01.jpg
  static/performer_male/noname_male_02.jpg
Labels: improvement

#500 Add parser support for 3-letter month
  pkg/manager/filename_parser.go
  ui/v2.5/src/components/SceneFilenameParser/ParserField.ts
Labels: improvement

#501 Make image extension check in zip files case insensitive
  go.mod
  pkg/models/model_gallery.go
  vendor/golang.org/x/image/riff/riff.go
  vendor/golang.org/x/image/vp8/decode.go
  vendor/golang.org/x/image/vp8/filter.go
  vendor/golang.org/x/image/vp8/idct.go
  vendor/golang.org/x/image/vp8/partition.go
  vendor/golang.org/x/image/vp8/pred.go
  vendor/golang.org/x/image/vp8/predfunc.go
  vendor/golang.org/x/image/vp8/quant.go
  vendor/golang.org/x/image/vp8/reconstruct.go
  vendor/golang.org/x/image/vp8/token.go
  vendor/golang.org/x/image/vp8l/decode.go
  vendor/golang.org/x/image/vp8l/huffman.go
  vendor/golang.org/x/image/vp8l/transform.go
  vendor/golang.org/x/image/webp/decode.go
  vendor/golang.org/x/image/webp/doc.go
  vendor/modules.txt
Labels: improvement

#493 Refactor build
  .gitattributes
  .travis.yml
  Makefile
  README.md
  pkg/api/check_version.go
  pkg/api/server.go
  pkg/ffmpeg/encoder.go
  pkg/manager/manager_tasks.go
  pkg/models/model_movie.go
  pkg/models/model_studio.go
  pkg/scraper/stash.go
  scripts/check-gofmt.sh
  scripts/cross-compile.sh
  ui/v2.5/package.json
  ui/v2.5/src/components/List/Pagination.tsx
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/src/index.scss
Labels: bug, improvement
