Repository stashapp/stash, pull requests merged in 2020-11, with the labels that each got.

#917 Add equals/not equals string criteria
  pkg/models/querybuilder_sql.go
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: bug, improvement

#913 Fix image clean
  pkg/manager/task_clean.go
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
Labels: bug

#919 Add gallery file info
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryFileInfoPanel.tsx
Labels: improvement

#912 Fix outstanding tagger issues
  pkg/models/querybuilder_performer.go
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_studio.go
  pkg/scraper/stashbox/stash_box.go
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Tagger/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/Tagger.tsx
  ui/v2.5/src/components/Tagger/utils.ts
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
Labels: bug

#877 Handle zip file modification
  pkg/database/database.go
  pkg/database/migrations/15_file_mod_time.up.sql
  pkg/database/transaction.go
  pkg/gallery/export.go
  pkg/image/export.go
  pkg/image/image.go
  pkg/manager/jsonschema/gallery.go
  pkg/manager/jsonschema/image.go
  pkg/manager/jsonschema/scene.go
  pkg/manager/task_scan.go
  pkg/models/model_gallery.go
  pkg/models/model_image.go
  pkg/models/model_scene.go
  pkg/models/querybuilder_gallery.go
  pkg/models/querybuilder_image.go
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_sql.go
  pkg/models/sqlite_timestamp.go
  pkg/scene/export.go
  ui/v2.5/src/models/list-filter/filter.ts
Labels: improvement

#927 Prevent studio parent id and scene rating from being unset when tagged
  graphql/documents/data/studio-slim.graphql
  ui/v2.5/src/components/Tagger/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/queries.ts
Labels: bug

#930 Fixing image for Freeones Scrapers
  pkg/scraper/freeones.go
Labels: bug

#928 Lightbox keybinds
  ui/v2.5/package.json
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/globals.d.ts
  ui/v2.5/yarn.lock
Labels: bug

#933 Prevent movie link from being wiped when tagging scene
  ui/v2.5/src/components/Tagger/StashSearchResult.tsx
Labels: bug

#935 Fix image memory issue
  graphql/documents/mutations/image.graphql
  pkg/image/image.go
  pkg/manager/image.go
Labels: bug

#937 Only set stash from env if not set
  pkg/manager/manager.go
Labels: bug

#941 Update findGalleries to only fetch imageCount instead of all images
  graphql/documents/data/gallery-slim.graphql
  graphql/documents/queries/gallery.graphql
  graphql/schema/types/gallery.graphql
  pkg/api/resolver_model_gallery.go
  ui/v2.5/src/components/Galleries/EditGalleriesDialog.tsx
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Galleries/GalleryList.tsx
  ui/v2.5/src/hooks/ListHook.tsx
Labels: improvement

#940 Selective scan
  graphql/schema/types/metadata.graphql
  pkg/api/resolver_mutation_metadata.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_clean.go
  pkg/utils/file.go
  ui/v2.5/src/components/Changelog/versions/v040.md
  ui/v2.5/src/components/Settings/SettingsTasksPanel/ScanDialog.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/components/Settings/StashConfiguration.tsx
  ui/v2.5/src/components/Shared/FolderSelect/FolderSelect.tsx
  ui/v2.5/src/components/Shared/FolderSelect/FolderSelectDialog.tsx
  ui/v2.5/src/components/Shared/styles.scss
Labels: feature

#938 Use symwalk for scrapers
  pkg/scraper/scrapers.go
Labels: bug

#947 Expand tagger manual entry and add link to tagger interface
  ui/v2.5/src/components/Help/Manual.tsx
  ui/v2.5/src/components/Tagger/Tagger.tsx
  ui/v2.5/src/docs/en/Tagger.md
Labels: improvement

#939 Added screenshots/previews to tagger list
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Tagger/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/Tagger.tsx
  ui/v2.5/src/components/Tagger/styles.scss
Labels: improvement

#820 Parallel scanning/generation, and combined scanning/preview/sprite
  go.mod
  go.sum
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  graphql/schema/types/metadata.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
  pkg/manager/generator_preview.go
  pkg/manager/generator_sprite.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_generate_markers.go
  pkg/manager/task_generate_preview.go
  pkg/manager/task_generate_sprite.go
  pkg/manager/task_scan.go
  pkg/manager/task_transcode.go
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/docs/en/Configuration.md
  vendor/github.com/remeh/sizedwaitgroup/LICENSE
  vendor/github.com/remeh/sizedwaitgroup/README.md
  vendor/github.com/remeh/sizedwaitgroup/sizedwaitgroup.go
  vendor/modules.txt
Labels: improvement

#914 Upgrade create-react-app and assorted libraries
  ui/v2.5/.eslintrc.json
  ui/v2.5/package.json
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryList.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/components/List/AddFilter.tsx
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/MainNavbar.tsx
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Movies/MovieList.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerList.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkersPanel.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Scenes/SceneMarkerList.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/StudioList.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/TagList.tsx
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/tsconfig.json
  ui/v2.5/yarn.lock
Labels: improvement

#943 Added natural sort for scene and image titles
  go.mod
  go.sum
  pkg/database/database.go
  pkg/models/querybuilder_movies.go
  pkg/models/querybuilder_sql.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  vendor/github.com/fvbommel/sortorder/.gitignore
  vendor/github.com/fvbommel/sortorder/LICENSE
  vendor/github.com/fvbommel/sortorder/README.md
  vendor/github.com/fvbommel/sortorder/doc.go
  vendor/github.com/fvbommel/sortorder/go.mod
  vendor/github.com/fvbommel/sortorder/go.sum
  vendor/github.com/fvbommel/sortorder/natsort.go
  vendor/modules.txt
Labels: improvement

#958 Add type policies for apollo cache
  ui/v2.5/src/core/createClient.ts
Labels: improvement

#961 Fix oversized movie images on scrape dialog
  ui/v2.5/src/components/Movies/MovieDetails/MovieScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/styles.scss
Labels: improvement

#965 Show studio as text in scene cards where studio image isn't set
  pkg/api/resolver_model_studio.go
  pkg/api/routes_studio.go
  pkg/models/querybuilder_studio.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Scenes/SceneCard.tsx
Labels: improvement

#932 Add TruncatedText component
  ui/v2.5/.stylelintrc
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryDetailPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryFileInfoPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/Image.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageDetailPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageFileInfoPanel.tsx
  ui/v2.5/src/components/Movies/MovieCard.tsx
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Performers/PerformerListTable.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneDetailPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneVideoFilterPanel.tsx
  ui/v2.5/src/components/Scenes/SceneListTable.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Shared/TruncatedText.tsx
  ui/v2.5/src/components/Shared/index.ts
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/components/Studios/StudioCard.tsx
  ui/v2.5/src/components/Tagger/PerformerModal.tsx
  ui/v2.5/src/components/Tagger/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/Tagger.tsx
  ui/v2.5/src/components/Tags/TagCard.tsx
  ui/v2.5/src/utils/text.ts
Labels: improvement

#973 Fix studio parent getting wiped in edit mode
  pkg/models/querybuilder_studio.go
Labels: bug

#968 Tune image referrer path
  pkg/scraper/image.go
Labels: bug
