Repository stashapp/stash, pull requests merged in 2020-06, with the labels that each got.

#590 Remove German language option
  ui/v2.5/src/components/Settings/SettingsInterfacePanel.tsx
  ui/v2.5/src/locale/de.json
  ui/v2.5/src/locale/index.ts
Labels: improvement

#584 Freeones scraper fixes/tweaking
  pkg/scraper/freeones.go
Labels: improvement

#589 Add polyfill for number unit formatting
  ui/v2.5/package.json
  ui/v2.5/src/App.tsx
  ui/v2.5/yarn.lock
Labels: bug

#599 Fix `sanitizeURL`
  ui/v2.5/src/utils/text.ts
Labels: bug

#604 Fix max loop duration not working
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: bug

#592 Reload scrapers button
  graphql/documents/mutations/scrapers.graphql
  graphql/schema/schema.graphql
  pkg/api/resolver_mutation_scraper.go
  pkg/scraper/scrapers.go
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/index.ts
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/index.scss
Labels: improvement

#567 Rating stars
  ui/v2.5/.stylelintrc
  ui/v2.5/package.json
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/RatingStars.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneDetailPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Shared/Icon.tsx
  ui/v2.5/yarn.lock
Labels: improvement

#595 Parent studios
  graphql/documents/data/studio.graphql
  graphql/documents/mutations/studio.graphql
  graphql/documents/queries/studio.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/studio.graphql
  pkg/api/resolver_model_studio.go
  pkg/api/resolver_mutation_studio.go
  pkg/api/resolver_query_find_studio.go
  pkg/database/database.go
  pkg/database/migrations/9_studios_parent_studio.up.sql
  pkg/manager/jsonschema/studio.go
  pkg/manager/studio.go
  pkg/manager/task_export.go
  pkg/manager/task_import.go
  pkg/models/model_studio.go
  pkg/models/querybuilder_movies.go
  pkg/models/querybuilder_movies_test.go
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_scene_test.go
  pkg/models/querybuilder_sql.go
  pkg/models/querybuilder_studio.go
  pkg/models/querybuilder_studio_test.go
  pkg/models/setup_test.go
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/List/AddFilter.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Studios/StudioCard.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioChildrenPanel.tsx
  ui/v2.5/src/components/Studios/StudioList.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/studios.ts
  ui/v2.5/src/models/list-filter/criteria/utils.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/utils/navigation.ts
Labels: feature

#606 Apply xpath parseDate after subScraper
  pkg/scraper/xpath.go
Labels: improvement

#615 freeones fixes
  pkg/scraper/freeones.go
Labels: bug

#562 [RFC] Revamp scene page
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/ScenePlayerScrubber.tsx
  ui/v2.5/src/components/ScenePlayer/styles.scss
  ui/v2.5/src/components/Scenes/SceneDetails/OCounterButton.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/PrimaryTags.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneDetailPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkerForm.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneOperationsPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/ScenePerformerPanel.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Shared/ImageInput.tsx
  ui/v2.5/src/utils/form.tsx
  ui/v2.5/src/utils/index.ts
Labels: improvement

#579 Add "split" xpath in post-processing , newlines in replace support
  pkg/scraper/xpath.go
  pkg/scraper/xpath_test.go
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/index.scss
Labels: feature

#614 Render pagination at top as well
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/hooks/ListHook.tsx
Labels: improvement

#621 Fix scene delete
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
Labels: bug

#622 Gallery list improvement
  graphql/documents/data/gallery.graphql
  graphql/documents/queries/gallery.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/gallery.graphql
  pkg/api/resolver_model_gallery.go
  pkg/api/resolver_query_find_gallery.go
  pkg/manager/task_clean.go
  pkg/manager/task_scan.go
  pkg/models/model_gallery.go
  pkg/models/querybuilder_gallery.go
  pkg/models/querybuilder_gallery_test.go
  pkg/models/setup_test.go
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Galleries/GalleryList.tsx
  ui/v2.5/src/components/Galleries/styles.scss
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Shared/TagLink.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/index.scss
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
  ui/v2.5/src/models/list-filter/criteria/utils.ts
  ui/v2.5/src/models/list-filter/filter.ts
Labels: improvement

#620 Add custom served folders
  pkg/api/server.go
  pkg/manager/config/config.go
  pkg/manager/config/urlmap.go
  pkg/manager/config/urlmap_test.go
  ui/v2.5/src/components/Changelog/versions/v030.tsx
Labels: feature

#624 Increase xpath redirects, use cookies
  go.mod
  go.sum
  pkg/scraper/xpath.go
  vendor/golang.org/x/net/publicsuffix/list.go
  vendor/golang.org/x/net/publicsuffix/table.go
  vendor/modules.txt
Labels: improvement

#618 Move image blobs into separate tables
  pkg/api/resolver_mutation_movie.go
  pkg/api/resolver_mutation_performer.go
  pkg/api/resolver_mutation_scene.go
  pkg/api/resolver_mutation_studio.go
  pkg/api/routes_movie.go
  pkg/api/routes_performer.go
  pkg/api/routes_scene.go
  pkg/api/routes_studio.go
  pkg/database/database.go
  pkg/database/migrations/10_image_tables.up.sql
  pkg/database/packr_source.go
  pkg/manager/jsonschema/movie.go
  pkg/manager/task_autotag_test.go
  pkg/manager/task_export.go
  pkg/manager/task_generate_screenshot.go
  pkg/manager/task_import.go
  pkg/models/model_movie.go
  pkg/models/model_performer.go
  pkg/models/model_scene.go
  pkg/models/model_studio.go
  pkg/models/querybuilder_movies.go
  pkg/models/querybuilder_movies_test.go
  pkg/models/querybuilder_performer.go
  pkg/models/querybuilder_performer_test.go
  pkg/models/querybuilder_scene.go
  pkg/models/querybuilder_scene_test.go
  pkg/models/querybuilder_sql.go
  pkg/models/querybuilder_studio.go
  pkg/models/querybuilder_studio_test.go
  pkg/models/setup_test.go
  pkg/utils/image.go
Labels: improvement

#629 Integrate build version in UI
  Makefile
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Settings/SettingsAboutPanel.tsx
Labels: improvement

#628 In-app help manual
  ui/v2.5/src/components/Changelog/Version.tsx
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/Help/Manual.tsx
  ui/v2.5/src/components/Help/Page.tsx
  ui/v2.5/src/components/Help/styles.scss
  ui/v2.5/src/components/MainNavbar.tsx
  ui/v2.5/src/docs/en/AutoTagging.md
  ui/v2.5/src/docs/en/Configuration.md
  ui/v2.5/src/docs/en/Contributing.md
  ui/v2.5/src/docs/en/Galleries.md
  ui/v2.5/src/docs/en/Help.md
  ui/v2.5/src/docs/en/Interface.md
  ui/v2.5/src/docs/en/Introduction.md
  ui/v2.5/src/docs/en/JSONSpec.md
  ui/v2.5/src/docs/en/SceneFilenameParser.md
  ui/v2.5/src/docs/en/Scraping.md
  ui/v2.5/src/docs/en/Tasks.md
  ui/v2.5/src/globals.d.ts
  ui/v2.5/src/index.scss
Labels: feature

#630 Support deleting multiple scenes
  graphql/documents/mutations/scene.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/scene.graphql
  pkg/api/resolver_mutation_scene.go
  ui/v2.5/src/components/Changelog/versions/v030.tsx
  ui/v2.5/src/components/List/AddFilter.tsx
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/components/Scenes/DeleteScenesDialog.tsx
  ui/v2.5/src/components/Scenes/EditScenesDialog.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/RatingStars.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Shared/Modal.tsx
  ui/v2.5/src/components/Shared/MultiSet.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/src/index.scss
  ui/v2.5/src/styles/_theme.scss
Labels: feature

#631 Fix UI not showing version number
  .travis.yml
  Makefile
Labels: bug

#632 [RFC] Fix query toolbar, performer/studio/movie page styling improvements
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/styles.scss
  ui/v2.5/src/index.scss
Labels: bug, improvement

#636 Strip debug symbols from release builds
  Makefile
  scripts/cross-compile.sh
Labels: improvement
