Repository stashapp/stash, pull requests merged in 2020-01, with the labels that each got.

#280 Add scenes tab to performer page
  ui/v2/src/components/performers/PerformerDetails/Performer.tsx
  ui/v2/src/components/performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2/src/components/performers/PerformerDetails/PerformerOperationsPanel.tsx
  ui/v2/src/components/performers/PerformerDetails/PerformerScenesPanel.tsx
  ui/v2/src/components/scenes/SceneList.tsx
  ui/v2/src/components/scenes/SceneListPage.tsx
  ui/v2/src/components/scenes/scenes.tsx
  ui/v2/src/core/StashService.ts
  ui/v2/src/hooks/ListHook.tsx
  ui/v2/src/index.scss
  ui/v2/src/utils/editabletext.tsx
  ui/v2/src/utils/table.tsx
Labels: improvement

#311 Use parameters for regex queries
  pkg/manager/task_autotag_test.go
  pkg/models/querybuilder_scene.go
Labels: improvement

#296 Add check version functionality
  graphql/documents/queries/misc.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/version.graphql
  pkg/api/check_version.go
  pkg/api/resolver.go
  pkg/api/server.go
  ui/v2/src/components/Settings/SettingsAboutPanel.tsx
  ui/v2/src/core/StashService.ts
Labels: feature

#313 Add scene duration filter
  graphql/schema/types/filters.graphql
  pkg/models/querybuilder_scene.go
  ui/v2/src/components/Shared/DurationInput.tsx
  ui/v2/src/components/list/AddFilter.tsx
  ui/v2/src/models/list-filter/criteria/criterion.ts
  ui/v2/src/models/list-filter/criteria/utils.ts
  ui/v2/src/models/list-filter/filter.ts
  ui/v2/src/utils/duration.ts
Labels: feature

#317 Fix react warnings
  go.mod
  go.sum
  ui/v2/src/components/Galleries/Gallery.tsx
  ui/v2/src/components/Galleries/GalleryList.tsx
  ui/v2/src/components/Galleries/GalleryViewer.tsx
  ui/v2/src/components/Settings/Settings.tsx
  ui/v2/src/components/Settings/SettingsAboutPanel.tsx
  ui/v2/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2/src/components/Settings/SettingsInterfacePanel.tsx
  ui/v2/src/components/Settings/SettingsLogsPanel.tsx
  ui/v2/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2/src/components/Shared/DetailsEditNavbar.tsx
  ui/v2/src/components/Shared/DurationInput.tsx
  ui/v2/src/components/Shared/FolderSelect/FolderSelect.tsx
  ui/v2/src/components/Shared/TagLink.tsx
  ui/v2/src/components/Sidebar.tsx
  ui/v2/src/components/Stats.tsx
  ui/v2/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2/src/components/Studios/StudioList.tsx
  ui/v2/src/components/Tags/TagList.tsx
  ui/v2/src/components/Wall/WallItem.tsx
  ui/v2/src/components/Wall/WallPanel.tsx
  ui/v2/src/components/list/ListFilter.tsx
  ui/v2/src/components/performers/PerformerDetails/Performer.tsx
  ui/v2/src/components/performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2/src/components/performers/PerformerDetails/PerformerOperationsPanel.tsx
  ui/v2/src/components/performers/PerformerDetails/PerformerScenesPanel.tsx
  ui/v2/src/components/scenes/SceneCard.tsx
  ui/v2/src/components/scenes/SceneDetails/Scene.tsx
  ui/v2/src/components/scenes/SceneDetails/SceneDetailPanel.tsx
  ui/v2/src/components/scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2/src/components/scenes/SceneDetails/SceneMarkersPanel.tsx
  ui/v2/src/components/scenes/SceneFilenameParser.tsx
  ui/v2/src/components/scenes/SceneListPage.tsx
  ui/v2/src/components/scenes/ScenePlayer/ScenePlayer.tsx
  ui/v2/src/components/scenes/ScenePlayer/ScenePlayerScrubber.tsx
  ui/v2/src/components/scenes/SceneSelectedOptions.tsx
  ui/v2/src/components/select/FilterMultiSelect.tsx
  ui/v2/src/components/select/FilterSelect.tsx
  ui/v2/src/components/select/ScrapePerformerSuggest.tsx
  ui/v2/src/components/select/ValidGalleriesSelect.tsx
  ui/v2/src/index.scss
  ui/v2/src/utils/duration.ts
  ui/v2/src/utils/image.tsx
  ui/v2/src/utils/table.tsx
  ui/v2/src/utils/text.ts
Labels: improvement

#322 Add useful links to about page
  ui/v2/src/components/Settings/SettingsAboutPanel.tsx
Labels: improvement

#297 Add LICENSE until we get all signers on the switch
  LICENSE
Labels: improvement

#324 Add timeout to neededGenerate function
  pkg/manager/manager_tasks.go
Labels: improvement

#319 Refresh yarn.lock
  ui/v2/yarn.lock
Labels: improvement

#327 Allow path separator in scene filename parser pattern
  pkg/manager/filename_parser.go
  ui/v2/src/components/scenes/SceneFilenameParser.tsx
Labels: improvement

#328 Accept random seed from UI for random sorting
  pkg/models/querybuilder_sql.go
  ui/v2/src/models/list-filter/filter.ts
Labels: improvement

#332 Scraper fixes
  graphql/documents/data/scrapers.graphql
  pkg/scraper/xpath.go
  pkg/scraper/xpath_test.go
Labels: bug

#326 Maintain filter parameters in session
  go.mod
  ui/v2/src/components/list/Pagination.tsx
  ui/v2/src/hooks/ListHook.tsx
  ui/v2/src/hooks/LocalForage.ts
  ui/v2/src/models/list-filter/filter.ts
Labels: improvement

#333 Add Xpath post processing and performer name query
  pkg/scraper/config.go
  pkg/scraper/xpath.go
  pkg/scraper/xpath_test.go
  ui/v2/src/components/performers/PerformerDetails/PerformerDetailsPanel.tsx
Labels: feature

#336 Change thumbnail default size and resize algorithm
  pkg/api/resolver_query_logs.go
  pkg/api/routes_gallery.go
  pkg/manager/manager.go
  pkg/manager/running_streams.go
  pkg/manager/scene.go
  pkg/manager/task_autotag_test.go
  pkg/models/model_gallery.go
  pkg/models/querybuilder_scene_marker.go
  pkg/utils/resources.go
  tools.go
Labels: improvement

#337 Add cache headers to static files and etags to performer images
  pkg/api/routes_performer.go
  pkg/api/server.go
Labels: improvement
