Repository stashapp/stash, pull requests merged in 2021-12, with the labels that each got.

#2087 Include sceneIDs when generating
  ui/v2.5/src/components/Dialogs/GenerateDialog.tsx
Labels: bug

#2083 Use inner join when getting images in a gallery
  pkg/sqlite/filter.go
  pkg/sqlite/filter_internal_test.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/image_test.go
  pkg/sqlite/movies.go
  pkg/sqlite/performer.go
  pkg/sqlite/query.go
  pkg/sqlite/repository.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_marker.go
  pkg/sqlite/studio.go
  pkg/sqlite/tag.go
Labels: improvement, go

#2091 Add performer aliases to stash-box tagging/scraping
  pkg/scraper/stashbox/stash_box.go
  ui/v2.5/src/components/Changelog/versions/v0120.md
  ui/v2.5/src/components/Tagger/PerformerModal.tsx
Labels: bug

#2090 Upgrade ansi-regex,normalize-url,postcss,ws (dependabot alerts)
  ui/v2.5/package.json
  ui/v2.5/yarn.lock
Labels: chore

#2079 Update Tasks documentation
  ui/v2.5/src/docs/en/Tasks.md
Labels: documentation

#2096 Heatmap and speed sorting/filtering for interactive scenes [rewrite]
  .gitignore
  go.mod
  go.sum
  graphql/documents/data/config.graphql
  graphql/documents/data/scene-slim.graphql
  graphql/documents/data/scene.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/metadata.graphql
  graphql/schema/types/scene.graphql
  pkg/api/resolver_model_scene.go
  pkg/api/routes_scene.go
  pkg/api/urlbuilders/scene.go
  pkg/database/database.go
  pkg/database/migrations/29_interactive_speed.up.sql
  pkg/manager/generator_interactive_heatmap_speed.go
  pkg/manager/manager.go
  pkg/manager/paths/paths_generated.go
  pkg/manager/paths/paths_scenes.go
  pkg/manager/task_generate.go
  pkg/manager/task_generate_interactive_heatmap_speed.go
  pkg/models/model_scene.go
  pkg/scene/delete.go
  pkg/scene/migrate_hash.go
  pkg/scene/scan.go
  pkg/sqlite/scene.go
  ui/v2.5/src/components/Changelog/versions/v0120.md
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Settings/Tasks/GenerateOptions.tsx
  ui/v2.5/src/components/Shared/GridCard.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/criteria/factory.ts
  ui/v2.5/src/models/list-filter/scenes.ts
  ui/v2.5/src/models/list-filter/types.ts
  vendor/github.com/lucasb-eyer/go-colorful/.gitignore
  vendor/github.com/lucasb-eyer/go-colorful/CHANGELOG.md
  vendor/github.com/lucasb-eyer/go-colorful/LICENSE
  vendor/github.com/lucasb-eyer/go-colorful/README.md
  vendor/github.com/lucasb-eyer/go-colorful/colorgens.go
  vendor/github.com/lucasb-eyer/go-colorful/colors.go
  vendor/github.com/lucasb-eyer/go-colorful/happy_palettegen.go
  vendor/github.com/lucasb-eyer/go-colorful/hexcolor.go
  vendor/github.com/lucasb-eyer/go-colorful/hsluv-snapshot-rev4.json
  vendor/github.com/lucasb-eyer/go-colorful/hsluv.go
  vendor/github.com/lucasb-eyer/go-colorful/soft_palettegen.go
  vendor/github.com/lucasb-eyer/go-colorful/warm_palettegen.go
  vendor/github.com/vearutop/statigz/.gitignore
  vendor/github.com/vearutop/statigz/.golangci.yml
  vendor/github.com/vearutop/statigz/Makefile
  vendor/github.com/vearutop/statigz/_testdata/bad.png.gz
  vendor/github.com/vearutop/statigz/_testdata/deeper/openapi.json.gz
  vendor/github.com/vearutop/statigz/_testdata/deeper/swagger.json.br
  vendor/github.com/vearutop/statigz/_testdata/favicon.png
  vendor/github.com/vearutop/statigz/_testdata/index.html
  vendor/github.com/vearutop/statigz/_testdata/index.html.gz
  vendor/github.com/vearutop/statigz/_testdata/swagger.json
  vendor/modules.txt
Labels: feature

#2098 Stick edit scene buttons to top
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/styles.scss
Labels: improvement, ui

#2101 Marker previews should respect preview audio setting
  pkg/ffmpeg/encoder_marker.go
  pkg/manager/task_generate_markers.go
  ui/v2.5/src/components/Changelog/versions/v0120.md
Labels: improvement

#2102 Include path and hashes in destroy hook input
  pkg/api/resolver_mutation_gallery.go
  pkg/api/resolver_mutation_image.go
  pkg/api/resolver_mutation_scene.go
  pkg/manager/task_clean.go
  pkg/plugin/hooks.go
  ui/v2.5/src/components/Changelog/versions/v0120.md
Labels: improvement

#2108 Security Hardening: Content Security Policy + more
  pkg/api/server.go
  ui/v2.5/index.html
  ui/v2.5/src/index.html.ejs
  ui/v2.5/src/locales/en-GB.json
Labels: improvement, chore

#2112 Fix auth in CSP
  pkg/api/server.go
Labels: bug

#2115 Fix images loading from stashdb
  pkg/api/server.go
Labels: bug

#2086 Settings UI refactor
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Changelog/versions/v0120.md
  ui/v2.5/src/components/Dialogs/GenerateDialog.tsx
  ui/v2.5/src/components/Help/Manual.tsx
  ui/v2.5/src/components/MainNavbar.tsx
  ui/v2.5/src/components/Settings/GeneratePreviewOptions.tsx
  ui/v2.5/src/components/Settings/Inputs.tsx
  ui/v2.5/src/components/Settings/SettingSection.tsx
  ui/v2.5/src/components/Settings/Settings.tsx
  ui/v2.5/src/components/Settings/SettingsAboutPanel.tsx
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/CheckboxGroup.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/components/Settings/SettingsLibraryPanel.tsx
  ui/v2.5/src/components/Settings/SettingsLogsPanel.tsx
  ui/v2.5/src/components/Settings/SettingsPluginsPanel.tsx
  ui/v2.5/src/components/Settings/SettingsScrapingPanel.tsx
  ui/v2.5/src/components/Settings/SettingsSecurityPanel.tsx
  ui/v2.5/src/components/Settings/SettingsServicesPanel.tsx
  ui/v2.5/src/components/Settings/SettingsSystemPanel.tsx
  ui/v2.5/src/components/Settings/SettingsToolsPanel.tsx
  ui/v2.5/src/components/Settings/StashBoxConfiguration.tsx
  ui/v2.5/src/components/Settings/StashConfiguration.tsx
  ui/v2.5/src/components/Settings/Tasks/DataManagementTasks.tsx
  ui/v2.5/src/components/Settings/Tasks/GenerateOptions.tsx
  ui/v2.5/src/components/Settings/Tasks/JobTable.tsx
  ui/v2.5/src/components/Settings/Tasks/LibraryTasks.tsx
  ui/v2.5/src/components/Settings/Tasks/PluginTasks.tsx
  ui/v2.5/src/components/Settings/Tasks/ScanOptions.tsx
  ui/v2.5/src/components/Settings/Tasks/SettingsTasksPanel.tsx
  ui/v2.5/src/components/Settings/Tasks/Task.tsx
  ui/v2.5/src/components/Settings/context.tsx
  ui/v2.5/src/components/Settings/styles.scss
  ui/v2.5/src/components/Setup/Setup.tsx
  ui/v2.5/src/components/Shared/FolderSelect/FolderSelectDialog.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Tagger/performers/PerformerTagger.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/docs/en/Tasks.md
  ui/v2.5/src/locales/en-GB.json
Labels: improvement, ui

#2119 Fix image querying
  pkg/sqlite/image.go
  pkg/sqlite/image_test.go
  pkg/sqlite/repository.go
Labels: bug

#2099 Player improvements
  ui/v2.5/src/components/Changelog/versions/v0120.md
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/styles.scss
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/docs/en/KeyboardShortcuts.md
Labels: improvement

#2128 Fix Safari websockets requests
  pkg/api/server.go
Labels: bug

#2132 Add media-src to content-security-policy
  pkg/api/server.go
Labels: bug

#2059 Skip cleaning for search by name scrape queries
  go.mod
  go.sum
  pkg/scraper/json.go
  pkg/scraper/mapped.go
  pkg/scraper/scraper.go
  pkg/scraper/xpath.go
  vendor/github.com/antchfx/htmlquery/README.md
  vendor/github.com/antchfx/htmlquery/query.go
  vendor/github.com/antchfx/xpath/README.md
  vendor/github.com/antchfx/xpath/build.go
  vendor/github.com/antchfx/xpath/cache.go
  vendor/github.com/antchfx/xpath/func.go
  vendor/github.com/antchfx/xpath/func_go110.go
  vendor/github.com/antchfx/xpath/func_pre_go110.go
  vendor/github.com/antchfx/xpath/operator.go
  vendor/github.com/antchfx/xpath/parse.go
  vendor/github.com/antchfx/xpath/query.go
  vendor/golang.org/x/net/internal/socket/complete_dontwait.go
  vendor/golang.org/x/net/internal/socket/complete_nodontwait.go
  vendor/golang.org/x/net/internal/socket/empty.s
  vendor/golang.org/x/net/internal/socket/rawconn_mmsg.go
  vendor/golang.org/x/net/internal/socket/rawconn_msg.go
  vendor/golang.org/x/net/internal/socket/sys_bsd.go
  vendor/golang.org/x/net/internal/socket/sys_linkname.go
  vendor/golang.org/x/net/internal/socket/sys_linux_386.go
  vendor/golang.org/x/net/internal/socket/sys_linux_s390x.go
  vendor/golang.org/x/net/internal/socket/sys_solaris.go
  vendor/golang.org/x/net/internal/socket/sys_solaris_amd64.s
  vendor/golang.org/x/net/internal/socket/sys_unix.go
  vendor/golang.org/x/net/publicsuffix/table.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/language/parse.go
  vendor/modules.txt
Labels: improvement

#2129 Add short sprite error logging
  pkg/manager/generator_sprite.go
Labels: bug

#2125 Selective clean
  graphql/schema/types/metadata.graphql
  pkg/gallery/filter.go
  pkg/image/filter.go
  pkg/manager/task_clean.go
  pkg/match/path.go
  pkg/scene/filter.go
  ui/v2.5/src/components/Changelog/versions/v0120.md
  ui/v2.5/src/components/Settings/Tasks/DataManagementTasks.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#2133 Fix ffmpeg downloader on windows
  pkg/ffmpeg/downloader.go
Labels: bug

#2139 Whitelist CDN used by playground
  pkg/api/server.go
Labels: bug

#2138 Fix UseFileMetadata when scanning
  pkg/manager/task_scan_scene.go
  pkg/scene/scan.go
Labels: bug

#2126 Add force transcode option
  graphql/schema/types/metadata.graphql
  pkg/manager/task_generate.go
  pkg/manager/task_transcode.go
  ui/v2.5/src/components/Changelog/versions/v0120.md
  ui/v2.5/src/components/Dialogs/GenerateDialog.tsx
  ui/v2.5/src/components/Settings/Tasks/GenerateOptions.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#2124 Support setting scrapers path in UI
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  ui/v2.5/src/components/Changelog/versions/v0120.md
  ui/v2.5/src/components/Settings/SettingsSystemPanel.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#2145 Creation and update dates visible for images and scenes
  graphql/documents/data/gallery.graphql
  graphql/documents/data/image.graphql
  graphql/documents/data/scene.graphql
  ui/v2.5/src/components/Changelog/versions/v0120.md
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryDetailPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageDetailPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneDetailPanel.tsx
Labels: improvement

#2150 Update styling of folder select error state
  ui/v2.5/src/components/Shared/FolderSelect/FolderSelect.tsx
Labels: bug, ui

#2146 Fix endless toast errors in Settings
  ui/v2.5/src/components/Settings/context.tsx
  ui/v2.5/src/components/Settings/styles.scss
Labels: bug

#2154 Make phash a link to duplicates
  ui/v2.5/src/components/Changelog/versions/v0120.md
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
  ui/v2.5/src/models/list-filter/criteria/phash.ts
  ui/v2.5/src/utils/navigation.ts
Labels: ui

#2180 Fix broken and outdated links in the Help document
  ui/v2.5/src/docs/en/Contributing.md
  ui/v2.5/src/docs/en/Interactive.md
  ui/v2.5/src/docs/en/Interface.md
  ui/v2.5/src/docs/en/Introduction.md
  ui/v2.5/src/docs/en/ScraperDevelopment.md
Labels: improvement, documentation

#2183 Explain recursive common fragments edge case
  ui/v2.5/src/docs/en/ScraperDevelopment.md
Labels: documentation
