Repository stashapp/stash, pull requests merged in 2021-09, with the labels that each got.

#1630 Unify scrape refactor
  gqlgen.yml
  graphql/documents/data/scrapers.graphql
  graphql/documents/queries/scrapers/scrapers.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/scraped-movie.graphql
  graphql/schema/types/scraped-performer.graphql
  graphql/schema/types/scraper.graphql
  pkg/api/resolver.go
  pkg/api/resolver_model_scraper.go
  pkg/api/resolver_query_scraper.go
  pkg/manager/task_stash_box_tag.go
  pkg/models/model_scraped_item.go
  pkg/scraper/action.go
  pkg/scraper/config.go
  pkg/scraper/image.go
  pkg/scraper/json.go
  pkg/scraper/mapped.go
  pkg/scraper/matchers.go
  pkg/scraper/scrapers.go
  pkg/scraper/script.go
  pkg/scraper/stash.go
  pkg/scraper/stashbox/stash_box.go
  pkg/scraper/xpath.go
  pkg/scraper/xpath_test.go
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieEditPanel.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieScrapeDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeModal.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerStashBoxModal.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/components/Tagger/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/TaggerList.tsx
  ui/v2.5/src/components/Tagger/TaggerScene.tsx
  ui/v2.5/src/components/Tagger/performers/PerformerTagger.tsx
  ui/v2.5/src/components/Tagger/utils.ts
  ui/v2.5/src/core/StashService.ts
Labels: chore

#1675 Add movies tab to Studios and Performers page
  graphql/schema/types/filters.graphql
  pkg/sqlite/movies.go
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/Movies/MovieList.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerMoviesPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioMoviesPanel.tsx
  ui/v2.5/src/models/list-filter/movies.ts
Labels: feature

#1676 Add Movie option to Scene bulk edit
  graphql/schema/types/scene.graphql
  pkg/api/resolver_mutation_scene.go
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/Scenes/EditScenesDialog.tsx
  ui/v2.5/src/components/Shared/MultiSet.tsx
Labels: feature

#1685 Remove assignments to _
  pkg/api/changeset_translator.go
Labels: chore

#1696 Fix data race in progress_test
  pkg/job/progress_test.go
Labels: chore

#1701 Add missing simplified Chinese translation
  ui/v2.5/src/locales/zh-CN.json
Labels: improvement

#1686 When stopping, close the database
  main.go
  pkg/database/database.go
  pkg/manager/manager.go
Labels: improvement

#1703 Correct error propagation
  pkg/manager/task_stash_box_tag.go
Labels: chore

#1704 Error strings noncapitalized
  pkg/api/check_version.go
  pkg/database/database.go
  pkg/ffmpeg/ffprobe.go
  pkg/manager/config/config.go
  pkg/manager/task_generate_screenshot.go
  pkg/plugin/raw.go
  pkg/scraper/url.go
  pkg/sqlite/repository.go
  pkg/sqlite/tag.go
  pkg/utils/file.go
Labels: chore

#1705 Avoid redundant break statements
  pkg/sqlite/sql.go
Labels: chore

#1709 Remove unused
  pkg/api/context_keys.go
  pkg/api/resolver_subscription_job.go
  pkg/api/routes_scene.go
  pkg/api/server.go
  pkg/api/session.go
  pkg/dlna/dms.go
  pkg/ffmpeg/hls.go
  pkg/gallery/export_test.go
  pkg/gallery/import_test.go
  pkg/image/export_test.go
  pkg/image/import_test.go
  pkg/logger/logger.go
  pkg/manager/filename_parser.go
  pkg/manager/jsonschema/utils.go
  pkg/manager/task_import.go
  pkg/scene/export_test.go
  pkg/scene/import_test.go
  pkg/scraper/action.go
  pkg/scraper/mapped.go
  pkg/scraper/url.go
  pkg/session/session.go
  pkg/sqlite/filter.go
  pkg/sqlite/gallery.go
  pkg/sqlite/scraped_item.go
  pkg/sqlite/sql.go
  pkg/utils/byterange.go
Labels: chore

#1710 Avoid wrapping strings.Replace in Contains
  pkg/scraper/mapped.go
Labels: chore

#1519 Tag hierarchy
  graphql/documents/data/tag.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/tag.graphql
  pkg/api/resolver_model_tag.go
  pkg/api/resolver_mutation_tag.go
  pkg/database/database.go
  pkg/database/migrations/26_tag_hierarchy.up.sql
  pkg/dlna/cds.go
  pkg/gallery/query.go
  pkg/image/query.go
  pkg/manager/jsonschema/tag.go
  pkg/manager/task_import.go
  pkg/models/mocks/TagReaderWriter.go
  pkg/models/tag.go
  pkg/sqlite/filter.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/image.go
  pkg/sqlite/image_test.go
  pkg/sqlite/movies.go
  pkg/sqlite/performer.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/query.go
  pkg/sqlite/repository.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_marker.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/tag.go
  pkg/tag/export.go
  pkg/tag/export_test.go
  pkg/tag/import.go
  pkg/tag/import_test.go
  pkg/tag/update.go
  pkg/tag/update_test.go
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/List/Filters/HierarchicalLabelValueFilter.tsx
  ui/v2.5/src/components/Shared/DeleteEntityDialog.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagDetailsPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagMarkersPanel.tsx
  ui/v2.5/src/components/Tags/TagList.tsx
  ui/v2.5/src/core/createClient.ts
  ui/v2.5/src/core/tags.ts
  ui/v2.5/src/locales/de-DE.json
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/pt-BR.json
  ui/v2.5/src/locales/zh-CN.json
  ui/v2.5/src/locales/zh-TW.json
  ui/v2.5/src/models/list-filter/criteria/tags.ts
  ui/v2.5/src/utils/navigation.ts
Labels: feature

#1714 Fix studio scene count sort
  pkg/sqlite/studio.go
Labels: bug

#1716 Make IHierarchicalLabeledIdCriterion backwards compatible
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/filter.ts
Labels: bug

#1712 Scrape scene by name
  pkg/api/resolver_query_scraper.go
  pkg/scraper/action.go
  pkg/scraper/config.go
  pkg/scraper/json.go
  pkg/scraper/mapped.go
  pkg/scraper/query_url.go
  pkg/scraper/scrapers.go
  pkg/scraper/script.go
  pkg/scraper/stash.go
  pkg/scraper/url.go
  pkg/scraper/xpath.go
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneQueryModal.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/docs/en/Scraping.md
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#1718 [Bug Fix] Fix scene markers editor mobile UI
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkerForm.tsx
  ui/v2.5/src/components/Shared/DurationInput.tsx
  ui/v2.5/src/index.scss
  ui/v2.5/src/styles/_theme.scss
Labels: bug

#1722 Update sv-SE.json
  ui/v2.5/src/locales/sv-SE.json
Labels: improvement

#1721 [Bug Fix] Disable float-on-scroll JWPlayer feature on mobile
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/utils/index.ts
  ui/v2.5/src/utils/screen.ts
Labels: bug

#1604 Generate screenshot images for markers
  graphql/documents/data/scene-marker.graphql
  graphql/schema/types/metadata.graphql
  graphql/schema/types/scene-marker.graphql
  pkg/api/resolver_model_scene_marker.go
  pkg/api/routes_scene.go
  pkg/api/urlbuilders/scene.go
  pkg/manager/manager_tasks.go
  pkg/manager/paths/paths_scene_markers.go
  pkg/manager/scene.go
  pkg/manager/task_generate_markers.go
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/Scenes/SceneGenerateDialog.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/GenerateButton.tsx
  ui/v2.5/src/components/Wall/WallItem.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#1693 Add new zh-tw localizations & move non-legacy localization keys
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/components/Stats.tsx
  ui/v2.5/src/locales/de-DE.json
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/pt-BR.json
  ui/v2.5/src/locales/sv-SE.json
  ui/v2.5/src/locales/zh-CN.json
  ui/v2.5/src/locales/zh-TW.json
Labels: chore

#1726 Add AND, OR and NOT support to studio filter
  graphql/schema/types/filters.graphql
  pkg/sqlite/performer_test.go
  pkg/sqlite/studio.go
  pkg/sqlite/studio_test.go
Labels: improvement

#1730 Adjustments German translation
  ui/v2.5/src/locales/de-DE.json
Labels: improvement

#1733 Make hierarchical criterion depth input optional
  graphql/schema/types/filters.graphql
  pkg/dlna/cds.go
  pkg/gallery/query.go
  pkg/image/query.go
  pkg/sqlite/filter.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/image_test.go
  pkg/sqlite/movies_test.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/studio_test.go
Labels: improvement

#1648 Support scraper logging to specific log levels
  pkg/logger/plugin.go
  pkg/plugin/common/log/log.go
  pkg/plugin/log.go
  pkg/scraper/script.go
  ui/v2.5/src/components/Changelog/versions/v0100.md
Labels: feature

#1713 Fix autotag tag alias
  pkg/autotag/gallery_test.go
  pkg/autotag/image_test.go
  pkg/autotag/scene_test.go
  pkg/autotag/tag.go
  pkg/manager/task_autotag.go
  ui/v2.5/src/components/Changelog/versions/v0100.md
Labels: bug

#1741 Scraper log improvements
  pkg/logger/logger.go
  pkg/logger/plugin.go
  pkg/plugin/log.go
  pkg/plugin/raw.go
  pkg/plugin/rpc.go
  pkg/scraper/script.go
Labels: bug, improvement

#1731 Execute Gallery.Create.Post plugin hook during scan
  pkg/manager/task_scan.go
  ui/v2.5/src/components/Changelog/versions/v0100.md
Labels: bug

#1739 Fix Scene Player CLS issue
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/styles.scss
Labels: improvement

#1743 Fix Query for Scene Markers
  pkg/sqlite/scene_marker.go
Labels: bug

#1715 Errcheck phase 1
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_mutation_plugin.go
  pkg/api/routes_image.go
  pkg/api/routes_movie.go
  pkg/api/routes_performer.go
  pkg/api/routes_scene.go
  pkg/api/routes_studio.go
  pkg/api/routes_tag.go
  pkg/database/database.go
  pkg/dlna/service.go
  pkg/ffmpeg/ffprobe.go
  pkg/ffmpeg/stream.go
  pkg/manager/config/config.go
  pkg/manager/config/config_concurrency_test.go
  pkg/manager/config/init.go
  pkg/manager/image.go
  pkg/manager/manager_tasks.go
  pkg/manager/paths/paths_generated.go
  pkg/manager/paths/paths_json.go
  pkg/manager/running_streams.go
  pkg/manager/screenshot.go
  pkg/manager/task_export.go
  pkg/manager/task_import.go
  pkg/manager/task_scan.go
  pkg/manager/task_stash_box_tag.go
  pkg/plugin/js.go
  pkg/plugin/js/gql.go
  pkg/plugin/js/log.go
  pkg/plugin/js/util.go
  pkg/plugin/plugins.go
  pkg/plugin/raw.go
  pkg/utils/crypto.go
  scripts/test_db_generator/makeTestDB.go
Labels: chore

#1684 Set NORMAL sync on sqlite3
  pkg/database/database.go
Labels: improvement

#1740 Add indexes for path and checksum to images
  pkg/database/custom_migrations.go
  pkg/database/database.go
  pkg/database/migrations/28_images_indexes.up.sql
  ui/v2.5/src/components/Changelog/versions/v0100.md
Labels: improvement

#1719 Support subpaths when serving stash through a reverse proxy
  README.md
  pkg/api/server.go
  ui/v2.5/package.json
  ui/v2.5/public/index.html
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/core/createClient.ts
  ui/v2.5/src/globals.d.ts
  ui/v2.5/src/index.tsx
Labels: feature

#1749 Only close DB if not nil
  pkg/database/database.go
Labels: bug

#1748 Reorder waitgroup completion
  pkg/manager/manager_tasks.go
  pkg/manager/task.go
  pkg/manager/task_generate_markers.go
  pkg/manager/task_generate_phash.go
  pkg/manager/task_generate_preview.go
  pkg/manager/task_generate_screenshot.go
  pkg/manager/task_generate_sprite.go
  pkg/manager/task_import.go
  pkg/manager/task_migrate_hash.go
  pkg/manager/task_scan.go
  pkg/manager/task_stash_box_tag.go
  pkg/manager/task_transcode.go
Labels: chore

#1753 Escape all regexp control characters
  pkg/autotag/performer_test.go
  pkg/autotag/studio_test.go
  pkg/autotag/tag_test.go
  pkg/autotag/tagger.go
  ui/v2.5/src/components/Changelog/versions/v0100.md
Labels: bug

#1655 Improve image scanning performance and thumbnail generation
  docker/build/x86_64/Dockerfile
  docker/ci/x86_64/Dockerfile
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  graphql/schema/types/metadata.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/api/routes_image.go
  pkg/image/image.go
  pkg/image/thumbnail.go
  pkg/manager/config/config.go
  pkg/manager/task_scan.go
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#1747 Lint checks phase 2
  pkg/api/resolver_mutation_metadata.go
  pkg/database/custom_migrations.go
  pkg/database/database.go
  pkg/database/transaction.go
  pkg/dlna/dms.go
  pkg/ffmpeg/encoder.go
  pkg/ffmpeg/stream.go
  pkg/image/image.go
  pkg/manager/config/config.go
  pkg/manager/config/config_concurrency_test.go
  pkg/manager/manager.go
  pkg/manager/task_export.go
  pkg/manager/task_generate_markers.go
  pkg/manager/task_stash_box_tag.go
  pkg/models/transaction.go
  pkg/scraper/script.go
  pkg/scraper/xpath.go
  pkg/sqlite/filter.go
  pkg/sqlite/query.go
  pkg/tag/update_test.go
  pkg/utils/boolean.go
  pkg/utils/oshash_internal_test.go
Labels: chore

#1767 Disable vips in Windows
  pkg/image/thumbnail.go
Labels: bug

#1770 Remove last jwt-go references
  go.mod
  go.sum
  vendor/modules.txt
Labels: chore

#1763 Add date & details to gallery card
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/utils/navigation.ts
Labels: improvement

#1765 Fix list state navigation
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/models/list-filter/filter.ts
Labels: bug

#1758 Movie card visual consistency
  graphql/documents/data/movie-slim.graphql
  graphql/documents/data/movie.graphql
  graphql/schema/types/movie.graphql
  pkg/api/resolver_model_movie.go
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/Movies/MovieCard.tsx
  ui/v2.5/src/components/Movies/styles.scss
Labels: improvement

#1759 Add golangci-lint workflow
  .github/workflows/build.yml
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
  README.md
  revive.toml
  scripts/check-gofmt.sh
Labels: chore

#1772 refactor: move from io/ioutil to io and os package
  pkg/api/check_version.go
  pkg/api/images.go
  pkg/api/resolver_mutation_metadata.go
  pkg/api/server.go
  pkg/autotag/integration_test.go
  pkg/dlna/dms.go
  pkg/ffmpeg/encoder.go
  pkg/ffmpeg/stream.go
  pkg/image/image.go
  pkg/manager/config/config.go
  pkg/manager/generator_sprite.go
  pkg/manager/jsonschema/utils.go
  pkg/manager/paths/paths_generated.go
  pkg/manager/task_export.go
  pkg/manager/task_generate_screenshot.go
  pkg/plugin/examples/goraw/main.go
  pkg/plugin/raw.go
  pkg/scraper/image.go
  pkg/scraper/json.go
  pkg/scraper/stashbox/stash_box.go
  pkg/scraper/url.go
  pkg/sqlite/setup_test.go
  pkg/utils/file.go
  pkg/utils/file_test.go
  pkg/utils/image.go
Labels: chore

#1760 Add movie count to performer and studio card
  graphql/documents/data/performer.graphql
  graphql/documents/data/studio.graphql
  graphql/schema/types/performer.graphql
  graphql/schema/types/studio.graphql
  pkg/api/resolver_model_performer.go
  pkg/api/resolver_model_studio.go
  pkg/models/mocks/MovieReaderWriter.go
  pkg/models/movie.go
  pkg/sqlite/movies.go
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Shared/PopoverCountButton.tsx
  ui/v2.5/src/components/Studios/StudioCard.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioPerformersPanel.tsx
  ui/v2.5/src/utils/navigation.ts
Labels: improvement

#1777 Fix scene marker sort by scene updated SQL error
  pkg/sqlite/scene_marker.go
  pkg/sqlite/scene_marker_test.go
Labels: bug

#1778 Accept svg for tag images in file selector
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
Labels: bug

#1779 Don't scan zero length files or directories
  pkg/manager/task_scan.go
  ui/v2.5/src/components/Changelog/versions/v0100.md
Labels: bug

#1781 Fix styling for scene duration on empty system
  ui/v2.5/src/components/Stats.tsx
Labels: bug

#1784 Fix integration-testing in the build action
  .github/workflows/build.yml
Labels: chore

#1783 Remove new-from-rev from the linter
  .golangci.yml
  pkg/api/routes_image.go
  pkg/gallery/export_test.go
  pkg/gallery/import_test.go
  pkg/image/export_test.go
  pkg/image/thumbnail.go
  pkg/movie/export_test.go
  pkg/performer/export_test.go
  pkg/scene/export_test.go
  pkg/sqlite/filter.go
  pkg/studio/export_test.go
  pkg/tag/export_test.go
Labels: chore

#1780 Don't preload videos
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: bug

#1787 Fix broken links
  README.md
  ui/v2.5/src/docs/en/Deduplication.md
Labels: documentation
