Repository stashapp/stash, pull requests merged in 2021-01, with the labels that each got.

#1015 Equalise card styles for movies/galleries/images
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Galleries/styles.scss
  ui/v2.5/src/components/Images/ImageCard.tsx
  ui/v2.5/src/components/Images/styles.scss
  ui/v2.5/src/components/Movies/MovieCard.tsx
  ui/v2.5/src/components/Movies/styles.scss
Labels: improvement

#1022 Strip file extension from scene title when scanning
  graphql/schema/types/metadata.graphql
  pkg/api/routes_scene.go
  pkg/ffmpeg/ffprobe.go
  pkg/manager/manager_tasks.go
  pkg/manager/scene.go
  pkg/manager/task_generate_markers.go
  pkg/manager/task_generate_preview.go
  pkg/manager/task_generate_screenshot.go
  pkg/manager/task_generate_sprite.go
  pkg/manager/task_scan.go
  pkg/manager/task_transcode.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
Labels: improvement

#1036 extend resolutions
  graphql/schema/types/filters.graphql
  pkg/models/querybuilder_gallery.go
  pkg/models/querybuilder_image.go
  pkg/models/querybuilder_scene.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Images/ImageDetails/ImageDetailPanel.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneDetailPanel.tsx
  ui/v2.5/src/models/list-filter/criteria/resolution.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/utils/text.ts
Labels: improvement

#1048 Cache fixes
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/core/createClient.ts
Labels: bug, improvement

#1050 Fix z-index of performer scrape selector and correct no options message
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Shared/Select.tsx
Labels: bug

#1051 Prevent studio from being selected as its own parent
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
Labels: bug

#1053 Add batch delete for performers/tags/studios/movies
  graphql/documents/mutations/movie.graphql
  graphql/documents/mutations/performer.graphql
  graphql/documents/mutations/studio.graphql
  graphql/documents/mutations/tag.graphql
  graphql/schema/schema.graphql
  pkg/api/resolver_mutation_movie.go
  pkg/api/resolver_mutation_performer.go
  pkg/api/resolver_mutation_studio.go
  pkg/api/resolver_mutation_tag.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Images/DeleteImagesDialog.tsx
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/Movies/MovieList.tsx
  ui/v2.5/src/components/Performers/PerformerList.tsx
  ui/v2.5/src/components/Scenes/DeleteScenesDialog.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Shared/DeleteEntityDialog.tsx
  ui/v2.5/src/components/Shared/index.ts
  ui/v2.5/src/components/Studios/StudioList.tsx
  ui/v2.5/src/components/Tags/TagList.tsx
  ui/v2.5/src/core/StashService.ts
Labels: feature

#1035 Fix vtt sprite generation ( issue #1033 )
  go.mod
  go.sum
  pkg/manager/generator_sprite.go
  pkg/utils/file.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  vendor/github.com/bmatcuk/doublestar/v2/.gitignore
  vendor/github.com/bmatcuk/doublestar/v2/.travis.yml
  vendor/github.com/bmatcuk/doublestar/v2/LICENSE
  vendor/github.com/bmatcuk/doublestar/v2/README.md
  vendor/github.com/bmatcuk/doublestar/v2/UPGRADING.md
  vendor/github.com/bmatcuk/doublestar/v2/doublestar.go
  vendor/github.com/bmatcuk/doublestar/v2/go.mod
  vendor/modules.txt
Labels: bug

#1064 Fix interface state storage
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/src/hooks/LocalForage.ts
Labels: bug

#1067 Login to docker before pulling/building
  docker/ci/x86_64/docker_push.sh
Labels: chore

#1069 Add backup database functionality
  graphql/documents/mutations/metadata.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/metadata.graphql
  pkg/api/migrate.go
  pkg/api/resolver_mutation_metadata.go
  pkg/database/database.go
  pkg/models/model_scene.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/core/StashService.ts
Labels: feature

#1076 Fix database reset
  pkg/database/database.go
Labels: bug

#1075 Update javascript libraries
  ui/v2.5/.eslintrc.json
  ui/v2.5/package.json
  ui/v2.5/src/components/Galleries/EditGalleriesDialog.tsx
  ui/v2.5/src/components/Images/EditImagesDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Scenes/EditScenesDialog.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkersPanel.tsx
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Tags/TagList.tsx
  ui/v2.5/yarn.lock
Labels: chore

#1080 Fix performer scrape select, and studio/gallery select glitching
  ui/v2.5/src/components/Shared/Select.tsx
Labels: bug

#1073 Force reload of custom css if it's updated
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
Labels: improvement

#1081 Add Dry Run option to clean task
  graphql/documents/mutations/metadata.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/metadata.graphql
  pkg/api/resolver_mutation_metadata.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_clean.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/core/StashService.ts
Labels: improvement

#1079 Make file upload limits configurable
  pkg/api/server.go
  pkg/manager/config/config.go
  pkg/manager/task_import.go
  pkg/models/sql.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/docs/en/Configuration.md
Labels: improvement

#1083 Update javascript polyfills
  ui/v2.5/package.json
  ui/v2.5/src/App.tsx
  ui/v2.5/src/globals.d.ts
  ui/v2.5/src/polyfills.ts
  ui/v2.5/yarn.lock
Labels: bug

#1085 Fix import file copying
  pkg/api/resolver_mutation_metadata.go
  pkg/manager/task_import.go
Labels: bug

#1091 Fixing Freeone Scraper
  pkg/scraper/freeones.go
Labels: bug
