Repository stashapp/stash, pull requests merged in 2021-05, with the labels that each got.

#1340 Revert always show preview videos on small devices
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/components/Scenes/styles.scss
Labels: bug

#1347 Several syntactical and content changes
  README.md
Labels: documentation

#1345 Autotag support for images and galleries
  graphql/schema/types/filters.graphql
  pkg/autotag/gallery.go
  pkg/autotag/gallery_test.go
  pkg/autotag/image.go
  pkg/autotag/image_test.go
  pkg/autotag/integration_test.go
  pkg/autotag/performer.go
  pkg/autotag/performer_test.go
  pkg/autotag/scene.go
  pkg/autotag/scene_test.go
  pkg/autotag/studio.go
  pkg/autotag/studio_test.go
  pkg/autotag/tag.go
  pkg/autotag/tag_test.go
  pkg/autotag/tagger.go
  pkg/gallery/update.go
  pkg/image/update.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_autotag.go
  pkg/models/model_gallery.go
  pkg/models/model_image.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/image.go
  pkg/sqlite/image_test.go
  pkg/sqlite/setup_test.go
  ui/v2.5/src/components/Changelog/versions/v070.md
Labels: improvement

#1277 Stash-Box Performer Tagger
  graphql/documents/data/scrapers.graphql
  graphql/documents/mutations/stash-box.graphql
  graphql/documents/queries/scrapers/scrapers.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/scraper.graphql
  graphql/stash-box/query.graphql
  pkg/api/resolver_mutation_stash_box.go
  pkg/api/resolver_query_scraper.go
  pkg/manager/job_status.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_stash_box_tag.go
  pkg/models/mocks/PerformerReaderWriter.go
  pkg/models/performer.go
  pkg/scraper/stashbox/graphql/generated_client.go
  pkg/scraper/stashbox/stash_box.go
  pkg/sqlite/performer.go
  pkg/sqlite/scene.go
  pkg/sqlite/studio.go
  ui/v2.5/package.json
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerList.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/components/Tagger/PerformerFieldSelector.tsx
  ui/v2.5/src/components/Tagger/PerformerModal.tsx
  ui/v2.5/src/components/Tagger/PerformerResult.tsx
  ui/v2.5/src/components/Tagger/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/StudioResult.tsx
  ui/v2.5/src/components/Tagger/Tagger.tsx
  ui/v2.5/src/components/Tagger/constants.ts
  ui/v2.5/src/components/Tagger/index.ts
  ui/v2.5/src/components/Tagger/performers/Config.tsx
  ui/v2.5/src/components/Tagger/performers/PerformerTagger.tsx
  ui/v2.5/src/components/Tagger/performers/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/queries.ts
  ui/v2.5/src/components/Tagger/styles.scss
  ui/v2.5/src/components/Tagger/utils.ts
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
  ui/v2.5/src/models/list-filter/criteria/utils.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/utils/text.ts
  ui/v2.5/yarn.lock
Labels: feature

#1359 Populate image/gallery title during scan
  pkg/image/image.go
  pkg/manager/task_scan.go
  pkg/utils/file.go
  ui/v2.5/src/components/Changelog/versions/v070.md
Labels: bug

#1358 Fix initial plugins/scrapers paths when initialising in home directory
  pkg/manager/config/config.go
  pkg/manager/config/init.go
  pkg/manager/manager.go
  ui/v2.5/src/components/Setup/Setup.tsx
Labels: bug

#1316 Add in-memory screenshot generation for sprites and phash
  pkg/ffmpeg/encoder.go
  pkg/ffmpeg/encoder_sprite_screenshot.go
  pkg/ffmpeg/encoder_transcode.go
  pkg/manager/generator_phash.go
  pkg/manager/generator_sprite.go
  ui/v2.5/src/components/Changelog/versions/v070.md
Labels: improvement

#1370 Remove unnecessary graphql fields
  graphql/documents/data/gallery-slim.graphql
  graphql/documents/data/gallery.graphql
  graphql/documents/data/image.graphql
  graphql/documents/data/movie.graphql
  graphql/documents/data/performer.graphql
  graphql/documents/data/scene.graphql
  graphql/documents/data/tag-slim.graphql
  graphql/documents/queries/gallery.graphql
  pkg/sqlite/filter.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/scene.go
  ui/v2.5/src/components/Galleries/EditGalleriesDialog.tsx
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScenesPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryList.tsx
  ui/v2.5/src/components/Galleries/GalleryWallCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneGalleriesPanel.tsx
  ui/v2.5/src/hooks/ListHook.tsx
Labels: bug

#1380 Fix initial setup issue issues
  graphql/documents/queries/settings/metadata.graphql
  graphql/schema/types/metadata.graphql
  pkg/manager/config/config.go
  pkg/manager/config/init.go
  pkg/manager/manager.go
  ui/v2.5/src/components/Setup/Setup.tsx
Labels: bug

#1295 Github build action refinement and caching
  .github/workflows/build.yml
  Makefile
  scripts/cross-compile.sh
Labels: chore

#1378 Add option to remove studio stash ids
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/v080.md
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
Labels: improvement

#1388 fix DirExists
  pkg/utils/file.go
  pkg/utils/file_test.go
Labels: bug

#1382 Shortcut scan walk for excluded folders
  pkg/manager/task_scan.go
  ui/v2.5/src/components/Changelog/versions/v080.md
  ui/v2.5/src/docs/en/Configuration.md
Labels: improvement

#1384 Make ffmpeg download location more portable
  pkg/api/resolver_mutation_metadata.go
  pkg/ffmpeg/downloader.go
  pkg/manager/manager.go
  pkg/manager/manager_tasks.go
  ui/v2.5/src/components/Setup/Setup.tsx
Labels: improvement

#1375 i18n: Add zh-TW localization strings
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/locale/index.ts
  ui/v2.5/src/locale/zh-TW.json
Labels: improvement

#1403 Clamp page to max pages
  ui/v2.5/src/hooks/ListHook.tsx
Labels: bug

#1399 Add subtractDays pp action to scraper
  pkg/scraper/mapped.go
  ui/v2.5/src/components/Changelog/versions/v080.md
  ui/v2.5/src/docs/en/Scraping.md
Labels: improvement

#1387 Apply all post processors to performer
  pkg/scraper/scrapers.go
  ui/v2.5/src/components/Changelog/versions/v080.md
Labels: bug

#1405 Studio Performers page
  graphql/schema/types/filters.graphql
  pkg/sqlite/performer.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/setup_test.go
  ui/v2.5/src/components/Changelog/versions/v080.md
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Performers/PerformerList.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioPerformersPanel.tsx
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/utils/navigation.ts
Labels: bounty, improvement

#1377 Add Handy / Funscript support
  graphql/documents/data/config.graphql
  graphql/documents/data/scene-slim.graphql
  graphql/documents/data/scene.graphql
  graphql/schema/types/config.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/scene.graphql
  pkg/api/resolver_model_scene.go
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/api/routes_scene.go
  pkg/api/urlbuilders/scene.go
  pkg/database/database.go
  pkg/database/migrations/23_scenes_interactive.up.sql
  pkg/manager/config/config.go
  pkg/manager/task_scan.go
  pkg/models/model_scene.go
  pkg/sqlite/scene.go
  pkg/utils/file.go
  ui/v2.5/package.json
  ui/v2.5/src/components/Changelog/versions/v080.md
  ui/v2.5/src/components/Help/Manual.tsx
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/ScenePlayerScrubber.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/docs/en/Interactive.md
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/interactive.ts
  ui/v2.5/src/models/list-filter/criteria/utils.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/utils/interactive.ts
  ui/v2.5/yarn.lock
Labels: feature

#1379 Job queueing
  graphql/documents/data/job.graphql
  graphql/documents/mutations/job.graphql
  graphql/documents/mutations/metadata.graphql
  graphql/documents/queries/job.graphql
  graphql/documents/queries/settings/metadata.graphql
  graphql/documents/subscriptions.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/job.graphql
  graphql/schema/types/metadata.graphql
  pkg/api/resolver_mutation_job.go
  pkg/api/resolver_mutation_metadata.go
  pkg/api/resolver_mutation_stash_box.go
  pkg/api/resolver_query_job.go
  pkg/api/resolver_query_metadata.go
  pkg/api/resolver_subscription_job.go
  pkg/api/resolver_subscription_metadata.go
  pkg/job/job.go
  pkg/job/manager.go
  pkg/job/manager_test.go
  pkg/job/progress.go
  pkg/job/progress_test.go
  pkg/job/subscribe.go
  pkg/manager/job_status.go
  pkg/manager/manager.go
  pkg/manager/manager_tasks.go
  pkg/manager/subscribe.go
  pkg/manager/task.go
  pkg/manager/task_autotag.go
  pkg/manager/task_export.go
  pkg/manager/task_import.go
  pkg/manager/task_plugin.go
  pkg/manager/task_scan.go
  pkg/manager/task_stash_box_tag.go
  ui/v2.5/src/components/Changelog/versions/v080.md
  ui/v2.5/src/components/Settings/SettingsTasksPanel/GenerateButton.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/JobTable.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/components/Settings/styles.scss
  ui/v2.5/src/components/Tagger/performers/PerformerTagger.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/core/createClient.ts
  ui/v2.5/src/styles/_theme.scss
Labels: feature

#1411 add REACT_APP_PLATFORM_PORT for development
  README.md
  ui/v2.5/src/core/createClient.ts
Labels: chore

#1413 Fix performer filters and sort keys
  pkg/sqlite/performer.go
  pkg/sqlite/performer_test.go
Labels: bug

#1417 Fix: file close even if file was not opened
  pkg/manager/jsonschema/gallery.go
  pkg/manager/jsonschema/image.go
  pkg/manager/jsonschema/mappings.go
  pkg/manager/jsonschema/movie.go
  pkg/manager/jsonschema/performer.go
  pkg/manager/jsonschema/scene.go
  pkg/manager/jsonschema/scraped.go
  pkg/manager/jsonschema/studio.go
  pkg/manager/jsonschema/tag.go
  pkg/plugin/config.go
  pkg/scraper/config.go
Labels: bug

#1416 Fix: login form label references
  ui/login/login.html
Labels: bug

#1414 Remove performer "is missing scenes" filter
  pkg/sqlite/performer.go
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
Labels: chore

#1381 This adds extra libraries required by scrapers
  docker/ci/x86_64/Dockerfile
Labels: improvement

#1421 Add `CreatedAt` & `UpdatedAt` to all object resolvers
  graphql/schema/types/gallery.graphql
  graphql/schema/types/image.graphql
  graphql/schema/types/movie.graphql
  graphql/schema/types/performer.graphql
  graphql/schema/types/scene-marker.graphql
  graphql/schema/types/scene.graphql
  graphql/schema/types/studio.graphql
  graphql/schema/types/tag.graphql
  pkg/api/resolver_model_gallery.go
  pkg/api/resolver_model_image.go
  pkg/api/resolver_model_movie.go
  pkg/api/resolver_model_performer.go
  pkg/api/resolver_model_scene.go
  pkg/api/resolver_model_scene_marker.go
  pkg/api/resolver_model_studio.go
  pkg/api/resolver_model_tag.go
  ui/v2.5/src/components/Changelog/versions/v080.md
  ui/v2.5/src/components/Scenes/SceneDetails/PrimaryTags.tsx
  ui/v2.5/src/components/Scenes/SceneListTable.tsx
  ui/v2.5/src/components/Shared/MultiSet.tsx
  ui/v2.5/src/components/Shared/Select.tsx
Labels: improvement

#1422 Cleanup fixes
  pkg/api/changeset_translator.go
  pkg/api/resolver.go
  pkg/api/resolver_model_scene.go
  pkg/manager/exclude_files.go
  pkg/manager/jsonschema/utils.go
  pkg/manager/task_transcode.go
  pkg/scraper/cookies.go
  pkg/scraper/mapped.go
  pkg/scraper/stashbox/stash_box.go
Labels: chore

#1425 Fix invalid scene queue generated link
  ui/v2.5/src/components/Changelog/versions/v080.md
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: bug

#1284 utils: vtt: test + rewrite
  pkg/utils/vtt.go
  pkg/utils/vtt_test.go
Labels: chore

#1285 utils: oshash: add tests
  pkg/utils/oshash.go
  pkg/utils/oshash_internal_test.go
Labels: chore

#1428 Revert scrubber debounce
  ui/v2.5/src/components/ScenePlayer/ScenePlayerScrubber.tsx
Labels: bug

#1419 Fix: unhandled errors
  pkg/api/resolver_mutation_scene.go
  pkg/api/resolver_query_configuration.go
  pkg/api/resolver_query_find_image.go
  pkg/api/resolver_query_find_scene.go
  pkg/ffmpeg/downloader.go
  pkg/manager/generator_sprite.go
  pkg/manager/task_stash_box_tag.go
  pkg/utils/file.go
Labels: chore

#1431 Fix scraper date parser failing when parsing time
  pkg/scraper/mapped.go
  ui/v2.5/src/components/Changelog/versions/v080.md
Labels: bug

#1412 Tag aliases
  graphql/documents/data/scene-marker.graphql
  graphql/documents/data/tag-slim.graphql
  graphql/documents/data/tag.graphql
  graphql/documents/mutations/tag.graphql
  graphql/documents/queries/misc.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/tag.graphql
  pkg/api/resolver_model_tag.go
  pkg/api/resolver_mutation_tag.go
  pkg/api/resolver_mutation_tag_test.go
  pkg/autotag/integration_test.go
  pkg/autotag/tag.go
  pkg/autotag/tag_test.go
  pkg/database/database.go
  pkg/database/migrations/24_tag_aliases.up.sql
  pkg/manager/filename_parser.go
  pkg/manager/jsonschema/tag.go
  pkg/manager/tag.go
  pkg/manager/task_autotag.go
  pkg/models/mocks/PerformerReaderWriter.go
  pkg/models/mocks/TagReaderWriter.go
  pkg/models/model_tag.go
  pkg/models/tag.go
  pkg/scraper/matchers.go
  pkg/sqlite/filter.go
  pkg/sqlite/repository.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/tag.go
  pkg/sqlite/tag_test.go
  pkg/tag/export.go
  pkg/tag/export_test.go
  pkg/tag/import.go
  pkg/tag/import_test.go
  pkg/tag/query.go
  pkg/tag/update.go
  ui/v2.5/src/components/Changelog/versions/v080.md
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Shared/StringListInput.tsx
  ui/v2.5/src/components/Tagger/queries.ts
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagDetailsPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
  ui/v2.5/src/components/Tags/styles.scss
  ui/v2.5/src/core/StashService.ts
Labels: bounty, feature

#1436 Fix scraped tag creation
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
Labels: bug

#1448 Fix sort by movies_scene_number
  pkg/sqlite/scene.go
Labels: bug

#1406 UI filter refactor
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Changelog/versions/v080.md
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryAddPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryImagesPanel.tsx
  ui/v2.5/src/components/List/AddFilter.tsx
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieScenesPanel.tsx
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioChildrenPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagMarkersPanel.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/core/performers.ts
  ui/v2.5/src/core/studios.ts
  ui/v2.5/src/core/tags.ts
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/src/locale/README.md
  ui/v2.5/src/locale/en-GB.json
  ui/v2.5/src/locale/en-US.json
  ui/v2.5/src/locale/zh-TW.json
  ui/v2.5/src/models/list-filter/criteria/country.ts
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/factory.ts
  ui/v2.5/src/models/list-filter/criteria/favorite.ts
  ui/v2.5/src/models/list-filter/criteria/galleries.ts
  ui/v2.5/src/models/list-filter/criteria/gender.ts
  ui/v2.5/src/models/list-filter/criteria/has-markers.ts
  ui/v2.5/src/models/list-filter/criteria/interactive.ts
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
  ui/v2.5/src/models/list-filter/criteria/movies.ts
  ui/v2.5/src/models/list-filter/criteria/none.ts
  ui/v2.5/src/models/list-filter/criteria/organized.ts
  ui/v2.5/src/models/list-filter/criteria/performers.ts
  ui/v2.5/src/models/list-filter/criteria/rating.ts
  ui/v2.5/src/models/list-filter/criteria/resolution.ts
  ui/v2.5/src/models/list-filter/criteria/studios.ts
  ui/v2.5/src/models/list-filter/criteria/tags.ts
  ui/v2.5/src/models/list-filter/factory.ts
  ui/v2.5/src/models/list-filter/filter-options.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/models/list-filter/galleries.ts
  ui/v2.5/src/models/list-filter/images.ts
  ui/v2.5/src/models/list-filter/movies.ts
  ui/v2.5/src/models/list-filter/performers.ts
  ui/v2.5/src/models/list-filter/scene-markers.ts
  ui/v2.5/src/models/list-filter/scenes.ts
  ui/v2.5/src/models/list-filter/studios.ts
  ui/v2.5/src/models/list-filter/tags.ts
  ui/v2.5/src/models/list-filter/types.ts
  ui/v2.5/src/models/sceneQueue.ts
  ui/v2.5/src/utils/navigation.ts
Labels: chore

#1415 Deprecation Fix: Updated gqlgen server handler initialization
  pkg/api/server.go
Labels: chore

#1456 Small UI filter fixes
  ui/v2.5/src/components/List/AddFilter.tsx
  ui/v2.5/src/models/list-filter/criteria/interactive.ts
Labels: bug, improvement

#1435 Make multiset mode buttons more obvious
  ui/v2.5/src/components/Changelog/versions/v080.md
  ui/v2.5/src/components/Shared/MultiSet.tsx
  ui/v2.5/src/index.scss
Labels: improvement
