Repository stashapp/stash, pull requests merged in 2021-10, with the labels that each got.

#1746 Filter tag by hierarchy
  graphql/schema/types/filters.graphql
  pkg/sqlite/setup_test.go
  pkg/sqlite/tag.go
  pkg/sqlite/tag_test.go
  scripts/test_db_generator/config.yml
  scripts/test_db_generator/makeTestDB.go
  scripts/test_db_generator/naming.go
  ui/v2.5/src/components/List/Filters/HierarchicalLabelValueFilter.tsx
  ui/v2.5/src/components/List/Filters/LabeledIdFilter.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/criteria/factory.ts
  ui/v2.5/src/models/list-filter/criteria/tags.ts
  ui/v2.5/src/models/list-filter/tags.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: feature

#1708 Lightbox pan, zoom and display mode options
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/Lightbox/LightboxImage.tsx
  ui/v2.5/src/hooks/Lightbox/context.tsx
  ui/v2.5/src/hooks/Lightbox/lightbox.scss
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/styles/_theme.scss
Labels: feature, bounty

#1750 Only group by if using having clauses
  pkg/sqlite/repository.go
  pkg/sqlite/tag.go
  pkg/sqlite/tag_test.go
  ui/v2.5/src/components/Changelog/versions/v0100.md
Labels: improvement

#1689 Add container_name to docker compose
  docker/production/docker-compose.yml
Labels: improvement

#1764 Fix video player sizing
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/ScenePlayer/styles.scss
Labels: bug

#1793 Fix Studios -> Stash ID filter
  pkg/sqlite/studio.go
  pkg/sqlite/studio_test.go
Labels: bug

#1791 Don't show studio error message while loading
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
Labels: bug

#1782 Allow setting metadata directory from UI
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#1792 Add parent/sub-tags to tag cards
  ui/v2.5/src/components/Tags/TagCard.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/utils/navigation.ts
Labels: improvement

#1786 Enable safe linters
  .golangci.yml
  pkg/autotag/gallery_test.go
  pkg/autotag/image_test.go
  pkg/autotag/performer_test.go
  pkg/autotag/scene_test.go
  pkg/autotag/studio_test.go
  pkg/autotag/tag_test.go
  pkg/logger/plugin.go
  pkg/manager/manager_tasks.go
  pkg/movie/export_test.go
  pkg/performer/export_test.go
  pkg/plugin/args.go
  pkg/scraper/url.go
  pkg/scraper/xpath_test.go
  pkg/studio/export_test.go
Labels: chore

#1797 Fix panic when serving missing marker routes
  pkg/api/routes_scene.go
Labels: bug

#1761 Disallow access in publicly exposed services
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/authentication.go
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/api/server.go
  pkg/manager/config/config.go
  pkg/manager/manager.go
  pkg/session/authentication.go
  ui/v2.5/src/components/Changelog/versions/v0100.md
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#1801 Make generate args optional
  graphql/schema/types/metadata.graphql
  pkg/manager/manager_tasks.go
Labels: improvement

#1808 Revert "Make generate args optional"
  graphql/schema/types/metadata.graphql
  pkg/manager/manager_tasks.go
Labels: bug

#1809 Reimplement: make generate options optional
  graphql/schema/types/metadata.graphql
  pkg/manager/manager_tasks.go
Labels: improvement

#1813 Add classnames to count popovers
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Images/ImageCard.tsx
  ui/v2.5/src/components/Movies/MovieCard.tsx
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Shared/PerformerPopoverButton.tsx
  ui/v2.5/src/components/Shared/PopoverCountButton.tsx
  ui/v2.5/src/components/Studios/StudioCard.tsx
  ui/v2.5/src/components/Tags/TagCard.tsx
Labels: improvement
