Repository stashapp/stash, pull requests merged in 2021-02, with the labels that each got.

#1057 Decouple galleries from scenes
  graphql/documents/data/gallery-slim.graphql
  graphql/documents/data/gallery.graphql
  graphql/documents/data/scene-slim.graphql
  graphql/documents/data/scene.graphql
  graphql/documents/queries/misc.graphql
  graphql/documents/queries/scene.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/gallery.graphql
  graphql/schema/types/scene.graphql
  pkg/api/resolver.go
  pkg/api/resolver_model_gallery.go
  pkg/api/resolver_model_scene.go
  pkg/api/resolver_mutation_gallery.go
  pkg/api/resolver_mutation_scene.go
  pkg/database/database.go
  pkg/database/migrations/18_scene_galleries.up.sql
  pkg/gallery/export.go
  pkg/manager/jsonschema/scene.go
  pkg/manager/scene.go
  pkg/manager/task_export.go
  pkg/manager/task_scan.go
  pkg/models/gallery.go
  pkg/models/mocks/GalleryReaderWriter.go
  pkg/models/mocks/SceneReaderWriter.go
  pkg/models/model_gallery.go
  pkg/models/scene.go
  pkg/scene/export.go
  pkg/scene/export_test.go
  pkg/scene/import.go
  pkg/scene/import_test.go
  pkg/scene/update.go
  pkg/scraper/stashbox/graphql/generated_client.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/setup_test.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Galleries/DeleteGalleriesDialog.tsx
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScenesPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryViewer.tsx
  ui/v2.5/src/components/Galleries/styles.scss
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneGalleriesPanel.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Shared/index.ts
  ui/v2.5/src/components/Tagger/styles.scss
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
Labels: feature

#1082 String regex filter criteria and selective autotag
  graphql/schema/types/filters.graphql
  graphql/schema/types/metadata.graphql
  pkg/api/resolver_mutation_metadata.go
  pkg/api/resolver_query_find_scene.go
  pkg/manager/filename_parser.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_autotag.go
  pkg/manager/task_autotag_test.go
  pkg/manager/task_clean.go
  pkg/models/extension_find_filter.go
  pkg/models/mocks/SceneReaderWriter.go
  pkg/models/scene.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/image_test.go
  pkg/sqlite/query.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/sql.go
  pkg/utils/file.go
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Settings/SettingsTasksPanel/DirectorySelectionDialog.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
Labels: improvement

#1100 Fix scene filename parser
  pkg/manager/filename_parser.go
Labels: bug

#1099 Minor UI tweaks
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Stats.tsx
  ui/v2.5/src/utils/text.ts
Labels: improvement

#1098 Don't delete downloads directory at startup if generated not set
  pkg/manager/manager.go
  pkg/manager/paths/paths_generated.go
  ui/v2.5/src/components/Changelog/versions/v050.md
Labels: bug

#1096 Fix tagger performance issue and date parsing
  ui/v2.5/src/components/Tagger/Tagger.tsx
Labels: bug

#1093 Add checksums for releases
  .travis.yml
  scripts/upload-pull-request.sh
Labels: chore

#921 Add selective cross compile
  scripts/cross-compile.sh
Labels: chore

#1109 fix json unmarshal error return
  pkg/scraper/script.go
Labels: bug

#1107 Tweak scraper script error printing
  pkg/scraper/script.go
Labels: improvement

#1103 fix check version
  pkg/api/check_version.go
  ui/v2.5/src/components/Changelog/versions/v050.md
Labels: bug

#1106 Migrate generated files when a scene is rescanned
  pkg/manager/migrate_hash.go
  pkg/manager/task_migrate_hash.go
  pkg/manager/task_scan.go
  ui/v2.5/src/components/Changelog/versions/v050.md
Labels: bug, improvement

#1117 Add donate button to navbar
  ui/v2.5/src/components/MainNavbar.tsx
  ui/v2.5/src/index.scss
Labels: improvement

#1118 Exclude media in generated directory
  pkg/manager/task_clean.go
  pkg/manager/task_scan.go
  ui/v2.5/src/components/Changelog/versions/v050.md
Labels: bug

#1112 Fix scene edit state resetting when scene is updated
  ui/v2.5/src/components/Changelog/versions/v050.md
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
Labels: bug

#1097 build arm and x86_64 docker containers
  .travis.yml
  docker/ci/x86_64/Dockerfile
  docker/ci/x86_64/docker_push.sh
Labels: chore

#1121 Add short names for Iran and Moldova
  ui/v2.5/src/utils/country.ts
Labels: improvement

#1133 Fix performer input values being lost when failing to create
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
Labels: bug

#1119 Add rescan option to overflow dropdown
  graphql/schema/types/metadata.graphql
  pkg/image/image.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_scan.go
  pkg/utils/boolean.go
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/v060.md
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Images/ImageDetails/Image.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
Labels: improvement

#1134 Enable keepalive for websocket connection
  pkg/api/server.go
Labels: bug

#1122 Random strings for cookie values
  pkg/scraper/config.go
  pkg/scraper/cookies.go
  pkg/utils/strings.go
  ui/v2.5/src/components/Changelog/versions/v060.md
  ui/v2.5/src/docs/en/Scraping.md
Labels: improvement

#1146 GitHub actions
  .github/workflows/build.yml
  .travis.yml.disabled
  scripts/check-gofmt.sh
  scripts/cross-compile.sh
Labels: chore

#1104 Mobile UI improvements
  ui/v2.5/package.json
  ui/v2.5/src/components/Changelog/versions/v060.md
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/OCounterButton.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Wall/WallItem.tsx
  ui/v2.5/src/polyfills.ts
  ui/v2.5/src/styles/_theme.scss
  ui/v2.5/yarn.lock
Labels: bug, improvement
