Repository stashapp/stash, pull requests merged in 2021-04, with the labels that each got.

#1247 Disable sounds on scene/marker wall previews by default
  pkg/manager/config/config.go
  ui/v2.5/src/components/Changelog/versions/v070.md
Labels: improvement

#1248 Upgrade x/image
  go.mod
  go.sum
  ui/v2.5/src/components/Changelog/versions/v070.md
  vendor/golang.org/x/image/bmp/reader.go
  vendor/golang.org/x/image/ccitt/reader.go
  vendor/golang.org/x/image/ccitt/table.go
  vendor/golang.org/x/image/tiff/fuzz.go
  vendor/golang.org/x/image/tiff/lzw/reader.go
  vendor/golang.org/x/image/tiff/reader.go
  vendor/golang.org/x/image/webp/decode.go
  vendor/modules.txt
Labels: bug, chore

#1251 Fix performer age timezone issues
  ui/v2.5/src/utils/text.ts
Labels: bug

#1250 Added random for studios, movies and tags
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/models/list-filter/filter.ts
Labels: improvement

#1271 Update various GQL `image` fields' comments
  graphql/schema/types/movie.graphql
  graphql/schema/types/performer.graphql
  graphql/schema/types/scene.graphql
  graphql/schema/types/scraped-movie.graphql
  graphql/schema/types/scraped-performer.graphql
  graphql/schema/types/scraper.graphql
  graphql/schema/types/studio.graphql
  graphql/schema/types/tag.graphql
Labels: chore

#1261 Support today,yesterday when using parseDate in scrapers
  pkg/scraper/mapped.go
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/docs/en/Scraping.md
Labels: improvement

#1264 Handle /healthz for liveness checks.
  pkg/api/server.go
  ui/v2.5/src/components/Changelog/versions/v070.md
Labels: improvement

#1249 Fix "Clear Image" button
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
Labels: bug

#1266 added an url filter option in scenes
  graphql/schema/types/filters.graphql
  pkg/sqlite/filter.go
  pkg/sqlite/filter_internal_test.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/movies.go
  pkg/sqlite/movies_test.go
  pkg/sqlite/performer.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/studio.go
  pkg/sqlite/studio_test.go
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/utils.ts
  ui/v2.5/src/models/list-filter/filter.ts
Labels: improvement

#1270 Added Auto scroll user back to the top when page navigation is clicked
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/hooks/ListHook.tsx
Labels: improvement

#1275 Remove external resource from Login page
  ui/login/login.css
  ui/login/login.html
  ui/v2.5/src/components/Changelog/versions/v070.md
Labels: bug

#1254 Join count filter criteria
  graphql/schema/types/filters.graphql
  pkg/sqlite/filter.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/image.go
  pkg/sqlite/image_test.go
  pkg/sqlite/performer.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/query.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/sql.go
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/utils.ts
  ui/v2.5/src/models/list-filter/filter.ts
Labels: improvement

#1190 Setup and migration UI refactor
  docker/build/x86_64/Dockerfile
  docker/ci/x86_64/Dockerfile
  docker/develop/x86_64/Dockerfile
  docker/production/x86_64/Dockerfile
  graphql/documents/mutations/config.graphql
  graphql/documents/queries/settings/metadata.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/config.graphql
  graphql/schema/types/metadata.graphql
  main.go
  pkg/api/migrate.go
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_mutation_metadata.go
  pkg/api/resolver_mutation_plugin.go
  pkg/api/resolver_mutation_scene.go
  pkg/api/resolver_mutation_stash_box.go
  pkg/api/resolver_query_configuration.go
  pkg/api/resolver_query_metadata.go
  pkg/api/resolver_query_scene.go
  pkg/api/resolver_query_scraper.go
  pkg/api/routes_scene.go
  pkg/api/server.go
  pkg/api/session.go
  pkg/database/database.go
  pkg/manager/apikey.go
  pkg/manager/checksum.go
  pkg/manager/config/config.go
  pkg/manager/config/init.go
  pkg/manager/manager.go
  pkg/manager/manager_tasks.go
  pkg/manager/paths/paths.go
  pkg/manager/paths/paths_generated.go
  pkg/manager/scene.go
  pkg/manager/task_clean.go
  pkg/manager/task_export.go
  pkg/manager/task_import.go
  pkg/manager/task_scan.go
  pkg/manager/task_transcode.go
  pkg/scraper/image.go
  pkg/scraper/scrapers.go
  pkg/scraper/url.go
  pkg/scraper/xpath_test.go
  pkg/sqlite/transaction.go
  ui/setup/index.html
  ui/setup/migrate.html
  ui/setup/milligram.min.css
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/components/Setup/Migrate.tsx
  ui/v2.5/src/components/Setup/Setup.tsx
  ui/v2.5/src/core/StashService.ts
Labels: feature

#1279 Support streaming via API key
  pkg/api/resolver_model_scene.go
  pkg/api/server.go
  pkg/api/urlbuilders/scene.go
  ui/v2.5/src/components/Changelog/versions/v070.md
Labels: improvement

#1263 Whitespace is not trimmed from the end of query strings
  pkg/sqlite/scene_test.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/sql.go
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/models/list-filter/filter.ts
Labels: bug

#1224 [Feature] Added slideshow to gallery in wall display mode
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/hooks/Interval.ts
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/Lightbox/context.tsx
  ui/v2.5/src/hooks/Lightbox/hooks.ts
  ui/v2.5/src/hooks/Lightbox/lightbox.scss
  ui/v2.5/src/hooks/PageVisibility.ts
  ui/v2.5/src/hooks/index.ts
Labels: feature

#1268 Simplify GH build pipeline.
  .github/workflows/build.yml
Labels: chore

#1293 Add scene/image/gallery popover count buttons for performer/studio/tag cards
  graphql/documents/data/performer.graphql
  graphql/documents/data/studio.graphql
  graphql/documents/data/tag.graphql
  graphql/schema/types/performer.graphql
  graphql/schema/types/studio.graphql
  graphql/schema/types/tag.graphql
  pkg/api/resolver_model_performer.go
  pkg/api/resolver_model_studio.go
  pkg/api/resolver_model_tag.go
  pkg/gallery/query.go
  pkg/image/query.go
  pkg/models/gallery.go
  pkg/models/image.go
  pkg/models/mocks/GalleryReaderWriter.go
  pkg/models/mocks/ImageReaderWriter.go
  pkg/models/mocks/SceneReaderWriter.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/image_test.go
  pkg/sqlite/query.go
  pkg/sqlite/repository.go
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Shared/PopoverCountButton.tsx
  ui/v2.5/src/components/Studios/StudioCard.tsx
  ui/v2.5/src/components/Tags/TagCard.tsx
  ui/v2.5/src/utils/navigation.ts
Labels: improvement

#1301 Skip validation of existing paths when adding new paths
  pkg/api/resolver_mutation_configure.go
  ui/v2.5/src/components/Changelog/versions/v070.md
Labels: bug

#1294 Sort performers in popover and card views
  graphql/documents/data/image-slim.graphql
  graphql/documents/data/scene-slim.graphql
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryDetailPanel.tsx
  ui/v2.5/src/components/Images/ImageCard.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageDetailPanel.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneDetailPanel.tsx
  ui/v2.5/src/components/Shared/PerformerPopoverButton.tsx
  ui/v2.5/src/core/performers.ts
Labels: improvement

#1273 Add http headers support to scraper
  pkg/scraper/config.go
  pkg/scraper/url.go
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/docs/en/Scraping.md
Labels: improvement

#1304 Update README with currently used ffmpeg URLs
  README.md
Labels: documentation

#1312 Fix fingerprint search when scene only has phash match
  ui/v2.5/src/components/Tagger/Tagger.tsx
Labels: bug

#1314 Fix performer scraping
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/utils/data.ts
  ui/v2.5/src/utils/index.ts
Labels: bug

#1320 Fix creating performer from gallery scrape dialog
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/core/StashService.ts
Labels: bug

#1307 Add studio `*_count` filters and sort options
  graphql/schema/types/filters.graphql
  pkg/sqlite/image_test.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/studio.go
  pkg/sqlite/studio_test.go
  ui/v2.5/src/models/list-filter/filter.ts
Labels: improvement

#1299 Separate UI
  pkg/api/server.go
  pkg/manager/config/config.go
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/docs/en/Configuration.md
Labels: improvement

#1309 Duplicate checker UI improvements
  pkg/manager/task_autotag.go
  pkg/models/extension_find_filter.go
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/components/SceneDuplicateChecker/SceneDuplicateChecker.tsx
  ui/v2.5/src/components/SceneDuplicateChecker/styles.scss
  ui/v2.5/src/components/Settings/Settings.tsx
  ui/v2.5/src/components/Settings/SettingsDuplicatePanel.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/components/Settings/SettingsToolsPanel.tsx
  ui/v2.5/src/components/Settings/styles.scss
  ui/v2.5/src/index.scss
Labels: improvement

#1321 Overwrite new performer image after clearing current image
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
Labels: bug

#1325 Movie scene sort
  pkg/sqlite/scene.go
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/components/Movies/MovieDetails/MovieScenesPanel.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/src/models/list-filter/filter.ts
Labels: improvement

#1322 Fix various generate issues
  pkg/manager/generator_preview.go
  pkg/manager/manager.go
  pkg/manager/manager_tasks.go
  pkg/utils/time.go
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/docs/en/Tagger.md
Labels: improvement

#1336 Fixed 0 for weight when a new performer is created and fixed the search is null
  graphql/schema/types/filters.graphql
  pkg/sqlite/performer.go
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/models/list-filter/filter.ts
Labels: bug

#1324 Auto tag rewrite
  pkg/autotag/integration_test.go
  pkg/autotag/performer.go
  pkg/autotag/performer_test.go
  pkg/autotag/scene.go
  pkg/autotag/scene_test.go
  pkg/autotag/studio.go
  pkg/autotag/studio_test.go
  pkg/autotag/tag.go
  pkg/autotag/tag_test.go
  pkg/autotag/tagger.go
  pkg/manager/manager_tasks.go
  pkg/manager/task_autotag.go
  pkg/models/extension_find_filter.go
  pkg/models/mocks/PerformerReaderWriter.go
  pkg/models/mocks/StudioReaderWriter.go
  pkg/models/mocks/TagReaderWriter.go
  pkg/models/performer.go
  pkg/models/studio.go
  pkg/models/tag.go
  pkg/sqlite/performer.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/studio.go
  pkg/sqlite/studio_test.go
  pkg/sqlite/tag.go
  pkg/sqlite/tag_test.go
  ui/v2.5/src/components/Changelog/versions/v070.md
Labels: improvement

#1337 Add lbToKg pp action to the scraper
  pkg/scraper/mapped.go
  pkg/scraper/xpath_test.go
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/docs/en/Scraping.md
Labels: feature

#1339 update docs to match current functionality
  graphql/schema/types/filters.graphql
Labels: documentation

#1308 Added rating to performers and studios
  graphql/documents/data/performer-slim.graphql
  graphql/documents/data/performer.graphql
  graphql/documents/data/studio-slim.graphql
  graphql/documents/data/studio.graphql
  graphql/documents/mutations/studio.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/performer.graphql
  graphql/schema/types/studio.graphql
  pkg/api/resolver_model_performer.go
  pkg/api/resolver_model_studio.go
  pkg/api/resolver_mutation_performer.go
  pkg/api/resolver_mutation_studio.go
  pkg/database/database.go
  pkg/database/migrations/22_performers_studios_rating.up.sql
  pkg/manager/jsonschema/performer.go
  pkg/manager/jsonschema/studio.go
  pkg/models/model_performer.go
  pkg/models/model_studio.go
  pkg/performer/export.go
  pkg/performer/export_test.go
  pkg/performer/import.go
  pkg/sqlite/performer.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/studio.go
  pkg/sqlite/studio_test.go
  pkg/studio/export.go
  pkg/studio/export_test.go
  pkg/studio/import.go
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/components/Performers/EditPerformersDialog.tsx
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Shared/Icon.tsx
  ui/v2.5/src/components/Studios/StudioCard.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/docs/en/JSONSpec.md
  ui/v2.5/src/models/list-filter/filter.ts
Labels: bounty, feature

#1329 Memo-ise list hook functions
  ui/v2.5/src/hooks/ListHook.tsx
Labels: bug

#1332 Apply scene queuing for all scene listviews
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneCardsGrid.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Scenes/SceneListTable.tsx
  ui/v2.5/src/components/Tagger/Tagger.tsx
  ui/v2.5/src/components/Wall/WallItem.tsx
  ui/v2.5/src/components/Wall/WallPanel.tsx
  ui/v2.5/src/locale/en-GB.json
  ui/v2.5/src/locale/en-US.json
  ui/v2.5/src/models/sceneQueue.ts
Labels: improvement

#1344 Added new filters (date and title) to galleries
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_test.go
  ui/v2.5/src/models/list-filter/filter.ts
Labels: improvement

#1338 Get distinct values from scraper
  pkg/scraper/mapped.go
  pkg/scraper/xpath_test.go
  pkg/utils/string_collections.go
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/docs/en/Scraping.md
Labels: improvement

#1357 Fix scene tagger bugs
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/components/Tagger/Config.tsx
  ui/v2.5/src/components/Tagger/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/Tagger.tsx
  ui/v2.5/src/components/Tagger/utils.ts
Labels: bug
