Repository stashapp/stash, pull requests merged in 2021-11, with the labels that each got.

#1929 Extend __typename stripper to fix interface config saving
  ui/v2.5/src/utils/data.ts
Labels: bug

#1932 Suppress a benign warning
  pkg/api/routes_studio.go
Labels: improvement

#1930 Fix undefined class in Grid Card
  ui/v2.5/src/components/Shared/GridCard.tsx
Labels: bug, ui

#1935 Clarify AutoTagging.md
  ui/v2.5/src/docs/en/AutoTagging.md
Labels: documentation

#1941 Small docker cleanup
  docker/build/x86_64/README.md
  docker/ci/x86_64/Dockerfile
  docker/production/README.md
  docker/production/x86_64/Dockerfile
Labels: improvement

#1942 Add bottom pagination to scene duplicate checker
  ui/v2.5/src/components/SceneDuplicateChecker/SceneDuplicateChecker.tsx
Labels: improvement, ui

#1947 Fix checkbox labels
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/components/Settings/SettingsDLNAPanel.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
Labels: bug

#1943 Add linux ffmpeg urls
  pkg/ffmpeg/downloader.go
Labels: improvement

#1934 Update and split up scraping docs
  ui/v2.5/src/components/Help/Manual.tsx
  ui/v2.5/src/docs/en/ScraperDevelopment.md
  ui/v2.5/src/docs/en/Scraping.md
Labels: documentation

#1944 File size scanning fixes
  pkg/file/scan.go
  pkg/gallery/scan.go
Labels: bug

#1769 Rework main navbar
  ui/v2.5/src/components/Changelog/versions/v0110.md
  ui/v2.5/src/components/MainNavbar.tsx
  ui/v2.5/src/index.scss
Labels: improvement, ui

#1952 Fix exclusion pattern inputs blurring on every keypress
  ui/v2.5/src/components/Changelog/versions/v0110.md
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/components/Settings/SettingsScrapingPanel.tsx
  ui/v2.5/src/components/Shared/StringListInput.tsx
  ui/v2.5/src/components/Shared/styles.scss
Labels: bug

#1955 Support StashIDs in scrape dialog
  ui/v2.5/src/components/Changelog/versions/v0110.md
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
Labels: bug

#1953 Move scene post update hook to outside Identify transaction
  pkg/api/resolver_model_scene.go
  pkg/identify/identify.go
  pkg/manager/task_identify.go
Labels: bug

#1926 Fix tag hierarchy validation
  pkg/api/resolver_mutation_tag.go
  pkg/models/mocks/TagReaderWriter.go
  pkg/models/model_tag.go
  pkg/models/tag.go
  pkg/sqlite/tag.go
  pkg/tag/update.go
  pkg/tag/update_test.go
  ui/v2.5/src/components/Changelog/versions/v0110.md
  ui/v2.5/src/index.scss
Labels: bug

#1785 Support Is (not) null for all multi criterions
  pkg/sqlite/filter.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/image.go
  pkg/sqlite/image_test.go
  pkg/sqlite/movies.go
  pkg/sqlite/performer.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_marker.go
  pkg/sqlite/scene_marker_test.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/tag.go
  pkg/sqlite/tag_test.go
  ui/v2.5/src/components/Changelog/versions/v0110.md
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
Labels: feature

#1921 Add display autoplay and playlist continue options
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
  pkg/manager/config/config_concurrency_test.go
  ui/v2.5/src/components/Changelog/versions/v0110.md
  ui/v2.5/src/components/Galleries/GalleryList.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/QueueViewer.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/components/Tagger/scenes/SceneTagger.tsx
  ui/v2.5/src/components/Wall/WallItem.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/sceneQueue.ts
Labels: feature

#1966 Fix Scenes Detail tab string
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
Labels: bug, ui

#1963 change translation typo error
  ui/v2.5/src/locales/zh-CN.json
Labels: documentation, ui

#1898 Improve flag and environment config overrides
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/api/server.go
  pkg/manager/config/config.go
  pkg/manager/config/config_concurrency_test.go
  pkg/manager/config/init.go
  pkg/manager/manager.go
  ui/v2.5/src/components/Setup/Setup.tsx
Labels: bug, improvement

#1967 French translation (fr-FR)
  pkg/api/locale.go
  ui/v2.5/src/components/Changelog/versions/v0110.md
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/locales/fr-FR.json
  ui/v2.5/src/locales/index.ts
Labels: documentation, ui

#1956 Update scene filename parser input styling
  ui/v2.5/src/components/SceneFilenameParser/SceneParserRow.tsx
  ui/v2.5/src/components/SceneFilenameParser/styles.scss
  ui/v2.5/src/index.scss
Labels: improvement, ui

#1980 Spiffy Readme
  .goreleaser.yml
  .travis.yml.disabled
  README.md
  docs/DEVELOPMENT.md
  docs/readme_assets/demo_image.png
  docs/readme_assets/docker_logo.svg
  docs/readme_assets/linux_logo.svg
  docs/readme_assets/mac_logo.svg
  docs/readme_assets/windows_logo.svg
Labels: documentation

#1979 Fix identify defaults always returning nil
  pkg/manager/config/config.go
Labels: bug

#1983 Confirm empty stash paths
  ui/v2.5/src/components/Setup/Setup.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: improvement, ui

#1985 Readme: Move floating link up to the top
  README.md
Labels: documentation

#1977 Fix performer tagger field updating
  pkg/scraper/stashbox/stash_box.go
  ui/v2.5/src/components/Tagger/PerformerFieldSelector.tsx
  ui/v2.5/src/components/Tagger/PerformerModal.tsx
  ui/v2.5/src/components/Tagger/constants.ts
Labels: bug

#1990 Apply python path resolution to plugins
  docker/ci/x86_64/Dockerfile
  pkg/plugin/raw.go
Labels: bug

#1996 Fix config path regression
  pkg/manager/config/init.go
Labels: bug, bug-verified

#2004 Fix entity creation bug during tag/performer scraping
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
Labels: bug

#2005 Fix invalid baseurl if host header already contains port
  pkg/api/server.go
Labels: bug

#2006 Resolve performer/studio stashIDs for scraped scenes
  pkg/match/scraped.go
  pkg/models/mocks/PerformerReaderWriter.go
  pkg/models/mocks/StudioReaderWriter.go
  pkg/models/performer.go
  pkg/models/studio.go
  pkg/scraper/scrapers.go
  pkg/scraper/stashbox/stash_box.go
  pkg/sqlite/performer.go
  pkg/sqlite/studio.go
Labels: bug

#2007 Fix trace loglevel
  graphql/schema/types/logging.graphql
  pkg/api/resolver_subscription_logging.go
Labels: bug, bug-verified

#1971 V0.11.0 User Survey
  ui/v2.5/src/components/Changelog/versions/v0110.md
Labels: documentation

#2013 Merge master back to develop for tag
  ui/v2.5/src/locales/zh-CN.json
Labels: chore

#1998 i18n: Update zh-tw & refactor various strings
  ui/v2.5/src/components/Galleries/DeleteGalleriesDialog.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Images/DeleteImagesDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerOperationsPanel.tsx
  ui/v2.5/src/components/Scenes/DeleteScenesDialog.tsx
  ui/v2.5/src/components/Scenes/SceneGenerateDialog.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/ImportDialog.tsx
  ui/v2.5/src/locales/de-DE.json
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/es-ES.json
  ui/v2.5/src/locales/fr-FR.json
  ui/v2.5/src/locales/it-IT.json
  ui/v2.5/src/locales/pt-BR.json
  ui/v2.5/src/locales/sv-SE.json
  ui/v2.5/src/locales/zh-CN.json
  ui/v2.5/src/locales/zh-TW.json
Labels: improvement

#2017 Only add image files to `imageBox` files slice
  pkg/api/images.go
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/v0120.md
Labels: bug

#2025 Add Translation section to Readme
  README.md
Labels: documentation

#2018 (Automated!) Translation updates
  ui/v2.5/src/locales/de-DE.json
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/es-ES.json
  ui/v2.5/src/locales/it-IT.json
  ui/v2.5/src/locales/zh-CN.json
Labels: improvement

#2036 Fix incorrect message id
  ui/v2.5/src/components/Scenes/SceneDetails/QueueViewer.tsx
Labels: bug

#1900 Vite-based frontend builds
  Makefile
  docs/DEVELOPMENT.md
  go.mod
  go.sum
  pkg/api/server.go
  ui/v2.5/.babelrc
  ui/v2.5/craco.config.js
  ui/v2.5/index.html
  ui/v2.5/package.json
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Settings/SettingsAboutPanel.tsx
  ui/v2.5/src/components/Shared/MarkdownPage.tsx
  ui/v2.5/src/core/createClient.ts
  ui/v2.5/src/utils/image.tsx
  ui/v2.5/tsconfig.json
  ui/v2.5/vite.config.js
  ui/v2.5/yarn.lock
  vendor/github.com/vearutop/statigz/LICENSE
  vendor/github.com/vearutop/statigz/README.md
  vendor/github.com/vearutop/statigz/brotli/encoding.go
  vendor/github.com/vearutop/statigz/brotli/encoding_test.go
  vendor/github.com/vearutop/statigz/go.mod
  vendor/github.com/vearutop/statigz/go.sum
  vendor/github.com/vearutop/statigz/server.go
  vendor/github.com/vearutop/statigz/server_test.go
  vendor/modules.txt
Labels: chore, ui, javascript

#2038 Fix Vite issues
  pkg/api/server.go
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Settings/SettingsAboutPanel.tsx
  ui/v2.5/src/core/createClient.ts
  ui/v2.5/src/globals.d.ts
  ui/v2.5/src/serviceWorker.ts
  ui/v2.5/vite.config.js
Labels: bug

#1893 Refactor scraper top half
  graphql/documents/queries/scrapers/freeones.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/scraper.graphql
  pkg/api/resolver.go
  pkg/api/resolver_query_scraper.go
  pkg/api/scraped_content.go
  pkg/identify/identify.go
  pkg/identify/identify_test.go
  pkg/manager/task_identify.go
  pkg/models/errors.go
  pkg/scraper/action.go
  pkg/scraper/autotag.go
  pkg/scraper/cache.go
  pkg/scraper/config.go
  pkg/scraper/config_scraper.go
  pkg/scraper/freeones.go
  pkg/scraper/group.go
  pkg/scraper/json.go
  pkg/scraper/mapped.go
  pkg/scraper/postprocessing.go
  pkg/scraper/scraper.go
  pkg/scraper/scrapers.go
  pkg/scraper/script.go
  pkg/scraper/stash.go
  pkg/scraper/xpath.go
  pkg/scraper/xpath_test.go
  ui/v2.5/src/core/StashService.ts
Labels: chore

#2010 Add a TagMergePost post-hook
  pkg/api/resolver_mutation_tag.go
  pkg/plugin/hooks.go
  ui/v2.5/src/components/Changelog/versions/v0120.md
  ui/v2.5/src/docs/en/Plugins.md
Labels: feature

#1973 Add forward seeking buttons to jwplayer
  ui/v2.5/src/components/Changelog/versions/v0120.md
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: feature, ui

#2039 Reenable gzipping, pull in statigz fix, fix proxy prefix
  go.mod
  go.sum
  pkg/api/server.go
  ui/v2.5/index.html
  ui/v2.5/vite.config.js
  vendor/github.com/vearutop/statigz/brotli/encoding.go
  vendor/github.com/vearutop/statigz/brotli/encoding_test.go
  vendor/github.com/vearutop/statigz/go.mod
  vendor/github.com/vearutop/statigz/go.sum
  vendor/github.com/vearutop/statigz/server.go
  vendor/github.com/vearutop/statigz/server_test.go
  vendor/modules.txt
Labels: bug

#2040 Fix hamming distance calculation in tagger
  ui/v2.5/package.json
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
  ui/v2.5/src/utils/hamming.ts
  ui/v2.5/yarn.lock
Labels: bug

#2044 Varied macOS fixes
  Makefile
  pkg/ffmpeg/downloader.go
  ui/v2.5/src/core/createClient.ts
  ui/v2.5/src/index.scss
Labels: bug

#1982 Add search string parsing
  pkg/models/search.go
  pkg/models/search_test.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/movies.go
  pkg/sqlite/performer.go
  pkg/sqlite/query.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_marker.go
  pkg/sqlite/sql.go
  pkg/sqlite/studio.go
  pkg/sqlite/tag.go
  ui/v2.5/src/components/Changelog/versions/v0120.md
  ui/v2.5/src/components/Help/Manual.tsx
  ui/v2.5/src/docs/en/Browsing.md
Labels: feature, bounty

#2050 Fix setting autostart options
  pkg/manager/config/config.go
  ui/v2.5/src/components/Changelog/versions/v0120.md
Labels: bug

#2052 Validate SQLiteDate
  pkg/models/sqlite_date.go
  pkg/models/sqlite_date_test.go
  ui/v2.5/src/components/Changelog/versions/v0120.md
Labels: bug

#2051 Select first tagger result if resolved
  ui/v2.5/src/components/Changelog/versions/v0120.md
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
Labels: bug

#1949 Tasks page refactor
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  graphql/schema/types/metadata.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
  ui/v2.5/src/components/Changelog/versions/v0120.md
  ui/v2.5/src/components/Dialogs/AutoTagDialog.tsx
  ui/v2.5/src/components/Dialogs/CleanDialog.tsx
  ui/v2.5/src/components/Dialogs/GenerateDialog.tsx
  ui/v2.5/src/components/Dialogs/IdentifyDialog/IdentifyDialog.tsx
  ui/v2.5/src/components/Dialogs/IdentifyDialog/styles.scss
  ui/v2.5/src/components/Dialogs/ScanDialog/Options.tsx
  ui/v2.5/src/components/Dialogs/ScanDialog/ScanDialog.tsx
  ui/v2.5/src/components/Dialogs/styles.scss
  ui/v2.5/src/components/Help/styles.scss
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneGenerateDialog.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/GenerateButton.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/components/Settings/styles.scss
  ui/v2.5/src/components/Shared/OperationButton.tsx
  ui/v2.5/src/index.scss
  ui/v2.5/src/locales/de-DE.json
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/es-ES.json
  ui/v2.5/src/locales/it-IT.json
  ui/v2.5/src/locales/pt-BR.json
  ui/v2.5/src/locales/sv-SE.json
  ui/v2.5/src/locales/zh-CN.json
  ui/v2.5/src/locales/zh-TW.json
  ui/v2.5/src/styles/_theme.scss
Labels: improvement, ui

#2057 Autotag: prefer studio name later in filename
  pkg/autotag/tagger.go
  pkg/match/path.go
  pkg/match/path_test.go
  pkg/scraper/autotag.go
  ui/v2.5/src/components/Changelog/versions/v0120.md
Labels: improvement

#2043 Scraper refactor middle
  pkg/api/resolver_mutation_stash_box.go
  pkg/api/resolver_query_scraper.go
  pkg/api/scraped_content.go
  pkg/manager/task_identify.go
  pkg/manager/task_stash_box_tag.go
  pkg/scraper/action.go
  pkg/scraper/cache.go
  pkg/scraper/group.go
  pkg/scraper/image.go
  pkg/scraper/json.go
  pkg/scraper/json_test.go
  pkg/scraper/mapped.go
  pkg/scraper/mapped_test.go
  pkg/scraper/postprocessing.go
  pkg/scraper/script.go
  pkg/scraper/stash.go
  pkg/scraper/stashbox/stash_box.go
  pkg/scraper/url.go
  pkg/scraper/xpath.go
  pkg/scraper/xpath_test.go
Labels: bug, chore

#1951 Support a minModTime input on metadata scans.
  gqlgen.yml
  graphql/schema/types/metadata.graphql
  graphql/schema/types/scalars.graphql
  pkg/manager/task_scan.go
  pkg/models/timestamp.go
  pkg/models/timestamp_test.go
Labels: feature

#2071 Fix identify ScrapedScene conversion
  pkg/manager/task_identify.go
Labels: bug

#1954 Refactor file deletion
  pkg/api/resolver_mutation_gallery.go
  pkg/api/resolver_mutation_image.go
  pkg/api/resolver_mutation_scene.go
  pkg/file/delete.go
  pkg/image/delete.go
  pkg/manager/image.go
  pkg/manager/running_streams.go
  pkg/manager/scene.go
  pkg/manager/task_clean.go
  pkg/scene/delete.go
  ui/v2.5/src/components/Changelog/versions/v0120.md
Labels: bug, improvement

#2075 Add Finnish Locale
  README.md
  pkg/api/locale.go
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/locales/index.ts
Labels: ui

#2068 Fix setting images
  pkg/scraper/image.go
  pkg/scraper/postprocessing.go
Labels: bug

#2061 Refactor tasks follow up
  ui/v2.5/src/components/Changelog/versions/v0120.md
  ui/v2.5/src/components/Dialogs/AutoTagDialog.tsx
  ui/v2.5/src/components/Dialogs/CleanDialog.tsx
  ui/v2.5/src/components/Dialogs/GenerateDialog.tsx
  ui/v2.5/src/components/Dialogs/IdentifyDialog/IdentifyDialog.tsx
  ui/v2.5/src/components/Dialogs/ScanDialog/ScanDialog.tsx
  ui/v2.5/src/components/MainNavbar.tsx
  ui/v2.5/src/components/Settings/Settings.tsx
  ui/v2.5/src/components/Settings/SettingsTasksPanel/SettingsTasksPanel.tsx
  ui/v2.5/src/components/Settings/Tasks/DataManagementTasks.tsx
  ui/v2.5/src/components/Settings/Tasks/DirectorySelectionDialog.tsx
  ui/v2.5/src/components/Settings/Tasks/GenerateOptions.tsx
  ui/v2.5/src/components/Settings/Tasks/ImportDialog.tsx
  ui/v2.5/src/components/Settings/Tasks/JobTable.tsx
  ui/v2.5/src/components/Settings/Tasks/LibraryTasks.tsx
  ui/v2.5/src/components/Settings/Tasks/PluginTasks.tsx
  ui/v2.5/src/components/Settings/Tasks/ScanOptions.tsx
  ui/v2.5/src/components/Settings/Tasks/SettingsTasksPanel.tsx
  ui/v2.5/src/components/Settings/Tasks/Task.tsx
  ui/v2.5/src/components/Settings/styles.scss
  ui/v2.5/src/components/SettingsButton.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/es-ES.json
  ui/v2.5/src/locales/it-IT.json
  ui/v2.5/src/locales/pt-BR.json
  ui/v2.5/src/locales/sv-SE.json
  ui/v2.5/src/locales/zh-CN.json
  ui/v2.5/src/locales/zh-TW.json
Labels: improvement, ui
