Repository stashapp/stash, pull requests merged in 2021-08, with the labels that each got.

#1534 Split up Tagger component
  ui/v2.5/src/components/Tagger/PerformerResult.tsx
  ui/v2.5/src/components/Tagger/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/Tagger.tsx
  ui/v2.5/src/components/Tagger/TaggerList.tsx
  ui/v2.5/src/components/Tagger/TaggerScene.tsx
  ui/v2.5/src/components/Tagger/styles.scss
  ui/v2.5/src/components/Tagger/taggerService.ts
  ui/v2.5/src/components/Tagger/utils.ts
Labels: chore

#1568 [Feature] Better resolution search
  graphql/schema/types/filters.graphql
  pkg/models/extension_resolution.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/image_test.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/setup_test.go
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/models/list-filter/criteria/resolution.ts
  ui/v2.5/src/utils/resolution.ts
Labels: feature

#1587 Portuguese translation
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/locales/index.ts
  ui/v2.5/src/locales/pt-BR.json
Labels: improvement

#1606 Fix unsetting performer gender
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/index.scss
Labels: bug

#1607 Fix inf values causing marshal error
  pkg/api/resolver_model_scene.go
  pkg/api/types.go
  ui/v2.5/src/components/Changelog/versions/v090.md
Labels: bug

#1609 Remove stripes and add background colour to default performer images
  static/performer/NoName01.png
  static/performer/NoName02.png
  static/performer/NoName03.png
  static/performer/NoName04.png
  static/performer/NoName05.png
  static/performer/NoName06.png
  static/performer/NoName07.png
  static/performer/NoName08.png
  static/performer/NoName09.png
  static/performer/NoName10.png
  static/performer/NoName11.png
  static/performer/NoName12.png
  static/performer/NoName13.png
  static/performer/NoName14.png
  static/performer/NoName15.png
  static/performer/NoName16.png
  static/performer/NoName17.png
  static/performer/NoName18.png
  static/performer/NoName19.png
  static/performer/NoName20.png
  static/performer/NoName21.png
  static/performer/NoName22.png
  static/performer/NoName23.png
  static/performer/NoName24.png
  static/performer/NoName25.png
  static/performer/NoName26.png
  static/performer/NoName27.png
  static/performer/NoName28.png
  static/performer/NoName29.png
  static/performer/NoName30.png
  static/performer/NoName31.png
  static/performer/NoName32.png
  static/performer/NoName33.png
  static/performer/NoName34.png
  static/performer/NoName35.png
  static/performer/NoName36.png
  static/performer/NoName37.png
  static/performer/NoName38.png
  static/performer/NoName39.png
  static/performer/NoName40.png
  ui/v2.5/src/components/Changelog/versions/v090.md
Labels: improvement

#1608 Set stash id during performer scrape
  graphql/documents/data/scrapers.graphql
  graphql/schema/types/scraped-performer.graphql
  pkg/models/model_scraped_item.go
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog.tsx
Labels: bug

#1605 Tagger UI improvements
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/components/Shared/Icon.tsx
  ui/v2.5/src/components/Shared/SuccessIcon.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/components/Tagger/Config.tsx
  ui/v2.5/src/components/Tagger/IncludeButton.tsx
  ui/v2.5/src/components/Tagger/PerformerResult.tsx
  ui/v2.5/src/components/Tagger/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/StudioResult.tsx
  ui/v2.5/src/components/Tagger/TaggerList.tsx
  ui/v2.5/src/components/Tagger/TaggerScene.tsx
  ui/v2.5/src/components/Tagger/constants.ts
  ui/v2.5/src/components/Tagger/styles.scss
  ui/v2.5/src/components/Tagger/taggerService.ts
Labels: feature

#1610 Upgrade github.com/tidwall/gjson
  go.mod
  go.sum
  vendor/github.com/tidwall/gjson/.travis.yml
  vendor/github.com/tidwall/gjson/README.md
  vendor/github.com/tidwall/gjson/SYNTAX.md
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/gjson/go.mod
  vendor/github.com/tidwall/gjson/go.sum
  vendor/github.com/tidwall/match/.travis.yml
  vendor/github.com/tidwall/match/README.md
  vendor/github.com/tidwall/match/go.mod
  vendor/github.com/tidwall/match/match.go
  vendor/github.com/tidwall/pretty/.travis.yml
  vendor/github.com/tidwall/pretty/README.md
  vendor/github.com/tidwall/pretty/go.mod
  vendor/github.com/tidwall/pretty/pretty.go
  vendor/modules.txt
Labels: chore

#1548 Restructure scraping settings
  graphql/documents/data/config.graphql
  graphql/documents/mutations/config.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/components/Settings/Settings.tsx
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/components/Settings/SettingsScrapingPanel.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/locales/de-DE.json
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/pt-BR.json
  ui/v2.5/src/locales/zh-TW.json
Labels: improvement

#1603 Actually implement TagFilter.marker_count
  pkg/sqlite/tag.go
  pkg/sqlite/tag_test.go
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/models/list-filter/tags.ts
Labels: feature

#1618 Remove unnecessary fields from StudioData
  graphql/documents/data/studio.graphql
Labels: bug

#1617 Scrape tag exclusions
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
  pkg/scraper/scrapers.go
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/components/Settings/SettingsScrapingPanel.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#1620 Add Chinese Simplified Translation
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/locales/index.ts
  ui/v2.5/src/locales/zh-CN.json
Labels: improvement

#1622 Fix links and styling of File Info tabs
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryFileInfoPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageFileInfoPanel.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/index.scss
  ui/v2.5/src/utils/field.tsx
Labels: improvement

#1623 Create default config directory during setup
  pkg/manager/manager.go
  ui/v2.5/src/components/Changelog/versions/v090.md
Labels: bug

#1628 Fix dropdown menus z-index issue
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/index.scss
Labels: bug

#1631 Update zh-tw localization
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagMergeDialog.tsx
  ui/v2.5/src/locales/zh-TW.json
Labels: improvement

#1629 Rebuild Studio page by splitting view and edit
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioDetailsPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/utils/field.tsx
Labels: improvement

#1632 Fix scrape dialog not showing when scraping url
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
Labels: bug

#1633 Overwrite phash during generate if flag set
  pkg/manager/manager_tasks.go
  pkg/manager/task_generate_phash.go
  ui/v2.5/src/components/Changelog/versions/v090.md
Labels: bug

#1559 Add (not) between modifiers for number criterion
  graphql/schema/types/filters.graphql
  pkg/sqlite/filter.go
  pkg/sqlite/performer.go
  pkg/sqlite/query.go
  pkg/sqlite/scene.go
  pkg/sqlite/sql.go
  pkg/sqlite/tag.go
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/components/List/AddFilterDialog.tsx
  ui/v2.5/src/components/List/Filters/DurationFilter.tsx
  ui/v2.5/src/components/List/Filters/HierarchicalLabelValueFilter.tsx
  ui/v2.5/src/components/List/Filters/InputFilter.tsx
  ui/v2.5/src/components/List/Filters/LabeledIdFilter.tsx
  ui/v2.5/src/components/List/Filters/NumberFilter.tsx
  ui/v2.5/src/components/List/Filters/OptionsFilter.tsx
  ui/v2.5/src/components/Shared/DurationInput.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: feature

#1634 Make performer scrape button a dropdown
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
Labels: improvement

#1635 Add scene queue keyboard shortcuts
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/docs/en/KeyboardShortcuts.md
Labels: improvement, bounty

#1643 Fix hierarchical criteria performance issue
  pkg/sqlite/filter.go
  ui/v2.5/src/components/Changelog/versions/v090.md
Labels: bug

#1636 Custom page size and saved zoom level
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/components/Galleries/GalleryList.tsx
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Tags/TagList.tsx
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/filter.ts
Labels: improvement, bounty

#1642 UI: Add checkbox to scenes List view
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Scenes/SceneListTable.tsx
Labels: improvement

#1639 Order sceneDuplicateChecker results by size
  pkg/sqlite/scene.go
  ui/v2.5/src/components/Changelog/versions/v090.md
Labels: improvement

#1668 Fix studio editing
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/utils/index.ts
  ui/v2.5/src/utils/stashIds.ts
Labels: bug

#1650 Fix scene bitrate unit
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: bug

#1654 Rebuild gallery edit using formik
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
Labels: improvement

#1665 Add option to filename parser to skip organized scenes
  graphql/schema/types/scene.graphql
  pkg/manager/filename_parser.go
  ui/v2.5/src/components/SceneFilenameParser/ParserInput.tsx
  ui/v2.5/src/components/SceneFilenameParser/SceneFilenameParser.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/en-US.json
Labels: feature

#1663 Add date, duration and rating to Movie sorting
  ui/v2.5/src/components/Changelog/versions/v090.md
  ui/v2.5/src/models/list-filter/movies.ts
Labels: feature

#1645 Fix: config race conditions with RWMutex
  pkg/manager/checksum.go
  pkg/manager/config/config.go
  pkg/manager/config/config_concurrency_test.go
  ui/v2.5/src/components/Changelog/versions/v090.md
Labels: bug

#1681 Fix Performers Is Missing: stash ID filter
  pkg/sqlite/performer.go
  ui/v2.5/src/components/Changelog/versions/v090.md
Labels: bug

#1678 Load TLS config files from config path before stash home
  README.md
  pkg/api/server.go
  pkg/ffmpeg/downloader.go
  pkg/manager/config/config.go
  pkg/manager/paths/paths.go
  pkg/plugin/plugins.go
  pkg/utils/file.go
  ui/v2.5/src/components/Changelog/versions/v090.md
Labels: improvement

#1688 Update docker file to add mechanicalsoup python library
  docker/ci/x86_64/Dockerfile
Labels: chore
