Repository stashapp/stash, pull requests merged in 2021-03, with the labels that each got.

#1120 Skip insecure certificates check when scraping
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
  pkg/scraper/image.go
  pkg/scraper/url.go
  ui/v2.5/src/components/Changelog/versions/v060.md
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
Labels: improvement

#1137 Change NULL filters to filter empty strings as well
  pkg/sqlite/query.go
  ui/v2.5/src/components/Changelog/versions/v060.md
Labels: bug

#1130 Add full timestamp for console/file logging
  pkg/logger/logger.go
  ui/v2.5/src/components/Changelog/versions/v060.md
Labels: improvement

#1142 Add check version support for armv7, arm64
  go.mod
  pkg/api/check_version.go
  ui/v2.5/src/components/Changelog/versions/v060.md
  vendor/golang.org/x/sys/cpu/asm_aix_ppc64.s
  vendor/golang.org/x/sys/cpu/byteorder.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_aix_ppc64.go
  vendor/golang.org/x/sys/cpu/cpu_arm.go
  vendor/golang.org/x/sys/cpu/cpu_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_arm64.s
  vendor/golang.org/x/sys/cpu/cpu_gc_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_gc_s390x.go
  vendor/golang.org/x/sys/cpu/cpu_gc_x86.go
  vendor/golang.org/x/sys/cpu/cpu_gccgo_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_gccgo_s390x.go
  vendor/golang.org/x/sys/cpu/cpu_gccgo_x86.c
  vendor/golang.org/x/sys/cpu/cpu_gccgo_x86.go
  vendor/golang.org/x/sys/cpu/cpu_linux.go
  vendor/golang.org/x/sys/cpu/cpu_linux_arm.go
  vendor/golang.org/x/sys/cpu/cpu_linux_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_mips64x.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_linux_ppc64x.go
  vendor/golang.org/x/sys/cpu/cpu_linux_s390x.go
  vendor/golang.org/x/sys/cpu/cpu_mips64x.go
  vendor/golang.org/x/sys/cpu/cpu_mipsx.go
  vendor/golang.org/x/sys/cpu/cpu_other_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_riscv64.go
  vendor/golang.org/x/sys/cpu/cpu_s390x.s
  vendor/golang.org/x/sys/cpu/cpu_wasm.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/cpu/cpu_x86.s
  vendor/golang.org/x/sys/cpu/hwcap_linux.go
  vendor/golang.org/x/sys/cpu/syscall_aix_ppc64_gc.go
  vendor/modules.txt
Labels: bug

#1147 Gallery filter fix
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/setup_test.go
  ui/v2.5/src/components/Changelog/versions/v060.md
Labels: bug

#1159 Fix SQL error in 8K resolution filter
  pkg/sqlite/image.go
  pkg/sqlite/scene.go
Labels: bug

#1154 Check if gallery is already associated during scanning
  pkg/manager/task_scan.go
  ui/v2.5/src/components/Changelog/versions/v060.md
Labels: bug

#1150 Expose url for URLReplace in JSON scrapeByURL and scrapeByFragment
  pkg/scraper/json.go
  pkg/scraper/query_url.go
  pkg/scraper/xpath.go
  ui/v2.5/src/components/Changelog/versions/v060.md
  ui/v2.5/src/docs/en/Scraping.md
Labels: improvement

#1115 Add sqlite filter builder. Add AND, OR, NOT filters to scene filter
  graphql/schema/types/filters.graphql
  pkg/manager/task_autotag.go
  pkg/models/extension_resolution.go
  pkg/models/scene.go
  pkg/sqlite/filter.go
  pkg/sqlite/filter_internal_test.go
  pkg/sqlite/query.go
  pkg/sqlite/repository.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/sql.go
Labels: chore, improvement

#1156 Find correct python executable
  pkg/scraper/script.go
  ui/v2.5/src/components/Changelog/versions/v060.md
  ui/v2.5/src/docs/en/Scraping.md
Labels: improvement

#1167 Change gallery icon to images
  ui/v2.5/src/components/MainNavbar.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
Labels: improvement

#1144 Detect cover images in subdirectories
  pkg/image/image.go
  pkg/image/image_test.go
  ui/v2.5/src/components/Changelog/versions/v060.md
Labels: bug

#1172 Fix tagger parsing bugs
  ui/v2.5/src/components/Tagger/Tagger.tsx
Labels: bug

#1168 Performer UI improvements
  ui/v2.5/.env
  ui/v2.5/package.json
  ui/v2.5/src/components/Changelog/versions/v060.md
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/index.scss
  ui/v2.5/src/utils/field.tsx
  ui/v2.5/yarn.lock
Labels: improvement

#1177 Fix scene form layout bugs
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/index.scss
Labels: bug

#1166 Add scrape gallery from fragment to UI
  ui/v2.5/src/components/Changelog/versions/v060.md
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/core/StashService.ts
Labels: improvement

#1169 Hide create option when searching in filters
  ui/v2.5/src/components/Changelog/versions/v060.md
  ui/v2.5/src/components/Shared/Select.tsx
Labels: improvement

#1176 Toggle visibility of unmatched scenes in Tagger
  ui/v2.5/src/components/Changelog/versions/v060.md
  ui/v2.5/src/components/Tagger/Tagger.tsx
Labels: improvement

#1187 Remove streaming resolutions over max configured
  pkg/api/resolver_query_scene.go
  pkg/manager/scene.go
  pkg/models/model_scene.go
  ui/v2.5/src/components/Changelog/versions/v060.md
Labels: bug

#1193 Upload Image from url
  pkg/api/resolver_mutation_movie.go
  pkg/api/resolver_mutation_performer.go
  pkg/api/resolver_mutation_scene.go
  pkg/api/resolver_mutation_studio.go
  pkg/api/resolver_mutation_tag.go
  pkg/utils/image.go
  ui/v2.5/src/components/Changelog/versions/v060.md
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Shared/DetailsEditNavbar.tsx
  ui/v2.5/src/components/Shared/ImageInput.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
Labels: bounty, improvement

#1192 Fix IsPathInDir
  pkg/utils/file.go
  pkg/utils/file_test.go
  ui/v2.5/src/components/Changelog/versions/v060.md
Labels: bug

#1179 Documentation Updates to README.md
  README.md
Labels: documentation

#1194 Refactor tag query
  graphql/schema/types/filters.graphql
  pkg/sqlite/tag.go
Labels: bug, improvement

#1195 Add Galleries tab to Tag details page
  ui/v2.5/src/components/Changelog/versions/v060.md
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagGalleriesPanel.tsx
Labels: improvement

#1198 Improve performer scrape search modal
  ui/v2.5/src/components/Changelog/versions/v060.md
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeModal.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Shared/index.ts
Labels: improvement

#1200 Add timestamp suffix to all image urls
  pkg/api/resolver_model_image.go
  pkg/api/resolver_model_movie.go
  pkg/api/resolver_model_performer.go
  pkg/api/resolver_model_studio.go
  pkg/api/resolver_model_tag.go
  pkg/api/urlbuilders/image.go
  pkg/api/urlbuilders/movie.go
  pkg/api/urlbuilders/performer.go
  pkg/api/urlbuilders/studio.go
  pkg/api/urlbuilders/tag.go
  pkg/utils/image.go
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
Labels: improvement

#1206 Performer edit UI further updates
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
  ui/v2.5/src/index.scss
Labels: improvement

#1208 Handle NULL in regex criteria
  pkg/sqlite/filter.go
  pkg/sqlite/filter_internal_test.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/query.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/setup_test.go
  ui/v2.5/src/components/Changelog/versions/v060.md
Labels: bug

#1207 Remove slim graphql endpoints
  graphql/documents/queries/misc.graphql
  graphql/schema/schema.graphql
  pkg/api/resolver_query_find_movie.go
  pkg/api/resolver_query_find_performer.go
  pkg/api/resolver_query_find_studio.go
  pkg/api/resolver_query_find_tag.go
  pkg/models/mocks/MovieReaderWriter.go
  pkg/models/mocks/PerformerReaderWriter.go
  pkg/models/mocks/StudioReaderWriter.go
  pkg/models/mocks/TagReaderWriter.go
  pkg/models/movie.go
  pkg/models/performer.go
  pkg/models/studio.go
  pkg/models/tag.go
  pkg/sqlite/movies.go
  pkg/sqlite/performer.go
  pkg/sqlite/studio.go
  pkg/sqlite/tag.go
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMovieTable.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Tagger/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/queries.ts
Labels: improvement

#1205 Add configFilePath and scrapersPath to configuration query
  graphql/schema/types/config.graphql
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
Labels: improvement

#1211 Add write mutex and max connection lifetime
  pkg/database/database.go
  pkg/sqlite/transaction.go
Labels: improvement

#1212 Fix filter building with sub-filters
  .gitignore
  pkg/sqlite/filter.go
  pkg/sqlite/filter_internal_test.go
Labels: bug

#1213 Fix panic on full import
  pkg/manager/task_import.go
Labels: bug

#1222 Add User Agent to image download requests
  pkg/scraper/image.go
  pkg/scraper/url.go
  pkg/utils/image.go
  pkg/utils/user_agent.go
Labels: bug

#1221 Correct tag link for gallery and images tags
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryDetailPanel.tsx
  ui/v2.5/src/components/Images/ImageCard.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageDetailPanel.tsx
  ui/v2.5/src/components/Shared/TagLink.tsx
  ui/v2.5/src/utils/navigation.ts
Labels: bug

#1230 Fix Freeones search
  pkg/scraper/freeones.go
Labels: bug

#1240 Merge master back to develop for tag
  .github/workflows/build.yml
Labels: chore

#1231 Update libraries and regenerate yarn.lock
  ui/v2.5/.eslintrc.json
  ui/v2.5/yarn.lock
Labels: chore

#1236 Fix performer search columns
  pkg/sqlite/performer.go
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/v060.md
  ui/v2.5/src/components/Changelog/versions/v070.md
Labels: improvement

#1237 Fix inaccurate age calculation
  ui/v2.5/src/components/Changelog/versions/v060.md
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/utils/text.ts
Labels: bug

#1214 Scene queuing
  pkg/api/resolver_query_find_scene.go
  pkg/manager/scene.go
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/styles.scss
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneCardsGrid.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/QueueViewer.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/locale/en-GB.json
  ui/v2.5/src/locale/en-US.json
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/models/sceneQueue.ts
Labels: bounty, feature

#1227 Movie UI refresh
  pkg/api/resolver_model_movie.go
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieDetailsPanel.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieEditPanel.tsx
  ui/v2.5/src/components/Movies/styles.scss
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/utils/field.tsx
Labels: improvement

#1232 Add format to performer field placeholder
  README.md
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
Labels: bug

#1241 Api key
  go.mod
  go.sum
  graphql/documents/data/config.graphql
  graphql/documents/mutations/config.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/api/server.go
  pkg/manager/apikey.go
  pkg/manager/config/config.go
  ui/v2.5/src/components/Changelog/versions/v070.md
  ui/v2.5/src/components/Settings/SettingsConfigurationPanel.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/docs/en/Configuration.md
  vendor/github.com/dgrijalva/jwt-go/.gitignore
  vendor/github.com/dgrijalva/jwt-go/.travis.yml
  vendor/github.com/dgrijalva/jwt-go/LICENSE
  vendor/github.com/dgrijalva/jwt-go/MIGRATION_GUIDE.md
  vendor/github.com/dgrijalva/jwt-go/README.md
  vendor/github.com/dgrijalva/jwt-go/VERSION_HISTORY.md
  vendor/github.com/dgrijalva/jwt-go/claims.go
  vendor/github.com/dgrijalva/jwt-go/doc.go
  vendor/github.com/dgrijalva/jwt-go/ecdsa.go
  vendor/github.com/dgrijalva/jwt-go/ecdsa_utils.go
  vendor/github.com/dgrijalva/jwt-go/errors.go
  vendor/github.com/dgrijalva/jwt-go/hmac.go
  vendor/github.com/dgrijalva/jwt-go/map_claims.go
  vendor/github.com/dgrijalva/jwt-go/none.go
  vendor/github.com/dgrijalva/jwt-go/parser.go
  vendor/github.com/dgrijalva/jwt-go/rsa.go
  vendor/github.com/dgrijalva/jwt-go/rsa_pss.go
  vendor/github.com/dgrijalva/jwt-go/rsa_utils.go
  vendor/github.com/dgrijalva/jwt-go/signing_method.go
  vendor/github.com/dgrijalva/jwt-go/token.go
  vendor/modules.txt
Labels: feature
