Repository stashapp/stash, pull requests merged in 2022-06, with the labels that each got.

#2611 Fix gallery updating
  pkg/gallery/scan.go
Labels: bug

#2577 Add support for submitting stash-box scene updates by draft
  pkg/scraper/stashbox/graphql/generated_client.go
  pkg/scraper/stashbox/graphql/generated_models.go
  pkg/scraper/stashbox/graphql/override.go
  pkg/scraper/stashbox/stash_box.go
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/v0160.md
  ui/v2.5/src/components/Dialogs/SubmitDraft.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#2638 Fix scraping more than 40 scenes from stash-box
  pkg/scraper/stashbox/stash_box.go
Labels: bug

#2654 Add missing gallery card classes
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
Labels: bug

#2655 Add alias for Laos
  ui/v2.5/src/utils/country.ts
Labels: bug

#2657 Update scene screenshot in edit panel
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
Labels: bug

#2658 Don't trim extension for folders when auto-tagging galleries
  internal/autotag/gallery.go
  internal/autotag/scene_test.go
  internal/autotag/tagger.go
  pkg/match/path.go
  pkg/scraper/autotag.go
  ui/v2.5/src/components/Changelog/versions/v0160.md
Labels: bug

#2656 Fix scene player event handler initialisation
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: bug

#2665 Don't switch to landscape for portrait videos
  ui/v2.5/src/components/Changelog/versions/v0160.md
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: bug

#2672 Fix ui config conversion
  internal/manager/config/map.go
Labels: bug

#2673 Add tag recommendation row
  ui/v2.5/src/components/FrontPage/Control.tsx
  ui/v2.5/src/components/FrontPage/styles.scss
  ui/v2.5/src/components/Tags/TagRecommendationRow.tsx
Labels: bug

#2668 Separate filter buttons from query field
  ui/v2.5/src/components/Changelog/versions/v0160.md
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/index.scss
Labels: improvement

#2664 Fix Synopsis json string in movie jsonschema
  pkg/models/jsonschema/movie.go
Labels: bug

#2678 Use hotkeys '[' and ']' to scrub video player forwards and backwards by 10% of the scene
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/docs/en/KeyboardShortcuts.md
Labels: feature, ui

#2686 UI and filter fixes
  ui/v2.5/src/components/FrontPage/RecommendationRow.tsx
  ui/v2.5/src/components/Galleries/GalleryRecommendationRow.tsx
  ui/v2.5/src/components/Images/ImageRecommendationRow.tsx
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/List/ListOperationButtons.tsx
  ui/v2.5/src/components/List/ListViewOptions.tsx
  ui/v2.5/src/components/Movies/MovieRecommendationRow.tsx
  ui/v2.5/src/components/Performers/PerformerRecommendationRow.tsx
  ui/v2.5/src/components/Scenes/SceneRecommendationRow.tsx
  ui/v2.5/src/components/Studios/StudioRecommendationRow.tsx
  ui/v2.5/src/components/Tags/TagRecommendationRow.tsx
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/src/models/list-filter/criteria/factory.ts
Labels: bug, ui

#2694 Fix proxy prefix replacement
  internal/api/server.go
Labels: bug

#2698 Fix saved filter search
  ui/v2.5/src/components/Changelog/versions/v0160.md
  ui/v2.5/src/components/List/SavedFilterList.tsx
Labels: bug

#2702 Treat edited values as scraped
  ui/v2.5/src/components/Changelog/versions/v0160.md
  ui/v2.5/src/components/Shared/ScrapeDialog.tsx
Labels: bug
