Repository stashapp/stash, pull requests merged in 2022-01, with the labels that each got.

#2190 Fix CreatedAt/UpdatedAt timezone and missing time [+ v0.13.0 changelog]
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/v0130.md
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryDetailPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageDetailPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneDetailPanel.tsx
  ui/v2.5/src/utils/text.ts
Labels: bug, ui

#2198 Fix oshash calculation for symlinks
  pkg/file/scan.go
  ui/v2.5/src/components/Changelog/versions/v0130.md
Labels: bug

#2189 Fix stash-box batch performer birthdate update
  pkg/manager/task_stash_box_tag.go
  ui/v2.5/src/components/Changelog/versions/v0130.md
Labels: bug

#2191 Fix conversion of multi word stash-box enums
  pkg/scraper/stashbox/stash_box.go
  ui/v2.5/src/components/Changelog/versions/v0130.md
Labels: bug

#2167 Fix scrubber sprite creation for short video files
  pkg/ffmpeg/encoder_sprite_screenshot.go
  pkg/ffmpeg/ffprobe.go
  pkg/ffmpeg/types.go
  pkg/manager/generator_sprite.go
  ui/v2.5/src/components/Changelog/versions/v0130.md
Labels: bug

#2169 Show counts on entity list tabs
  ui/v2.5/src/components/Changelog/versions/v0130.md
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Settings/SettingsServicesPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/index.scss
Labels: improvement, ui

#2173 Add stash-box credentials validation
  graphql/documents/queries/settings/config.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/config.graphql
  graphql/stash-box/query.graphql
  pkg/api/resolver_query_configuration.go
  pkg/scraper/stashbox/graphql/generated_client.go
  pkg/scraper/stashbox/stash_box.go
  ui/v2.5/src/components/Changelog/versions/v0130.md
  ui/v2.5/src/components/Settings/StashBoxConfiguration.tsx
Labels: feature, ui

#2179 Add Gender Icons to Performers
  ui/v2.5/src/components/Changelog/versions/v0130.md
  ui/v2.5/src/components/Performers/GenderIcon.tsx
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Shared/GridCard.tsx
  ui/v2.5/src/components/Tagger/PerformerModal.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: improvement, ui

#2174 Resolve hostname for chromium RDP requests
  pkg/scraper/url.go
  ui/v2.5/src/components/Changelog/versions/v0130.md
Labels: bug

#2200 Touch up Performer Page
  ui/v2.5/src/components/Changelog/versions/v0130.md
  ui/v2.5/src/components/Movies/MovieDetails/MovieEditPanel.tsx
  ui/v2.5/src/components/Performers/GenderIcon.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerOperationsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/components/Tagger/PerformerModal.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: improvement, ui

#2194 Add preview languages
  README.md
  pkg/api/locale.go
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/locales/index.ts
Labels: documentation, ui

#2217 Allow stash to be iframed
  pkg/api/server.go
  ui/v2.5/src/components/Changelog/versions/v0130.md
Labels: bug

#2228 Deprecate x-forwarded-port
  pkg/api/server.go
Labels: bug

#2223 Only show one modal when tagging performers
  ui/v2.5/src/components/Tagger/performers/PerformerTagger.tsx
Labels: bug

#2222 Fix performer tagger gender setting
  ui/v2.5/src/utils/gender.ts
Labels: bug

#2212 add link to Scene Filename Parser docs
  ui/v2.5/src/docs/en/SceneFilenameParser.md
Labels: documentation

#2230 Show country flags for ISO coded countries
  ui/v2.5/src/utils/country.ts
Labels: improvement

#2237 Fix vite manifest.json crash
  ui/v2.5/index.html
Labels: bug

#2233 Prevent creation of dupe filters
  ui/v2.5/src/components/List/AddFilterDialog.tsx
  ui/v2.5/src/hooks/ListHook.tsx
Labels: bug

#2241 Only update tags if not dirtied
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
  ui/v2.5/src/hooks/state.ts
Labels: bug

#2258 Reuse static server for multiple requests
  pkg/api/server.go
Labels: improvement, go

#2254 Fix preview video stopping media on Android
  ui/v2.5/src/components/Scenes/SceneCard.tsx
Labels: bug, ui

#2259 Add Japanese, upgrade Dutch and Portuguese
  README.md
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/locales/index.ts
Labels: improvement, ui

#2246 Add Tasks table to Logs Page
  ui/v2.5/src/components/Settings/SettingsLogsPanel.tsx
Labels: feature, ui

#2220 Fix button spacing, fix gender/country height
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Shared/DetailsEditNavbar.tsx
Labels: improvement, ui
