Repository stashapp/stash, pull requests merged in 2022-03, with the labels that each got.

#2355 Distance match phashes on bulk stash-box query
  pkg/scraper/stashbox/stash_box.go
  ui/v2.5/src/components/Changelog/versions/v0130.md
Labels: bug

#2274 Add title, rating, o-counter to image lightbox
  ui/v2.5/src/components/Changelog/versions/v0130.md
  ui/v2.5/src/components/Images/ImageDetails/Image.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/OCounterButton.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/Lightbox/context.tsx
  ui/v2.5/src/hooks/Lightbox/lightbox.scss
Labels: feature, ui

#2363 Remove single unicode character from autotag query
  main.go
  pkg/match/path.go
  pkg/sqlite/performer.go
Labels: bug

#2372 Fix release asset uploads
  .github/workflows/build.yml
Labels: chore

#2368 Autotag optimisation
  pkg/autotag/gallery.go
  pkg/autotag/gallery_test.go
  pkg/autotag/image.go
  pkg/autotag/image_test.go
  pkg/autotag/integration_test.go
  pkg/autotag/performer.go
  pkg/autotag/performer_test.go
  pkg/autotag/scene.go
  pkg/autotag/scene_test.go
  pkg/autotag/studio.go
  pkg/autotag/studio_test.go
  pkg/autotag/tag.go
  pkg/autotag/tag_test.go
  pkg/autotag/tagger.go
  pkg/database/functions.go
  pkg/database/regex.go
  pkg/manager/task_autotag.go
  pkg/match/cache.go
  pkg/match/path.go
  pkg/scraper/autotag.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/performer.go
  pkg/sqlite/scene.go
  pkg/sqlite/studio.go
  pkg/sqlite/tag.go
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/v0140.md
Labels: improvement

#2353 i18n: Migrate hard strings
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryImagesPanel.tsx
  ui/v2.5/src/components/MainNavbar.tsx
  ui/v2.5/src/components/Movies/EditMoviesDialog.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieScrapeDialog.tsx
  ui/v2.5/src/components/Performers/EditPerformersDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerCreate.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/ExternalPlayerButton.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Settings/Inputs.tsx
  ui/v2.5/src/components/Settings/SettingsServicesPanel.tsx
  ui/v2.5/src/components/Shared/FolderSelect/FolderSelect.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Tagger/scenes/sceneTaggerModals.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/locales/de-DE.json
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/es-ES.json
  ui/v2.5/src/locales/fi-FI.json
  ui/v2.5/src/locales/fr-FR.json
  ui/v2.5/src/locales/it-IT.json
  ui/v2.5/src/locales/ja-JP.json
  ui/v2.5/src/locales/nl-NL.json
  ui/v2.5/src/locales/pt-BR.json
  ui/v2.5/src/locales/sv-SE.json
  ui/v2.5/src/locales/tr-TR.json
  ui/v2.5/src/locales/zh-CN.json
  ui/v2.5/src/locales/zh-TW.json
Labels: chore

#2365 Read theme color from config file
  pkg/api/server.go
  pkg/manager/config/config.go
  ui/v2.5/index.html
  ui/v2.5/src/components/Changelog/versions/v0140.md
  ui/v2.5/src/docs/en/Configuration.md
Labels: feature

#2378 Use case-insensitive matching in nameMatchesPath
  pkg/match/path.go
  pkg/match/path_test.go
  ui/v2.5/src/components/Changelog/versions/v0140.md
Labels: bug

#2375 Fix identify and script scraper bugs
  pkg/api/resolver_query_scraper.go
  pkg/api/scraped_content.go
  pkg/identify/identify.go
  pkg/identify/identify_test.go
  pkg/manager/task_identify.go
  pkg/scraper/cache.go
  pkg/scraper/json.go
  pkg/scraper/json_test.go
  pkg/scraper/mapped.go
  pkg/scraper/script.go
  ui/v2.5/src/components/Changelog/versions/v0140.md
Labels: bug

#2386 Hotfix 0.13.1
  pkg/match/path.go
  pkg/match/path_test.go
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/v0131.md
Labels: bug

#2387 V0.13.1 to develop
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/v0131.md
  ui/v2.5/src/components/Changelog/versions/v0140.md
Labels: chore

#2388 Don't generate thumbnails for webp
  internal/api/routes_image.go
  internal/manager/task_scan_image.go
  pkg/ffmpeg/image.go
  pkg/image/thumbnail.go
  pkg/image/webp.go
  pkg/image/webp_internal_test.go
  ui/v2.5/src/components/Changelog/versions/v0140.md
Labels: bug

#2390 Order gallery images by path
  internal/api/resolver_model_gallery.go
  pkg/image/query.go
Labels: bug

#2391 Move tag exclusion to scrape query resolver
  internal/api/resolver_query_scraper.go
  pkg/scraper/cache.go
  pkg/scraper/postprocessing.go
  ui/v2.5/src/components/Changelog/versions/v0140.md
Labels: bug

#2403 Scroll to next image using lightbox
  ui/v2.5/src/components/Changelog/versions/v0140.md
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/Lightbox/LightboxImage.tsx
Labels: improvement, bounty

#2407 Use first sorted by path image as cover by default
  internal/api/resolver_model_gallery.go
Labels: bug

#2408 Don't include stash_ids if not setting
  ui/v2.5/src/components/Changelog/versions/v0140.md
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
Labels: bug

#2406 Persist lightbox settings
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_query_configuration.go
  internal/manager/config/config.go
  internal/manager/config/config_concurrency_test.go
  ui/v2.5/src/components/Changelog/versions/v0140.md
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/core/enums.ts
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/Lightbox/LightboxImage.tsx
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/src/hooks/LocalForage.ts
  ui/v2.5/src/locales/en-GB.json
Labels: improvement, bounty

#2411 Fix local docker builds under new projext org
  docker/build/x86_64/Dockerfile
Labels: bug

#2409 Python path setting
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_query_configuration.go
  internal/manager/config/config.go
  internal/manager/config/config_concurrency_test.go
  pkg/exec/command.go
  pkg/plugin/plugins.go
  pkg/plugin/raw.go
  pkg/plugin/task.go
  pkg/python/exec.go
  pkg/scraper/cache.go
  pkg/scraper/script.go
  pkg/scraper/xpath_test.go
  ui/v2.5/src/components/Changelog/versions/v0140.md
  ui/v2.5/src/components/Settings/SettingsSystemPanel.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#2396 Fix plugin examples (go rpc/raw)
  pkg/plugin/examples/common/graphql.go
  pkg/plugin/examples/goraw/main.go
  pkg/plugin/examples/gorpc/main.go
Labels: bug

#2416 Fix ffmpeg download
  pkg/ffmpeg/downloader.go
Labels: bug

#2418 Always open browser from systray
  internal/desktop/systray_nonlinux.go
  ui/v2.5/src/components/Changelog/versions/v0140.md
Labels: bug

#2419 Initialise queryConfig if not present
  ui/v2.5/src/hooks/ListHook.tsx
Labels: bug

#2421 Only cache log items that meet minimum log level
  internal/log/logger.go
Labels: bug

#2422 Improve performance of gallery and image queries
  internal/api/resolver_model_gallery.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/scene.go
  pkg/sqlite/sql.go
Labels: improvement

#2425 Fix windows ffmpeg concat path
  pkg/ffmpeg/encoder_scene_preview_chunk.go
Labels: bug

#2426 Fix lightbox issues
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/Lightbox/LightboxImage.tsx
Labels: bug

#2100 Replace JW Player with video.js
  graphql/documents/data/scene.graphql
  graphql/documents/queries/scene.graphql
  graphql/schema/types/scene.graphql
  internal/api/resolver_model_scene.go
  internal/manager/scene.go
  ui/v2.5/package.json
  ui/v2.5/public/jwplayer/jwplayer.controls.js
  ui/v2.5/public/jwplayer/jwplayer.core.controls.html5.js
  ui/v2.5/public/jwplayer/jwplayer.core.controls.js
  ui/v2.5/public/jwplayer/jwplayer.core.controls.polyfills.html5.js
  ui/v2.5/public/jwplayer/jwplayer.core.controls.polyfills.js
  ui/v2.5/public/jwplayer/jwplayer.core.js
  ui/v2.5/public/jwplayer/jwplayer.js
  ui/v2.5/public/jwplayer/notice.txt
  ui/v2.5/public/jwplayer/polyfills.intersection-observer.js
  ui/v2.5/public/jwplayer/polyfills.webvtt.js
  ui/v2.5/public/jwplayer/provider.html5.js
  ui/v2.5/public/jwplayer/vttparser.js
  ui/v2.5/src/components/Changelog/versions/v0140.md
  ui/v2.5/src/components/ScenePlayer/PlaylistButtons.ts
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/index.ts
  ui/v2.5/src/components/ScenePlayer/live.ts
  ui/v2.5/src/components/ScenePlayer/styles.scss
  ui/v2.5/src/components/Scenes/SceneDetails/QueueViewer.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkerForm.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkersPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneVideoFilterPanel.tsx
  ui/v2.5/src/index.scss
  ui/v2.5/src/models/sceneQueue.ts
  ui/v2.5/src/utils/index.ts
  ui/v2.5/src/utils/jwplayer.ts
  ui/v2.5/yarn.lock
Labels: improvement, ui

#2441 Scene player fixes
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/styles.scss
Labels: bug

#2450 allow full screen and inline play on iOS
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: bug

#2454 use min value for skipping forward
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: bug, ui

#2447 Add marker videojs plugin
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/markers.ts
  ui/v2.5/src/components/ScenePlayer/styles.scss
Labels: bug

#2448 Add persist volume plugin
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/persist-volume.ts
Labels: bug

#2449 Add source selector plugin
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/live.ts
  ui/v2.5/src/components/ScenePlayer/source-selector.ts
  ui/v2.5/src/components/ScenePlayer/styles.scss
Labels: bug

#2455 Videojs big buttons
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/big-buttons.ts
  ui/v2.5/src/components/ScenePlayer/styles.scss
Labels: improvement
