Repository stashapp/stash, pull requests merged in 2022-04, with the labels that each got.

#2458 Fix 10bit vp9 streaming
  pkg/ffmpeg/stream.go
Labels: bug

#2459 Fix video filters
  ui/v2.5/src/components/ScenePlayer/styles.scss
  ui/v2.5/src/components/Scenes/SceneDetails/SceneVideoFilterPanel.tsx
Labels: bug

#2461 Don't overwrite with empty values in tagger
  ui/v2.5/src/components/Changelog/versions/v0140.md
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
Labels: bug

#2467 Improve bulk performer editing
  graphql/documents/data/performer-slim.graphql
  ui/v2.5/src/components/Changelog/versions/v0140.md
  ui/v2.5/src/components/Performers/EditPerformersDialog.tsx
  ui/v2.5/src/components/Shared/BulkUpdateTextInput.tsx
  ui/v2.5/src/components/Shared/Icon.tsx
  ui/v2.5/src/components/Shared/IndeterminateCheckbox.tsx
  ui/v2.5/src/components/Shared/MultiSet.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/utils/bulkUpdate.ts
Labels: improvement

#2468 Do not display tabs with no content
  ui/v2.5/src/components/Changelog/versions/v0140.md
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/utils/render.tsx
Labels: improvement

#2466 Mobile scene details page revamp
  ui/v2.5/src/index.scss
Labels: improvement

#2193 Add support for the Handy APIv2
  ui/v2.5/package.json
  ui/v2.5/src/components/Changelog/versions/v0140.md
  ui/v2.5/src/utils/interactive.ts
  ui/v2.5/yarn.lock
Labels: feature, improvement

#2457 Fix lightbox issues
  ui/v2.5/src/components/Changelog/versions/v0140.md
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/LocalForage.ts
  ui/v2.5/src/locales/en-GB.json
Labels: bug

#2471 Fix scene edit panel not updating on scene change
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
Labels: bug

#2439 Add ignore autotag flag
  graphql/documents/data/performer-slim.graphql
  graphql/documents/data/performer.graphql
  graphql/documents/data/studio.graphql
  graphql/documents/data/tag.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/performer.graphql
  graphql/schema/types/studio.graphql
  graphql/schema/types/tag.graphql
  internal/api/resolver_mutation_performer.go
  internal/api/resolver_mutation_studio.go
  internal/api/resolver_mutation_tag.go
  internal/autotag/integration_test.go
  internal/manager/task_autotag.go
  pkg/database/database.go
  pkg/database/migrations/30_ignore_autotag.up..sql
  pkg/models/jsonschema/performer.go
  pkg/models/jsonschema/studio.go
  pkg/models/jsonschema/tag.go
  pkg/models/model_performer.go
  pkg/models/model_studio.go
  pkg/models/model_tag.go
  pkg/performer/export.go
  pkg/performer/export_test.go
  pkg/performer/import.go
  pkg/sqlite/performer.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/studio.go
  pkg/sqlite/studio_test.go
  pkg/sqlite/tag.go
  pkg/sqlite/tag_test.go
  pkg/studio/export.go
  pkg/studio/export_test.go
  pkg/studio/import.go
  pkg/studio/import_test.go
  pkg/tag/export.go
  pkg/tag/export_test.go
  pkg/tag/import.go
  pkg/tag/import_test.go
  ui/v2.5/src/components/Changelog/versions/v0140.md
  ui/v2.5/src/components/Performers/EditPerformersDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
  ui/v2.5/src/index.scss
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/factory.ts
  ui/v2.5/src/models/list-filter/performers.ts
  ui/v2.5/src/models/list-filter/studios.ts
  ui/v2.5/src/models/list-filter/tags.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: feature, bounty

#2475 Make desktop.Start run on main thread
  cmd/stash/main.go
  internal/desktop/desktop.go
  internal/manager/favicon.go
  internal/manager/manager.go
Labels: bug

#2482 Fix only one tag markers on scene
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkersPanel.tsx
Labels: bug

#2484 Fix CSP directives for playground
  internal/api/server.go
Labels: bug

#2486 Revert #2466 due to portrait video issues
  ui/v2.5/src/components/Changelog/versions/v0140.md
  ui/v2.5/src/index.scss
Labels: bug

#2487 Revert "Do not display tabs with no content (#2468)"
  ui/v2.5/src/components/Changelog/versions/v0140.md
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/utils/render.tsx
Labels: bug

#2477 Freebsd compile errors
  Makefile
  internal/desktop/desktop_platform_nixes.go
  internal/desktop/systray_nixes.go
  internal/desktop/systray_nonlinux.go
Labels: bug

#2483 Merge performer list when saving scene from tagger
  ui/v2.5/src/components/Changelog/versions/v0140.md
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
Labels: bug

#2485 Handle graphql errors correctly during draft submission
  pkg/scraper/stashbox/stash_box.go
Labels: bug

#2501 Fix video layout on touch enabled devices
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/v0150.md
  ui/v2.5/src/components/ScenePlayer/styles.scss
Labels: bug

#2488 Hoist context, enable errchkjson
  .golangci.yml
  internal/api/resolver_mutation_metadata.go
  internal/manager/manager.go
  internal/manager/manager_tasks.go
  internal/manager/task_autotag.go
  internal/manager/task_clean.go
  internal/manager/task_export.go
  internal/manager/task_generate.go
  internal/manager/task_generate_interactive_heatmap_speed.go
  internal/manager/task_generate_markers.go
  internal/manager/task_generate_phash.go
  internal/manager/task_generate_screenshot.go
  internal/manager/task_scan.go
  internal/manager/task_scan_gallery.go
  internal/manager/task_scan_image.go
  internal/manager/task_scan_scene.go
  internal/manager/task_stash_box_tag.go
  pkg/gallery/scan.go
  pkg/image/scan.go
  pkg/job/manager.go
  pkg/plugin/js/log.go
  pkg/plugin/raw.go
  pkg/scene/scan.go
  pkg/scraper/script.go
Labels: chore

#2515 Fix submission of scene drafts without performers
  .gqlgenc.yml
  pkg/scraper/stashbox/graphql/generated_client.go
  pkg/scraper/stashbox/graphql/generated_models.go
  pkg/scraper/stashbox/graphql/override.go
  ui/v2.5/src/components/Changelog/versions/v0150.md
Labels: bug

#2518 Fix GraphQL Playground CSP directives for Firefox
  internal/api/server.go
Labels: bug

#2502 Refresh marker panel on marker create
  ui/v2.5/src/components/Changelog/versions/v0150.md
  ui/v2.5/src/components/ScenePlayer/ScenePlayerScrubber.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Shared/TagLink.tsx
  ui/v2.5/src/components/Wall/WallItem.tsx
  ui/v2.5/src/core/StashService.ts
Labels: bug

#2524 Fix image thumbnail generation
  internal/api/routes_image.go
  internal/manager/task_scan_image.go
  pkg/ffmpeg/generate.go
  pkg/ffmpeg/transcoder/image.go
  pkg/hash/videophash/phash.go
  pkg/image/thumbnail.go
Labels: bug

#2527 Fix crash when cancelling pending tasks
  internal/manager/manager.go
  ui/v2.5/src/components/Changelog/versions/v0150.md
Labels: bug
