Repository stashapp/stash, pull requests merged in 2022-07, with the labels that each got.

#2724 Fix lodash-es typos
  ui/v2.5/src/components/Scenes/EditScenesDialog.tsx
  ui/v2.5/src/hooks/LocalForage.ts
  ui/v2.5/src/utils/bulkUpdate.ts
Labels: bug

#2738 Enable automated build for files-refactor
  .github/workflows/build.yml
Labels: chore

#2744 [Files Refactor] Filter and sort by file count
  graphql/schema/types/filters.graphql
  pkg/models/gallery.go
  pkg/models/image.go
  pkg/models/scene.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/scene.go
  ui/v2.5/src/docs/en/Changelog/v0170.md
  ui/v2.5/src/docs/en/ReleaseNotes/index.ts
  ui/v2.5/src/docs/en/ReleaseNotes/v0170.md
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/factory.ts
  ui/v2.5/src/models/list-filter/galleries.ts
  ui/v2.5/src/models/list-filter/images.ts
  ui/v2.5/src/models/list-filter/scenes.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: feature

#2749 Fix UI crash when scene has stash ids but no stash-box configured
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Dialogs/SubmitDraft.tsx
Labels: bug

#2748 Fix messages when adding/removing gallery image
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryImagesPanel.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: bug

#2754 Fix incorrect image displayed in lightbox
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/components/Changelog/versions/v0161.md
  ui/v2.5/src/hooks/Lightbox/hooks.ts
Labels: bug

#2752 Fix non-default video stream from ffprobe result
  pkg/ffmpeg/ffprobe.go
  ui/v2.5/src/components/Changelog/versions/v0161.md
Labels: bug

#2755 Allow unauthenticated access to UI assets
  internal/api/authentication.go
  ui/v2.5/src/components/Changelog/versions/v0161.md
Labels: bug

#2756 Fix keyboard shortcuts not working after selecting
  ui/v2.5/src/components/Changelog/versions/v0161.md
  ui/v2.5/src/components/List/ListOperationButtons.tsx
  ui/v2.5/src/components/Shared/GridCard.tsx
Labels: bug

#2757 Fix % character in tag name causing UI crash
  ui/v2.5/src/components/Changelog/versions/v0161.md
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: bug

#2772 Fix locale import missing translation properties
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Changelog/versions/v0161.md
Labels: bug
