Repository stashapp/stash, pull requests merged in 2022-09, with the labels that each got.

#2868 [Files Refactor] Bug fixes
  internal/api/resolver_mutation_gallery.go
  internal/api/resolver_mutation_stash_box.go
  internal/autotag/gallery.go
  internal/autotag/image.go
  internal/autotag/scene.go
  internal/autotag/tagger.go
  internal/manager/task_clean.go
  internal/manager/task_export.go
  pkg/gallery/delete.go
  pkg/gallery/scan.go
  pkg/gallery/service.go
  pkg/image/delete.go
  pkg/image/scan.go
  pkg/models/model_gallery.go
  pkg/models/model_image.go
  pkg/models/model_scene.go
  pkg/scene/delete.go
  pkg/scene/scan.go
  pkg/scene/service.go
  pkg/scraper/stashbox/stash_box.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/scene.go
Labels: bug

#2873 [Files Refactor] Use DisplayName in autotag errors
  internal/manager/task_autotag.go
Labels: bug

#2880 [Files Refactor] Set primary flag when cleaning
  internal/api/resolver_mutation_gallery.go
  internal/manager/task_clean.go
  internal/manager/task_export.go
  pkg/models/model_gallery.go
  pkg/models/model_image.go
  pkg/models/model_scene.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/migrations/32_files.up.sql
  pkg/sqlite/scene.go
  pkg/sqlite/table.go
  ui/v2.5/src/components/Setup/Migrate.tsx
Labels: bug

#2883 [Files Refactor] Fix filename generation in export
  pkg/models/jsonschema/file_folder.go
  pkg/models/jsonschema/folder.go
Labels: bug

#2886 [Files Refactor] Fix stack overflow creating windows network folders
  internal/manager/import_file.go
  pkg/sqlite/migrations/32_postmigrate.go
Labels: bug

#2892 [Files Refactor] Don't require fingerprint calculation post-migrate
  internal/manager/task_import.go
  pkg/file/scan.go
  pkg/models/jsonschema/file_folder.go
  pkg/sqlite/migrations/32_files.up.sql
Labels: bug, improvement

#2893 [Files Refactor] Cleanup
  internal/desktop/desktop_platform_windows.go
  internal/manager/config/config.go
  internal/manager/task_scan_gallery.go
  internal/manager/task_scan_image.go
  internal/manager/task_scan_scene.go
  pkg/gallery/scan.go
  pkg/image/scan.go
  pkg/scene/scan.go
  pkg/utils/strings_test.go
  ui/v2.5/src/docs/en/Changelog/v0170.md
  ui/v2.5/src/docs/en/MigrationNotes/32.md
  ui/v2.5/src/docs/en/ReleaseNotes/20220826.md
  ui/v2.5/src/docs/en/ReleaseNotes/index.ts
  ui/v2.5/src/docs/en/ReleaseNotes/v0170.md
Labels: chore

#2904 [Files Refactor] Optimize database after migration
  pkg/sqlite/database.go
Labels: improvement

#2906 [Files Refactor] Use batching for pre/post-migration
  pkg/sqlite/migrations/32_postmigrate.go
  pkg/sqlite/migrations/32_premigrate.go
  ui/v2.5/src/docs/en/MigrationNotes/32.md
Labels: improvement

#2894 Fix panic when custom performer image location is invalid
  internal/api/images.go
Labels: bug

#2900 Disable http2 and fix https detection
  internal/api/server.go
Labels: bug

#2897 Fix incorrect gallery when clicking queue item
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
Labels: bug

#2896 Apply autostartVideoOnPlaySelected to queue
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: bug

#2895 Fix continue queue checkbox not persisting
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
Labels: bug

#2910 Fix https detection with reverse proxy
  internal/api/server.go
Labels: bug

#2701 Performer/Studio/Tag/Gallery Create compnent has default name as search query
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryCreate.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/MainNavbar.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerCreate.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioCreate.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagCreate.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
  ui/v2.5/src/docs/en/Changelog/v0170.md
Labels: feature

#2899 Fix URL encoding
  ui/v2.5/src/components/FrontPage/Control.tsx
  ui/v2.5/src/components/List/SavedFilterList.tsx
  ui/v2.5/src/docs/en/Changelog/v0170.md
  ui/v2.5/src/hooks/ListHook.tsx
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/models/list-filter/types.ts
  ui/v2.5/src/models/sceneQueue.ts
Labels: bug

#2915 Fix relationship not loaded panic when using DLNA
  internal/dlna/cds.go
Labels: bug

#2919 Split by whitespace for path includes/excludes
  pkg/sqlite/filter.go
Labels: bug

#2928 Fix bulk add movie to scenes and autotag transaction error
  internal/api/resolver_mutation_scene.go
  internal/manager/repository.go
  internal/manager/task_autotag.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/table.go
Labels: bug

#2920 Use post commit hook for post-create plugin hooks
  internal/api/resolver_mutation_tag_test.go
  internal/identify/identify_test.go
  internal/manager/task_clean.go
  pkg/file/delete.go
  pkg/gallery/scan.go
  pkg/image/scan.go
  pkg/plugin/plugins.go
  pkg/scene/scan.go
  pkg/sqlite/hooks.go
  pkg/sqlite/transaction.go
  pkg/txn/hooks.go
  pkg/txn/transaction.go
Labels: bug

#2918 Fix incorrectly formatted timestamps
  pkg/gallery/scan.go
  pkg/image/scan.go
  pkg/scene/scan.go
  pkg/sqlite/database.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/migrations/33_postmigrate.go
  pkg/sqlite/migrations/33_time_fix.up.sql
  pkg/sqlite/scene.go
Labels: bug

#2926 Set explicit SameSite=Lax on session cookie
  pkg/session/session.go
Labels: improvement

#2927 Suppress benign broken pipe and context closed warnings
  internal/api/routes_image.go
  internal/api/routes_movie.go
  internal/api/routes_performer.go
  internal/api/routes_scene.go
  internal/api/routes_studio.go
  internal/api/routes_tag.go
  internal/manager/running_streams.go
  pkg/ffmpeg/stream.go
  pkg/file/file.go
  pkg/fsutil/file.go
  pkg/utils/image.go
Labels: improvement

#2929 Fix gallery checksum resolver error
  internal/api/resolver_model_gallery.go
  internal/api/resolver_mutation_gallery.go
  internal/manager/task_clean.go
  internal/manager/task_export.go
  pkg/models/model_gallery.go
  pkg/scraper/query_url.go
  pkg/scraper/stash.go
Labels: bug

#2933 More timestamp corrections
  pkg/sqlite/database.go
  pkg/sqlite/file.go
  pkg/sqlite/folder.go
  pkg/sqlite/folder_test.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/migrations/33_noop.up.sql
  pkg/sqlite/migrations/33_postmigrate.go
  pkg/sqlite/migrations/34_indexes.up.sql
  pkg/sqlite/migrations/34_postmigrate.go
  pkg/sqlite/record.go
  pkg/sqlite/scene.go
Labels: bug

#2935 Various bug fixes
  internal/manager/fingerprint.go
  pkg/file/fingerprint.go
  pkg/file/fingerprint_test.go
  pkg/file/scan.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/image.go
  pkg/sqlite/image_test.go
  pkg/sqlite/repository.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_test.go
Labels: bug

#2938 Various bug fixes
  internal/dlna/cds.go
  internal/dlna/paging.go
  internal/manager/fingerprint.go
  pkg/file/file.go
  pkg/file/fingerprint.go
  pkg/file/scan.go
  pkg/scraper/stashbox/stash_box.go
Labels: bug

#2707 [Feature] Add ruby and faraday gem to stash for use in scrapers
  docker/ci/x86_64/Dockerfile
Labels: chore

#2837 Custom localization
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_query_configuration.go
  internal/api/server.go
  internal/manager/config/config.go
  internal/manager/config/config_concurrency_test.go
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/docs/en/Changelog/v0170.md
  ui/v2.5/src/docs/en/Manual/Interface.md
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/en-US.json
Labels: feature

#2943 Fix JSON.parse console error
  internal/api/server.go
Labels: bug

#2945 Various bug fixes
  graphql/documents/data/scene-slim.graphql
  internal/api/routes_image.go
  internal/api/routes_scene.go
  pkg/file/fingerprint.go
  pkg/file/fingerprint_test.go
  pkg/file/scan.go
  pkg/gallery/scan.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/scene.go
  pkg/sqlite/sql.go
Labels: bug

#2946 Only set video algorithm after migration 12
  internal/manager/checksum.go
  internal/manager/config/config.go
  internal/manager/config/config_concurrency_test.go
  internal/manager/manager.go
  internal/manager/post_migrate.go
  pkg/sqlite/migrations/12_postmigrate.go
  ui/v2.5/src/docs/en/Changelog/v0170.md
Labels: bug

#2947 Suppress new context canceled errors
  internal/api/routes_image.go
  internal/api/routes_scene.go
Labels: improvement

#2951 Handle file rescan
  internal/manager/task_clean.go
  internal/manager/task_scan.go
  pkg/file/clean.go
  pkg/file/handler.go
  pkg/file/scan.go
  pkg/fsutil/dir.go
  pkg/gallery/scan.go
  pkg/image/scan.go
  pkg/models/model_file.go
  pkg/scene/hash.go
  pkg/scene/scan.go
  pkg/txn/hooks.go
  pkg/txn/transaction.go
Labels: bug, needs testing

#2955 Rebuild association tables, ensure file-system-based galleries cannot be changed
  internal/api/resolver_mutation_gallery.go
  internal/api/resolver_mutation_image.go
  internal/manager/repository.go
  pkg/gallery/service.go
  pkg/gallery/update.go
  pkg/gallery/validation.go
  pkg/sliceutil/intslice/int_collections.go
  pkg/sqlite/database.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/image_test.go
  pkg/sqlite/migrations/35_assoc_tables.up.sql
  pkg/sqlite/repository.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/tag.go
  pkg/sqlite/tx.go
Labels: bug, chore

#2953 Add backup directory path setting
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_mutation_metadata.go
  internal/api/resolver_query_configuration.go
  internal/manager/config/config.go
  internal/manager/config/config_concurrency_test.go
  internal/manager/manager.go
  pkg/sqlite/database.go
  ui/v2.5/src/components/Settings/SettingsSystemPanel.tsx
  ui/v2.5/src/docs/en/Changelog/v0170.md
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#2925 Performance improvements
  Makefile
  pkg/sqlite/filter.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/movies.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_test.go
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/hooks/ListHook.tsx
Labels: improvement, needs testing

#2840 Stashbox tagger reorder
  ui/v2.5/src/components/Tagger/scenes/SceneTagger.tsx
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
  ui/v2.5/src/docs/en/Changelog/v0170.md
Labels: ui, needs testing

#2832 [Feature] Config option for sub content display
  internal/api/resolver_query_configuration.go
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/components/Settings/context.tsx
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/core/studios.ts
  ui/v2.5/src/core/tags.ts
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#2965 Fix update duplicate ids
  pkg/sqlite/scene_test.go
  pkg/sqlite/table.go
Labels: bug

#2966 Fix backup issues
  internal/api/resolver_mutation_configure.go
  pkg/sqlite/database.go
Labels: bug
