Repository stashapp/stash, pull requests merged in 2022-12, with the labels that each got.

#3146 Performer Active Years is submitted to Stashbox
  pkg/scraper/stashbox/stash_box.go
Labels: feature, backend

#3154 Fix a bunch of scanning / tagging bugs
  pkg/file/walk.go
  pkg/hash/oshash/oshash.go
  pkg/hash/oshash/oshash_internal_test.go
  pkg/hash/oshash/oshash_test.go
  pkg/match/path.go
Labels: bug

#3195 Add injected css/javascript to plugins
  internal/api/server.go
  pkg/plugin/config.go
  pkg/plugin/plugins.go
  ui/v2.5/src/docs/en/Changelog/v0190.md
  ui/v2.5/src/docs/en/Manual/EmbeddedPlugins.md
  ui/v2.5/src/docs/en/Manual/ExternalPlugins.md
  ui/v2.5/src/docs/en/Manual/Plugins.md
Labels: feature

#3240 Clean missing captions during scan
  internal/manager/task_scan.go
  pkg/file/video/caption.go
  pkg/scene/scan.go
  ui/v2.5/src/docs/en/Changelog/v0190.md
Labels: bug

#3241 Fix image exclusion pattern applying to all files
  internal/manager/task_scan.go
  ui/v2.5/src/docs/en/Changelog/v0190.md
Labels: bug

#3242 Fix wall items not showing scene titles where title not set
  ui/v2.5/src/components/Wall/WallItem.tsx
  ui/v2.5/src/docs/en/Changelog/v0190.md
Labels: bug

#3243 Fix date fields not being nulled correctly when cleared
  internal/api/changeset_translator.go
  pkg/sqlite/record.go
  ui/v2.5/src/docs/en/Changelog/v0190.md
Labels: bug

#3251 Fix incorrect performer removed after creation
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/docs/en/Changelog/v0190.md
Labels: bug

#3252 Fix aliases formatted incorrect in performer dialog
  ui/v2.5/src/components/Tagger/PerformerModal.tsx
Labels: bug

#3244 Correct title ordering for objects without titles
  pkg/sqlite/database.go
  pkg/sqlite/functions.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/image.go
  pkg/sqlite/scene.go
  ui/v2.5/src/docs/en/Changelog/v0190.md
Labels: bug

#3257 Fix placeholder in string list input
  ui/v2.5/src/components/Settings/Inputs.tsx
  ui/v2.5/src/components/Shared/StringListInput.tsx
Labels: bug

#3256 Fix generate preview overwrite behaviour
  internal/manager/task_generate.go
  internal/manager/task_generate_preview.go
  ui/v2.5/src/docs/en/Changelog/v0190.md
Labels: bug

#3279 Revert "Update Dockerfile"
  docker/ci/x86_64/Dockerfile
Labels: chore

#3278 Fix failing ARM builds
  docker/ci/x86_64/Dockerfile
Labels: chore

#3282 Restore old stash id filtering code
  pkg/sqlite/performer.go
Labels: bug

#3283 Fix UI crash when scraping new scene
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
Labels: bug

#3285 Fix performer migration
  pkg/sqlite/migrations/42_performer_disambig_aliases.up.sql
  pkg/sqlite/migrations/42_postmigrate.go
Labels: bug

#3015 [Feature] Images new fields : URL & Date
  graphql/documents/data/image-slim.graphql
  graphql/documents/data/image.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/image.graphql
  internal/api/resolver_model_image.go
  internal/api/resolver_mutation_image.go
  pkg/image/export.go
  pkg/image/export_test.go
  pkg/image/import.go
  pkg/models/image.go
  pkg/models/jsonschema/image.go
  pkg/models/model_image.go
  pkg/sqlite/database.go
  pkg/sqlite/image.go
  pkg/sqlite/image_test.go
  pkg/sqlite/migrations/43_image_date_url.up.sql
  pkg/sqlite/setup_test.go
  ui/v2.5/src/components/Images/ImageDetails/ImageDetailPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageFileInfoPanel.tsx
  ui/v2.5/src/docs/en/Changelog/v0190.md
  ui/v2.5/src/models/list-filter/images.ts
  ui/v2.5/src/utils/text.ts
Labels: feature

#3186 Add anonymise database task
  graphql/documents/mutations/metadata.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/metadata.graphql
  internal/api/resolver_mutation_metadata.go
  pkg/sqlite/anonymise.go
  pkg/sqlite/anonymise_test.go
  pkg/sqlite/database.go
  pkg/utils/func.go
  ui/v2.5/src/components/Settings/Tasks/DataManagementTasks.tsx
  ui/v2.5/src/components/Settings/Tasks/SettingsTasksPanel.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/docs/en/Changelog/v0190.md
  ui/v2.5/src/locales/en-GB.json
Labels: feature
