Repository stashapp/stash, pull requests merged in 2022-10, with the labels that each got.

#2949 Add default thumbnails for scenes and images
  internal/api/routes_image.go
  internal/manager/running_streams.go
  internal/static/embed.go
  internal/static/image/image.svg
  internal/static/scene/scene.svg
  pkg/file/file.go
Labels: improvement

#2708 Add descriptions to tags and display tag cards on hover
  graphql/documents/data/tag.graphql
  graphql/schema/types/tag.graphql
  internal/api/resolver_model_tag.go
  internal/api/resolver_mutation_tag.go
  pkg/models/jsonschema/tag.go
  pkg/models/model_tag.go
  pkg/sqlite/database.go
  pkg/sqlite/migrations/36_tags_description.up.sql
  pkg/tag/export.go
  pkg/tag/export_test.go
  pkg/tag/import.go
  pkg/tag/import_test.go
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Shared/TagLink.tsx
  ui/v2.5/src/components/Tags/TagCard.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
  ui/v2.5/src/components/Tags/TagPopover.tsx
  ui/v2.5/src/components/Tags/styles.scss
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/docs/en/Changelog/v0170.md
  ui/v2.5/src/locales/en-GB.json
Labels: feature, bounty

#2978 Associate funscript files on scan
  pkg/file/file.go
  pkg/file/image/scan.go
  pkg/file/scan.go
  pkg/file/video/scan.go
Labels: bug

#2781 #1810 Truncate large numbers on buttons
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/components/Shared/Counter.tsx
  ui/v2.5/src/components/Shared/PopoverCountButton.tsx
  ui/v2.5/src/components/Shared/index.ts
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/docs/en/Changelog/v0170.md
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/utils/text.ts
Labels: feature

#2974 Make scenes page list view checkbox fill entire cell
  ui/v2.5/src/components/Scenes/SceneListTable.tsx
  ui/v2.5/src/components/Scenes/styles.scss
Labels: improvement, ui

#2790 [Files Refactor] Object file management
  graphql/documents/data/file.graphql
  graphql/documents/mutations/file.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/gallery.graphql
  graphql/schema/types/image.graphql
  graphql/schema/types/scene.graphql
  internal/api/resolver_mutation_file.go
  internal/api/resolver_mutation_gallery.go
  internal/api/resolver_mutation_image.go
  internal/api/resolver_mutation_scene.go
  internal/manager/repository.go
  pkg/models/gallery.go
  pkg/models/model_scene.go
  pkg/sqlite/file.go
  pkg/sqlite/file_test.go
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryFileInfoPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageFileInfoPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
  ui/v2.5/src/components/Shared/DeleteFilesDialog.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/index.scss
  ui/v2.5/src/locales/en-GB.json
Labels: feature, needs testing

#2980 Fix list view cell padding
  ui/v2.5/src/components/Scenes/styles.scss
Labels: chore

#2987 Address issue loading all subtitles
  internal/api/routes_scene.go
Labels: bug

#2981 Add apikey to streams
  internal/api/resolver_model_scene.go
  internal/api/urlbuilders/scene.go
  internal/manager/scene.go
Labels: bug

#2982 Fix setup/migrate redirects on subpath proxies
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Setup/Migrate.tsx
Labels: bug

#2992 Fixes gender-mapping with StashBox
  pkg/scraper/stashbox/graphql/generated_client.go
  pkg/scraper/stashbox/graphql/generated_models.go
  pkg/scraper/stashbox/stash_box.go
Labels: bug

#2990 Fix tag/studio alias and caption null filtering
  pkg/sqlite/filter.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/studio_test.go
  pkg/sqlite/tag_test.go
  ui/v2.5/src/models/list-filter/criteria/captions.ts
Labels: bug

#2993 Include primary tag in tag marker count sorting
  pkg/sqlite/tag.go
  pkg/sqlite/tag_test.go
Labels: bug

#2994 Use primary tag name as marker title where title is empty
  graphql/documents/data/scene-slim.graphql
  ui/v2.5/src/components/Scenes/SceneDetails/PrimaryTags.tsx
  ui/v2.5/src/components/Shared/TagLink.tsx
  ui/v2.5/src/components/Wall/WallItem.tsx
  ui/v2.5/src/core/markers.ts
  ui/v2.5/src/utils/navigation.ts
Labels: bug

#2995 Create missing covers during scan
  internal/manager/task_scan.go
  pkg/sqlite/scene.go
  ui/v2.5/src/docs/en/Changelog/v0170.md
  ui/v2.5/src/docs/en/ReleaseNotes/v0170.md
Labels: bug

#2996 Fix video playback hanging at end
  internal/api/routes_scene.go
  internal/manager/running_streams.go
Labels: bug

#2997 Fix phash match presentation
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
Labels: bug

#3007 Fix video looping instead of continuing playlist
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/QueueViewer.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
Labels: bug

#3014 Fix dataloaders not loading in js plugins
  internal/api/server.go
  pkg/plugin/js/gql.go
Labels: bug

#3021 Handle null video durations in migration
  pkg/file/video/scan.go
  pkg/sqlite/migrations/32_files.up.sql
Labels: bug

#3022 Fix export zip paths when exporting from Windows
  internal/manager/import.go
  internal/manager/task_export.go
  internal/manager/task_import.go
Labels: bug

#3036 Fix zip gallery renaming
  pkg/file/scan.go
Labels: bug

#3039 Ignore non-existing scenes in fingerprint submits
  pkg/scraper/stashbox/stash_box.go
Labels: bug

#3040 Use basename as title if empty when scraping by fragment
  pkg/models/model_gallery.go
  pkg/scraper/stash.go
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
Labels: bug

#3046 Fix symlink size calculation
  pkg/file/fs.go
  pkg/file/scan.go
  pkg/file/zip.go
Labels: bug

#3047 Reimplement case-insensitivity move bug fix
  pkg/file/fs.go
  pkg/file/scan.go
  pkg/file/zip.go
  pkg/sqlite/file.go
Labels: bug

#3030 add `pre-ui` to default make target and update documentation
  Makefile
  docs/DEVELOPMENT.md
Labels: chore

#3050 Minor UI fix for StashId display in FileInfoPanel
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
Labels: improvement, ui

#3011 Add Tag description filter
  graphql/schema/types/filters.graphql
  pkg/models/tag.go
  pkg/sqlite/tag.go
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/docs/en/Changelog/v0180.md
  ui/v2.5/src/models/list-filter/criteria/factory.ts
  ui/v2.5/src/models/list-filter/tags.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: feature

#1922 Change performer country value to be ISO code
  pkg/scraper/country.go
  pkg/scraper/postprocessing.go
  pkg/sqlite/database.go
  pkg/sqlite/migrations/37_iso_country_names.up.sql
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/List/AddFilterDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerStashBoxModal.tsx
  ui/v2.5/src/components/Shared/CountryFlag.tsx
  ui/v2.5/src/components/Shared/CountryLabel.tsx
  ui/v2.5/src/components/Shared/CountrySelect.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog.tsx
  ui/v2.5/src/components/Shared/index.ts
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/components/Tagger/PerformerModal.tsx
  ui/v2.5/src/docs/en/Changelog/v0180.md
  ui/v2.5/src/locales/countryNames/zh-TW.json
  ui/v2.5/src/locales/index.ts
  ui/v2.5/src/models/list-filter/criteria/country.ts
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/factory.ts
  ui/v2.5/src/utils/country.ts
  ui/v2.5/src/utils/index.ts
Labels: improvement

#3056 Fix subtitle read error panic
  internal/api/routes_scene.go
Labels: bug

#3044 Fix URL encoding again
  ui/v2.5/src/models/list-filter/filter.ts
Labels: bug

#3057 Performer refactor
  internal/api/changeset_translator.go
  internal/api/images.go
  internal/api/resolver_model_performer.go
  internal/api/resolver_mutation_performer.go
  internal/api/routes_performer.go
  internal/api/urlbuilders/performer.go
  internal/autotag/gallery_test.go
  internal/autotag/image_test.go
  internal/autotag/integration_test.go
  internal/autotag/performer.go
  internal/autotag/performer_test.go
  internal/autotag/scene_test.go
  internal/autotag/tagger.go
  internal/dlna/cds.go
  internal/identify/performer.go
  internal/identify/performer_test.go
  internal/manager/task_autotag.go
  internal/manager/task_stash_box_tag.go
  pkg/gallery/import.go
  pkg/gallery/import_test.go
  pkg/image/import.go
  pkg/image/import_test.go
  pkg/match/path.go
  pkg/models/mocks/PerformerReaderWriter.go
  pkg/models/model_performer.go
  pkg/models/performer.go
  pkg/performer/export.go
  pkg/performer/export_test.go
  pkg/performer/import.go
  pkg/performer/import_test.go
  pkg/performer/update.go
  pkg/performer/validate.go
  pkg/performer/validate_test.go
  pkg/scene/import.go
  pkg/scene/import_test.go
  pkg/scraper/autotag.go
  pkg/scraper/stashbox/stash_box.go
  pkg/sqlite/database.go
  pkg/sqlite/performer.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/scene.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/tables.go
  pkg/sqlite/tag_test.go
  pkg/sqlite/transaction.go
Labels: chore
