Repository stashapp/stash, pull requests merged in 2022-05, with the labels that each got.

#2549 Fix streaming scenes not able to be deleted
  internal/api/routes_scene.go
  internal/manager/running_streams.go
  pkg/fsutil/lock_manager.go
  ui/v2.5/src/components/Scenes/DeleteScenesDialog.tsx
Labels: bug

#2551 Accept gif and webp for images
  ui/v2.5/src/components/Shared/ImageInput.tsx
Labels: improvement

#2553 Generate single preview video for short scenes
  pkg/scene/generate/preview.go
Labels: bug

#2552 Encode query string
  ui/v2.5/src/models/list-filter/filter.ts
Labels: bug

#2554 Migrate vtt contents when hash changes
  pkg/scene/migrate_hash.go
Labels: bug

#2543 Improve Windows stash behaviour
  Makefile
  cmd/stash/main.go
  go.mod
  go.sum
  internal/api/server.go
  internal/desktop/desktop.go
  internal/desktop/desktop_platform_darwin.go
  internal/desktop/desktop_platform_nixes.go
  internal/desktop/desktop_platform_windows.go
  internal/desktop/dialog_nonwindows.go
  internal/desktop/dialog_windows.go
  internal/manager/manager.go
  internal/manager/manager_tasks.go
  internal/manager/post_migrate.go
  internal/manager/task_plugin.go
  ui/v2.5/src/components/Changelog/versions/v0150.md
  vendor/github.com/apenwarr/fixconsole/.gitignore
  vendor/github.com/apenwarr/fixconsole/LICENSE
  vendor/github.com/apenwarr/fixconsole/fixconsole_default.go
  vendor/github.com/apenwarr/fixconsole/fixconsole_windows.go
  vendor/github.com/apenwarr/w32/AUTHORS
  vendor/github.com/apenwarr/w32/LICENSE
  vendor/github.com/apenwarr/w32/README.md
  vendor/github.com/apenwarr/w32/advapi32.go
  vendor/github.com/apenwarr/w32/advapi32_constants.go
  vendor/github.com/apenwarr/w32/advapi32_typedef.go
  vendor/github.com/apenwarr/w32/alpc.go
  vendor/github.com/apenwarr/w32/alpc_constants.go
  vendor/github.com/apenwarr/w32/alpc_typedef.go
  vendor/github.com/apenwarr/w32/comctl32.go
  vendor/github.com/apenwarr/w32/comdlg32.go
  vendor/github.com/apenwarr/w32/constants.go
  vendor/github.com/apenwarr/w32/create_process.go
  vendor/github.com/apenwarr/w32/create_process_constants.go
  vendor/github.com/apenwarr/w32/create_process_typedef.go
  vendor/github.com/apenwarr/w32/dwmapi.go
  vendor/github.com/apenwarr/w32/fork.go
  vendor/github.com/apenwarr/w32/fork_constants.go
  vendor/github.com/apenwarr/w32/fork_typedef.go
  vendor/github.com/apenwarr/w32/gdi32.go
  vendor/github.com/apenwarr/w32/gdiplus.go
  vendor/github.com/apenwarr/w32/idispatch.go
  vendor/github.com/apenwarr/w32/istream.go
  vendor/github.com/apenwarr/w32/iunknown.go
  vendor/github.com/apenwarr/w32/kernel32.go
  vendor/github.com/apenwarr/w32/ole32.go
  vendor/github.com/apenwarr/w32/oleaut32.go
  vendor/github.com/apenwarr/w32/opengl32.go
  vendor/github.com/apenwarr/w32/psapi.go
  vendor/github.com/apenwarr/w32/shell32.go
  vendor/github.com/apenwarr/w32/typedef.go
  vendor/github.com/apenwarr/w32/user32.go
  vendor/github.com/apenwarr/w32/utils.go
  vendor/github.com/apenwarr/w32/vars.go
  vendor/modules.txt
Labels: improvement

#2546 Play scene when scrubber clicked
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: bug

#2547 Fix audio not in video previews
  pkg/ffmpeg/transcoder/splice.go
Labels: bug

#2550 Change playback rates and fix rates after seeking
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: bug, improvement

#2560 Don't show dialog box when run from terminal
  cmd/stash/main.go
  internal/desktop/desktop.go
Labels: bug

#2561 Fix thumbnail generation
  internal/manager/task_scan_scene.go
Labels: bug

#2544 Prevent lightbox transition until specific number of scroll events
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  internal/api/resolver_mutation_configure.go
  internal/manager/config/config.go
  ui/v2.5/src/components/Changelog/versions/v0150.md
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/Lightbox/LightboxImage.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: improvement, bounty

#2563 Fix slideshow autoplaying when on another tab
  ui/v2.5/src/components/Changelog/versions/v0150.md
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/PageVisibility.ts
Labels: bug

#2571 Recommendation home page
  ui/v2.5/package.json
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Changelog/versions/v0150.md
  ui/v2.5/src/components/MainNavbar.tsx
  ui/v2.5/src/components/Recommendations/Recommendations.tsx
  ui/v2.5/src/components/Recommendations/styles.scss
  ui/v2.5/src/index.scss
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/yarn.lock
Labels: feature

#2555 Improve Handy integration
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Changelog/versions/v0150.md
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/hooks/Interactive/context.tsx
  ui/v2.5/src/hooks/Interactive/interactive.scss
  ui/v2.5/src/hooks/Interactive/interactive.ts
  ui/v2.5/src/hooks/Interactive/status.tsx
  ui/v2.5/src/index.scss
  ui/v2.5/src/locales/en-GB.json
Labels: bug, improvement

#2581 Fix direct stream not working in Safari
  internal/manager/running_streams.go
Labels: bug

#2578 Recommendations page bug fixes and refactoring
  ui/v2.5/src/components/Galleries/GalleryRecommendationRow.tsx
  ui/v2.5/src/components/Movies/MovieRecommendationRow.tsx
  ui/v2.5/src/components/Performers/PerformerRecommendationRow.tsx
  ui/v2.5/src/components/Recommendations/Recommendations.tsx
  ui/v2.5/src/components/Recommendations/styles.scss
  ui/v2.5/src/components/Scenes/SceneRecommendationRow.tsx
  ui/v2.5/src/components/Studios/StudioRecommendationRow.tsx
  ui/v2.5/src/core/recommendations.ts
  ui/v2.5/src/locales/en-GB.json
Labels: bug

#2586 Add Danish and Polish i18n support
  README.md
  internal/api/locale.go
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/locales/index.ts
Labels: i18n

#2584 CSS: Fix mobile filter tags
  ui/v2.5/src/components/List/FilterTags.tsx
  ui/v2.5/src/index.scss
Labels: improvement, ui

#2594 Fix gallery scan
  internal/manager/task_scan_gallery.go
Labels: bug

#2601 Add Korean Language
  internal/api/locale.go
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/locales/index.ts
Labels: i18n
