Repository stashapp/stash, pull requests merged in 2022-02, with the labels that each got.

#2234 Add support for submitting performer/scene drafts to stash-box
  graphql/documents/mutations/stash-box.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/stash-box.graphql
  graphql/stash-box/query.graphql
  pkg/api/resolver_mutation_stash_box.go
  pkg/scraper/stashbox/graphql/generated_client.go
  pkg/scraper/stashbox/graphql/generated_models.go
  pkg/scraper/stashbox/stash_box.go
  ui/v2.5/src/components/Changelog/versions/v0130.md
  ui/v2.5/src/components/Dialogs/SubmitDraft.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerSubmitButton.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
  ui/v2.5/src/components/Shared/DetailsEditNavbar.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/utils/index.ts
  ui/v2.5/src/utils/stashbox.ts
Labels: feature

#2229 Remove trusted proxies
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/authentication.go
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
  pkg/manager/config/config_concurrency_test.go
  pkg/session/authentication.go
  pkg/session/authentication_test.go
  ui/v2.5/src/components/Changelog/versions/v0130.md
  ui/v2.5/src/components/Settings/SettingsSecurityPanel.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: improvement, backend

#2275 Add lightbox preview button to image card
  ui/v2.5/src/components/Changelog/versions/v0130.md
  ui/v2.5/src/components/Images/ImageCard.tsx
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/index.scss
Labels: feature, ui

#2265 Delete funscripts while deleting scene
  pkg/scene/delete.go
  ui/v2.5/src/components/Changelog/versions/v0130.md
  ui/v2.5/src/components/Scenes/DeleteScenesDialog.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: bug

#2278 Fix build for renamed armv6
  docker/ci/x86_64/Dockerfile
  pkg/api/check_version.go
Labels: bug

#2279 Add proper home screen icon for mobile users
  ui/v2.5/index.html
Labels: ui

#2209 Cleaned up some language.
  README.md
Labels: documentation

#2294 Disable image lightbox for multi-selection
  ui/v2.5/src/components/Images/ImageList.tsx
Labels: bug, ui

#2301 Make changes to fix special characters in Criterion labels (#1819)
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
Labels: bug, ui

#2282 Add additional fields to bulk performer dialog
  ui/v2.5/src/components/Performers/EditPerformersDialog.tsx
Labels: feature, ui

#2257 Add Several Media Performer Detail Filters, Scene Filters and Sort
  graphql/schema/types/filters.graphql
  pkg/sqlite/filter.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/scene.go
  pkg/sqlite/sql.go
  ui/v2.5/src/components/Changelog/versions/v0130.md
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/en-US.json
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/factory.ts
  ui/v2.5/src/models/list-filter/criteria/favorite.ts
  ui/v2.5/src/models/list-filter/criteria/phash.ts
  ui/v2.5/src/models/list-filter/galleries.ts
  ui/v2.5/src/models/list-filter/images.ts
  ui/v2.5/src/models/list-filter/scenes.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: feature

#2314 True case insensitive regex support
  pkg/manager/exclude_files.go
  pkg/manager/exclude_files_test.go
Labels: bug

#2295 Update apple touch icon
  ui/v2.5/index.html
  ui/v2.5/public/apple-touch-icon.png
Labels: ui

#2304 Localize hard strings in submission & performer tagger
  ui/v2.5/src/components/Dialogs/SubmitDraft.tsx
  ui/v2.5/src/components/Tagger/performers/Config.tsx
  ui/v2.5/src/components/Tagger/performers/PerformerTagger.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/zh-TW.json
Labels: chore

#2283 Add bulk movie update
  graphql/documents/mutations/movie.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/movie.graphql
  pkg/api/resolver_mutation_movie.go
  ui/v2.5/src/components/Changelog/versions/v0130.md
  ui/v2.5/src/components/Galleries/EditGalleriesDialog.tsx
  ui/v2.5/src/components/Images/EditImagesDialog.tsx
  ui/v2.5/src/components/Movies/EditMoviesDialog.tsx
  ui/v2.5/src/components/Movies/MovieList.tsx
  ui/v2.5/src/components/Performers/EditPerformersDialog.tsx
  ui/v2.5/src/components/Scenes/EditScenesDialog.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/utils/bulkUpdate.ts
Labels: feature, ui

#2317 Scan now uses exclude regex on gallery zips
  pkg/manager/image.go
  ui/v2.5/src/components/Changelog/versions/v0130.md
Labels: bug

#2319 Clamp generator parameters
  pkg/manager/generator.go
  ui/v2.5/src/components/Settings/GeneratePreviewOptions.tsx
Labels: bug

#2323 Performer tagger modal will load country name instead of code
  ui/v2.5/src/components/Tagger/PerformerModal.tsx
Labels: bug

#2330 Fix windows systray icon just hanging out
  go.mod
  go.sum
  pkg/desktop/systray_nonlinux.go
  vendor/github.com/kermieisinthehouse/systray/systray_windows.go
  vendor/modules.txt
Labels: improvement

#2329 Fix Performer Save Edit button position
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Shared/styles.scss
Labels: bug, ui

#2320 Internationalise hard-coded strings
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryDetailPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageDetailPanel.tsx
Labels: chore

#2327 Add missing card classes
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Images/ImageCard.tsx
  ui/v2.5/src/components/Movies/MovieCard.tsx
  ui/v2.5/src/components/Movies/styles.scss
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Shared/GridCard.tsx
  ui/v2.5/src/components/Studios/StudioCard.tsx
Labels: improvement

#2324 Add gallery icon to image card
  ui/v2.5/src/components/Images/ImageCard.tsx
Labels: improvement

#2325 Add setting for showing scene scrubber by default
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  pkg/api/resolver_mutation_configure.go
  pkg/api/resolver_query_configuration.go
  pkg/manager/config/config.go
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#2328 Combine system preview generation options
  ui/v2.5/src/components/Dialogs/GenerateDialog.tsx
  ui/v2.5/src/components/Settings/Tasks/LibraryTasks.tsx
Labels: bug

#2339 Fix performer tags not applying on scene scrapers
  pkg/scraper/mapped.go
Labels: bug

#2335 Add filesize on scene cards, invisibly
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/styles.scss
Labels: feature, ui

#2346 Remove ChunkDuration warning
  pkg/manager/generator.go
Labels: bug

#2343 Disable macos bundling until issues resolved
  .github/workflows/build.yml
  README.md
Labels: chore

#2336 Handle unicode characters in autotag
  pkg/match/path.go
  pkg/match/path_test.go
  pkg/sqlite/performer.go
  pkg/sqlite/repository.go
  pkg/sqlite/studio.go
  pkg/sqlite/tag.go
Labels: bug

#2342 Remove generate preview options from tasks page
  ui/v2.5/src/components/Settings/Inputs.tsx
  ui/v2.5/src/components/Settings/Tasks/GenerateOptions.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: improvement, ui
