Repository stashapp/stash, pull requests merged in 2023-06, with the labels that each got.

#3792 Fixes filter issues
  ui/v2.5/src/components/Scenes/SceneDetails/SceneVideoFilterPanel.tsx
Labels: bug, javascript

#3793 Fix videojs-vr issues
  ui/v2.5/src/@types/videojs-vr.d.ts
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/vrmode.ts
Labels: bug, javascript

#3775 Fix joined hierarchical filtering
  pkg/models/filter.go
  pkg/sqlite/filter.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/image.go
  pkg/sqlite/image_test.go
  pkg/sqlite/movies.go
  pkg/sqlite/performer.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_marker.go
  pkg/sqlite/scene_marker_test.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/tag.go
  pkg/sqlite/tag_test.go
  ui/v2.5/src/components/List/Filters/SelectableFilter.tsx
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/tags.ts
Labels: bug, backend

#3729 Fix iOS captions
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/styles.scss
Labels: bug, javascript

#3802 Update gallery when adding image via scan
  pkg/image/scan.go
Labels: bug

#3772 Filter tweaks
  ui/v2.5/src/components/List/CriterionEditor.tsx
  ui/v2.5/src/components/List/Filters/PerformersFilter.tsx
  ui/v2.5/src/components/List/Filters/SelectableFilter.tsx
  ui/v2.5/src/components/List/Filters/StudiosFilter.tsx
  ui/v2.5/src/components/List/Filters/TagsFilter.tsx
  ui/v2.5/src/components/Shared/ClearableInput.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/criteria/country.ts
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
  ui/v2.5/src/models/list-filter/criteria/none.ts
  ui/v2.5/src/models/list-filter/criteria/performers.ts
  ui/v2.5/src/models/list-filter/criteria/phash.ts
  ui/v2.5/src/models/list-filter/criteria/rating.ts
  ui/v2.5/src/models/list-filter/criteria/stash-ids.ts
  ui/v2.5/src/models/list-filter/criteria/studios.ts
  ui/v2.5/src/models/list-filter/criteria/tags.ts
  ui/v2.5/src/models/list-filter/filter.ts
Labels: bug, improvement, javascript

#3804 Fix tagger query path on Windows
  ui/v2.5/src/components/Tagger/utils.ts
Labels: bug, javascript

#3805 Don't prompt for unsaved changes when navigating within main page
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieEditPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
  ui/v2.5/src/utils/navigation.ts
Labels: bug, javascript

#3803 Include studio code in scene merge dialog
  ui/v2.5/src/components/Scenes/SceneMergeDialog.tsx
Labels: bug

#3826 Fix clip log message
  pkg/file/image/scan.go
Labels: bug, backend

#3798 Make displayed resolution information coherent for 2:1/VR files
  graphql/schema/types/filters.graphql
  pkg/models/resolution.go
  ui/v2.5/src/utils/resolution.ts
  ui/v2.5/src/utils/text.ts
Labels: improvement, backend, javascript

#3816 Include subsidiary studios/tags in tab badge counters
  graphql/documents/data/studio.graphql
  graphql/documents/data/tag.graphql
  graphql/schema/types/movie.graphql
  graphql/schema/types/performer.graphql
  graphql/schema/types/studio.graphql
  graphql/schema/types/tag.graphql
  internal/api/resolver_model_movie.go
  internal/api/resolver_model_performer.go
  internal/api/resolver_model_studio.go
  internal/api/resolver_model_tag.go
  pkg/gallery/query.go
  pkg/image/query.go
  pkg/models/mocks/MovieReaderWriter.go
  pkg/models/mocks/SceneMarkerReaderWriter.go
  pkg/models/mocks/SceneReaderWriter.go
  pkg/models/movie.go
  pkg/models/scene.go
  pkg/models/scene_marker.go
  pkg/movie/query.go
  pkg/performer/query.go
  pkg/scene/marker_query.go
  pkg/scene/query.go
  pkg/sqlite/movies.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_marker.go
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Images/ImageDetails/Image.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Shared/Counter.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
Labels: bug, improvement, backend, javascript

#3828 Prevent fullscreen break when loading scene
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
Labels: bug, javascript

#3829 Sort special characters before numbers
  go.mod
  go.sum
  pkg/sqlite/driver.go
  vendor/github.com/WithoutPants/sortorder/LICENSE
  vendor/github.com/WithoutPants/sortorder/casefolded/README.md
  vendor/github.com/WithoutPants/sortorder/casefolded/natsort.go
  vendor/modules.txt
Labels: bug, bounty, backend

#3836 fix: return newly created filter
  internal/api/resolver_mutation_saved_filter.go
Labels: bug, backend

#3851 fix: onQueueMoreScenes was adding new scenes at the start of the queue
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
Labels: bug

#3845 Handle missing studio ids in getHierarchicalValues
  pkg/sqlite/filter.go
  pkg/sqlite/scene_test.go
Labels: bug

#3846 Fix marker tag filtering
  pkg/sqlite/scene_marker.go
  pkg/sqlite/scene_marker_test.go
  pkg/sqlite/setup_test.go
Labels: bug
