Repository stashapp/stash, pull requests merged in 2023-02, with the labels that each got.

#3410 Handle unset rating system
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/hooks/keybinds.ts
Labels: bug

#3408 Clear search term when clicking popover pill
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/docs/en/Changelog/v0190.md
  ui/v2.5/src/models/list-filter/filter.ts
Labels: bug

#3407 Remove is (not) null modifier for resume and play times
  ui/v2.5/src/models/list-filter/criteria/factory.ts
Labels: bug

#3357 Add additional latest version info
  graphql/documents/queries/misc.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/version.graphql
  internal/api/check_version.go
  internal/api/resolver.go
  internal/api/server.go
  ui/v2.5/src/components/Settings/SettingsAboutPanel.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#3405 Add count attribute to badges
  ui/v2.5/src/components/Shared/Counter.tsx
Labels: improvement

#3406 Set performer disambiguation for names with parentheses
  pkg/sqlite/migrations/42_postmigrate.go
Labels: improvement

#3409 Fix save disabled when creating new object with name
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagCreate.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
Labels: bug

#3414 Fix multi scrape bug with fileless scenes
  pkg/scraper/stashbox/stash_box.go
  ui/v2.5/src/docs/en/Changelog/v0190.md
Labels: bug

#3415 Handle folder symlinks correctly during clean
  pkg/file/clean.go
  ui/v2.5/src/docs/en/Changelog/v0190.md
Labels: bug

#3417 Use absolute paths when creating config file
  internal/manager/manager.go
Labels: bug

#3424 Add regex validation
  internal/api/resolver_mutation_configure.go
Labels: improvement

#3428 Error reliably on invalid filters
  pkg/sqlite/file.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/movies.go
  pkg/sqlite/performer.go
  pkg/sqlite/query.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_marker.go
  pkg/sqlite/studio.go
  pkg/sqlite/tag.go
Labels: bug

#3429 Disable tag popover for create tag option
  ui/v2.5/src/components/Shared/Select.tsx
Labels: bug

#3389 Support non-utf8 encoding for zip files
  go.mod
  go.sum
  pkg/file/zip.go
  vendor/github.com/xWTF/chardet/2022.go
  vendor/github.com/xWTF/chardet/AUTHORS
  vendor/github.com/xWTF/chardet/LICENSE
  vendor/github.com/xWTF/chardet/README.md
  vendor/github.com/xWTF/chardet/detector.go
  vendor/github.com/xWTF/chardet/icu-license.html
  vendor/github.com/xWTF/chardet/multi_byte.go
  vendor/github.com/xWTF/chardet/recognizer.go
  vendor/github.com/xWTF/chardet/single_byte.go
  vendor/github.com/xWTF/chardet/unicode.go
  vendor/github.com/xWTF/chardet/utf8.go
  vendor/modules.txt
Labels: bug

#3433 Fix gallery zip scan context
  pkg/file/scan.go
  pkg/job/context.go
  pkg/job/manager.go
  pkg/utils/context.go
Labels: bug

#3438 Improve 'item not found' pages
  internal/api/resolver_query_find_gallery.go
  internal/api/resolver_query_find_image.go
  internal/api/resolver_query_find_movie.go
  internal/api/resolver_query_find_performer.go
  internal/api/resolver_query_find_saved_filter.go
  internal/api/resolver_query_find_scene.go
  internal/api/resolver_query_find_studio.go
  internal/api/resolver_query_find_tag.go
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
Labels: improvement

#3425 Fix golangci-lint error
  pkg/scraper/cookies.go
Labels: chore

#3439 Tagger use first available URL if no studio URL
  pkg/scraper/stashbox/stash_box.go
Labels: bug

#3157 Sort duplicate scenes by path
  pkg/sqlite/scene.go
Labels: improvement

#3434 Fix custom CSS/JS requiring force-reload
  internal/api/server.go
Labels: improvement

#3445 Fix yup schemas
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
Labels: bug

#3444 Fix allTags cache reset
  graphql/documents/queries/misc.graphql
  ui/v2.5/src/core/StashService.ts
Labels: bug

#3376 Added VFR Detection
  internal/manager/task_generate_preview.go
  pkg/scene/generate/preview.go
Labels: improvement

#3369 Added favorite button in Performer grid view
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Performers/styles.scss
Labels: feature, ui

#3456 Fix batch performer panic
  internal/manager/task_stash_box_tag.go
Labels: bug

#3452 Optimize allData queries
  graphql/documents/queries/misc.graphql
  graphql/schema/schema.graphql
  internal/api/resolver_query_find_gallery.go
  internal/api/resolver_query_find_image.go
  internal/api/resolver_query_find_scene.go
  internal/api/resolver_query_find_scene_marker.go
  pkg/models/mocks/SceneMarkerReaderWriter.go
  pkg/models/mocks/SceneReaderWriter.go
  pkg/models/scene_marker.go
  pkg/sqlite/scene_marker.go
  pkg/sqlite/scene_marker_test.go
  ui/v2.5/src/components/List/Filters/HierarchicalLabelValueFilter.tsx
  ui/v2.5/src/components/List/Filters/LabeledIdFilter.tsx
  ui/v2.5/src/components/Shared/MultiSet.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Tagger/scenes/PerformerResult.tsx
  ui/v2.5/src/components/Tagger/scenes/StudioResult.tsx
Labels: bug, improvement

#3448 Minor gallery-related fixes
  graphql/documents/data/scene-slim.graphql
  ui/v2.5/src/components/Dialogs/IdentifyDialog/styles.scss
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneListTable.tsx
  ui/v2.5/src/styles/_theme.scss
Labels: bug

#3462 Merge 0.19.1 branch
  ui/v2.5/src/docs/en/Changelog/v0190.md
Labels: chore

#3464 Fix latest version for dev builds
  internal/api/check_version.go
Labels: bug

#3466 Fix scene merge dialog
  ui/v2.5/src/components/FrontPage/FrontPageConfig.tsx
  ui/v2.5/src/components/Scenes/SceneMergeDialog.tsx
Labels: bug

#3467 Add changelog for v0.20.0
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/docs/en/Changelog/v0200.md
Labels: chore

#3391 Improved gallery cover lookup
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  internal/api/resolver_model_gallery.go
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_query_configuration.go
  internal/manager/config/config.go
  pkg/image/query.go
  ui/v2.5/src/components/Settings/SettingsLibraryPanel.tsx
  ui/v2.5/src/docs/en/Changelog/v0200.md
  ui/v2.5/src/docs/en/Manual/Configuration.md
  ui/v2.5/src/locales/de-DE.json
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/it-IT.json
Labels: improvement

#3475 add missing brew packages to build instructions
  docs/DEVELOPMENT.md
Labels: documentation

#3374 Show funscript heatmaps in player
  ui/v2.5/src/components/ScenePlayer/ScenePlayerScrubber.tsx
  ui/v2.5/src/components/ScenePlayer/styles.scss
  ui/v2.5/src/docs/en/Changelog/v0200.md
Labels: feature, ui

#3373 Add ranges to funscript heatmaps
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_query_configuration.go
  internal/manager/config/config.go
  internal/manager/generator_interactive_heatmap_speed.go
  internal/manager/task_generate_interactive_heatmap_speed.go
  ui/v2.5/src/components/Settings/SettingsSystemPanel.tsx
  ui/v2.5/src/docs/en/Changelog/v0200.md
  ui/v2.5/src/locales/en-GB.json
Labels: feature, ui

#3378 Added the ability to do Sequential Scans
  internal/manager/config/config.go
  internal/manager/task_scan.go
  pkg/txn/hooks.go
  pkg/txn/transaction.go
  ui/v2.5/src/docs/en/Changelog/v0200.md
  ui/v2.5/src/docs/en/Manual/Configuration.md
Labels: feature

#3274 Overhaul HLS streaming
  internal/api/byterange.go
  internal/api/resolver_mutation_configure.go
  internal/api/routes_scene.go
  internal/api/server.go
  internal/manager/manager.go
  internal/manager/running_streams.go
  internal/manager/scene.go
  pkg/ffmpeg/hls.go
  pkg/ffmpeg/stream.go
  pkg/ffmpeg/stream_segmented.go
  pkg/ffmpeg/stream_transcode.go
  ui/v2.5/src/docs/en/Changelog/v0200.md
  ui/v2.5/src/docs/en/Manual/Configuration.md
  ui/v2.5/src/docs/en/ReleaseNotes/index.ts
  ui/v2.5/src/docs/en/ReleaseNotes/v0200.md
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#3459 Add setting for dropdown limit
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/docs/en/Changelog/v0200.md
  ui/v2.5/src/locales/en-GB.json
Labels: improvement, bounty, needs testing

#3465 Include database cover in draft submission if filesystem version not present
  internal/api/resolver_mutation_stash_box.go
  internal/manager/repository.go
  pkg/scene/screenshot.go
  pkg/scraper/stashbox/stash_box.go
  ui/v2.5/src/components/Dialogs/SubmitDraft.tsx
  ui/v2.5/src/docs/en/Changelog/v0200.md
Labels: bug, needs testing

#3491 Fix custom transcode arguments
  pkg/ffmpeg/stream.go
  pkg/ffmpeg/stream_segmented.go
  pkg/ffmpeg/stream_transcode.go
  ui/v2.5/src/locales/en-GB.json
Labels: bug

#3488 Use matched stash id boolean as the name suggests
  ui/v2.5/src/components/Tagger/scenes/PerformerResult.tsx
  ui/v2.5/src/docs/en/Changelog/v0200.md
Labels: bug

#3482 Fix filter hooks
  ui/v2.5/src/core/performers.ts
  ui/v2.5/src/core/studios.ts
  ui/v2.5/src/core/tags.ts
Labels: bug
