Repository stashapp/stash, pull requests merged in 2023-04, with the labels that each got.

#3646 Don't regenerate covers if present during scan
  internal/manager/task_generate_screenshot.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/scene_test.go
Labels: bug

#3647 Fix empty strings overwriting during scrape
  ui/v2.5/src/components/Scenes/SceneMergeDialog.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog.tsx
Labels: bug

#3560 Sort case insensitive, date by newest first
  go.mod
  go.sum
  pkg/sqlite/driver.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/movies.go
  pkg/sqlite/performer.go
  pkg/sqlite/scene.go
  pkg/sqlite/sql.go
  pkg/sqlite/studio.go
  pkg/sqlite/tag.go
  ui/v2.5/src/models/list-filter/filter.ts
  vendor/github.com/fvbommel/sortorder/.gitignore
  vendor/github.com/fvbommel/sortorder/README.md
  vendor/github.com/fvbommel/sortorder/casefolded/README.md
  vendor/github.com/fvbommel/sortorder/casefolded/natsort.go
  vendor/github.com/fvbommel/sortorder/doc.go
  vendor/github.com/fvbommel/sortorder/natsort.go
  vendor/modules.txt
Labels: improvement, backend

#3562 Log errors returned from graphql
  internal/api/error.go
  internal/api/resolver_mutation_configure.go
  internal/api/server.go
  internal/api/session.go
  internal/log/logger.go
  pkg/logger/basic.go
  pkg/logger/logger.go
  pkg/session/session.go
Labels: improvement

#3576 Use 100% width on cards in mobile
  ui/v2.5/src/components/Galleries/styles.scss
  ui/v2.5/src/components/Images/styles.scss
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Tags/styles.scss
Labels: ui

#3577 Embed default icons
  internal/api/routes_studio.go
  internal/api/routes_tag.go
  internal/static/embed.go
  internal/static/studio/studio.svg
  internal/static/tag/tag.svg
  pkg/models/model_studio.go
  pkg/models/model_tag.go
  pkg/sqlite/setup_test.go
Labels: improvement, ui

#3578 Require source selector click to show
  ui/v2.5/src/components/ScenePlayer/styles.scss
Labels: improvement, ui

#3579 add conditionals to avoid url base duplication on stashbox submit
  pkg/scraper/stashbox/stash_box.go
Labels: bug

#3596 Phash distance filter
  graphql/schema/types/filters.graphql
  pkg/models/filter.go
  pkg/models/scene.go
  pkg/sqlite/driver.go
  pkg/sqlite/phash.go
  pkg/sqlite/scene.go
  ui/v2.5/src/components/List/CriterionEditor.tsx
  ui/v2.5/src/components/List/Filters/PhashFilter.tsx
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/factory.ts
  ui/v2.5/src/models/list-filter/criteria/phash.ts
  ui/v2.5/src/models/list-filter/types.ts
  ui/v2.5/src/utils/navigation.ts
Labels: feature

#3620 Use ReadTxn for performer aliases
  internal/api/resolver_model_performer.go
Labels: improvement, backend

#3616 Typo in Settings > System > Transcoding
  ui/v2.5/src/locales/en-GB.json
Labels: documentation

#3629 Update Help > Tasks manual
  ui/v2.5/src/docs/en/Manual/Tasks.md
Labels: documentation

#3668 Add 0.21 changelog
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/docs/en/Changelog/v0210.md
Labels: chore

#3603 Add opt-in UI sourcemaps
  Makefile
  ui/v2.5/vite.config.js
Labels: improvement, chore

#3610 Fix zip gallery moving
  pkg/file/folder.go
  pkg/file/move.go
  pkg/file/scan.go
Labels: bug

#3674 Use chevron icons instead of < and >
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/ScenePlayer/ScenePlayerScrubber.tsx
  ui/v2.5/src/components/ScenePlayer/styles.scss
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
Labels: improvement, javascript

#3653 Add hint for alias duplicates
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Shared/StringListInput.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
Labels: improvement, javascript

#3588 Add O-Counter for Performers and Sort/Filter Performers by O-Counter
  graphql/documents/data/performer.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/performer.graphql
  internal/api/resolver_model_performer.go
  pkg/models/image.go
  pkg/models/mocks/ImageReaderWriter.go
  pkg/models/mocks/SceneReaderWriter.go
  pkg/models/performer.go
  pkg/models/scene.go
  pkg/scraper/stashbox/graphql/generated_models.go
  pkg/sqlite/filter.go
  pkg/sqlite/image.go
  pkg/sqlite/performer.go
  pkg/sqlite/scene.go
  pkg/sqlite/sql.go
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Performers/PerformerListTable.tsx
  ui/v2.5/src/models/list-filter/performers.ts
Labels: improvement, backend

#3563 Add performer pairings/appears with tab to performers
  graphql/documents/data/performer.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/performer.graphql
  internal/api/resolver_model_performer.go
  pkg/models/performer.go
  pkg/performer/query.go
  pkg/sqlite/performer.go
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/performerAppearsWithPanel.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/utils/navigation.ts
Labels: feature, bounty, ui

#3675 Pinned Filters
  ui/v2.5/src/components/List/EditFilterDialog.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/core/config.ts
Labels: improvement, ui, backend

#3632 Remove styling from #performer-page div
  ui/v2.5/src/components/Performers/styles.scss
Labels: improvement, ui

#3648 Fix latest version error
  internal/api/check_version.go
Labels: bug, backend

#3650 Use big-buttons instead of videojs-mobile-ui touch controls
  ui/v2.5/package.json
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/big-buttons.ts
  ui/v2.5/yarn.lock
Labels: bug, javascript
