Repository stashapp/stash, pull requests merged in 2023-08, with the labels that each got.

#3982 Details redesign bug fixes
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Shared/GridCard.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/index.scss
  ui/v2.5/src/utils/apple.ts
Labels: bug

#3978 Fix parent/child links on tag pages
  ui/v2.5/src/components/Shared/TagLink.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagDetailsPanel.tsx
  ui/v2.5/src/utils/navigation.ts
Labels: bug

#3913 Add allow adding avif as images
  pkg/file/image/scan.go
Labels: bug

#3964 performer: stashbox: show age, gender, and image
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerStashBoxModal.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#3965 performer: scrape dialog: allow selecting from multiple images
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog.tsx
Labels: feature

#3979 Re-add to hide video player overflow
  ui/v2.5/src/components/ScenePlayer/styles.scss
Labels: bug

#3990 Detail redesign round 2 bug fixes
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioDetailsPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagDetailsPanel.tsx
  ui/v2.5/src/index.scss
Labels: bug, improvement

#3991 Add v0.22.0 changelog
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/docs/en/Changelog/v0220.md
Labels: chore

#3988 Rename marker folders when hash changes
  pkg/models/paths/paths_scene_markers.go
  pkg/scene/migrate_hash.go
Labels: bug

#3989 Refactor scraped image selector
  ui/v2.5/src/components/Shared/ImageSelector.tsx
  ui/v2.5/src/components/Shared/LoadingIndicator.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/locales/en-GB.json
Labels: bug, improvement

#3995 Details redesign tweaks and refactoring
  graphql/documents/data/gallery-slim.graphql
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/FrontPage/FrontPage.tsx
  ui/v2.5/src/components/Galleries/Galleries.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Images/ImageDetails/Image.tsx
  ui/v2.5/src/components/Images/Images.tsx
  ui/v2.5/src/components/List/ItemList.tsx
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Movies/Movies.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/Performers.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
  ui/v2.5/src/components/Scenes/Scenes.tsx
  ui/v2.5/src/components/Settings/Settings.tsx
  ui/v2.5/src/components/Shared/DetailImage.tsx
  ui/v2.5/src/components/Shared/GridCard.tsx
  ui/v2.5/src/components/Shared/constants.ts
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioDetailsPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/components/Studios/Studios.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/Tags.tsx
  ui/v2.5/src/core/createClient.ts
  ui/v2.5/src/hooks/detailsPanel.ts
  ui/v2.5/src/hooks/scrollToTop.ts
  ui/v2.5/src/hooks/title.ts
  ui/v2.5/src/utils/image.tsx
Labels: improvement

#4001 Fix creating from non-stashbox sources in Scene Tagger
  ui/v2.5/src/components/Tagger/context.tsx
  ui/v2.5/src/components/Tagger/scenes/StudioModal.tsx
Labels: bug

#3996 fix separator being used around null fields
  ui/v2.5/src/components/Movies/MovieDetails/MovieDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioDetailsPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagDetailsPanel.tsx
  ui/v2.5/src/index.scss
  ui/v2.5/src/utils/apple.ts
Labels: bug

#4004 Added scene and image file deletion logging
  pkg/image/delete.go
  pkg/scene/delete.go
Labels: improvement

#4005 Fix urls disappearing when merging scenes
  ui/v2.5/src/components/Scenes/SceneMergeDialog.tsx
Labels: bug

#4007 More concise Auto Tagging documentation
  ui/v2.5/src/docs/en/Manual/AutoTagging.md
Labels: documentation

#4012 move item-list-container in detail-body
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/index.scss
Labels: bug

#4017 Make folder select easier to click
  ui/v2.5/src/components/Shared/FolderSelect/FolderSelect.tsx
  ui/v2.5/src/components/Shared/styles.scss
Labels: improvement

#4018 Fix performer tag sort
  internal/identify/scene_test.go
  pkg/sqlite/performer.go
Labels: improvement

#4024 Fix bulk performer tagger
  internal/identify/performer.go
  internal/identify/performer_test.go
  internal/manager/manager_tasks.go
  internal/manager/task_stash_box_tag.go
  pkg/models/model_scraped_item.go
  pkg/models/model_scraped_item_test.go
  pkg/scraper/stashbox/stash_box.go
  ui/v2.5/src/components/Tagger/PerformerFieldSelector.tsx
  ui/v2.5/src/components/Tagger/constants.ts
  ui/v2.5/src/components/Tagger/performers/Config.tsx
  ui/v2.5/src/components/Tagger/performers/PerformerTagger.tsx
  ui/v2.5/src/components/Tagger/performers/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/studios/Config.tsx
  ui/v2.5/src/components/Tagger/studios/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/studios/StudioFieldSelector.tsx
  ui/v2.5/src/components/Tagger/studios/StudioTagger.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/utils/duration.ts
  ui/v2.5/src/utils/text.ts
Labels: bug

#4038 Add explicit option to store blobs in database at setup
  graphql/schema/types/config.graphql
  internal/manager/manager.go
  ui/v2.5/src/components/Setup/Setup.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: bug

#4039 Change drop location for dropdown menus
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
Labels: bug

#4040 Show primary tag error on touch or submit
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkerForm.tsx
Labels: bug

#4029 Make x button on badges easier to click
  ui/v2.5/src/index.scss
Labels: bug

#4047 Fix show all details default behavior
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
Labels: bug

#4031 Tagger config option to mark scene as organized
  ui/v2.5/src/components/Tagger/constants.ts
  ui/v2.5/src/components/Tagger/context.tsx
  ui/v2.5/src/components/Tagger/scenes/Config.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#4032 Details pages start with populated content tab
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
Labels: improvement

#4022 Preview scrubber
  ui/v2.5/package.json
  ui/v2.5/src/components/ScenePlayer/ScenePlayerScrubber.tsx
  ui/v2.5/src/components/Scenes/PreviewScrubber.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/hooks/sprite.ts
  ui/v2.5/src/models/sceneQueue.ts
Labels: feature

#4013 Performer select refactor
  graphql/documents/data/performer-slim.graphql
  graphql/documents/queries/misc.graphql
  graphql/documents/queries/performer.graphql
  graphql/schema/schema.graphql
  internal/api/resolver_query_find_performer.go
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerSelect.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Shared/FilterSelect.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Tagger/queries.ts
  ui/v2.5/src/components/Tagger/scenes/PerformerResult.tsx
  ui/v2.5/src/core/StashService.ts
Labels: improvement

#4051 [Bug Fix] Nil pointer dereference in scraper
  internal/api/resolver_query_scraper.go
Labels: bug

#3904 Region-based Looping (a.k.a. A/B looping) utilizing videojs-abloop plugin
  ui/v2.5/package.json
  ui/v2.5/src/@types/videojs-abloop.d.ts
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/docs/en/Manual/KeyboardShortcuts.md
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/yarn.lock
Labels: feature, documentation

#4063 Fix thumbnail scrubber crash
  ui/v2.5/src/components/Scenes/PreviewScrubber.tsx
Labels: bug

#4069 Refactor scrape dialog
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieScrapeDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneMergeDialog.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog/ScrapeDialog.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog/ScrapedObjectsRow.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog/createObjects.ts
  ui/v2.5/src/components/Shared/ScrapeDialog/scrapeResult.ts
  ui/v2.5/src/utils/data.ts
Labels: bug
