Repository stashapp/stash, pull requests merged in 2023-12, with the labels that each got.

#4344 Fix crash on blank aliases/urls
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Shared/StringListInput.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
  ui/v2.5/src/index.scss
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/utils/form.tsx
  ui/v2.5/src/utils/yup.ts
Labels: bug

#4355 Refactor and fix stash-box submit dialog
  ui/v2.5/src/components/Dialogs/SubmitDraft.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerSubmitButton.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Shared/Modal.tsx
  ui/v2.5/src/core/StashService.ts
Labels: bug

#4343 Merge url's in scene tagger instead of replacing
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
Labels: bug

#4360 Fix CI pip externally-managed-environment error
  Makefile
  docker/build/x86_64/Dockerfile-CUDA
  docker/ci/x86_64/Dockerfile
Labels: chore

#4358 Fix desktop notification duration formatting
  internal/manager/init.go
Labels: bug

#4361 Use int64 for sample-related FFProbeStream fields
  pkg/ffmpeg/types.go
Labels: bug

#4364 Default package sources
  internal/manager/config/config.go
  ui/v2.5/src/docs/en/Manual/Plugins.md
  ui/v2.5/src/docs/en/Manual/Scraping.md
  ui/v2.5/src/docs/en/ReleaseNotes/index.ts
  ui/v2.5/src/docs/en/ReleaseNotes/v0240.md
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#4371 Fix studio svg scaling
  ui/v2.5/src/components/Scenes/styles.scss
Labels: bug

#4372 Set PYTHONPATH environment variable for Python script scrapers
  pkg/plugin/raw.go
  pkg/python/env.go
  pkg/scraper/script.go
Labels: improvement

#4380 Add changelog for 0.24.0
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/docs/en/Changelog/v0240.md
Labels: chore

#4386 Include image total O-Count on stats page
  internal/api/resolver.go
  pkg/models/mocks/ImageReaderWriter.go
  pkg/models/repository_image.go
  pkg/sqlite/image.go
Labels: bug

#4387 Show confirmation when deleting via keybind
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
Labels: bug

#4382 Package manager UI-related tweaks
  graphql/documents/data/config.graphql
  graphql/documents/queries/plugins.graphql
  graphql/documents/queries/scrapers/scrapers.graphql
  graphql/schema/types/config.graphql
  graphql/schema/types/package.graphql
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_query_configuration.go
  internal/api/resolver_query_package.go
  internal/manager/config/config.go
  ui/v2.5/src/components/Settings/PluginPackageManager.tsx
  ui/v2.5/src/components/Settings/ScraperPackageManager.tsx
  ui/v2.5/src/components/Settings/SettingsSystemPanel.tsx
  ui/v2.5/src/components/Shared/PackageManager/PackageManager.tsx
  ui/v2.5/src/components/Shared/PackageManager/styles.scss
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#4376 Support setting file fingerprints
  graphql/schema/schema.graphql
  graphql/schema/types/file.graphql
  internal/api/resolver_mutation_file.go
  pkg/models/mocks/FileReaderWriter.go
  pkg/models/repository_file.go
  pkg/sqlite/file.go
  pkg/sqlite/fingerprint.go
Labels: feature

#4388 Ensure plugin scripts are loaded in correct order
  ui/v2.5/src/hooks/useScript.tsx
Labels: bug

#4394 Fix saved filter UI bugs
  ui/v2.5/src/components/FrontPage/FrontPageConfig.tsx
  ui/v2.5/src/components/List/Filters/PhashFilter.tsx
  ui/v2.5/src/components/List/SavedFilterList.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/index.scss
  ui/v2.5/src/locales/en-GB.json
Labels: bug

#4396 Fix Scene Tagger config blacklist
  ui/v2.5/src/components/Tagger/scenes/Config.tsx
Labels: bug

#4347 Update macOS readme links
  README.md
  docker/production/README.md
Labels: documentation

#4400 Revert modal button order change
  ui/v2.5/src/components/Shared/Modal.tsx
Labels: bug

#4402 Use 8.14.3-r0 of vips
  docker/ci/x86_64/Dockerfile
Labels: bug

#4403 Workaround setting protocol on external player url
  ui/v2.5/src/components/Scenes/SceneDetails/ExternalPlayerButton.tsx
Labels: bug
