Repository stashapp/stash, pull requests merged in 2023-09, with the labels that each got.

#4078 Allow empty values for because of isnull and isnotnull
  pkg/sqlite/migrations/49_postmigrate.go
Labels: bug report

#4075 Fix URL and aliases update nil dereference
  internal/api/resolver_mutation_performer.go
  internal/api/resolver_mutation_scene.go
Labels: bug

#4094 Handle equality when scraping scene performers
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneMergeDialog.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog/scrapeResult.ts
Labels: bug

#4057 Frontpage Mobile Fix
  ui/v2.5/src/index.scss
Labels: improvement

#4098 Adjust compact details
  ui/v2.5/src/index.scss
Labels: improvement

#4099 Do not log ECONNRESET errors when serving transcoded video files
  pkg/ffmpeg/stream_transcode.go
Labels: improvement

#4101 Improve error reporting when moving a transcoded file fails
  pkg/fsutil/file.go
  pkg/scene/generate/generator.go
Labels: improvement

#4105 Fix rating and country filters
  ui/v2.5/src/models/list-filter/criteria/country.ts
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/factory.ts
  ui/v2.5/src/models/list-filter/criteria/rating.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/models/list-filter/galleries.ts
  ui/v2.5/src/models/list-filter/images.ts
  ui/v2.5/src/models/list-filter/movies.ts
  ui/v2.5/src/models/list-filter/performers.ts
  ui/v2.5/src/models/list-filter/scenes.ts
  ui/v2.5/src/models/list-filter/studios.ts
Labels: bug

#4104 Fixed: `CopyFile` not working
  pkg/fsutil/file.go
Labels: bug

#4108 Update Configuration.md by changing cpu_cores to logical cores
  ui/v2.5/src/docs/en/Manual/Configuration.md
Labels: documentation

#4090 Filter criterion fixes
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryAddPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryImagesPanel.tsx
  ui/v2.5/src/components/List/CriterionEditor.tsx
  ui/v2.5/src/components/List/EditFilterDialog.tsx
  ui/v2.5/src/components/List/Filters/DurationFilter.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieEditPanel.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieScenesPanel.tsx
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkerForm.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/components/Settings/SettingsServicesPanel.tsx
  ui/v2.5/src/components/Shared/DurationInput.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioChildrenPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagMarkersPanel.tsx
  ui/v2.5/src/core/performers.ts
  ui/v2.5/src/core/studios.ts
  ui/v2.5/src/core/tags.ts
  ui/v2.5/src/models/list-filter/criteria/captions.ts
  ui/v2.5/src/models/list-filter/criteria/circumcised.ts
  ui/v2.5/src/models/list-filter/criteria/country.ts
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/factory.ts
  ui/v2.5/src/models/list-filter/criteria/favorite.ts
  ui/v2.5/src/models/list-filter/criteria/galleries.ts
  ui/v2.5/src/models/list-filter/criteria/has-chapters.ts
  ui/v2.5/src/models/list-filter/criteria/has-markers.ts
  ui/v2.5/src/models/list-filter/criteria/interactive.ts
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
  ui/v2.5/src/models/list-filter/criteria/movies.ts
  ui/v2.5/src/models/list-filter/criteria/none.ts
  ui/v2.5/src/models/list-filter/criteria/organized.ts
  ui/v2.5/src/models/list-filter/criteria/path.ts
  ui/v2.5/src/models/list-filter/criteria/performers.ts
  ui/v2.5/src/models/list-filter/criteria/phash.ts
  ui/v2.5/src/models/list-filter/criteria/rating.ts
  ui/v2.5/src/models/list-filter/criteria/resolution.ts
  ui/v2.5/src/models/list-filter/criteria/studios.ts
  ui/v2.5/src/models/list-filter/criteria/tags.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/models/list-filter/galleries.ts
  ui/v2.5/src/models/list-filter/images.ts
  ui/v2.5/src/models/list-filter/movies.ts
  ui/v2.5/src/models/list-filter/performers.ts
  ui/v2.5/src/models/list-filter/scenes.ts
  ui/v2.5/src/models/list-filter/types.ts
  ui/v2.5/src/utils/duration.ts
  ui/v2.5/src/utils/editabletext.tsx
  ui/v2.5/src/utils/form.tsx
  ui/v2.5/src/utils/table.tsx
Labels: bug, chore

#4000 Multiple image URLs
  graphql/documents/data/image-slim.graphql
  graphql/documents/data/image.graphql
  graphql/schema/types/image.graphql
  graphql/schema/types/scene.graphql
  internal/api/changeset_translator.go
  internal/api/resolver_model_image.go
  internal/api/resolver_mutation_image.go
  internal/api/resolver_mutation_scene.go
  internal/manager/task_export.go
  pkg/image/export.go
  pkg/image/export_test.go
  pkg/image/import.go
  pkg/models/jsonschema/image.go
  pkg/models/jsonschema/scene.go
  pkg/models/mocks/ImageReaderWriter.go
  pkg/models/model_image.go
  pkg/models/repository_image.go
  pkg/sqlite/anonymise.go
  pkg/sqlite/database.go
  pkg/sqlite/image.go
  pkg/sqlite/image_test.go
  pkg/sqlite/migrations/50_image_urls.up.sql
  pkg/sqlite/setup_test.go
  pkg/sqlite/tables.go
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageFileInfoPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Shared/URLField.tsx
  ui/v2.5/src/utils/yup.ts
Labels: feature

#4006 Scene Duplicate Checker UI & Feature Improvement
  ui/v2.5/src/components/SceneDuplicateChecker/SceneDuplicateChecker.tsx
  ui/v2.5/src/components/SceneDuplicateChecker/styles.scss
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#4126 Update htmlquery dependency
  go.mod
  go.sum
Labels: bug, chore

#4119 Fix scene merge nil dereference
  internal/api/resolver_mutation_scene.go
Labels: bug

#3894 Lightbox infinite scrolling improvements
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/Lightbox/LightboxImage.tsx
Labels: improvement

#4131 Allow Autoplay when loading the site first time
  ui/v2.5/src/components/Images/ImageWallItem.tsx
Labels: bug

#4130 Fix bulk movie update
  internal/api/changeset_translator.go
Labels: bug

#4133 Fix bulk tagger again
  internal/manager/manager_tasks.go
  pkg/models/relationships.go
  pkg/sqlite/migrations/48_premigrate.go
Labels: bug

#3931 Add Icons to tags if they have parent/child tags
  graphql/documents/data/scene-marker.graphql
  graphql/documents/data/tag-slim.graphql
  graphql/schema/types/tag.graphql
  internal/api/resolver_model_tag.go
  pkg/models/mocks/TagReaderWriter.go
  pkg/models/repository_tag.go
  pkg/sqlite/tag.go
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryDetailPanel.tsx
  ui/v2.5/src/components/Images/ImageCard.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageDetailPanel.tsx
  ui/v2.5/src/components/Movies/MovieCard.tsx
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/SceneDuplicateChecker/SceneDuplicateChecker.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/PrimaryTags.tsx
  ui/v2.5/src/components/Shared/PerformerPopoverButton.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Shared/TagLink.tsx
  ui/v2.5/src/components/Tagger/scenes/TaggerScene.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagDetailsPanel.tsx
  ui/v2.5/src/components/Tags/TagPopover.tsx
  ui/v2.5/src/components/Tags/styles.scss
  ui/v2.5/src/core/files.ts
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/utils/navigation.ts
Labels: improvement

#4139 Help text for animated image previews
  ui/v2.5/src/components/Settings/Tasks/GenerateOptions.tsx
  ui/v2.5/src/components/Settings/Tasks/ScanOptions.tsx
  ui/v2.5/src/docs/en/Manual/Interface.md
  ui/v2.5/src/docs/en/Manual/Tasks.md
  ui/v2.5/src/locales/en-GB.json
Labels: documentation

#4149 Fix lightbox fullscreen issues
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/Lightbox/context.tsx
  ui/v2.5/src/hooks/Lightbox/hooks.ts
Labels: bug

#4151 Filter migration fix
  pkg/sqlite/migrations/49_postmigrate.go
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
Labels: bug

#4148 PerformerSelect Tagger bugfixes
  ui/v2.5/src/components/Performers/PerformerSelect.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Shared/FilterSelect.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog/ScrapedObjectsRow.tsx
  ui/v2.5/src/components/Tagger/scenes/PerformerResult.tsx
  ui/v2.5/src/components/Tagger/styles.scss
Labels: bug

#4142 Fix width of image selection arrow div
  ui/v2.5/src/components/Shared/ScrapeDialog/ScrapeDialog.tsx
  ui/v2.5/src/components/Shared/styles.scss
Labels: improvement

#4147 Allow scene scrapers to return full movie data
  graphql/documents/data/scrapers.graphql
Labels: improvement

#4114 Gallery URLs
  graphql/documents/data/gallery-slim.graphql
  graphql/documents/data/gallery.graphql
  graphql/documents/data/scrapers.graphql
  graphql/schema/types/gallery.graphql
  graphql/schema/types/scraper.graphql
  internal/api/resolver_model_gallery.go
  internal/api/resolver_mutation_gallery.go
  pkg/gallery/export.go
  pkg/gallery/export_test.go
  pkg/gallery/import.go
  pkg/gallery/import_test.go
  pkg/models/gallery.go
  pkg/models/jsonschema/gallery.go
  pkg/models/mocks/GalleryReaderWriter.go
  pkg/models/model_gallery.go
  pkg/models/repository_gallery.go
  pkg/scraper/gallery.go
  pkg/scraper/query_url.go
  pkg/scraper/stash.go
  pkg/sqlite/database.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/migrations/51_gallery_urls.up.sql
  pkg/sqlite/scene.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/tables.go
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryFileInfoPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
Labels: feature

#4144 Fix false positive mismatch in Movie Scrape dialog
  ui/v2.5/src/components/Movies/MovieDetails/MovieScrapeDialog.tsx
Labels: bug

#4157 Fix gallery scraper URL loading
  pkg/scraper/cache.go
Labels: bug
