Repository stashapp/stash, pull requests merged in 2023-01, with the labels that each got.

#3300 Added Label for Russian Subtitle
  ui/v2.5/src/utils/caption.ts
Labels: i18n

#3331 en-US message for customise
  ui/v2.5/src/locales/en-US.json
Labels: i18n

#3301 Performer age calculation on images
  ui/v2.5/src/components/Images/ImageDetails/ImageDetailPanel.tsx
Labels: improvement

#3305 Include URL query in login redirects
  internal/api/authentication.go
  ui/v2.5/src/docs/en/Changelog/v0190.md
Labels: bug

#3352 [Documentation] Replaces wiki links with new documentation site
  README.md
  internal/api/authentication.go
  internal/manager/config/config.go
  pkg/session/authentication.go
  ui/v2.5/src/components/Settings/SettingsAboutPanel.tsx
  ui/v2.5/src/components/Settings/SettingsLibraryPanel.tsx
  ui/v2.5/src/docs/en/Manual/Help.md
  ui/v2.5/src/docs/en/Manual/Interface.md
  ui/v2.5/src/docs/en/Manual/JSONSpec.md
Labels: documentation

#3354 Update description for Custom CSS/JS
  ui/v2.5/src/locales/en-GB.json
Labels: documentation

#3216 Allow configuration of ffmpeg args
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_query_configuration.go
  internal/api/routes_scene.go
  internal/manager/config/config.go
  internal/manager/generator_sprite.go
  internal/manager/manager.go
  internal/manager/task_generate.go
  internal/manager/task_generate_screenshot.go
  internal/manager/task_scan.go
  pkg/ffmpeg/stream.go
  pkg/ffmpeg/transcoder/transcode.go
  pkg/scene/generate/generator.go
  pkg/scene/generate/preview.go
  pkg/scene/generate/transcode.go
  ui/v2.5/src/components/Settings/SettingsSystemPanel.tsx
  ui/v2.5/src/docs/en/Changelog/v0190.md
  ui/v2.5/src/docs/en/Manual/Configuration.md
  ui/v2.5/src/locales/en-GB.json
Labels: feature, bounty

#3335 Submit fields scene code and director to stashbox
  pkg/scraper/stashbox/graphql/generated_client.go
  pkg/scraper/stashbox/graphql/generated_models.go
  pkg/scraper/stashbox/graphql/override.go
  pkg/scraper/stashbox/stash_box.go
Labels: feature

#3355 CSS update to unify popover location
  ui/v2.5/src/components/FrontPage/styles.scss
Labels: improvement, ui

#3276 Fix and improve captions detection
  pkg/file/file.go
  pkg/file/video/caption.go
  pkg/sqlite/file.go
Labels: bug

#3377 Bug: noticed that high performance preview generation had been turned off.
  internal/manager/task_generate_preview.go
Labels: bug

#3246 Fix scene studio results when doing a search scrape
  pkg/scraper/mapped.go
Labels: bug
