Repository stashapp/stash, pull requests merged in 2023-05, with the labels that each got.

#3710 Add Matrix badge and link in support section
  README.md
Labels: documentation

#3687 Fix scene marker pinned filters
  ui/v2.5/src/components/List/EditFilterDialog.tsx
Labels: bug, javascript

#3689 Ignore graphql context canceled errors
  internal/api/error.go
Labels: bug, backend

#3683 Removed a sentence that is technically irrelevant to auto tagging
  ui/v2.5/src/docs/en/Manual/AutoTagging.md
Labels: documentation

#3645 Adds ability to configure sort order for DLNA videos
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_query_configuration.go
  internal/dlna/cds.go
  internal/dlna/dms.go
  internal/dlna/service.go
  internal/manager/config/config.go
  ui/v2.5/src/components/Settings/SettingsServicesPanel.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/utils/dlnaVideoSort.ts
Labels: feature, ui, backend

#3691 Sort scrapers by name
  pkg/scraper/cache.go
Labels: improvement, backend

#3633 Fix scene scraper movie error
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
Labels: bug, javascript

#3661 Fix generate task override behaviour
  internal/manager/task_generate.go
  internal/manager/task_generate_interactive_heatmap_speed.go
  internal/manager/task_generate_phash.go
  internal/manager/task_generate_preview.go
  internal/manager/task_generate_screenshot.go
  internal/manager/task_generate_sprite.go
  internal/manager/task_scan.go
  internal/manager/task_transcode.go
  ui/v2.5/src/locales/en-GB.json
Labels: bug, backend

#3690 Fix filter dialog datepicker button padding
  ui/v2.5/src/components/List/styles.scss
Labels: improvement, ui

#3663 Limit duplicate matching to files that have ~ same duration
  graphql/documents/queries/scene.graphql
  graphql/schema/schema.graphql
  internal/api/resolver_query_find_scene.go
  pkg/models/mocks/SceneReaderWriter.go
  pkg/models/scene.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_test.go
  pkg/utils/phash.go
  ui/v2.5/src/components/SceneDuplicateChecker/SceneDuplicateChecker.tsx
  ui/v2.5/src/components/SceneDuplicateChecker/styles.scss
  ui/v2.5/src/locales/en-GB.json
Labels: improvement, backend, javascript

#3686 WallPanel refactor
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkersPanel.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Scenes/SceneMarkerList.tsx
  ui/v2.5/src/components/Wall/WallItem.tsx
  ui/v2.5/src/components/Wall/WallPanel.tsx
Labels: chore, javascript

#3676 Fix deceptive WEBM playback in Safari
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/source-selector.ts
  ui/v2.5/src/components/ScenePlayer/styles.scss
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/vite.config.js
Labels: bug, javascript

#3696 Identify: Select existing value on edit
  ui/v2.5/src/components/Dialogs/IdentifyDialog/FieldOptions.tsx
Labels: bug, javascript

#3705 Lightbox movie covers
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Movies/styles.scss
  ui/v2.5/src/components/Performers/styles.scss
Labels: improvement, javascript

#3718 Include missing fields in performer batch tag
  internal/manager/task_stash_box_tag.go
Labels: bug, backend

#3719 Include precision in rating star classname
  ui/v2.5/src/components/Shared/Rating/RatingStars.tsx
Labels: improvement, ui

#3725 Log warning when library overlaps generated folder in scan
  internal/manager/task_scan.go
Labels: improvement, backend

#3715 Folder Gallery creation on a per folder basis
  pkg/image/scan.go
  ui/v2.5/src/docs/en/Manual/Configuration.md
  ui/v2.5/src/locales/en-GB.json
Labels: improvement, backend

#3730 ChapterBug // Fix jump to wrong page
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
Labels: bug, javascript

#3736 Fix missing tag images
  internal/api/resolver_model_tag.go
Labels: bug, backend

#3598 Change modifier selector to pills
  ui/v2.5/src/components/List/CriterionEditor.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/index.scss
  ui/v2.5/src/models/list-filter/criteria/captions.ts
Labels: improvement, ui

#3739 Allow filter headers to be tabbable
  ui/v2.5/src/components/List/EditFilterDialog.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/styles/_theme.scss
Labels: improvement, ui

#3740 Filter query
  ui/v2.5/src/components/List/EditFilterDialog.tsx
  ui/v2.5/src/components/List/ItemList.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/docs/en/Manual/KeyboardShortcuts.md
  ui/v2.5/src/utils/focus.ts
Labels: feature, javascript

#3754 Fix bulk performer update plugin hook
  internal/api/resolver_mutation_performer.go
Labels: bug, backend

#3747 Honor DLNA sort order for content exceeding the first page
  internal/dlna/cds.go
  internal/dlna/paging.go
Labels: bug, backend

#3627 Add penis length and circumcision stats to performers.
  graphql/documents/data/performer-slim.graphql
  graphql/documents/data/performer.graphql
  graphql/documents/data/scrapers.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/performer.graphql
  graphql/schema/types/scraped-performer.graphql
  internal/api/images.go
  internal/api/resolver_mutation_performer.go
  internal/identify/performer.go
  internal/identify/performer_test.go
  internal/manager/task_stash_box_tag.go
  pkg/models/filter.go
  pkg/models/jsonschema/performer.go
  pkg/models/model_performer.go
  pkg/models/model_scraped_item.go
  pkg/models/performer.go
  pkg/performer/export.go
  pkg/performer/export_test.go
  pkg/performer/import.go
  pkg/scraper/autotag.go
  pkg/scraper/performer.go
  pkg/scraper/stash.go
  pkg/scraper/stashbox/stash_box.go
  pkg/sqlite/database.go
  pkg/sqlite/filter.go
  pkg/sqlite/migrations/46_penis_stats.up.sql
  pkg/sqlite/performer.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/record.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/sql.go
  pkg/sqlite/values.go
  pkg/utils/strings.go
  ui/v2.5/src/components/List/CriterionEditor.tsx
  ui/v2.5/src/components/List/Filters/BooleanFilter.tsx
  ui/v2.5/src/components/List/Filters/OptionFilter.tsx
  ui/v2.5/src/components/List/Filters/OptionsFilter.tsx
  ui/v2.5/src/components/List/Filters/OptionsListFilter.tsx
  ui/v2.5/src/components/Performers/EditPerformersDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/criteria/circumcised.ts
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/factory.ts
  ui/v2.5/src/models/list-filter/performers.ts
  ui/v2.5/src/models/list-filter/types.ts
  ui/v2.5/src/utils/circumcised.ts
  ui/v2.5/src/utils/units.ts
Labels: feature, ui, backend

#3682 Updated the English auto_tag_based_on_filenames message
  ui/v2.5/src/locales/en-GB.json
Labels: i18n

#3757 Update Metadata Bugfix
  pkg/file/image/scan.go
Labels: bug, improvement, backend

#3764 Clip preview fix
  internal/manager/task_generate_clip_preview.go
  pkg/image/thumbnail.go
Labels: bug, backend

#3767 Fix performer image display
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Shared/ImageInput.tsx
Labels: bug

#3765 fix Clip Gif Support
  ui/v2.5/src/components/Images/ImageDetails/Image.tsx
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/Lightbox/types.ts
  ui/v2.5/src/utils/visualFile.ts
Labels: improvement, javascript

#3619 Improve studio/tag/performer filtering
  graphql/schema/types/filters.graphql
  pkg/models/filter.go
  pkg/sqlite/filter.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_marker.go
  pkg/sqlite/tag.go
  ui/v2.5/src/components/List/CriterionEditor.tsx
  ui/v2.5/src/components/List/Filters/PerformersFilter.tsx
  ui/v2.5/src/components/List/Filters/SelectableFilter.tsx
  ui/v2.5/src/components/List/Filters/StudiosFilter.tsx
  ui/v2.5/src/components/List/Filters/TagsFilter.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/components/Shared/ClearableInput.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/components/Studios/StudioDetails/StudioPerformersPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagMarkersPanel.tsx
  ui/v2.5/src/core/performers.ts
  ui/v2.5/src/core/studios.ts
  ui/v2.5/src/core/tags.ts
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/performers.ts
  ui/v2.5/src/models/list-filter/criteria/studios.ts
  ui/v2.5/src/models/list-filter/criteria/tags.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/models/list-filter/types.ts
  ui/v2.5/src/utils/keyboard.ts
  ui/v2.5/src/utils/navigation.ts
Labels: feature, improvement

#3768 Error logging improvements
  internal/api/error.go
  internal/manager/task_autotag.go
  pkg/scraper/stashbox/stash_box.go
Labels: improvement

#3758 Fix Interactive Heatmaps to match the length of the video
  internal/manager/generator_interactive_heatmap_speed.go
Labels: bug, backend

#3507 Safari skip file transcodes
  ui/v2.5/package.json
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/yarn.lock
Labels: improvement, javascript

#3782 Fix performer image display again and refactoring
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryCreate.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/Image.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieCreate.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerCreate.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneCreate.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioCreate.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagCreate.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
  ui/v2.5/src/core/StashService.ts
Labels: bug, improvement, chore, javascript

#3636 Adds videojs-vr support
  ui/v2.5/package.json
  ui/v2.5/public/vr.svg
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/styles.scss
  ui/v2.5/src/components/ScenePlayer/vrmode.ts
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneVideoFilterPanel.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/yarn.lock
Labels: feature, ui, javascript

#3770 Male performer images
  internal/api/images.go
  internal/static/performer_male/Male01.png
  internal/static/performer_male/Male02.png
  internal/static/performer_male/Male03.png
  internal/static/performer_male/Male04.png
  internal/static/performer_male/Male05.png
  internal/static/performer_male/Male06.png
  internal/static/performer_male/noname_male_01.jpg
  internal/static/performer_male/noname_male_02.jpg
Labels: improvement

#3771 Update gallery UpdatedAt timestamp on contents change
  internal/api/resolver_mutation_image.go
  internal/manager/repository.go
  pkg/gallery/service.go
  pkg/gallery/update.go
  pkg/models/update.go
  pkg/models/update_test.go
  ui/v2.5/src/core/StashService.ts
Labels: improvement, bounty, backend

#3788 Use string criterion for name
  ui/v2.5/src/models/list-filter/criteria/factory.ts
Labels: bug
