Repository stashapp/stash, pull requests merged in 2023-03, with the labels that each got.

#3497 Improve release notes dialog
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Dialogs/ReleaseNotesDialog.tsx
  ui/v2.5/src/components/Setup/Setup.tsx
  ui/v2.5/src/docs/en/ReleaseNotes/index.ts
  ui/v2.5/src/docs/en/ReleaseNotes/v0170.md
Labels: bug, improvement

#3495 [Feature] Development quickstart guide and Makefile additions
  .gitignore
  Makefile
  docs/DEVELOPMENT.md
Labels: chore

#3490 Improve legacy browser support
  ui/v2.5/package.json
  ui/v2.5/vite.config.js
  ui/v2.5/yarn.lock
Labels: bug, chore

#3093 Replace react-markdown with react-remark
  ui/v2.5/package.json
  ui/v2.5/src/components/Help/Manual.tsx
  ui/v2.5/src/components/Help/context.tsx
  ui/v2.5/src/components/Shared/MarkdownPage.tsx
  ui/v2.5/yarn.lock
Labels: chore

#3500 Improve dynamic import error message
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/ErrorBoundary.tsx
  ui/v2.5/src/components/Help/context.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/Scenes.tsx
  ui/v2.5/src/hooks/Lightbox/context.tsx
  ui/v2.5/src/index.scss
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/utils/lazyComponent.ts
Labels: improvement

#3508 Add divider to gallery tab
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Galleries/styles.scss
  ui/v2.5/src/docs/en/Changelog/v0200.md
Labels: improvement, ui

#3504 Setup improvements
  graphql/schema/types/config.graphql
  internal/manager/manager.go
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Settings/SettingsSystemPanel.tsx
  ui/v2.5/src/components/Setup/Migrate.tsx
  ui/v2.5/src/components/Setup/Setup.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/core/createClient.ts
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#3275 Add DASH streams for VP9 transcoding
  go.mod
  go.sum
  internal/api/routes_scene.go
  internal/manager/scene.go
  pkg/ffmpeg/stream_segmented.go
  ui/v2.5/package.json
  ui/v2.5/src/@types/videojs-contrib-dash.d.ts
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/docs/en/Changelog/v0200.md
  ui/v2.5/yarn.lock
  vendor/github.com/zencoder/go-dash/v3/LICENSE
  vendor/github.com/zencoder/go-dash/v3/helpers/ptrs/ptrs.go
  vendor/github.com/zencoder/go-dash/v3/mpd/duration.go
  vendor/github.com/zencoder/go-dash/v3/mpd/events.go
  vendor/github.com/zencoder/go-dash/v3/mpd/mpd.go
  vendor/github.com/zencoder/go-dash/v3/mpd/mpd_attr.go
  vendor/github.com/zencoder/go-dash/v3/mpd/mpd_read_write.go
  vendor/github.com/zencoder/go-dash/v3/mpd/pssh.go
  vendor/github.com/zencoder/go-dash/v3/mpd/segment.go
  vendor/github.com/zencoder/go-dash/v3/mpd/validate.go
  vendor/modules.txt
Labels: feature

#3509 Fix yup schemas
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieCreate.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieEditPanel.tsx
  ui/v2.5/src/components/Performers/EditPerformersDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerCreate.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioCreate.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagCreate.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
  ui/v2.5/src/docs/en/Changelog/v0200.md
  ui/v2.5/src/locales/cs-CZ.json
  ui/v2.5/src/locales/da-DK.json
  ui/v2.5/src/locales/de-DE.json
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/es-ES.json
  ui/v2.5/src/locales/et-EE.json
  ui/v2.5/src/locales/fi-FI.json
  ui/v2.5/src/locales/fr-FR.json
  ui/v2.5/src/locales/it-IT.json
  ui/v2.5/src/locales/ja-JP.json
  ui/v2.5/src/locales/ko-KR.json
  ui/v2.5/src/locales/nl-NL.json
  ui/v2.5/src/locales/pl-PL.json
  ui/v2.5/src/locales/pt-BR.json
  ui/v2.5/src/locales/ru-RU.json
  ui/v2.5/src/locales/sv-SE.json
  ui/v2.5/src/locales/tr-TR.json
  ui/v2.5/src/locales/zh-CN.json
  ui/v2.5/src/locales/zh-TW.json
  ui/v2.5/src/utils/gender.ts
Labels: bug, chore

#3511 Improved wall view for images
  ui/v2.5/package.json
  ui/v2.5/src/components/Galleries/GalleryViewer.tsx
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/docs/en/Changelog/v0200.md
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/utils/imageWall.ts
  ui/v2.5/yarn.lock
Labels: improvement, ui

#3419 Simple hardware encoding
  Makefile
  docker/build/x86_64/Dockerfile-CUDA
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_query_configuration.go
  internal/manager/config/config.go
  internal/manager/manager.go
  pkg/ffmpeg/codec.go
  pkg/ffmpeg/codec_hardware.go
  pkg/ffmpeg/ffmpeg.go
  pkg/ffmpeg/filter.go
  pkg/ffmpeg/frame_rate.go
  pkg/ffmpeg/generate.go
  pkg/ffmpeg/stream.go
  pkg/ffmpeg/stream_segmented.go
  pkg/ffmpeg/stream_transcode.go
  pkg/hash/videophash/phash.go
  pkg/image/thumbnail.go
  pkg/scene/generate/generator.go
  ui/v2.5/src/components/Settings/SettingsSystemPanel.tsx
  ui/v2.5/src/docs/en/Changelog/v0200.md
  ui/v2.5/src/docs/en/Manual/Configuration.md
  ui/v2.5/src/locales/en-GB.json
Labels: feature, needs testing

#3520 Fix performer height/weight clearing
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
Labels: bug

#3516 Improve scaling for column wall images
  ui/v2.5/src/components/Images/ImageList.tsx
Labels: improvement, ui

#3521 Add DASH to docs and log messages
  pkg/ffmpeg/stream.go
  ui/v2.5/src/docs/en/Changelog/v0200.md
  ui/v2.5/src/docs/en/Manual/Configuration.md
  ui/v2.5/src/docs/en/ReleaseNotes/v0200.md
  ui/v2.5/src/locales/en-GB.json
Labels: documentation

#3519 Fix unit conversion rounding
  ui/v2.5/src/utils/units.ts
Labels: improvement

#3514 add divider on more details pages
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/docs/en/Changelog/v0200.md
  ui/v2.5/src/index.scss
Labels: improvement, ui

#3525 Fix undefined containerHeight error with imageWall columns
  ui/v2.5/src/components/Images/ImageList.tsx
Labels: bug

#3532 Address additional overflow on performer page
  ui/v2.5/src/components/Performers/styles.scss
Labels: bug, ui

#3533 Fix lint error on macOS
  internal/desktop/systray_nonlinux.go
Labels: bug

#3524 Add debounce hook
  ui/v2.5/.eslintrc.json
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeModal.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerStashBoxModal.tsx
  ui/v2.5/src/components/Settings/context.tsx
  ui/v2.5/src/components/Shared/FolderSelect/FolderSelect.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Shared/TruncatedText.tsx
  ui/v2.5/src/hooks/Interval.ts
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/debounce.ts
Labels: improvement

#3527 Automatic database optimization and performance tweaks
  pkg/sqlite/database.go
  pkg/sqlite/driver.go
Labels: bug, improvement

#3528 Clear performer image on cancel
  ui/v2.5/src/components/Movies/MovieDetails/MovieEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
Labels: bug

#3536 Add show sprite button to scene tagger list
  ui/v2.5/src/components/Tagger/scenes/SceneTagger.tsx
  ui/v2.5/src/components/Tagger/scenes/TaggerScene.tsx
  ui/v2.5/src/components/Tagger/styles.scss
  ui/v2.5/src/docs/en/Changelog/v0200.md
Labels: improvement

#3542 Anonymise marker titles
  pkg/sqlite/anonymise.go
  pkg/sqlite/tables.go
Labels: bug

#3544 Handle large and all entity queries
  pkg/models/find_filter.go
  pkg/sqlite/batch.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/movies.go
  pkg/sqlite/performer.go
  pkg/sqlite/scene.go
  pkg/sqlite/studio.go
  pkg/sqlite/tag.go
  ui/v2.5/src/components/List/ListFilter.tsx
Labels: bug

#3289 Add Chapters for Galleries
  graphql/documents/data/gallery-chapter.graphql
  graphql/documents/data/gallery-slim.graphql
  graphql/documents/data/gallery.graphql
  graphql/documents/mutations/gallery-chapter.graphql
  graphql/schema/schema.graphql
  graphql/schema/types/filters.graphql
  graphql/schema/types/gallery-chapter.graphql
  graphql/schema/types/gallery.graphql
  internal/api/resolver.go
  internal/api/resolver_model_gallery.go
  internal/api/resolver_model_gallery_chapter.go
  internal/api/resolver_mutation_gallery.go
  internal/manager/repository.go
  internal/manager/task_export.go
  internal/manager/task_import.go
  pkg/gallery/chapter_import.go
  pkg/gallery/delete.go
  pkg/gallery/export.go
  pkg/gallery/export_test.go
  pkg/gallery/import.go
  pkg/gallery/service.go
  pkg/models/gallery.go
  pkg/models/gallery_chapter.go
  pkg/models/jsonschema/gallery.go
  pkg/models/mocks/GalleryChapterReaderWriter.go
  pkg/models/mocks/transaction.go
  pkg/models/model_gallery_chapter.go
  pkg/models/repository.go
  pkg/plugin/hooks.go
  pkg/sqlite/database.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_chapter.go
  pkg/sqlite/gallery_chapter_test.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/migrations/44_gallery_chapters.up.sql
  pkg/sqlite/setup_test.go
  pkg/sqlite/transaction.go
  scripts/test_db_generator/config.yml
  scripts/test_db_generator/makeTestDB.go
  ui/v2.5/src/components/Galleries/GalleryDetails/ChapterEntry.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryChapterForm.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryChaptersPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryImagesPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryWallCard.tsx
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/docs/en/Changelog/v0200.md
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/Lightbox/context.tsx
  ui/v2.5/src/hooks/Lightbox/hooks.ts
  ui/v2.5/src/hooks/Lightbox/lightbox.scss
  ui/v2.5/src/hooks/Lightbox/types.ts
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/criteria/factory.ts
  ui/v2.5/src/models/list-filter/criteria/has-chapters.ts
  ui/v2.5/src/models/list-filter/galleries.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: feature

#3515 UI filter builder
  ui/v2.5/src/components/List/AddFilterDialog.tsx
  ui/v2.5/src/components/List/CriterionEditor.tsx
  ui/v2.5/src/components/List/EditFilterDialog.tsx
  ui/v2.5/src/components/List/FilterTags.tsx
  ui/v2.5/src/components/List/Filters/BooleanFilter.tsx
  ui/v2.5/src/components/List/Filters/DateFilter.tsx
  ui/v2.5/src/components/List/Filters/FilterButton.tsx
  ui/v2.5/src/components/List/Filters/HierarchicalLabelValueFilter.tsx
  ui/v2.5/src/components/List/Filters/InputFilter.tsx
  ui/v2.5/src/components/List/Filters/LabeledIdFilter.tsx
  ui/v2.5/src/components/List/Filters/NumberFilter.tsx
  ui/v2.5/src/components/List/Filters/OptionsFilter.tsx
  ui/v2.5/src/components/List/Filters/OptionsListFilter.tsx
  ui/v2.5/src/components/List/Filters/StashIDFilter.tsx
  ui/v2.5/src/components/List/Filters/TimestampFilter.tsx
  ui/v2.5/src/components/List/ItemList.tsx
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/docs/en/Changelog/v0200.md
  ui/v2.5/src/hooks/state.ts
  ui/v2.5/src/index.scss
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/rating.ts
  ui/v2.5/src/models/list-filter/criteria/stash-ids.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: improvement, ui, needs testing

#3541 Fix /stream endpoint serving directory for fileless scenes
  internal/api/routes_scene.go
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
Labels: bug

#3548 Fix batch performer tagging with multiple endpoints
  internal/manager/manager_tasks.go
  internal/manager/task_stash_box_tag.go
  pkg/models/stash_ids.go
  ui/v2.5/src/components/Tagger/performers/PerformerTagger.tsx
Labels: bug

#3556 Filter edit fixes
  ui/v2.5/src/components/List/CriterionEditor.tsx
  ui/v2.5/src/components/List/Filters/FilterButton.tsx
  ui/v2.5/src/components/Shared/CountrySelect.tsx
  ui/v2.5/src/models/list-filter/filter.ts
Labels: bug, improvement, ui

#3555 Login fixes
  internal/api/authentication.go
  internal/api/server.go
  ui/login/login.css
Labels: bug, improvement

#3540 Added Intel QSV drivers to docker
  docker/build/x86_64/Dockerfile-CUDA
Labels: chore

#3543 Fix incorrect performer data being sent and submitted when multiple stash-box endpoints configured
  ui/v2.5/src/components/Dialogs/SubmitDraft.tsx
  ui/v2.5/src/components/Tagger/performers/PerformerTagger.tsx
Labels: bug

#3564 Fix scan cover defaults
  pkg/sqlite/migrations/45_postmigrate.go
  ui/v2.5/src/components/Settings/Tasks/ScanOptions.tsx
Labels: bug

#3569 Fix scene scraping
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
Labels: bug

#3570 Add folder browser to path filter field
  ui/v2.5/src/components/List/CriterionEditor.tsx
  ui/v2.5/src/components/List/Filters/PathFilter.tsx
  ui/v2.5/src/components/Shared/FolderSelect/FolderSelect.tsx
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/factory.ts
  ui/v2.5/src/models/list-filter/galleries.ts
  ui/v2.5/src/models/list-filter/images.ts
  ui/v2.5/src/models/list-filter/scenes.ts
Labels: improvement

#3571 Add linux package lists
  docs/DEVELOPMENT.md
Labels: documentation

#3568 Warn on charset decoding issues
  pkg/file/zip.go
Labels: bug

#3593 Add busy timeout to database connection
  pkg/sqlite/database.go
Labels: bug

#3600 Fix path filtering when directory has whitespace in it
  ui/v2.5/src/components/List/Filters/PathFilter.tsx
  ui/v2.5/src/components/Shared/FolderSelect/FolderSelect.tsx
Labels: bug

#3599 Blob fixes
  internal/api/resolver_model_movie.go
  internal/api/resolver_mutation_stash_box.go
  internal/identify/scene.go
  internal/identify/scene_test.go
  internal/manager/running_streams.go
  pkg/models/mocks/MovieReaderWriter.go
  pkg/models/movie.go
  pkg/movie/export.go
  pkg/movie/export_test.go
  pkg/performer/export.go
  pkg/performer/export_test.go
  pkg/scene/export.go
  pkg/scene/export_test.go
  pkg/sqlite/blob.go
  pkg/sqlite/blob/fs.go
  pkg/sqlite/movies.go
  pkg/studio/export.go
  pkg/studio/export_test.go
  pkg/tag/export.go
  pkg/tag/export_test.go
Labels: bug, release-blocker

#3608 Fix moveFiles for zip files
  internal/api/resolver_mutation_file.go
  internal/manager/repository.go
  pkg/file/file.go
  pkg/file/folder.go
  pkg/file/move.go
Labels: bug

#3613 Add default blob data location
  docker/production/docker-compose.yml
Labels: chore
