Repository stashapp/stash, pull requests merged in 2023-07, with the labels that each got.

#3876 Makefile cleanup
  Makefile
Labels: chore

#3857 Fix scene missing flicker on scene page
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
Labels: bug

#3817 Add folder move detection
  pkg/file/file.go
  pkg/file/folder_rename_detect.go
  pkg/file/scan.go
  pkg/sqlite/file.go
Labels: improvement

#3843 Add codec filters
  graphql/schema/types/filters.graphql
  pkg/models/scene.go
  pkg/sqlite/scene.go
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/criteria/factory.ts
  ui/v2.5/src/models/list-filter/scenes.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: feature

#2872 Add AirPlay and Chromecast support
  docker/build/x86_64/Dockerfile
  internal/api/server.go
  ui/v2.5/package.json
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/styles.scss
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/hooks/useScript.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/yarn.lock
Labels: feature

#3756 Allow serving of interactive CSVs directly to Handy
  graphql/documents/data/config.graphql
  graphql/schema/types/config.graphql
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_query_configuration.go
  internal/api/routes_scene.go
  internal/manager/config/config.go
  internal/manager/config/config_concurrency_test.go
  internal/manager/generator_interactive_heatmap_speed.go
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/hooks/Interactive/context.tsx
  ui/v2.5/src/hooks/Interactive/interactive.ts
  ui/v2.5/src/locales/en-GB.json
Labels: improvement, backend, javascript

#3812 Add additional stats to the Stats page
  .gitignore
  graphql/documents/queries/misc.graphql
  graphql/schema/types/stats.graphql
  internal/api/resolver.go
  pkg/models/mocks/SceneReaderWriter.go
  pkg/models/scene.go
  pkg/sqlite/scene.go
  ui/v2.5/src/components/Stats.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: improvement, backend, javascript

#3707 Identify: Options to skip multiple results and single name performers
  graphql/documents/data/config.graphql
  graphql/schema/types/metadata.graphql
  internal/identify/identify.go
  internal/identify/identify_test.go
  internal/identify/options.go
  internal/identify/performer.go
  internal/identify/performer_test.go
  internal/identify/scene.go
  internal/identify/scene_test.go
  internal/identify/studio.go
  internal/manager/task_identify.go
  pkg/scraper/stashbox/stash_box.go
  ui/v2.5/src/components/Dialogs/IdentifyDialog/FieldOptions.tsx
  ui/v2.5/src/components/Dialogs/IdentifyDialog/IdentifyDialog.tsx
  ui/v2.5/src/components/Dialogs/IdentifyDialog/Options.tsx
  ui/v2.5/src/components/Dialogs/IdentifyDialog/ThreeStateBoolean.tsx
  ui/v2.5/src/components/Dialogs/styles.scss
  ui/v2.5/src/docs/en/Manual/Identify.md
  ui/v2.5/src/locales/en-GB.json
Labels: bug, improvement, backend, javascript

#3864 add phasher
  .gitignore
  Makefile
  cmd/phasher/main.go
Labels: feature

#3883 Add `-v/--version` flag to print version string
  Makefile
  internal/api/check_version.go
  internal/api/resolver.go
  internal/api/server.go
  internal/build/version.go
  internal/desktop/desktop.go
  internal/manager/config/config.go
  internal/manager/config/init.go
Labels: feature

#3898 Revert "Add AirPlay and Chromecast support"
  docker/build/x86_64/Dockerfile
  internal/api/server.go
  ui/v2.5/package.json
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/styles.scss
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/hooks/useScript.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/yarn.lock
Labels: bug

#3901 Improve Makefile
  .github/workflows/build.yml
  Makefile
  docker/build/x86_64/Dockerfile
  docker/build/x86_64/Dockerfile-CUDA
  docs/DEVELOPMENT.md
Labels: bug, chore

#3903 Add missing scene player shortcuts to Help -> Keyboard Shortcuts
  ui/v2.5/src/docs/en/Manual/KeyboardShortcuts.md
Labels: documentation

#3882 Safari video height css fix
  ui/v2.5/src/components/ScenePlayer/styles.scss
Labels: bug

#3905 Add nil checks in identify
  internal/identify/identify.go
Labels: bug

#3902 Add keyboard shortcut to toggle video looping in scene player
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/docs/en/Manual/KeyboardShortcuts.md
Labels: feature, documentation, javascript

#3852 Multiple scene URLs
  graphql/documents/data/scene-slim.graphql
  graphql/documents/data/scene.graphql
  graphql/documents/data/scrapers.graphql
  graphql/schema/types/scene.graphql
  graphql/schema/types/scraper.graphql
  internal/api/resolver_model_scene.go
  internal/api/resolver_mutation_scene.go
  internal/api/resolver_mutation_stash_box.go
  internal/autotag/integration_test.go
  internal/identify/identify.go
  internal/identify/identify_test.go
  internal/identify/scene.go
  internal/manager/repository.go
  pkg/models/jsonschema/scene.go
  pkg/models/mocks/SceneReaderWriter.go
  pkg/models/model_scene.go
  pkg/models/model_scene_test.go
  pkg/models/relationships.go
  pkg/models/scene.go
  pkg/models/update.go
  pkg/scene/export.go
  pkg/scene/export_test.go
  pkg/scene/import.go
  pkg/scraper/cache.go
  pkg/scraper/postprocessing.go
  pkg/scraper/query_url.go
  pkg/scraper/scene.go
  pkg/scraper/stash.go
  pkg/scraper/stashbox/stash_box.go
  pkg/sliceutil/collections.go
  pkg/sqlite/anonymise.go
  pkg/sqlite/database.go
  pkg/sqlite/migrations/47_scene_urls.up.sql
  pkg/sqlite/scene.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/table.go
  pkg/sqlite/tables.go
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneMergeDialog.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog.tsx
  ui/v2.5/src/components/Shared/StringListInput.tsx
  ui/v2.5/src/components/Shared/URLField.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/components/Tagger/context.tsx
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/utils/field.tsx
Labels: feature

#3907 Chromcast support
  docker/build/x86_64/Dockerfile
  docker/build/x86_64/Dockerfile-CUDA
  internal/api/server.go
  ui/v2.5/package.json
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/styles.scss
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/hooks/useScript.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/yarn.lock
Labels: feature

#3908 Fix docker build
  docker/build/x86_64/Dockerfile
  docker/build/x86_64/Dockerfile-CUDA
Labels: chore

#3933 Add badge for GitHub sponsors
  README.md
Labels: documentation

#3924 Minor refactor
  gqlgen.yml
  internal/api/models.go
  internal/api/models_test.go
  internal/api/resolver_query_find_scene.go
  pkg/models/filename_parser.go
  pkg/models/int64.go
  pkg/scene/filename_parser.go
Labels: chore

#3939 Place popover to right on edit pages
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkerForm.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Shared/TagLink.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
  ui/v2.5/src/components/Tags/TagPopover.tsx
Labels: bug

#3919 Disable videojs-mobile-ui on Safari
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: bug

#3942 Add THREE.js properties to videojs-vr plugin object
  ui/v2.5/package.json
  ui/v2.5/src/@types/videojs-vr.d.ts
  ui/v2.5/yarn.lock
Labels: chore

#3940 Include old URL in script input
  pkg/scraper/cache.go
  pkg/scraper/scraper.go
  pkg/scraper/stash.go
Labels: bug

#3920 Add SQL graphql mutations
  graphql/schema/schema.graphql
  graphql/schema/types/sql.graphql
  internal/api/resolver.go
  pkg/sqlite/database.go
Labels: feature

#3927 Always include gallery card in scene details
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneGalleriesPanel.tsx
Labels: improvement

#3945 Fix scene marker/gallery chapter update overwriting created at date
  graphql/schema/types/gallery-chapter.graphql
  graphql/schema/types/scene-marker.graphql
  internal/api/resolver_mutation_gallery.go
  internal/api/resolver_mutation_movie.go
  internal/api/resolver_mutation_scene.go
  internal/api/types.go
  pkg/models/gallery_chapter.go
  pkg/models/mocks/GalleryChapterReaderWriter.go
  pkg/models/mocks/SceneMarkerReaderWriter.go
  pkg/models/model_gallery_chapter.go
  pkg/models/model_scene_marker.go
  pkg/models/scene_marker.go
  pkg/sqlite/gallery_chapter.go
  pkg/sqlite/scene_marker.go
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryChapterForm.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkerForm.tsx
  ui/v2.5/src/index.scss
Labels: bug

#3954 Return scrape results if only relationships are returned
  pkg/scraper/mapped.go
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieScrapeDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
Labels: bug

#3955 Fix scene marker issues
  pkg/models/model_scene_marker.go
  pkg/sqlite/gallery_chapter.go
  pkg/sqlite/performer.go
  pkg/sqlite/scene_marker.go
  pkg/sqlite/tag.go
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryChapterForm.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryChaptersPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkerForm.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkersPanel.tsx
Labels: bug

#3929 Add database optimise task
  graphql/documents/mutations/metadata.graphql
  graphql/schema/schema.graphql
  internal/api/resolver_mutation_metadata.go
  internal/manager/manager_tasks.go
  internal/manager/task_optimise.go
  pkg/sqlite/anonymise.go
  pkg/sqlite/database.go
  ui/v2.5/src/components/Settings/Tasks/DataManagementTasks.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/en-US.json
Labels: feature

#3946 Details page redesign
  ui/v2.5/src/components/List/ItemList.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieCreate.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieDetailsPanel.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieEditPanel.tsx
  ui/v2.5/src/components/Movies/styles.scss
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerCreate.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/components/Shared/CountryFlag.tsx
  ui/v2.5/src/components/Shared/DetailItem.tsx
  ui/v2.5/src/components/Shared/GridCard.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioCreate.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioDetailsPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagCreate.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagDetailsPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagEditPanel.tsx
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/docs/en/Manual/KeyboardShortcuts.md
  ui/v2.5/src/index.scss
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/utils/image.tsx
Labels: improvement, ui

#3968 Use TagLink for parent/child tag badges
  ui/v2.5/src/components/Tags/TagDetails/TagDetailsPanel.tsx
Labels: bug

#3969 Fix scraped movie to create input translation
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/core/movies.ts
  ui/v2.5/src/core/performers.ts
Labels: bug

#3973 Fix graphql caching issues
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/core/createClient.ts
Labels: bug
