Repository stashapp/stash, pull requests merged in 2024-09, with the labels that each got.

#5200 Add info about regex modifiers
  ui/v2.5/src/docs/en/Manual/Browsing.md
Labels: documentation

#5182 Gallery cover url
  graphql/schema/types/gallery.graphql
  internal/api/resolver_model_gallery.go
  internal/api/routes_gallery.go
  internal/api/urlbuilders/gallery.go
  internal/dlna/dms.go
  internal/static/embed.go
  internal/static/gallery/gallery.svg
  pkg/image/query.go
  pkg/models/repository_image.go
  ui/v2.5/graphql/data/gallery-slim.graphql
  ui/v2.5/graphql/data/gallery.graphql
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Galleries/GalleryListTable.tsx
  ui/v2.5/src/components/Galleries/GalleryWallCard.tsx
Labels: bug, improvement

#5188 Adjust image dimensions for exif orientation
  go.mod
  go.sum
  pkg/file/image/orientation.go
  pkg/file/image/scan.go
Labels: bug

#5189 Scan video orientation
  cmd/phasher/main.go
  internal/manager/init.go
  internal/manager/manager.go
  pkg/ffmpeg/codec_hardware.go
  pkg/ffmpeg/ffmpeg.go
  pkg/ffmpeg/ffmpeg_test.go
  pkg/ffmpeg/ffprobe.go
  pkg/ffmpeg/stream.go
  pkg/ffmpeg/types.go
  pkg/file/image/scan.go
  pkg/file/video/scan.go
  pkg/image/thumbnail.go
Labels: bug

#5199 Prevent window scrolling on mouse wheel scroll when numeric input field is focused and hovered
  ui/v2.5/src/utils/form.tsx
Labels: bug

#5204 Don't focus query field on select
  ui/v2.5/src/components/List/Filters/SelectableFilter.tsx
Labels: bug

#5205 Only give height to gallery-container on larger devices
  ui/v2.5/src/components/Galleries/styles.scss
Labels: improvement

#5206 Show page numbers on low page count
  ui/v2.5/src/components/List/Pagination.tsx
Labels: improvement

#5212 lint: switch exportloopref to copyloopvar per warning message
  .golangci.yml
Labels: chore

#5217 Gallery scrubber code cleanup
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
Labels: chore

#5218 Fix Tag and Alias odd spacing
  ui/v2.5/src/components/Performers/PerformerSelect.tsx
  ui/v2.5/src/components/Studios/StudioSelect.tsx
  ui/v2.5/src/components/Tags/TagSelect.tsx
Labels: bug

#5216 Don't try to migrate non-existent vtt files
  pkg/scene/migrate_hash.go
Labels: bug

#5221 Fix scene filter panel colour slider range
  ui/v2.5/src/components/Scenes/SceneDetails/SceneVideoFilterPanel.tsx
  ui/v2.5/src/components/Scenes/styles.scss
Labels: bug

#5213 Fix handling of files to delete during delete Gallery operation
  pkg/gallery/delete.go
  pkg/gallery/service.go
  pkg/image/delete.go
  pkg/models/mocks/ImageReaderWriter.go
  pkg/models/mocks/SceneReaderWriter.go
  pkg/models/repository_image.go
  pkg/sqlite/image.go
  pkg/sqlite/table.go
Labels: bug

#5183 Make Scrubbers touchscreen capable
  ui/v2.5/src/components/Shared/HoverScrubber.tsx
Labels: improvement

#5195 Add linkTypes to performer popover
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Images/ImageCard.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Shared/PerformerPopoverButton.tsx
  ui/v2.5/src/components/Shared/TagLink.tsx
Labels: bug

#5187 replace stashBox validation
  internal/manager/config/config.go
Labels: improvement

#5222 Fix gallery scrubber image order
  pkg/sqlite/image.go
Labels: bug

#5191 Gallery scrubber wall view
  ui/v2.5/src/components/Galleries/GalleryWallCard.tsx
  ui/v2.5/src/components/Galleries/styles.scss
  ui/v2.5/src/components/Shared/HoverScrubber.tsx
Labels: feature

#5223 Show option for sub-content only if there are child objects
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
Labels: improvement

#5225 Use gallery updated at for cover mod time
  internal/api/routes_gallery.go
  internal/api/routes_image.go
  pkg/utils/http.go
Labels: bug

#5228 Fix scroll to top behaviour
  ui/v2.5/src/components/List/ItemList.tsx
  ui/v2.5/src/components/List/util.ts
Labels: bug

#5234 Add note about saved filter sorting
  ui/v2.5/src/docs/en/Manual/Browsing.md
Labels: documentation

#5229 Fix `source-selector` being blocked on mobile
  ui/v2.5/src/components/ScenePlayer/styles.scss
Labels: bug

#5241 Bottom Page-Count button causes scenes page to reset to top
  ui/v2.5/src/components/List/Pagination.tsx
Labels: bug

#5235 Updating Reload Scrapers formatting
  ui/v2.5/src/components/Shared/ScraperMenu.tsx
  ui/v2.5/src/components/Shared/styles.scss
Labels: improvement

#5246 Fix performer disambiguation styling in select
  ui/v2.5/src/components/Performers/styles.scss
Labels: bug

#5244 Anonymise missing fields
  pkg/sqlite/anonymise.go
Labels: bug

#5243 Fix hover scrubber error in Firefox
  ui/v2.5/src/components/Shared/HoverScrubber.tsx
Labels: bug

#5242 Set max-height for all modals
  ui/v2.5/src/components/Help/styles.scss
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/index.scss
Labels: bug

#5245 (PluginAPI) ImageDetailPanel Patch Component
  ui/v2.5/src/components/Images/ImageDetails/ImageDetailPanel.tsx
  ui/v2.5/src/docs/en/Manual/UIPluginApi.md
Labels: chore

#5247 Rename movies to groups in menu items in 65 post-migration
  pkg/sqlite/migrations/58_postmigrate.go
  pkg/sqlite/migrations/65_postmigrate.go
Labels: bug

#5249 Handle symlink zip files
  pkg/file/fs.go
  pkg/file/scan.go
  pkg/file/zip.go
  pkg/models/fs.go
  pkg/models/model_file.go
  pkg/sqlite/file.go
  pkg/sqlite/folder.go
Labels: bug

#5250 Default database backup to same directory as database
  internal/manager/config/config.go
Labels: bug

#5251 Emit error in SafeMove if remove from source fails
  pkg/fsutil/file.go
Labels: bug

#5253 Add portals for selects in dialogs
  ui/v2.5/src/components/Dialogs/IdentifyDialog/Options.tsx
  ui/v2.5/src/components/Galleries/EditGalleriesDialog.tsx
  ui/v2.5/src/components/Groups/ContainingGroupsMultiSet.tsx
  ui/v2.5/src/components/Groups/EditGroupsDialog.tsx
  ui/v2.5/src/components/Groups/GroupDetails/RelatedGroupTable.tsx
  ui/v2.5/src/components/Images/EditImagesDialog.tsx
  ui/v2.5/src/components/Performers/EditPerformersDialog.tsx
  ui/v2.5/src/components/Scenes/EditScenesDialog.tsx
  ui/v2.5/src/components/Shared/MultiSet.tsx
  ui/v2.5/src/components/Tags/EditTagsDialog.tsx
Labels: bug

#5254 Add UI option for rescan scan option
  ui/v2.5/src/components/Settings/Tasks/ScanOptions.tsx
  ui/v2.5/src/docs/en/Manual/Tasks.md
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#5260 Update upload-artifact action to pass build
  .github/workflows/build.yml
Labels: chore

#5267 Fix preview scrubber touch issues
  ui/v2.5/src/components/Galleries/GalleryPreviewScrubber.tsx
  ui/v2.5/src/components/Scenes/PreviewScrubber.tsx
  ui/v2.5/src/components/Shared/HoverScrubber.tsx
  ui/v2.5/src/hooks/sprite.ts
Labels: bug

#5271 Weblate translation update
  ui/v2.5/src/locales/de-DE.json
  ui/v2.5/src/locales/es-ES.json
  ui/v2.5/src/locales/fr-FR.json
  ui/v2.5/src/locales/ja-JP.json
  ui/v2.5/src/locales/sv-SE.json
  ui/v2.5/src/locales/uk-UA.json
  ui/v2.5/src/locales/zh-CN.json
  ui/v2.5/src/locales/zh-TW.json
Labels: chore

#5274 Database connection pool refactor
  pkg/sqlite/anonymise.go
  pkg/sqlite/database.go
  pkg/sqlite/migrate.go
  pkg/sqlite/migrations/45_postmigrate.go
  pkg/sqlite/migrations/48_premigrate.go
  pkg/sqlite/migrations/60_postmigrate.go
  pkg/sqlite/transaction.go
  pkg/sqlite/transaction_test.go
  pkg/txn/transaction.go
  ui/v2.5/src/docs/en/Manual/Configuration.md
Labels: bug, feature

#5280 Replace movie with group in manual
  ui/v2.5/src/docs/en/Manual/Browsing.md
  ui/v2.5/src/docs/en/Manual/JSONSpec.md
  ui/v2.5/src/docs/en/Manual/KeyboardShortcuts.md
  ui/v2.5/src/docs/en/Manual/Plugins.md
  ui/v2.5/src/docs/en/Manual/Scraping.md
  ui/v2.5/src/docs/en/Manual/UIPluginApi.md
Labels: documentation

#5279 Fix scene number sorting when scene belongs to more than one group
  pkg/sqlite/scene.go
Labels: bug

#5282 Fix migrations not using tx
  pkg/sqlite/migrations/32_postmigrate.go
  pkg/sqlite/migrations/32_premigrate.go
  pkg/sqlite/migrations/34_postmigrate.go
  pkg/sqlite/migrations/42_postmigrate.go
  pkg/sqlite/migrations/45_postmigrate.go
  pkg/sqlite/migrations/49_postmigrate.go
  pkg/sqlite/migrations/52_postmigrate.go
  pkg/sqlite/migrations/55_postmigrate.go
  pkg/sqlite/migrations/64_postmigrate.go
Labels: bug

#5283 Prevent mouse wheel window scrolling on other number fields
  ui/v2.5/src/components/List/Filters/HierarchicalLabelValueFilter.tsx
  ui/v2.5/src/components/List/Filters/NumberFilter.tsx
  ui/v2.5/src/components/List/Filters/PhashFilter.tsx
  ui/v2.5/src/components/List/Filters/SelectableFilter.tsx
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/List/Pagination.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneGroupTable.tsx
  ui/v2.5/src/components/Settings/GeneratePreviewOptions.tsx
  ui/v2.5/src/components/Settings/Inputs.tsx
  ui/v2.5/src/components/Shared/Rating/RatingNumber.tsx
  ui/v2.5/src/utils/form.tsx
Labels: bug

#5299 Fix merge dialog select boxes display issue
  ui/v2.5/src/components/Scenes/SceneMergeDialog.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagMergeDialog.tsx
  ui/v2.5/src/docs/en/Changelog/v0270.md
Labels: bug

#5310 Fix link menu issues
  ui/v2.5/src/components/Shared/ExternalLinksButton.tsx
Labels: bug

#5309 Update README.md to indicate minimal Windows versions required from 0.27.0 version
  README.md
Labels: documentation

#5319 Refresh URL if random seed set
  ui/v2.5/src/components/List/util.ts
Labels: bug

#5320 Fix parent/child tag sort order
  pkg/sqlite/table.go
  pkg/sqlite/tables.go
Labels: bug

#5321 Fix page > total redirecting to first page instead of last
  ui/v2.5/src/components/List/util.ts
Labels: bug
