Repository stashapp/stash, pull requests merged in 2024-08, with the labels that each got.

#5109 Fixed filters saving incorrectly
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/performers.ts
  ui/v2.5/src/models/list-filter/criteria/phash.ts
  ui/v2.5/src/models/list-filter/criteria/rating.ts
  ui/v2.5/src/models/list-filter/criteria/stash-ids.ts
Labels: bug

#5123 Codeberg weblate update
  ui/v2.5/src/locales/cs-CZ.json
  ui/v2.5/src/locales/da-DK.json
  ui/v2.5/src/locales/de-DE.json
  ui/v2.5/src/locales/es-ES.json
  ui/v2.5/src/locales/et-EE.json
  ui/v2.5/src/locales/fi-FI.json
  ui/v2.5/src/locales/fr-FR.json
  ui/v2.5/src/locales/hi.json
  ui/v2.5/src/locales/hu-HU.json
  ui/v2.5/src/locales/id-ID.json
  ui/v2.5/src/locales/it-IT.json
  ui/v2.5/src/locales/ja-JP.json
  ui/v2.5/src/locales/ko-KR.json
  ui/v2.5/src/locales/lv.json
  ui/v2.5/src/locales/nb_NO.json
  ui/v2.5/src/locales/nl-NL.json
  ui/v2.5/src/locales/nn.json
  ui/v2.5/src/locales/pl-PL.json
  ui/v2.5/src/locales/pt-BR.json
  ui/v2.5/src/locales/ro-RO.json
  ui/v2.5/src/locales/ru-RU.json
  ui/v2.5/src/locales/sv-SE.json
  ui/v2.5/src/locales/th-TH.json
  ui/v2.5/src/locales/tr-TR.json
  ui/v2.5/src/locales/zh-CN.json
  ui/v2.5/src/locales/zh-TW.json
Labels: chore

#5126 Filter issue fixes
  ui/v2.5/src/components/List/FilterProvider.tsx
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/components/List/util.ts
  ui/v2.5/src/components/Shared/ClearableInput.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/gender.ts
  ui/v2.5/src/models/list-filter/criteria/performers.ts
  ui/v2.5/src/models/list-filter/criteria/phash.ts
  ui/v2.5/src/models/list-filter/criteria/rating.ts
  ui/v2.5/src/models/list-filter/criteria/stash-ids.ts
Labels: bug

#5127 Fix view history imported from o-history json
  pkg/scene/import.go
  pkg/scene/import_test.go
Labels: bug

#5128 Fix broken link in development documentation.
  docs/DEVELOPMENT.md
Labels: documentation

#5129 Add missing performer sort options to whitelist
  pkg/sqlite/performer.go
  ui/v2.5/src/models/list-filter/performers.ts
Labels: improvement

#5125 UI nested instead
  pkg/plugin/examples/react-component/src/testReact.scss
  pkg/plugin/examples/react-component/src/testReact.tsx
  ui/v2.5/src/docs/en/Manual/UIPluginApi.md
  ui/v2.5/src/patch.tsx
Labels: improvement

#5136 PatchComponentRedo
  internal/dlna/cds.go
  pkg/plugin/raw.go
  pkg/scraper/stashbox/stash_box.go
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/CheckboxGroup.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
Labels: chore

#5142 QOL Move Reload Scrapers to Top
  ui/v2.5/src/components/Shared/ScraperMenu.tsx
Labels: improvement

#5166 Truncate scenes_o_dates and scenes_view_dates as part of anonymize
  pkg/sqlite/anonymise.go
Labels: bug

#5167 Use existing consts for table names in anonymise.go where available
  pkg/sqlite/anonymise.go
Labels: chore

#5097 Markers scene filter
  graphql/schema/types/filters.graphql
  pkg/models/scene_marker.go
  pkg/sqlite/scene_marker_filter.go
  ui/v2.5/src/components/List/Filters/LabeledIdFilter.tsx
  ui/v2.5/src/models/list-filter/criteria/scenes.ts
  ui/v2.5/src/models/list-filter/scene-markers.ts
Labels: feature

#5154 Add video codec profiles
  pkg/ffmpeg/codec.go
  pkg/ffmpeg/codec_hardware.go
  pkg/ffmpeg/stream_transcode.go
  pkg/ffmpeg/transcoder/screenshot.go
  pkg/ffmpeg/transcoder/splice.go
Labels: bug, improvement

#5171 Update builtin freeones scraper
  pkg/scraper/freeones.go
Labels: bug

#5169 Add package docs and project vision/goals
  docs/CONTRIBUTING.md
  internal/api/doc.go
  internal/api/loaders/dataloaders.go
  internal/api/server.go
  internal/api/urlbuilders/doc.go
  internal/autotag/doc.go
  internal/build/version.go
  internal/desktop/desktop.go
  internal/dlna/doc.go
  internal/identify/identify.go
  internal/log/logger.go
  internal/manager/manager.go
  internal/static/embed.go
  pkg/file/file.go
  pkg/fsutil/fs.go
  pkg/gallery/service.go
  pkg/group/doc.go
  pkg/image/service.go
  pkg/javascript/vm.go
  pkg/job/job.go
  pkg/match/path.go
  pkg/models/doc.go
  pkg/models/json/json_time.go
  pkg/models/jsonschema/doc.go
  pkg/models/mocks/database.go
  pkg/models/paths/paths.go
  pkg/performer/doc.go
  pkg/pkg/pkg.go
  pkg/python/exec.go
  pkg/scene/generate/generator.go
  pkg/scene/service.go
  pkg/scraper/scraper.go
  pkg/scraper/stashbox/stash_box.go
  pkg/session/session.go
  pkg/sliceutil/collections.go
  pkg/sqlite/doc.go
  pkg/studio/doc.go
  pkg/tag/doc.go
  pkg/txn/transaction.go
  pkg/utils/doc.go
Labels: chore

#5170 Replace group image with more consistent svg
  internal/static/embed.go
  internal/static/group/group.png
  internal/static/group/group.svg
Labels: improvement

#5172 Bump linux ffmpeg URL for latest version
  pkg/ffmpeg/downloader.go
Labels: chore

#5165 Persist tagger settings and change defaults
  ui/v2.5/src/components/Tagger/config.ts
  ui/v2.5/src/components/Tagger/constants.ts
  ui/v2.5/src/components/Tagger/context.tsx
  ui/v2.5/src/components/Tagger/performers/PerformerTagger.tsx
  ui/v2.5/src/components/Tagger/studios/StudioTagger.tsx
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/docs/en/ReleaseNotes/index.ts
  ui/v2.5/src/docs/en/ReleaseNotes/v0270.md
Labels: improvement

#5176 Standardizing the delete dropdown.
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Images/ImageDetails/Image.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
Labels: improvement

#5177 Add Overlay-duration to span
  ui/v2.5/src/components/Scenes/SceneCard.tsx
Labels: improvement

#5145 Scene player presentation improvements
  ui/v2.5/src/components/ScenePlayer/source-selector.ts
  ui/v2.5/src/components/ScenePlayer/styles.scss
Labels: improvement

#5161 [Bug Fix] Fix Studio Pluralization
  ui/v2.5/src/components/Studios/StudioCard.tsx
Labels: bug

#5141 Removing Play Button With No File
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/styles.scss
Labels: improvement

#5179 Update gqlgen and gqlparser dependencies
  go.mod
  go.sum
Labels: chore

#4778 chore: use errors.New to replace fmt.Errorf with no parameters will much better
  pkg/file/import.go
Labels: chore

#5053 Support for assigning any image from a gallery as the cover
  graphql/schema/schema.graphql
  graphql/schema/types/gallery.graphql
  internal/api/resolver_mutation_gallery.go
  internal/manager/repository.go
  pkg/gallery/update.go
  pkg/image/query.go
  pkg/models/mocks/GalleryReaderWriter.go
  pkg/models/mocks/ImageReaderWriter.go
  pkg/models/repository_gallery.go
  pkg/models/repository_image.go
  pkg/sqlite/database.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/image.go
  pkg/sqlite/migrations/66_gallery_cover.up.sql
  pkg/sqlite/table.go
  pkg/sqlite/tables.go
  ui/v2.5/graphql/mutations/gallery.graphql
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryImagesPanel.tsx
  ui/v2.5/src/components/List/ItemList.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#5168 Create a section in the history panel to reset scene activity
  graphql/schema/schema.graphql
  internal/api/resolver_mutation_scene.go
  pkg/models/mocks/SceneReaderWriter.go
  pkg/models/repository_scene.go
  pkg/sqlite/scene.go
  ui/v2.5/graphql/mutations/scene.graphql
  ui/v2.5/src/components/Scenes/SceneDetails/SceneHistoryPanel.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/locales/en-GB.json
Labels: feature
