Repository stashapp/stash, pull requests merged in 2024-03, with the labels that each got.

#4644 fix lightbox display modes
  ui/v2.5/src/hooks/Lightbox/LightboxImage.tsx
Labels: bug

#4650 Fix URL prefix re-inserted when redirecting settings page
  ui/v2.5/src/components/Settings/Settings.tsx
Labels: bug

#4653 Prevent bitmap images from being scanned as image clips
  pkg/file/image/scan.go
Labels: bug

#4660 Fix ffmpeg error when trying to scale and copy video
  internal/manager/task_transcode.go
  pkg/scene/generate/transcode.go
Labels: bug

#4657 Fix image clip webm not being cleaned
  internal/manager/task/clean_generated.go
Labels: bug

#4658 Fit cards code improvement
  ui/v2.5/package.json
  ui/v2.5/src/components/Galleries/GalleryGridCard.tsx
  ui/v2.5/src/components/Images/ImageGridCard.tsx
  ui/v2.5/src/components/Movies/MovieCardGrid.tsx
  ui/v2.5/src/components/Performers/PerformerCardGrid.tsx
  ui/v2.5/src/components/Scenes/SceneCardsGrid.tsx
  ui/v2.5/src/components/Shared/GridCard/GridCard.tsx
  ui/v2.5/src/components/Studios/StudioCardGrid.tsx
  ui/v2.5/src/components/Tags/TagCardGrid.tsx
  ui/v2.5/yarn.lock
Labels: improvement

#4665 fix image card width on front page
  ui/v2.5/src/components/FrontPage/styles.scss
Labels: bug

#4662 Fix text color of medium fingerprint matches
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
Labels: bug

#4676 Update StashDB details in README.md
  README.md
Labels: documentation

#4670 play monitoring improvement
  ui/v2.5/src/components/ScenePlayer/track-activity.ts
Labels: improvement

#4682 Downgrade astisub
  go.mod
  go.sum
Labels: bug

#4620 Save task options
  graphql/schema/schema.graphql
  internal/api/resolver_mutation_configure.go
  pkg/utils/map.go
  pkg/utils/map_test.go
  ui/v2.5/graphql/client-schema.graphql
  ui/v2.5/graphql/mutations/config.graphql
  ui/v2.5/src/components/Settings/Tasks/LibraryTasks.tsx
  ui/v2.5/src/components/Settings/context.tsx
  ui/v2.5/src/core/StashService.ts
Labels: improvement

#4649 Added Sort Performers by Last O At / Last Played At / Play Count and Added Filter Performers by Play Count. Changes to display O Count rather than O-Counter for better consistency. Grammar fixes for 'Interactive Speed' and 'pHash'.
  graphql/schema/types/filters.graphql
  pkg/models/performer.go
  pkg/sqlite/performer.go
  ui/v2.5/src/components/Performers/PerformerListTable.tsx
  ui/v2.5/src/components/Scenes/SceneListTable.tsx
  ui/v2.5/src/components/Scenes/SceneMergeDialog.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/images.ts
  ui/v2.5/src/models/list-filter/performers.ts
  ui/v2.5/src/models/list-filter/scenes.ts
Labels: feature, improvement

#4621 Make directors and photographers clickable in detail view
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryDetailPanel.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageDetailPanel.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieDetailsPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneDetailPanel.tsx
  ui/v2.5/src/components/Shared/Link.tsx
  ui/v2.5/src/utils/navigation.ts
Labels: improvement

#4631 Replace javascript module otto with goja
  go.mod
  go.sum
  pkg/javascript/gql.go
  pkg/javascript/log.go
  pkg/javascript/util.go
  pkg/javascript/vm.go
  pkg/plugin/common/msg.go
  pkg/plugin/js.go
  pkg/plugin/js/gql.go
  pkg/plugin/js/log.go
  pkg/plugin/js/util.go
  pkg/scraper/mapped.go
Labels: chore

#4683 Minor mobile fixes
  ui/v2.5/src/components/List/EditFilterDialog.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/utils/focus.ts
  ui/v2.5/src/utils/screen.ts
Labels: improvement, ui

#4666 Make migration an asynchronous task
  graphql/schema/schema.graphql
  graphql/schema/types/job.graphql
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_mutation_migrate.go
  internal/api/resolver_query_job.go
  internal/manager/manager.go
  internal/manager/manager_tasks.go
  internal/manager/task/clean_generated.go
  internal/manager/task/migrate.go
  internal/manager/task/migrate_blobs.go
  internal/manager/task/migrate_scene_screenshots.go
  internal/manager/task/packages.go
  internal/manager/task_autotag.go
  internal/manager/task_clean.go
  internal/manager/task_generate.go
  internal/manager/task_identify.go
  internal/manager/task_optimise.go
  internal/manager/task_plugin.go
  internal/manager/task_scan.go
  pkg/job/job.go
  pkg/job/manager.go
  pkg/job/manager_test.go
  pkg/sqlite/database.go
  pkg/sqlite/migrate.go
  ui/v2.5/graphql/data/job.graphql
  ui/v2.5/graphql/subscriptions.graphql
  ui/v2.5/src/App.tsx
  ui/v2.5/src/ConnectionMonitor.tsx
  ui/v2.5/src/components/Settings/Tasks/JobTable.tsx
  ui/v2.5/src/components/Settings/styles.scss
  ui/v2.5/src/components/Setup/Migrate.tsx
  ui/v2.5/src/components/Setup/styles.scss
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/core/createClient.ts
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/utils/job.ts
Labels: improvement

#4692 Use new studio selector in movie scrape dialog
  ui/v2.5/src/components/Movies/MovieDetails/MovieEditPanel.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieScrapeDialog.tsx
Labels: bug

#4700 Fix unhandled error
  internal/api/resolver_query_find_image.go
Labels: bug

#4705 Apply filter hook to results filter only
  ui/v2.5/src/components/List/ItemList.tsx
Labels: improvement

#4713 Bitrate filter
  graphql/schema/types/filters.graphql
  pkg/models/scene.go
  pkg/sqlite/scene.go
  ui/v2.5/src/models/list-filter/scenes.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: feature

#4688 Change ffmpeg handling
  cmd/phasher/main.go
  graphql/schema/schema.graphql
  graphql/schema/types/config.graphql
  graphql/schema/types/metadata.graphql
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_query_configuration.go
  internal/manager/config/config.go
  internal/manager/init.go
  internal/manager/manager.go
  internal/manager/models.go
  internal/manager/task/download_ffmpeg.go
  pkg/ffmpeg/codec_hardware.go
  pkg/ffmpeg/downloader.go
  pkg/ffmpeg/ffmpeg.go
  pkg/ffmpeg/ffprobe.go
  pkg/fsutil/file.go
  ui/v2.5/graphql/data/config.graphql
  ui/v2.5/graphql/mutations/config.graphql
  ui/v2.5/graphql/queries/settings/metadata.graphql
  ui/v2.5/src/components/Settings/SettingsSystemPanel.tsx
  ui/v2.5/src/components/Setup/Setup.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#4715 Fix selected tagger search result being lost when creating objects
  ui/v2.5/src/components/Tagger/context.tsx
  ui/v2.5/src/components/Tagger/scenes/SceneTagger.tsx
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/scenes/utils.ts
  ui/v2.5/src/components/Tagger/styles.scss
Labels: bug
