Repository stashapp/stash, pull requests merged in 2024-10, with the labels that each got.

#5325 Fix UI error when image has no files
  ui/v2.5/src/components/Images/ImageDetails/Image.tsx
Labels: bug

#5328 Fix panic when deleting image with no files
  pkg/sqlite/image.go
Labels: bug

#5327 fix: fix slice init length
  pkg/models/model_joins.go
Labels: bug

#5334 Fix rating display in filter tags
  ui/v2.5/src/components/List/ItemList.tsx
Labels: bug

#5335 Exclude null values from image studio id index
  pkg/sqlite/database.go
  pkg/sqlite/migrations/68_image_studio_index.up.sql
Labels: bug

#5318 Add `include_sub_groups` message ID
  ui/v2.5/src/components/List/Filters/HierarchicalLabelValueFilter.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: bug

#5337 Fix match studio/performer links in tagger view
  ui/v2.5/src/components/Tagger/scenes/PerformerResult.tsx
  ui/v2.5/src/components/Tagger/scenes/StudioResult.tsx
Labels: bug

#5323 Add Open Container Image annotations as labels to the Docker image
  docker/ci/x86_64/Dockerfile
Labels: chore

#5340 Scene player fixes and improvements
  pkg/ffmpeg/stream_transcode.go
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/live.ts
Labels: bug

#5348 Handle legacy scene movies criterion in saved filters
  ui/v2.5/src/models/list-filter/criteria/groups.ts
  ui/v2.5/src/models/list-filter/scenes.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: bug

#5349 Restore persistence in selection when paging
  ui/v2.5/src/components/List/util.ts
Labels: bug

#5350 Add blobs location to env binds
  internal/manager/config/init.go
Labels: bug

#5358 Prevent duplicate entries in selection list
  ui/v2.5/src/components/List/util.ts
Labels: bug

#5363 adding exists check before dropping constraints
  pkg/sqlite/migrations/62_performer_urls.up.sql
Labels: bug

#5377 Fix duplicate items appearing in selected list (again)
  ui/v2.5/src/components/List/util.ts
  ui/v2.5/src/components/Shared/GridCard/GridCard.tsx
Labels: bug

#5379 More scene player bug fixes
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/ScenePlayer/source-selector.ts
Labels: bug

#5416 remove bencoder.pyx, update vips
  docker/ci/x86_64/Dockerfile
Labels: chore

#5360 Use slices package from the stdlib when possible
  internal/api/resolver_query_find_image.go
  internal/api/resolver_query_find_scene.go
  internal/api/resolver_query_package.go
  internal/autotag/gallery.go
  internal/autotag/image.go
  internal/autotag/performer.go
  internal/autotag/scene.go
  internal/autotag/tag.go
  internal/dlna/cds.go
  internal/dlna/whitelist.go
  internal/identify/identify.go
  internal/identify/identify_test.go
  pkg/gallery/import.go
  pkg/group/import.go
  pkg/group/validate.go
  pkg/image/import.go
  pkg/image/scan.go
  pkg/performer/import.go
  pkg/plugin/plugins.go
  pkg/scene/import.go
  pkg/scene/merge.go
  pkg/sliceutil/collections.go
  pkg/sliceutil/collections_test.go
  pkg/sliceutil/stringslice/string_collections.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_chapter.go
  pkg/sqlite/group.go
  pkg/sqlite/group_test.go
  pkg/sqlite/image.go
  pkg/sqlite/performer.go
  pkg/sqlite/saved_filter.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_marker.go
  pkg/sqlite/scene_marker_test.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/studio.go
  pkg/sqlite/tag.go
  pkg/studio/import.go
Labels: chore

#5396 show/hide details via CSS rather than Javascript
  ui/v2.5/src/components/Groups/GroupDetails/GroupDetailsPanel.tsx
  ui/v2.5/src/components/Groups/styles.scss
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Studios/StudioDetails/StudioDetailsPanel.tsx
  ui/v2.5/src/components/Studios/styles.scss
Labels: improvement

#5367 Group details: Flippable images in expanded view.
  ui/v2.5/src/components/Groups/GroupDetails/Group.tsx
  ui/v2.5/src/components/Groups/styles.scss
Labels: improvement

#5401 Update Scenes' 'Updated At' Date on Heatmap Gen & Expand Error Log
  internal/manager/task_generate_interactive_heatmap_speed.go
Labels: improvement

#5288 Remove unnecessary scroll to top on mount for top level query pages
  ui/v2.5/src/components/Galleries/Galleries.tsx
  ui/v2.5/src/components/Groups/Groups.tsx
  ui/v2.5/src/components/Images/Images.tsx
  ui/v2.5/src/components/Performers/Performers.tsx
  ui/v2.5/src/components/Scenes/Scenes.tsx
  ui/v2.5/src/components/Studios/Studios.tsx
  ui/v2.5/src/components/Tags/Tags.tsx
Labels: bug

#5203 Move modifiers into selectable options in object filter selectors
  ui/v2.5/src/components/List/CriterionEditor.tsx
  ui/v2.5/src/components/List/Filters/SelectableFilter.tsx
  ui/v2.5/src/components/List/Filters/StudiosFilter.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#5391 Upgrade gqlgenc and regenerate stash-box client
  .github/workflows/build.yml
  .github/workflows/golangci-lint.yml
  docker/compiler/Dockerfile
  docker/compiler/Makefile
  go.mod
  go.sum
  gqlgen.yml
  internal/api/server.go
  internal/manager/task_scan.go
  pkg/scraper/stashbox/graphql/generated_client.go
  pkg/scraper/stashbox/graphql/generated_models.go
  pkg/scraper/stashbox/stash_box.go
Labels: bug, chore

#5428 Fix scraping stash-box performers with null birthdates
  graphql/stash-box/query.graphql
  pkg/scraper/stashbox/graphql/generated_client.go
  pkg/scraper/stashbox/stash_box.go
Labels: bug

#5259 Add updated_at field to stash_id's
  gqlgen.yml
  graphql/schema/types/stash-box.graphql
  internal/api/changeset_translator.go
  internal/api/resolver_mutation_performer.go
  internal/api/resolver_mutation_scene.go
  internal/api/resolver_mutation_studio.go
  internal/identify/identify.go
  internal/identify/scene.go
  internal/identify/scene_test.go
  pkg/models/model_scene.go
  pkg/models/model_scraped_item.go
  pkg/models/model_scraped_item_test.go
  pkg/models/performer.go
  pkg/models/scene.go
  pkg/models/stash_ids.go
  pkg/models/studio.go
  pkg/scene/update_test.go
  pkg/sqlite/database.go
  pkg/sqlite/migrations/69_stash_id_updated_at.up.sql
  pkg/sqlite/repository.go
  pkg/sqlite/table.go
  ui/v2.5/graphql/data/performer-slim.graphql
  ui/v2.5/graphql/data/performer.graphql
  ui/v2.5/graphql/data/scene-slim.graphql
  ui/v2.5/graphql/data/scene.graphql
  ui/v2.5/graphql/data/studio-slim.graphql
  ui/v2.5/graphql/data/studio.graphql
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Shared/StashID.tsx
  ui/v2.5/src/components/Tagger/PerformerModal.tsx
  ui/v2.5/src/components/Tagger/context.tsx
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/scenes/StudioModal.tsx
  ui/v2.5/src/utils/stashIds.ts
Labels: bounty
