Repository stashapp/stash, pull requests merged in 2024-05, with the labels that each got.

#4766 chore: fix struct names
  pkg/file/clean.go
  pkg/models/repository_blob.go
  pkg/models/value.go
Labels: chore

#4770 Select first result in Tagger when selectedResult is not defined
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
Labels: bug

#4798 Fix filterHook not applied to scene card queue
  ui/v2.5/src/components/List/ItemList.tsx
Labels: bug

#4799 Fix interactive speed being lost when file is moved
  pkg/file/scan.go
  pkg/models/model_file.go
Labels: bug

#4800 Fix duplicate scene checker select logic
  ui/v2.5/src/components/SceneDuplicateChecker/SceneDuplicateChecker.tsx
Labels: bug

#4801 Clean duplicate aliases when creating from performer tagger
  ui/v2.5/src/components/Tagger/performers/StashSearchResult.tsx
Labels: bug

#4820 Fix alias issue when tagging performer from stash-box
  pkg/scraper/stashbox/stash_box.go
  pkg/sliceutil/stringslice/string_collections.go
Labels: bug

#4784 Better support for Samsung SmartTV for built-in DLNA server
  internal/dlna/cds.go
  internal/dlna/dms.go
Labels: bug

#4728 Tag Favoriting
  graphql/schema/types/filters.graphql
  graphql/schema/types/tag.graphql
  internal/api/resolver_mutation_tag.go
  pkg/models/jsonschema/tag.go
  pkg/models/model_tag.go
  pkg/models/tag.go
  pkg/scraper/stashbox/graphql/generated_models.go
  pkg/sqlite/database.go
  pkg/sqlite/migrations/57_tag_favorite.up.sql
  pkg/sqlite/setup_test.go
  pkg/sqlite/tag.go
  pkg/tag/export.go
  pkg/tag/export_test.go
  pkg/tag/import.go
  ui/v2.5/graphql/data/tag.graphql
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagCard.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/styles.scss
  ui/v2.5/src/models/list-filter/criteria/favorite.ts
  ui/v2.5/src/models/list-filter/tags.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: feature

#4765 Full hardware transcoding
  pkg/ffmpeg/codec_hardware.go
  pkg/ffmpeg/ffmpeg.go
  pkg/ffmpeg/stream_segmented.go
  pkg/ffmpeg/stream_transcode.go
Labels: improvement

#4825 Fix black screen after migrating with release notes
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Setup/Migrate.tsx
  ui/v2.5/src/core/StashService.ts
Labels: bug

#4824 Build UI artifacts
  .github/workflows/build.yml
  Makefile
  internal/api/server.go
  internal/manager/config/config.go
  internal/manager/config/config_concurrency_test.go
  internal/manager/config/init.go
Labels: improvement, chore

#4710 Enable track activity by default
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/docs/en/ReleaseNotes/index.ts
  ui/v2.5/src/docs/en/ReleaseNotes/v0260.md
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#4829 Add last_played_at filter
  graphql/schema/types/filters.graphql
  pkg/models/scene.go
  pkg/sqlite/scene.go
  ui/v2.5/src/models/list-filter/scenes.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: feature

#4832 New scene select with additional fields
  ui/v2.5/graphql/data/scene.graphql
  ui/v2.5/graphql/queries/scene.graphql
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneMergeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneSelect.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Shared/ReassignFilesDialog.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/pluginApi.d.ts
Labels: feature

#4842 Return 401 code for `ErrUnauthorized` errors
  internal/api/authentication.go
Labels: bug

#4836 feat: Make DLNA port configurable
  graphql/schema/types/config.graphql
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_query_configuration.go
  internal/dlna/service.go
  internal/manager/config/config.go
  internal/manager/config/config_concurrency_test.go
  ui/v2.5/graphql/data/config.graphql
  ui/v2.5/src/components/Settings/SettingsServicesPanel.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#4854 Fix values being reset when changing mode
  ui/v2.5/src/components/Images/EditImagesDialog.tsx
  ui/v2.5/src/components/Scenes/EditScenesDialog.tsx
Labels: bug

#4852 Warn if ffmpeg lacks codecs
  internal/manager/init.go
  pkg/ffmpeg/ffmpeg.go
Labels: bug

#4840 Add scenes filter to galleries
  graphql/schema/types/filters.graphql
  pkg/models/gallery.go
  pkg/scraper/stashbox/graphql/generated_models.go
  pkg/sqlite/gallery.go
  ui/v2.5/src/components/List/Filters/LabeledIdFilter.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/scenes.ts
  ui/v2.5/src/models/list-filter/galleries.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: feature

#4851 Add additional fields and restyle Movie select and Gallery select
  pkg/sqlite/movies.go
  ui/v2.5/graphql/data/gallery.graphql
  ui/v2.5/graphql/data/movie-slim.graphql
  ui/v2.5/src/components/Galleries/GallerySelect.tsx
  ui/v2.5/src/components/Galleries/styles.scss
  ui/v2.5/src/components/Movies/MovieSelect.tsx
  ui/v2.5/src/components/Movies/styles.scss
  ui/v2.5/src/components/Scenes/SceneSelect.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog/ScrapedObjectsRow.tsx
Labels: improvement

#4835 update popover delay
  ui/v2.5/src/components/Shared/HoverPopover.tsx
Labels: improvement

#4855 Default SetCoverImage to true in identify
  internal/identify/identify.go
Labels: bug

#4113 Add scan option to force gallery zip rescan
  graphql/schema/types/metadata.graphql
  internal/manager/config/tasks.go
  internal/manager/task_scan.go
  pkg/file/scan.go
  ui/v2.5/graphql/data/config.graphql
Labels: feature

#4845 Replace viper with koanf
  cmd/stash/main.go
  go.mod
  go.sum
  graphql/schema/schema.graphql
  internal/manager/config/config.go
  internal/manager/config/config_concurrency_test.go
  internal/manager/config/config_test.go
  internal/manager/config/init.go
  internal/manager/config/map.go
  internal/manager/config/map_test.go
  pkg/sqlite/database.go
  pkg/sqlite/migrations/58_config_correct.up.sql
  pkg/sqlite/migrations/58_postmigrate.go
  ui/v2.5/src/components/Settings/Tasks/LibraryTasks.tsx
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/docs/en/MigrationNotes/58.md
  ui/v2.5/src/docs/en/MigrationNotes/index.ts
Labels: bug, chore

#4864 Fix python not being resolved correctly if not in path
  pkg/plugin/config.go
  pkg/python/exec.go
Labels: bug

#4865 Enforce whitelist for sort values (CVE-2024-32231)
  graphql/schema/types/filters.graphql
  pkg/sqlite/file.go
  pkg/sqlite/gallery.go
  pkg/sqlite/image.go
  pkg/sqlite/movies.go
  pkg/sqlite/performer.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_marker.go
  pkg/sqlite/sql.go
  pkg/sqlite/studio.go
  pkg/sqlite/tag.go
Labels: bug

#4866 Change umask when creating config file to exclude user write (CVE-2024-32233)
  internal/manager/config/config.go
Labels: bug

#4867 Add JS plugin name to the log line prefix
  pkg/javascript/log.go
  pkg/plugin/js.go
Labels: improvement

#4868 Fix setting pointers corrupting config in memory
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_mutation_plugin.go
  internal/desktop/systray_nonlinux.go
  internal/manager/config/config.go
  internal/manager/config/config_concurrency_test.go
  internal/manager/manager.go
  pkg/sqlite/migrations/45_postmigrate.go
  pkg/sqlite/migrations/58_postmigrate.go
Labels: bug

#4869 Fix inconsistent field names in javascript plugin hooks
  pkg/javascript/vm.go
  pkg/plugin/js.go
Labels: bug

#4870 Fix corrupted frontPageContent keys during migration
  pkg/sqlite/migrations/58_postmigrate.go
  pkg/utils/map.go
  pkg/utils/map_test.go
Labels: bug

#4872 Apply scraped tag exclusions galleries and performers
  internal/api/resolver_query_scraper.go
Labels: bug

#4874 Add polyfill for EventTarget constructor
  ui/v2.5/package.json
  ui/v2.5/src/polyfills.ts
  ui/v2.5/yarn.lock
Labels: bug

#4875 Add v0.26.0 changelog
  ui/v2.5/src/components/Changelog/Changelog.tsx
  ui/v2.5/src/docs/en/Changelog/v0260.md
Labels: chore

#4887 Delete .github/FUNDING.yml
  .github/FUNDING.yml
Labels: chore

#4894 Fix SQL error when querying performers with missing aliases
  pkg/sqlite/performer.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/setup_test.go
Labels: bug

#4895 Fix relevance sorting when name/alias contains leading spaces
  ui/v2.5/src/utils/query.ts
Labels: bug

#4896 Fix operations not using effective filter on sub-view pages
  ui/v2.5/src/components/List/ItemList.tsx
Labels: bug

#4873 Default create missing to true in Identify
  ui/v2.5/src/components/Dialogs/IdentifyDialog/IdentifyDialog.tsx
  ui/v2.5/src/docs/en/Manual/Identify.md
Labels: improvement

#4899 Fix ffmpeg resolution when in current directory
  internal/api/resolver_mutation_configure.go
  internal/manager/config/config.go
  internal/manager/init.go
  pkg/plugin/plugins.go
Labels: bug

#4902 Tweak relevant sort algorithm
  ui/v2.5/src/utils/query.ts
Labels: bug

#4903 Support patching select sorting function
  ui/v2.5/src/components/Galleries/GallerySelect.tsx
  ui/v2.5/src/components/Movies/MovieSelect.tsx
  ui/v2.5/src/components/Performers/PerformerSelect.tsx
  ui/v2.5/src/components/Scenes/SceneSelect.tsx
  ui/v2.5/src/components/Studios/StudioSelect.tsx
  ui/v2.5/src/components/Tags/TagSelect.tsx
  ui/v2.5/src/docs/en/Manual/UIPluginApi.md
  ui/v2.5/src/patch.tsx
Labels: improvement
