Repository stashapp/stash, pull requests merged in 2024-06, with the labels that each got.

#4909 Set config file when provided
  internal/manager/config/init.go
Labels: bug

#4931 Fix reading task defaults
  internal/manager/config/config.go
Labels: bug

#4934 Fix hwCanFullHWTranscode not detecting no filter errors
  pkg/ffmpeg/codec_hardware.go
  pkg/ffmpeg/stream_segmented.go
  pkg/ffmpeg/stream_transcode.go
Labels: bug

#4921 Update manual documentation
  ui/v2.5/src/docs/en/Manual/AutoTagging.md
  ui/v2.5/src/docs/en/Manual/Browsing.md
  ui/v2.5/src/docs/en/Manual/Configuration.md
  ui/v2.5/src/docs/en/Manual/EmbeddedPlugins.md
  ui/v2.5/src/docs/en/Manual/ExternalPlugins.md
  ui/v2.5/src/docs/en/Manual/Introduction.md
  ui/v2.5/src/docs/en/Manual/JSONSpec.md
  ui/v2.5/src/docs/en/Manual/Plugins.md
  ui/v2.5/src/docs/en/Manual/SceneFilenameParser.md
  ui/v2.5/src/docs/en/Manual/ScraperDevelopment.md
  ui/v2.5/src/docs/en/Manual/Scraping.md
  ui/v2.5/src/docs/en/Manual/Tagger.md
  ui/v2.5/src/docs/en/Manual/Tasks.md
Labels: documentation

#4943 Fix tag display issue in performer scrape dialog
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
Labels: bug

#4944 Add console javascript object for backwards compatibility
  pkg/javascript/console.go
  pkg/javascript/vm.go
Labels: bug

#4953 Fix studio selection in scraping dialogs
  ui/v2.5/src/components/Shared/ScrapeDialog/ScrapedObjectsRow.tsx
Labels: bug

#4946 Fix typos in docs (en)
  ui/v2.5/src/docs/en/Changelog/v0200.md
  ui/v2.5/src/docs/en/Manual/Configuration.md
  ui/v2.5/src/docs/en/Manual/Introduction.md
  ui/v2.5/src/docs/en/ReleaseNotes/v0240.md
Labels: documentation

#4822 Update to Go 1.22
  .github/workflows/build.yml
  .github/workflows/golangci-lint.yml
  Makefile
  docker/build/x86_64/Dockerfile
  docker/build/x86_64/Dockerfile-CUDA
  docker/compiler/Dockerfile
  docker/compiler/Makefile
  go.mod
  go.sum
Labels: chore

#4861 Add related object filter criteria to various filter types in graphql schema
  graphql/schema/types/filters.graphql
  pkg/match/cache.go
  pkg/models/filter.go
  pkg/models/gallery.go
  pkg/models/image.go
  pkg/models/movie.go
  pkg/models/performer.go
  pkg/models/scene.go
  pkg/models/scene_marker.go
  pkg/models/studio.go
  pkg/models/tag.go
  pkg/sqlite/blob.go
  pkg/sqlite/criterion_handlers.go
  pkg/sqlite/database.go
  pkg/sqlite/file.go
  pkg/sqlite/filter.go
  pkg/sqlite/gallery.go
  pkg/sqlite/gallery_filter.go
  pkg/sqlite/gallery_test.go
  pkg/sqlite/image.go
  pkg/sqlite/image_filter.go
  pkg/sqlite/image_test.go
  pkg/sqlite/movies.go
  pkg/sqlite/movies_filter.go
  pkg/sqlite/performer.go
  pkg/sqlite/performer_filter.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/repository.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_filter.go
  pkg/sqlite/scene_marker.go
  pkg/sqlite/scene_marker_filter.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/sql.go
  pkg/sqlite/studio.go
  pkg/sqlite/studio_filter.go
  pkg/sqlite/studio_test.go
  pkg/sqlite/table.go
  pkg/sqlite/tag.go
  pkg/sqlite/tag_filter.go
  pkg/sqlite/tx.go
Labels: feature

#4882 Make pagination more compact
  ui/v2.5/src/components/List/Pagination.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/index.scss
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#4893 Validate custom locale and javascript strings
  ui/v2.5/src/components/Settings/Inputs.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#4900 Movie URLs
  graphql/schema/types/movie.graphql
  graphql/schema/types/scraped-movie.graphql
  internal/api/resolver_model_movie.go
  internal/api/resolver_mutation_movie.go
  internal/manager/task_export.go
  pkg/models/jsonschema/movie.go
  pkg/models/mocks/MovieReaderWriter.go
  pkg/models/model_movie.go
  pkg/models/model_scraped_item.go
  pkg/models/repository_movie.go
  pkg/movie/export.go
  pkg/movie/export_test.go
  pkg/movie/import.go
  pkg/scraper/movie.go
  pkg/sqlite/anonymise.go
  pkg/sqlite/criterion_handlers.go
  pkg/sqlite/database.go
  pkg/sqlite/gallery_filter.go
  pkg/sqlite/image_filter.go
  pkg/sqlite/migrations/59_movie_urls.up.sql
  pkg/sqlite/movies.go
  pkg/sqlite/movies_filter.go
  pkg/sqlite/movies_test.go
  pkg/sqlite/performer_filter.go
  pkg/sqlite/scene_filter.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/studio_filter.go
  pkg/sqlite/tables.go
  pkg/sqlite/tag_filter.go
  ui/v2.5/graphql/data/movie.graphql
  ui/v2.5/graphql/data/scrapers.graphql
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieEditPanel.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieScrapeDialog.tsx
  ui/v2.5/src/components/Shared/ExternalLinksButton.tsx
  ui/v2.5/src/components/Shared/styles.scss
Labels: feature

#4910 Allow SSL cert paths to be specified in config
  internal/manager/config/config.go
Labels: feature

#4922 Scraper inputs
  pkg/scraper/cache.go
  pkg/scraper/json.go
  pkg/scraper/script.go
  pkg/scraper/stash.go
Labels: improvement

#4924 Correct Stash box endpoint inputs
  graphql/schema/types/scraper.graphql
  graphql/schema/types/stash-box.graphql
  internal/api/resolver_mutation_stash_box.go
  internal/api/resolver_query_scraper.go
  internal/api/stash_box.go
  internal/manager/manager_tasks.go
  pkg/scraper/stashbox/stash_box.go
  ui/v2.5/src/components/Dialogs/SubmitDraft.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerStashBoxModal.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Tagger/constants.ts
  ui/v2.5/src/components/Tagger/context.tsx
  ui/v2.5/src/components/Tagger/performers/PerformerTagger.tsx
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/scenes/sceneTaggerModals.tsx
  ui/v2.5/src/components/Tagger/studios/StudioTagger.tsx
  ui/v2.5/src/core/StashService.ts
Labels: chore

#4935 Plugin api improvements
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Settings/Inputs.tsx
  ui/v2.5/src/components/Settings/SettingsPluginsPanel.tsx
  ui/v2.5/src/docs/en/Manual/UIPluginApi.md
  ui/v2.5/src/pluginApi.d.ts
  ui/v2.5/src/pluginApi.tsx
Labels: improvement

#4937 Add log and utils modules to the Javascript VM used in scrapers
  pkg/scraper/mapped.go
Labels: improvement

#4925 Bulk edit tags
  graphql/schema/schema.graphql
  graphql/schema/types/tag.graphql
  internal/api/resolver_model_tag.go
  internal/api/resolver_mutation_tag.go
  pkg/models/mocks/TagReaderWriter.go
  pkg/models/model_tag.go
  pkg/models/relationships.go
  pkg/models/repository_tag.go
  pkg/sqlite/tables.go
  pkg/sqlite/tag.go
  pkg/tag/update.go
  pkg/tag/update_test.go
  pkg/tag/validate.go
  ui/v2.5/graphql/mutations/tag.graphql
  ui/v2.5/src/components/Tags/EditTagsDialog.tsx
  ui/v2.5/src/components/Tags/TagList.tsx
  ui/v2.5/src/core/StashService.ts
Labels: feature

#4947 In performer scrapers, forward non-http single performer images
  pkg/models/model_scraped_item.go
  pkg/scraper/image.go
Labels: bug

#4962 Default view filters
  go.mod
  graphql/schema/schema.graphql
  internal/api/resolver_mutation_saved_filter.go
  internal/api/resolver_query_find_saved_filter.go
  pkg/models/saved_filter.go
  pkg/sqlite/database.go
  pkg/sqlite/migrations/60_default_filter_move.up.sql
  pkg/sqlite/migrations/60_postmigrate.go
  pkg/sqlite/saved_filter.go
  pkg/sqlite/saved_filter_test.go
  ui/v2.5/graphql/client-schema.graphql
  ui/v2.5/graphql/mutations/filter.graphql
  ui/v2.5/graphql/queries/filter.graphql
  ui/v2.5/src/components/Galleries/Galleries.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryImagesPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryList.tsx
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/components/Images/Images.tsx
  ui/v2.5/src/components/List/ItemList.tsx
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/List/SavedFilterList.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/components/List/util.ts
  ui/v2.5/src/components/List/views.ts
  ui/v2.5/src/components/Movies/MovieDetails/MovieScenesPanel.tsx
  ui/v2.5/src/components/Movies/MovieList.tsx
  ui/v2.5/src/components/Movies/Movies.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerGalleriesPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerImagesPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerMoviesPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScenesPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/performerAppearsWithPanel.tsx
  ui/v2.5/src/components/Performers/PerformerList.tsx
  ui/v2.5/src/components/Performers/Performers.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Scenes/SceneMarkerList.tsx
  ui/v2.5/src/components/Scenes/Scenes.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioChildrenPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioGalleriesPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioImagesPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioMoviesPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioPerformersPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioScenesPanel.tsx
  ui/v2.5/src/components/Studios/StudioList.tsx
  ui/v2.5/src/components/Studios/Studios.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagGalleriesPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagImagesPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagMarkersPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagPerformersPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagScenesPanel.tsx
  ui/v2.5/src/components/Tags/TagList.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/core/createClient.ts
  ui/v2.5/src/docs/en/MigrationNotes/60.md
  ui/v2.5/src/docs/en/MigrationNotes/index.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/models/sceneQueue.ts
  ui/v2.5/src/pluginApi.d.ts
Labels: improvement

#4958 Performer urls
  graphql/schema/types/performer.graphql
  graphql/schema/types/scraped-performer.graphql
  internal/api/resolver_model_performer.go
  internal/api/resolver_mutation_performer.go
  internal/manager/task/migrate.go
  pkg/models/jsonschema/performer.go
  pkg/models/mocks/PerformerReaderWriter.go
  pkg/models/model_performer.go
  pkg/models/model_scraped_item.go
  pkg/models/model_scraped_item_test.go
  pkg/models/performer.go
  pkg/models/repository_performer.go
  pkg/performer/export.go
  pkg/performer/export_test.go
  pkg/performer/import.go
  pkg/performer/url.go
  pkg/scraper/json.go
  pkg/scraper/performer.go
  pkg/scraper/postprocessing.go
  pkg/scraper/scraper.go
  pkg/scraper/stashbox/stash_box.go
  pkg/scraper/xpath.go
  pkg/sqlite/anonymise.go
  pkg/sqlite/database.go
  pkg/sqlite/migrations/62_performer_urls.up.sql
  pkg/sqlite/performer.go
  pkg/sqlite/performer_filter.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/tables.go
  pkg/utils/url.go
  pkg/utils/url_test.go
  ui/v2.5/graphql/data/performer-slim.graphql
  ui/v2.5/graphql/data/performer.graphql
  ui/v2.5/graphql/data/scrapers.graphql
  ui/v2.5/src/components/Performers/EditPerformersDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeDialog.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScrapeModal.tsx
  ui/v2.5/src/components/Shared/ExternalLinksButton.tsx
  ui/v2.5/src/components/Tagger/PerformerModal.tsx
  ui/v2.5/src/components/Tagger/constants.ts
  ui/v2.5/src/components/Tagger/styles.scss
  ui/v2.5/src/core/performers.ts
  ui/v2.5/src/models/list-filter/criteria/is-missing.ts
  ui/v2.5/src/utils/text.ts
Labels: feature

#4858 Add tags to studios
  graphql/schema/types/filters.graphql
  graphql/schema/types/studio.graphql
  graphql/schema/types/tag.graphql
  internal/api/resolver_model_studio.go
  internal/api/resolver_model_tag.go
  internal/api/resolver_mutation_studio.go
  internal/manager/task_export.go
  internal/manager/task_import.go
  pkg/models/jsonschema/studio.go
  pkg/models/mocks/StudioReaderWriter.go
  pkg/models/mocks/TagReaderWriter.go
  pkg/models/model_studio.go
  pkg/models/repository_studio.go
  pkg/models/repository_tag.go
  pkg/models/studio.go
  pkg/models/tag.go
  pkg/sqlite/database.go
  pkg/sqlite/migrations/63_studio_tags.up.sql
  pkg/sqlite/setup_test.go
  pkg/sqlite/studio.go
  pkg/sqlite/studio_filter.go
  pkg/sqlite/studio_test.go
  pkg/sqlite/tables.go
  pkg/sqlite/tag.go
  pkg/sqlite/tag_filter.go
  pkg/sqlite/tag_test.go
  pkg/studio/export_test.go
  pkg/studio/import.go
  pkg/studio/import_test.go
  pkg/studio/query.go
  ui/v2.5/graphql/data/studio-slim.graphql
  ui/v2.5/graphql/data/studio.graphql
  ui/v2.5/graphql/data/tag.graphql
  ui/v2.5/src/components/Shared/PopoverCountButton.tsx
  ui/v2.5/src/components/Shared/TagLink.tsx
  ui/v2.5/src/components/Studios/StudioCard.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioDetailsPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/components/Tags/TagCard.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagStudiosPanel.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/criteria/tags.ts
  ui/v2.5/src/models/list-filter/galleries.ts
  ui/v2.5/src/models/list-filter/images.ts
  ui/v2.5/src/models/list-filter/movies.ts
  ui/v2.5/src/models/list-filter/scenes.ts
  ui/v2.5/src/models/list-filter/studios.ts
  ui/v2.5/src/models/list-filter/tags.ts
  ui/v2.5/src/models/list-filter/types.ts
  ui/v2.5/src/utils/navigation.ts
Labels: feature, bounty

#4993 Fix identify clearing parent studio when merging
  internal/identify/studio.go
  internal/manager/task_stash_box_tag.go
  pkg/models/model_scraped_item.go
  pkg/models/model_scraped_item_test.go
Labels: bug

#4994 Fix join function for studio scenes_filter handler
  pkg/sqlite/studio_filter.go
Labels: bug

#5000 Fix key for tagger scenes
  ui/v2.5/src/components/Tagger/scenes/SceneTagger.tsx
Labels: bug

#4999 Fix save default filter not clearing criteria
  ui/v2.5/src/components/List/SavedFilterList.tsx
Labels: bug

#4992 Add schema migration to fix view_date format
  pkg/sqlite/database.go
  pkg/sqlite/migrations/64_fixes.up.sql
  pkg/sqlite/migrations/64_postmigrate.go
Labels: bug

#4986 Add apple encoder and fix extra_hw_frames bug
  pkg/ffmpeg/codec_hardware.go
  pkg/ffmpeg/ffmpeg.go
  pkg/ffmpeg/ffmpeg_test.go
  pkg/ffmpeg/filter.go
  pkg/ffmpeg/stream_segmented.go
  pkg/ffmpeg/stream_transcode.go
Labels: bug

#5005 Added path column to tables in list view
  ui/v2.5/src/components/Galleries/GalleryListTable.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/components/Scenes/SceneListTable.tsx
Labels: improvement

#5014 Fix scene marker query
  pkg/sqlite/scene_marker.go
  pkg/sqlite/scene_marker_test.go
Labels: bug

#5004 Address resize loop
  ui/v2.5/src/components/Shared/GridCard/GridCard.tsx
Labels: bug

#5019 Check for null disambiguation on validate
  pkg/performer/validate.go
  pkg/performer/validate_test.go
Labels: bug
