Repository stashapp/stash, pull requests merged in 2024-12, with the labels that each got.

#5521 Hide legacy groups criterion option
  ui/v2.5/src/components/List/EditFilterDialog.tsx
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/groups.ts
Labels: bug

#5522 Fix scraped tags issues
  ui/v2.5/src/hooks/tagsEdit.tsx
Labels: bug

#5523 Fix UI plugin race conditions
  ui/v2.5/src/App.tsx
  ui/v2.5/src/hooks/useScript.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/plugins.tsx
Labels: bug

#5487 Performer custom fields
  graphql/schema/types/filters.graphql
  graphql/schema/types/metadata.graphql
  graphql/schema/types/performer.graphql
  internal/api/json.go
  internal/api/json_test.go
  internal/api/loaders/customfieldsloader_gen.go
  internal/api/loaders/dataloaders.go
  internal/api/resolver_model_performer.go
  internal/api/resolver_mutation_configure.go
  internal/api/resolver_mutation_performer.go
  internal/autotag/integration_test.go
  internal/identify/performer.go
  internal/identify/performer_test.go
  internal/manager/task_stash_box_tag.go
  pkg/gallery/import.go
  pkg/gallery/import_test.go
  pkg/image/import.go
  pkg/image/import_test.go
  pkg/models/custom_fields.go
  pkg/models/filter.go
  pkg/models/jsonschema/performer.go
  pkg/models/mocks/PerformerReaderWriter.go
  pkg/models/model_performer.go
  pkg/models/performer.go
  pkg/models/repository_performer.go
  pkg/performer/export.go
  pkg/performer/export_test.go
  pkg/performer/import.go
  pkg/performer/import_test.go
  pkg/scene/import.go
  pkg/scene/import_test.go
  pkg/sqlite/anonymise.go
  pkg/sqlite/custom_fields.go
  pkg/sqlite/custom_fields_test.go
  pkg/sqlite/database.go
  pkg/sqlite/filter.go
  pkg/sqlite/migrations/71_custom_fields.up.sql
  pkg/sqlite/performer.go
  pkg/sqlite/performer_filter.go
  pkg/sqlite/performer_test.go
  pkg/sqlite/query.go
  pkg/sqlite/repository.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/tables.go
  pkg/utils/json.go
  pkg/utils/map.go
  pkg/utils/map_test.go
  ui/v2.5/graphql/data/performer.graphql
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Shared/CollapseButton.tsx
  ui/v2.5/src/components/Shared/CustomFields.tsx
  ui/v2.5/src/components/Shared/DetailItem.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#5528 Add PerformerSelect as loadable component
  pkg/plugin/examples/react-component/src/testReact.tsx
  ui/v2.5/src/pluginApi.tsx
Labels: chore

#5529 docs: update ScraperDevelopment.md
  ui/v2.5/src/docs/en/Manual/ScraperDevelopment.md
Labels: documentation
