Repository stashapp/stash, pull requests merged in 2024-11, with the labels that each got.

#5311 Markers can have end time
  graphql/schema/types/scene-marker.graphql
  internal/api/resolver_mutation_scene.go
  pkg/models/model_scene_marker.go
  pkg/sqlite/database.go
  pkg/sqlite/migrations/70_markers_end.up.sql
  pkg/sqlite/scene_marker.go
  ui/v2.5/graphql/data/scene-marker.graphql
  ui/v2.5/graphql/mutations/scene-marker.graphql
  ui/v2.5/src/components/Scenes/SceneDetails/PrimaryTags.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkerForm.tsx
  ui/v2.5/src/components/Wall/WallItem.tsx
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/utils/text.ts
Labels: feature

#5431 Sub second marker timestamp precision
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkerForm.tsx
  ui/v2.5/src/components/Shared/DurationInput.tsx
  ui/v2.5/src/utils/text.ts
Labels: feature

#5437 Setting marker end time with clock button uses full precision
  ui/v2.5/src/components/Scenes/SceneDetails/SceneMarkerForm.tsx
Labels: bug

#5459 Refactor setup wizard to fix text input
  ui/v2.5/src/components/Setup/Setup.tsx
  ui/v2.5/src/components/Setup/styles.scss
  ui/v2.5/src/locales/en-GB.json
Labels: bug

#5462 Fix scraped tag name being used in matched scraped tags field
  ui/v2.5/src/components/Shared/ScrapeDialog/ScrapedObjectsRow.tsx
Labels: bug

#5461 Fix video files with identical phashes being merged during scan
  pkg/file/scan.go
  pkg/models/fingerprint.go
  pkg/scene/scan.go
Labels: bug

#5465 Maintain saved filters in full export/import
  internal/manager/json_utils.go
  internal/manager/task_export.go
  internal/manager/task_import.go
  pkg/models/jsonschema/load.go
  pkg/models/jsonschema/saved_filter.go
  pkg/models/paths/paths_json.go
  pkg/savedfilter/export.go
  pkg/savedfilter/export_test.go
  pkg/savedfilter/import.go
  pkg/savedfilter/import_test.go
  ui/v2.5/src/components/Settings/Tasks/DataManagementTasks.tsx
Labels: bug

#5476 Lint fixes
  .github/workflows/golangci-lint.yml
  pkg/sqlite/criterion_handlers.go
  pkg/sqlite/gallery_filter.go
  pkg/utils/vtt.go
Labels: chore

#5474 Fix stash scraper errors and add apikey field
  go.mod
  go.sum
  pkg/plugin/examples/common/graphql.go
  pkg/plugin/util/client.go
  pkg/scraper/config.go
  pkg/scraper/graphql.go
  pkg/scraper/image.go
  pkg/scraper/stash.go
  ui/v2.5/src/docs/en/Manual/ScraperDevelopment.md
Labels: bug, feature

#5496 Convert json numbers to numbers in JSON inputs
  internal/api/resolver_mutation_configure.go
  pkg/utils/json.go
  pkg/utils/map.go
  pkg/utils/map_test.go
Labels: bug

#5497 Validate tagger blacklist entries
  ui/v2.5/src/components/Tagger/scenes/Config.tsx
  ui/v2.5/src/components/Tagger/utils.ts
  ui/v2.5/src/locales/en-GB.json
Labels: bug, improvement

#5493 Update tripwire link
  internal/api/authentication.go
  internal/manager/config/config.go
  pkg/session/authentication.go
Labels: documentation

#5507 Tagger preview scrubber and thumbnail
  ui/v2.5/src/components/Tagger/scenes/SceneTagger.tsx
  ui/v2.5/src/components/Tagger/scenes/TaggerScene.tsx
  ui/v2.5/src/components/Tagger/styles.scss
Labels: bug

#5472 Scene Marker duration filter and sort
  graphql/schema/types/filters.graphql
  pkg/models/scene_marker.go
  pkg/sqlite/scene_marker.go
  pkg/sqlite/scene_marker_filter.go
  pkg/sqlite/scene_marker_test.go
  pkg/sqlite/setup_test.go
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/scene-markers.ts
Labels: feature

#5443 Scene Marker grid view
  graphql/schema/schema.graphql
  internal/api/resolver_mutation_scene.go
  ui/v2.5/graphql/data/scene-marker.graphql
  ui/v2.5/graphql/mutations/scene-marker.graphql
  ui/v2.5/src/components/Scenes/DeleteSceneMarkersDialog.tsx
  ui/v2.5/src/components/Scenes/PreviewScrubber.tsx
  ui/v2.5/src/components/Scenes/SceneMarkerCard.tsx
  ui/v2.5/src/components/Scenes/SceneMarkerCardsGrid.tsx
  ui/v2.5/src/components/Scenes/SceneMarkerList.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Settings/Tasks/GenerateOptions.tsx
  ui/v2.5/src/components/Shared/TagLink.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/scene-markers.ts
  ui/v2.5/src/utils/navigation.ts
Labels: feature
