Repository stashapp/stash, pull requests merged in 2024-07, with the labels that each got.

#5029 updating scrapedPerformerToCreateInput to pass Disambiguation
  ui/v2.5/src/core/performers.ts
Labels: bug

#5030 Add Opus as supported audio for mp4
  pkg/ffmpeg/browser.go
Labels: bug

#5038 Rename movie components to group in UI code
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/FrontPage/Control.tsx
  ui/v2.5/src/components/Groups/EditGroupsDialog.tsx
  ui/v2.5/src/components/Groups/GroupCard.tsx
  ui/v2.5/src/components/Groups/GroupCardGrid.tsx
  ui/v2.5/src/components/Groups/GroupDetails/Group.tsx
  ui/v2.5/src/components/Groups/GroupDetails/GroupCreate.tsx
  ui/v2.5/src/components/Groups/GroupDetails/GroupDetailsPanel.tsx
  ui/v2.5/src/components/Groups/GroupDetails/GroupEditPanel.tsx
  ui/v2.5/src/components/Groups/GroupDetails/GroupScenesPanel.tsx
  ui/v2.5/src/components/Groups/GroupDetails/GroupScrapeDialog.tsx
  ui/v2.5/src/components/Groups/GroupList.tsx
  ui/v2.5/src/components/Groups/GroupRecommendationRow.tsx
  ui/v2.5/src/components/Groups/GroupSelect.tsx
  ui/v2.5/src/components/Groups/Groups.tsx
  ui/v2.5/src/components/Groups/styles.scss
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerGroupsPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneGroupPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneGroupTable.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog/ScrapedObjectsRow.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog/createObjects.ts
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioGroupsPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagGroupsPanel.tsx
  ui/v2.5/src/core/groups.ts
  ui/v2.5/src/index.scss
  ui/v2.5/src/models/list-filter/criteria/groups.ts
  ui/v2.5/src/models/list-filter/factory.ts
  ui/v2.5/src/models/list-filter/groups.ts
  ui/v2.5/src/models/list-filter/scenes.ts
  ui/v2.5/src/models/list-filter/tags.ts
  ui/v2.5/src/utils/navigation.ts
Labels: chore

#5041 Scraper menu filter
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Shared/ScraperMenu.tsx
  ui/v2.5/src/components/Shared/styles.scss
Labels: improvement

#5040 Metadata Providers -> Scraper list improvements
  ui/v2.5/src/components/Settings/SettingsScrapingPanel.tsx
  ui/v2.5/src/components/Settings/styles.scss
  ui/v2.5/src/components/Shared/CollapseButton.tsx
Labels: improvement

#5042 Adds mutex protection around dms.Eventing
  internal/dlna/dms.go
Labels: bug

#5037 Various detail page refactoring
  ui/v2.5/src/components/Groups/GroupDetails/Group.tsx
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Shared/CollapseButton.tsx
  ui/v2.5/src/components/Shared/DetailsPage/AliasList.tsx
  ui/v2.5/src/components/Shared/DetailsPage/BackgroundImage.tsx
  ui/v2.5/src/components/Shared/DetailsPage/DetailTitle.tsx
  ui/v2.5/src/components/Shared/DetailsPage/HeaderImage.tsx
  ui/v2.5/src/components/Shared/DetailsPage/Tabs.tsx
  ui/v2.5/src/components/Shared/ExternalLinksButton.tsx
  ui/v2.5/src/components/Shared/FavoriteIcon.tsx
  ui/v2.5/src/components/Shared/LoadingIndicator.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/components/Studios/StudioCard.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/hooks/Lightbox/LightboxLink.tsx
Labels: chore

#5043 Use the rescan option when rescanning files from menu
  ui/v2.5/src/components/Galleries/GalleryDetails/Gallery.tsx
  ui/v2.5/src/components/Images/ImageDetails/Image.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
Labels: bug

#5044 Rename movie group backend
  internal/api/loaders/grouploader_gen.go
  internal/api/resolver_model_studio.go
  internal/api/resolver_model_tag.go
  internal/api/routes_group.go
  internal/api/urlbuilders/group.go
  internal/manager/task_export.go
  internal/manager/task_import.go
  internal/static/embed.go
  internal/static/group/group.png
  pkg/group/export.go
  pkg/group/export_test.go
  pkg/group/import.go
  pkg/group/import_test.go
  pkg/group/query.go
  pkg/models/group.go
  pkg/models/jsonschema/group.go
  pkg/models/model_group.go
  pkg/models/repository_group.go
  pkg/sqlite/group.go
  pkg/sqlite/group_filter.go
  pkg/sqlite/group_test.go
Labels: chore

#5076 Add birthdate to performer select and restyle
  ui/v2.5/graphql/data/performer-slim.graphql
  ui/v2.5/src/components/Performers/PerformerSelect.tsx
  ui/v2.5/src/components/Performers/styles.scss
Labels: improvement

#5061 Copy apikey query parameter to DASH & HLS manifest
  pkg/ffmpeg/stream_segmented.go
Labels: improvement

#5090 fix missing transgender SVG color
  ui/v2.5/src/components/Performers/styles.scss
Labels: bug

#5102 Allow detection for n-prefixed ffmpeg version string
  pkg/ffmpeg/ffmpeg.go
Labels: bug

#5082 Rename movie tables to groups in database schema
  pkg/sqlite/anonymise.go
  pkg/sqlite/database.go
  pkg/sqlite/group.go
  pkg/sqlite/group_filter.go
  pkg/sqlite/migrations/65_movie_group_rename.up.sql
  pkg/sqlite/scene.go
  pkg/sqlite/scene_filter.go
  pkg/sqlite/table.go
  pkg/sqlite/tag.go
  pkg/sqlite/tag_filter.go
Labels: chore

#5106 Fix bulk scene setting groups
  internal/api/resolver_mutation_scene.go
Labels: bug

#5080 Refactor ItemList code and re-enable viewing sub-tag/studio content
  ui/v2.5/src/components/Galleries/GalleryList.tsx
  ui/v2.5/src/components/Groups/GroupList.tsx
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/components/List/FilterProvider.tsx
  ui/v2.5/src/components/List/FilteredListToolbar.tsx
  ui/v2.5/src/components/List/ItemList.tsx
  ui/v2.5/src/components/List/ListFilter.tsx
  ui/v2.5/src/components/List/ListOperationButtons.tsx
  ui/v2.5/src/components/List/ListProvider.tsx
  ui/v2.5/src/components/List/PagedList.tsx
  ui/v2.5/src/components/List/util.ts
  ui/v2.5/src/components/Performers/PerformerList.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Scenes/SceneMarkerList.tsx
  ui/v2.5/src/components/Shared/FilterSelect.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioChildrenPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioGalleriesPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioGroupsPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioImagesPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioPerformersPanel.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioScenesPanel.tsx
  ui/v2.5/src/components/Studios/StudioList.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagGalleriesPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagGroupsPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagImagesPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagMarkersPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagPerformersPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagScenesPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagStudiosPanel.tsx
  ui/v2.5/src/components/Tags/TagList.tsx
  ui/v2.5/src/core/studios.ts
  ui/v2.5/src/core/tags.ts
  ui/v2.5/src/hooks/modal.ts
  ui/v2.5/src/index.scss
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/utils/bulkUpdate.ts
  ui/v2.5/src/utils/data.ts
Labels: bug, chore
