Repository stashapp/stash, pull requests merged in 2024-01, with the labels that each got.

#4424 Add CSP to plugin from the yaml file
  pkg/plugin/config.go
Labels: bug

#4414 Add join to intCriterionHandler
  pkg/sqlite/filter.go
Labels: bug

#4432 Fix scraped performer alias matching
  pkg/match/scraped.go
Labels: bug

#4420 Fixes package manger head border
  ui/v2.5/src/components/Shared/PackageManager/PackageManager.tsx
  ui/v2.5/src/components/Shared/PackageManager/styles.scss
  ui/v2.5/src/index.scss
Labels: bug

#4428 Scene queue autoplay
  ui/v2.5/src/components/Scenes/SceneDetails/QueueViewer.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/models/sceneQueue.ts
Labels: bug

#4430 Fix settings tab links
  ui/v2.5/src/components/Settings/Settings.tsx
Labels: bug

#4434 Hide select all checkbox for plugin sources
  ui/v2.5/src/components/Settings/ScraperPackageManager.tsx
  ui/v2.5/src/components/Shared/PackageManager/PackageManager.tsx
Labels: improvement

#4435 Sort plugin settings
  pkg/plugin/config.go
Labels: bug

#4412 Update FieldStrategyOverwrite to work when scene has no existing URL
  internal/identify/identify.go
Labels: bug

#4440 Hide the Tag input in the Tagger when Set Tags is disabled
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
Labels: improvement

#4441 Calculate DetailImage fallback width using rem
  ui/v2.5/src/components/Shared/DetailImage.tsx
  ui/v2.5/src/utils/units.ts
Labels: bug

#4442 Don't bail on error when scraping all
  ui/v2.5/src/components/Tagger/context.tsx
  ui/v2.5/src/hooks/Toast.tsx
  ui/v2.5/src/utils/errors.ts
Labels: bug

#4443 Fix error when creating/updating performer with alias == name
  internal/manager/task_stash_box_tag.go
  pkg/scraper/stashbox/stash_box.go
Labels: bug

#4446 Fix generated marker files rename error when merging scenes
  pkg/scene/merge.go
Labels: bug

#4450 Don't retry failed autoplay
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: bug

#4454 Fix studio name uniqueness validation
  internal/api/resolver_mutation_studio.go
  internal/manager/task_stash_box_tag.go
  pkg/studio/validate.go
  pkg/studio/validate_test.go
Labels: bug

#4404 added support for image orientation filter
  graphql/schema/types/filters.graphql
  pkg/models/filter.go
  pkg/models/image.go
  pkg/models/orientation.go
  pkg/models/scene.go
  pkg/sqlite/criterion_handlers.go
  pkg/sqlite/image.go
  pkg/sqlite/scene.go
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/criteria/orientation.ts
  ui/v2.5/src/models/list-filter/images.ts
  ui/v2.5/src/models/list-filter/scenes.ts
  ui/v2.5/src/models/list-filter/types.ts
  ui/v2.5/src/utils/orientation.ts
Labels: feature

#4448 Improved scene queue
  ui/v2.5/src/components/Scenes/SceneDetails/QueueViewer.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/models/sceneQueue.ts
Labels: improvement

#4419 Update Performer gender filter
  graphql/schema/types/filters.graphql
  pkg/models/performer.go
  pkg/sqlite/performer.go
  ui/v2.5/src/models/list-filter/criteria/circumcised.ts
  ui/v2.5/src/models/list-filter/criteria/gender.ts
Labels: improvement

#4374 Move zip files while moving folders
  pkg/file/folder.go
  pkg/file/move.go
  pkg/file/scan.go
Labels: improvement

#4416 Add support for disabling mobile media-viewer's fullscreen auto-rotate
  pkg/sqlite/setup_test.go
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/fr-FR.json
  ui/v2.5/src/locales/sv-SE.json
Labels: feature

#4378 Advanced settings
  ui/v2.5/src/components/Dialogs/GenerateDialog.tsx
  ui/v2.5/src/components/Settings/Inputs.tsx
  ui/v2.5/src/components/Settings/SettingSection.tsx
  ui/v2.5/src/components/Settings/Settings.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/components/Settings/SettingsSystemPanel.tsx
  ui/v2.5/src/components/Settings/Tasks/DataManagementTasks.tsx
  ui/v2.5/src/components/Settings/Tasks/GenerateOptions.tsx
  ui/v2.5/src/components/Settings/Tasks/LibraryTasks.tsx
  ui/v2.5/src/components/Settings/Tasks/ScanOptions.tsx
  ui/v2.5/src/components/Settings/context.tsx
  ui/v2.5/src/components/Settings/styles.scss
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#4368 Improved list view for scenes, galleries and performers
  ui/v2.5/src/components/Galleries/GalleryList.tsx
  ui/v2.5/src/components/Galleries/GalleryListTable.tsx
  ui/v2.5/src/components/List/ListTable.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerList.tsx
  ui/v2.5/src/components/Performers/PerformerListTable.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Scenes/SceneListTable.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/hooks/useTableColumns.ts
  ui/v2.5/src/index.scss
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/utils/navigation.ts
Labels: improvement, ui

#4468 Clarify session setting description
  ui/v2.5/src/locales/en-GB.json
Labels: i18n

#4509 Minor UI fixes
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Settings/Inputs.tsx
  ui/v2.5/src/components/Shared/styles.scss
  ui/v2.5/src/components/Tagger/performers/PerformerTagger.tsx
Labels: bug

#4515 Only use details background image when provided
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
Labels: improvement
