Repository stashapp/stash, pull requests merged in 2024-02, with the labels that each got.

#4506 Frontend fix media_err_decode on playback
  ui/v2.5/src/components/ScenePlayer/source-selector.ts
Labels: bug

#4497 Improve list table readability
  ui/v2.5/src/components/Galleries/GalleryListTable.tsx
  ui/v2.5/src/components/List/ListTable.tsx
  ui/v2.5/src/components/List/styles.scss
  ui/v2.5/src/components/Scenes/SceneListTable.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Shared/Select.tsx
Labels: bug, improvement

#4501 Link improvements and fixes
  ui/v2.5/src/components/Dialogs/SubmitDraft.tsx
  ui/v2.5/src/components/Movies/MovieDetails/Movie.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieDetailsPanel.tsx
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Performers/PerformerSelect.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
  ui/v2.5/src/components/Settings/SettingsAboutPanel.tsx
  ui/v2.5/src/components/Settings/SettingsLibraryPanel.tsx
  ui/v2.5/src/components/Settings/SettingsPluginsPanel.tsx
  ui/v2.5/src/components/Settings/SettingsScrapingPanel.tsx
  ui/v2.5/src/components/Settings/styles.scss
  ui/v2.5/src/components/Setup/Migrate.tsx
  ui/v2.5/src/components/Setup/Setup.tsx
  ui/v2.5/src/components/Shared/ExternalLink.tsx
  ui/v2.5/src/components/Shared/StashID.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioDetailsPanel.tsx
  ui/v2.5/src/components/Tagger/PerformerModal.tsx
  ui/v2.5/src/components/Tagger/performers/PerformerTagger.tsx
  ui/v2.5/src/components/Tagger/scenes/PerformerResult.tsx
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/scenes/StudioModal.tsx
  ui/v2.5/src/components/Tagger/scenes/StudioResult.tsx
  ui/v2.5/src/components/Tagger/scenes/TaggerScene.tsx
  ui/v2.5/src/components/Tagger/studios/StudioTagger.tsx
  ui/v2.5/src/index.scss
  ui/v2.5/src/utils/field.tsx
Labels: bug, chore

#4498 Fix login page favicon on Firefox
  ui/login/login.html
Labels: bug

#4526 Fix tag selector in scrape dialogs
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneMergeDialog.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog/ScrapedObjectsRow.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog/createObjects.ts
  ui/v2.5/src/utils/data.ts
Labels: bug

#4493 Studio select refactor
  graphql/documents/data/studio.graphql
  graphql/documents/queries/misc.graphql
  graphql/documents/queries/studio.graphql
  graphql/schema/schema.graphql
  internal/api/resolver_query_find_studio.go
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Movies/MovieDetails/MovieEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneMergeDialog.tsx
  ui/v2.5/src/components/Shared/FilterSelect.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog/ScrapedObjectsRow.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog/createObjects.ts
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioEditPanel.tsx
  ui/v2.5/src/components/Studios/StudioSelect.tsx
  ui/v2.5/src/core/StashService.ts
Labels: improvement

#4489 expose useful libs
  ui/v2.5/src/docs/en/Manual/UIPluginApi.md
  ui/v2.5/src/pluginApi.tsx
Labels: improvement

#4527 Fix UI crash during setup
  ui/v2.5/src/components/Settings/Inputs.tsx
  ui/v2.5/src/components/Settings/context.tsx
Labels: bug

#4480 Support filesize in scene table list
  ui/v2.5/src/components/Scenes/SceneListTable.tsx
Labels: improvement

#4479 Studio child count filter and sort
  graphql/schema/types/filters.graphql
  pkg/models/studio.go
  pkg/sqlite/sql.go
  pkg/sqlite/studio.go
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/studios.ts
Labels: feature

#4528 Improve sorting of results when entering text in select fields
  ui/v2.5/src/components/List/Filters/PerformersFilter.tsx
  ui/v2.5/src/components/List/Filters/StudiosFilter.tsx
  ui/v2.5/src/components/List/Filters/TagsFilter.tsx
  ui/v2.5/src/components/Performers/PerformerSelect.tsx
  ui/v2.5/src/components/Studios/StudioSelect.tsx
  ui/v2.5/src/components/Tags/TagSelect.tsx
  ui/v2.5/src/utils/query.ts
Labels: improvement

#4529 Fix tag popper over card
  ui/v2.5/src/components/Tags/styles.scss
Labels: bug

#4533 Fix UI config mutation not working
  ui/v2.5/graphql/client-schema.graphql
  ui/v2.5/graphql/mutations/config.graphql
  ui/v2.5/src/components/Settings/context.tsx
Labels: bug

#4535 Add gallery select filter and fix image gallery filtering
  graphql/schema/schema.graphql
  internal/api/resolver_query_find_gallery.go
  ui/v2.5/graphql/data/gallery.graphql
  ui/v2.5/graphql/queries/gallery.graphql
  ui/v2.5/src/components/Galleries/GallerySelect.tsx
  ui/v2.5/src/components/Galleries/styles.scss
  ui/v2.5/src/components/List/Filters/LabeledIdFilter.tsx
  ui/v2.5/src/components/List/Filters/PerformersFilter.tsx
  ui/v2.5/src/components/List/Filters/StudiosFilter.tsx
  ui/v2.5/src/components/List/Filters/TagsFilter.tsx
  ui/v2.5/src/components/Performers/PerformerSelect.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneMergeDialog.tsx
  ui/v2.5/src/components/Shared/FilterSelect.tsx
  ui/v2.5/src/components/Shared/Select.tsx
  ui/v2.5/src/components/Studios/StudioSelect.tsx
  ui/v2.5/src/components/Tags/TagSelect.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/models/list-filter/images.ts
  ui/v2.5/src/utils/query.ts
Labels: bug, improvement

#4539 Wrap card popovers
  ui/v2.5/src/components/Scenes/styles.scss
Labels: bug

#4540 Common studio overlay component
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Galleries/GalleryList.tsx
  ui/v2.5/src/components/Images/ImageCard.tsx
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/components/Movies/MovieCard.tsx
  ui/v2.5/src/components/Movies/MovieCardGrid.tsx
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Performers/PerformerCardGrid.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneCardsGrid.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Shared/GridCard/GridCard.tsx
  ui/v2.5/src/components/Shared/GridCard/StudioOverlay.tsx
  ui/v2.5/src/components/Shared/GridCard/styles.scss
  ui/v2.5/src/components/Studios/StudioCard.tsx
  ui/v2.5/src/components/Studios/StudioCardGrid.tsx
  ui/v2.5/src/components/Tags/TagCard.tsx
  ui/v2.5/src/components/Tags/TagCardGrid.tsx
  ui/v2.5/src/index.scss
Labels: bug, chore

#4541 Add disambiguation to performer link and performer select values
  ui/v2.5/graphql/data/scene-slim.graphql
  ui/v2.5/src/components/Performers/PerformerSelect.tsx
  ui/v2.5/src/components/Performers/styles.scss
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Shared/PerformerPopoverButton.tsx
  ui/v2.5/src/components/Shared/TagLink.tsx
Labels: improvement

#4546 Plugin api improvements
  ui/v2.5/src/components/Galleries/GallerySelect.tsx
  ui/v2.5/src/components/Performers/PerformerSelect.tsx
  ui/v2.5/src/components/Shared/CountrySelect.tsx
  ui/v2.5/src/components/Shared/DateInput.tsx
  ui/v2.5/src/components/Shared/FolderSelect/FolderSelect.tsx
  ui/v2.5/src/components/Studios/StudioSelect.tsx
  ui/v2.5/src/components/Tags/TagSelect.tsx
  ui/v2.5/src/docs/en/Manual/UIPluginApi.md
  ui/v2.5/src/hooks/Toast.tsx
  ui/v2.5/src/pluginApi.tsx
Labels: chore

#4538 Fix url not updated for default tab on Performer/Studio/Tag pages
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
Labels: bug

#4548 Fix scraped studio not matching existing value
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneQueryModal.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog/ScrapedObjectsRow.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog/createObjects.ts
  ui/v2.5/src/components/Shared/ScrapeDialog/scrapeResult.ts
Labels: bug

#4557 Heatmap fix segment repeating
  internal/manager/generator_interactive_heatmap_speed.go
Labels: bug

#4565 Fix country selector in bulk performer edit dialog
  ui/v2.5/src/components/Performers/EditPerformersDialog.tsx
  ui/v2.5/src/components/Performers/styles.scss
Labels: bug

#4567 Fix merge not deleting deleted scene generated files
  internal/api/resolver_mutation_scene.go
  internal/manager/repository.go
  pkg/scene/merge.go
Labels: bug

#4566 Developer option: extra blob paths
  Makefile
  internal/manager/config/config.go
  internal/manager/manager.go
  pkg/sqlite/blob.go
  pkg/sqlite/blob/fs.go
  ui/v2.5/src/docs/en/Manual/Configuration.md
Labels: feature

#4578 Weblate translations update
  ui/v2.5/src/locales/da-DK.json
  ui/v2.5/src/locales/de-DE.json
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/locales/en-US.json
  ui/v2.5/src/locales/es-ES.json
  ui/v2.5/src/locales/et-EE.json
  ui/v2.5/src/locales/fi-FI.json
  ui/v2.5/src/locales/fr-FR.json
  ui/v2.5/src/locales/hu-HU.json
  ui/v2.5/src/locales/it-IT.json
  ui/v2.5/src/locales/ja-JP.json
  ui/v2.5/src/locales/ko-KR.json
  ui/v2.5/src/locales/nl-NL.json
  ui/v2.5/src/locales/pl-PL.json
  ui/v2.5/src/locales/pt-BR.json
  ui/v2.5/src/locales/ru-RU.json
  ui/v2.5/src/locales/sv-SE.json
  ui/v2.5/src/locales/tr-TR.json
  ui/v2.5/src/locales/zh-CN.json
  ui/v2.5/src/locales/zh-TW.json
Labels: chore

#4581 Update translation files
  ui/v2.5/src/locales/bn-BD.json
  ui/v2.5/src/locales/cs-CZ.json
  ui/v2.5/src/locales/da-DK.json
  ui/v2.5/src/locales/de-DE.json
  ui/v2.5/src/locales/es-ES.json
  ui/v2.5/src/locales/et-EE.json
  ui/v2.5/src/locales/fi-FI.json
  ui/v2.5/src/locales/fr-FR.json
  ui/v2.5/src/locales/hr-HR.json
  ui/v2.5/src/locales/hu-HU.json
  ui/v2.5/src/locales/it-IT.json
  ui/v2.5/src/locales/ja-JP.json
  ui/v2.5/src/locales/ko-KR.json
  ui/v2.5/src/locales/nl-NL.json
  ui/v2.5/src/locales/pl-PL.json
  ui/v2.5/src/locales/pt-BR.json
  ui/v2.5/src/locales/ro-RO.json
  ui/v2.5/src/locales/ru-RU.json
  ui/v2.5/src/locales/sv-SE.json
  ui/v2.5/src/locales/th-TH.json
  ui/v2.5/src/locales/tr-TR.json
  ui/v2.5/src/locales/uk-UA.json
  ui/v2.5/src/locales/zh-CN.json
  ui/v2.5/src/locales/zh-TW.json
Labels: chore

#4584 Toast improvements
  ui/v2.5/src/components/Galleries/GallerySelect.tsx
  ui/v2.5/src/components/MainNavbar.tsx
  ui/v2.5/src/components/Performers/PerformerSelect.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Settings/Inputs.tsx
  ui/v2.5/src/components/Settings/SettingsToolsPanel.tsx
  ui/v2.5/src/components/Shared/CountrySelect.tsx
  ui/v2.5/src/components/Shared/DateInput.tsx
  ui/v2.5/src/components/Shared/FolderSelect/FolderSelect.tsx
  ui/v2.5/src/components/Shared/Icon.tsx
  ui/v2.5/src/components/Studios/StudioSelect.tsx
  ui/v2.5/src/components/Tags/TagSelect.tsx
  ui/v2.5/src/hooks/Toast.tsx
  ui/v2.5/src/index.scss
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/patch.tsx
  ui/v2.5/src/pluginApi.tsx
  ui/v2.5/src/plugins.tsx
Labels: improvement

#4570 Fix invalid share causing error during cleaning
  pkg/file/clean.go
Labels: bug

#4572 Merge studio stash ids when saving in studio tagger
  ui/v2.5/src/components/Tagger/context.tsx
  ui/v2.5/src/components/Tagger/studios/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/studios/StudioTagger.tsx
  ui/v2.5/src/components/Tagger/utils.ts
Labels: bug

#4571 Error if duplicate plugin id is loaded
  pkg/plugin/plugins.go
Labels: bug

#4591 Plugin manager - don't error out if a single source url not fetched
  pkg/pkg/manager.go
Labels: bug

#4573 Add galleries to image edit panel
  ui/v2.5/src/components/Galleries/GallerySelect.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
Labels: feature

#4592 Fix default url not redirecting in studio page
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
Labels: bug

#4593 Default tag hover popover to right
  ui/v2.5/src/components/Tags/TagSelect.tsx
Labels: bug

#4597 Fix 404 not returning immediately in asset handler
  internal/api/routes_plugin.go
Labels: bug

#4595 add pluginApi.d.ts
  ui/v2.5/.eslintrc.json
  ui/v2.5/src/pluginApi.d.ts
Labels: chore

#4588 Movie scene sorting
  pkg/sqlite/scene.go
Labels: bug

#4598 Improve handling of moved and added video files
  internal/manager/manager_tasks.go
  internal/manager/task_generate_phash.go
  internal/manager/task_scan.go
  pkg/file/scan.go
Labels: bug

#4599 Show upgradable packages only when checking for updates
  ui/v2.5/src/components/Settings/PluginPackageManager.tsx
  ui/v2.5/src/components/Settings/ScraperPackageManager.tsx
  ui/v2.5/src/components/Shared/PackageManager/PackageManager.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#4606 Include primary tag name in search and sort
  pkg/sqlite/scene_marker.go
Labels: bug

#4602 Add option to generate image thumbnails during generate
  graphql/schema/types/metadata.graphql
  internal/api/routes_image.go
  internal/manager/init.go
  internal/manager/manager.go
  internal/manager/task_generate.go
  internal/manager/task_generate_image_thumbnail.go
  internal/manager/task_scan.go
  pkg/models/generate.go
  ui/v2.5/graphql/data/config.graphql
  ui/v2.5/src/components/Dialogs/GenerateDialog.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Settings/Tasks/GenerateOptions.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#4603 Plugin API improvements
  graphql/schema/schema.graphql
  internal/api/resolver_mutation_plugin.go
  internal/manager/task_plugin.go
  pkg/plugin/args.go
  pkg/plugin/config.go
  pkg/plugin/convert.go
  pkg/plugin/examples/js/js.js
  pkg/plugin/js.go
  pkg/plugin/plugins.go
  pkg/plugin/raw.go
  pkg/plugin/rpc.go
  ui/v2.5/graphql/mutations/plugins.graphql
  ui/v2.5/src/core/StashService.ts
Labels: feature

#4532 Scene play and o-counter history view and editing
  graphql/schema/schema.graphql
  graphql/schema/types/scene.graphql
  internal/api/loaders/dataloaders.go
  internal/api/loaders/scenelastplayedloader_gen.go
  internal/api/loaders/sceneocountloader_gen.go
  internal/api/loaders/sceneohistoryloader_gen.go
  internal/api/loaders/sceneplaycountloader_gen.go
  internal/api/loaders/sceneplayhistoryloader_gen.go
  internal/api/resolver.go
  internal/api/resolver_model_scene.go
  internal/api/resolver_mutation_scene.go
  internal/api/types.go
  internal/manager/repository.go
  internal/manager/task_export.go
  pkg/models/jsonschema/scene.go
  pkg/models/mocks/SceneReaderWriter.go
  pkg/models/model_scene.go
  pkg/models/relationships.go
  pkg/models/repository_scene.go
  pkg/scene/export.go
  pkg/scene/export_test.go
  pkg/scene/import.go
  pkg/scene/merge.go
  pkg/sliceutil/collections.go
  pkg/sqlite/database.go
  pkg/sqlite/filter.go
  pkg/sqlite/history.go
  pkg/sqlite/image.go
  pkg/sqlite/migrations/55_manual_history.up.sql
  pkg/sqlite/migrations/55_postmigrate.go
  pkg/sqlite/performer.go
  pkg/sqlite/record.go
  pkg/sqlite/repository.go
  pkg/sqlite/scene.go
  pkg/sqlite/scene_test.go
  pkg/sqlite/setup_test.go
  pkg/sqlite/sql.go
  pkg/sqlite/table.go
  pkg/sqlite/tables.go
  pkg/sqlite/timestamp.go
  ui/v2.5/graphql/data/scene.graphql
  ui/v2.5/graphql/mutations/scene.graphql
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneHistoryPanel.tsx
  ui/v2.5/src/components/Scenes/SceneMergeDialog.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/components/Shared/DateInput.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/docs/en/Manual/KeyboardShortcuts.md
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#4608 Support setting galleries in multiple images
  ui/v2.5/src/components/Galleries/GallerySelect.tsx
  ui/v2.5/src/components/Images/EditImagesDialog.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Shared/MultiSet.tsx
  ui/v2.5/src/utils/bulkUpdate.ts
Labels: feature

#4610 Fix auto tag from object not honouring the ignore autotag flag
  internal/manager/task_autotag.go
  ui/v2.5/src/components/Performers/PerformerDetails/Performer.tsx
  ui/v2.5/src/components/Shared/DetailsEditNavbar.tsx
  ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx
  ui/v2.5/src/components/Tags/TagDetails/Tag.tsx
Labels: bug

#4607 Add Clean generated files task
  gqlgen.yml
  graphql/schema/schema.graphql
  graphql/schema/types/metadata.graphql
  internal/api/resolver_mutation_metadata.go
  internal/manager/task/clean_generated.go
  pkg/models/repository.go
  pkg/models/repository_blob.go
  pkg/sqlite/blob.go
  pkg/sqlite/transaction.go
  ui/v2.5/graphql/mutations/metadata.graphql
  ui/v2.5/src/components/Settings/Tasks/CleanGeneratedDialog.tsx
  ui/v2.5/src/components/Settings/Tasks/DataManagementTasks.tsx
  ui/v2.5/src/components/Settings/Tasks/LibraryTasks.tsx
  ui/v2.5/src/core/StashService.ts
  ui/v2.5/src/core/config.ts
  ui/v2.5/src/locales/en-GB.json
Labels: feature

#4492 Implement UI event dispatcher/listener
  pkg/plugin/examples/react-component/src/testReact.tsx
  ui/v2.5/src/App.tsx
  ui/v2.5/src/docs/en/Manual/UIPluginApi.md
  ui/v2.5/src/hooks/event.ts
  ui/v2.5/src/pluginApi.tsx
Labels: feature

#4616 Serve original filename with image
  pkg/models/model_file.go
Labels: improvement

#4626 Add last o sort option
  pkg/sqlite/scene.go
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/src/models/list-filter/scenes.ts
Labels: feature

#4627 Change handlerRequiredFilter to check for .forcegallery
  internal/manager/task_scan.go
Labels: bug

#4618 Improve scene tagger prioritization
  ui/v2.5/src/components/Tagger/scenes/SceneTagger.tsx
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/styles.scss
Labels: improvement

#4630 Fix penis length being incorrectly truncated
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx
Labels: bug

#4637 Use proxy in utils.ReadImageFromURL
  pkg/utils/image.go
Labels: bug

#4122 Adding disambiguation to performer draft
  pkg/scraper/stashbox/graphql/generated_client.go
  pkg/scraper/stashbox/graphql/generated_models.go
  pkg/scraper/stashbox/stash_box.go
Labels: improvement
