Repository stashapp/stash, pull requests merged in 2025-04, with the labels that each got.

#5780 Import/export bug fixes
  internal/manager/task_export.go
  pkg/fsutil/file.go
  pkg/fsutil/file_test.go
  pkg/tag/export.go
Labels: bug

#5798 Log to stdout on exit error
  cmd/stash/main.go
Labels: bug

#5752 Sort tags by name while scraping or merging scenes
  internal/api/resolver_query_find_tag.go
  internal/api/resolver_query_scraper.go
  pkg/models/model_scraped_item.go
  pkg/scraper/tag.go
  pkg/sqlite/tag.go
  pkg/stashbox/graphql/generated_models.go
  ui/v2.5/src/components/Tags/TagSelect.tsx
Labels: improvement

#5791 Partial fix for #2761 - Add reverse proxy prefix to HLS links
  pkg/ffmpeg/stream_segmented.go
Labels: bug

#5800 Fix marker preview deleted when modifying marker with duration
  internal/api/resolver_mutation_scene.go
Labels: bug

#5799 Ignore missing scenes when submitting fingerprints
  internal/api/resolver_mutation_stash_box.go
  internal/manager/repository.go
  pkg/models/mocks/SceneReaderWriter.go
  pkg/models/mocks/query.go
  pkg/models/repository_scene.go
  pkg/scene/find.go
  pkg/sqlite/scene.go
Labels: bug

#5801 Revert dot marker styling changes
  ui/v2.5/src/components/ScenePlayer/markers.css
  ui/v2.5/src/components/ScenePlayer/markers.ts
  ui/v2.5/src/components/ScenePlayer/styles.scss
Labels: bug

#5689 update Dockerfile-CUDA
  docker/build/x86_64/Dockerfile-CUDA
Labels: chore

#5804 Fix range marker alignment
  ui/v2.5/src/components/ScenePlayer/markers.ts
Labels: bug

#5810 Fix to find a match for a parent studio
  pkg/match/scraped.go
Labels: bug

#5820 Add missing group scraper fields
  internal/api/resolver_query_scraper.go
  internal/api/scraped_content.go
  pkg/scraper/config.go
  pkg/scraper/mapped.go
Labels: bug

#5829 Update markdown syntax for Scrapers Development page
  ui/v2.5/src/docs/en/Manual/ScraperDevelopment.md
Labels: documentation

#5846 Update runner image
  .github/workflows/build.yml
Labels: chore
