Repository stashapp/stash, pull requests merged in 2025-01, with the labels that each got.

#5630 docs: Add note about lack of SOCKS5 support
  ui/v2.5/src/docs/en/Manual/Configuration.md
Labels: documentation

#5607 docs: clarify regex case sensitivity
  ui/v2.5/src/docs/en/Manual/Browsing.md
Labels: documentation

#5603 Update Tasks.md
  ui/v2.5/src/docs/en/Manual/Tasks.md
Labels: documentation

#5586 Fix typo in in-app manual
  ui/v2.5/src/docs/en/Manual/Plugins.md
Labels: documentation

#5566 Update PerformerModal.tsx to fix aliases exclusions
  ui/v2.5/src/components/Tagger/PerformerModal.tsx
Labels: bug

#5535 feat: Add ETA for tasks
  ui/v2.5/graphql/subscriptions.graphql
  ui/v2.5/package.json
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Settings/Tasks/JobTable.tsx
  ui/v2.5/src/components/Settings/styles.scss
  ui/v2.5/src/locales/en-GB.json
  ui/v2.5/yarn.lock
Labels: improvement

#5542 Use Marker endSeconds value when generating previews
  internal/manager/task_generate_markers.go
  pkg/scene/generate/marker_preview.go
Labels: improvement

#5567 Find scene markers by ID
  graphql/schema/schema.graphql
  internal/api/resolver_query_find_scene_marker.go
Labels: feature

#5578 Fix Handy script not playing after revisiting scene
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: bug

#5581 Automatically resync Handy
  ui/v2.5/src/hooks/Interactive/context.tsx
Labels: improvement

#5636 Weblate translation update
  ui/v2.5/src/App.tsx
  ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx
  ui/v2.5/src/locales/README.md
  ui/v2.5/src/locales/cs-CZ.json
  ui/v2.5/src/locales/de-DE.json
  ui/v2.5/src/locales/en-US.json
  ui/v2.5/src/locales/es-ES.json
  ui/v2.5/src/locales/et-EE.json
  ui/v2.5/src/locales/fr-FR.json
  ui/v2.5/src/locales/hi-IN.json
  ui/v2.5/src/locales/index.ts
  ui/v2.5/src/locales/ja-JP.json
  ui/v2.5/src/locales/ko-KR.json
  ui/v2.5/src/locales/lv-LV.json
  ui/v2.5/src/locales/nb-NO.json
  ui/v2.5/src/locales/nl-NL.json
  ui/v2.5/src/locales/nn-NO.json
  ui/v2.5/src/locales/pl-PL.json
  ui/v2.5/src/locales/sk-SK.json
  ui/v2.5/src/locales/sv-SE.json
  ui/v2.5/src/locales/tr-TR.json
  ui/v2.5/src/locales/uk-UA.json
  ui/v2.5/src/locales/vi-VN.json
  ui/v2.5/src/locales/zh-CN.json
  ui/v2.5/src/locales/zh-TW.json
Labels: chore
