Repository stashapp/stash, pull requests merged in 2025-09, with the labels that each got.

#6031 Add media hardware key support
  ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx
Labels: improvement

#6023 exclude empty regex exclude
  internal/manager/exclude_files.go
Labels: bug

#6073 Allow scan to continue when encountering an error
  pkg/file/folder_rename_detect.go
Labels: bug

#6012 Add gallery link to image lightbox
  ui/v2.5/src/core/files.ts
  ui/v2.5/src/core/galleries.ts
  ui/v2.5/src/hooks/Lightbox/Lightbox.tsx
  ui/v2.5/src/hooks/Lightbox/lightbox.scss
  ui/v2.5/src/hooks/Lightbox/types.ts
Labels: improvement

#6006 Treat images with no exif metadata as well-oriented
  pkg/file/image/orientation.go
Labels: bug

#6087 Fix descender line-height
  ui/v2.5/src/index.scss
Labels: bug

#6095 Add search term filter tag to scene list filter tags
  ui/v2.5/src/components/List/FilterTags.tsx
  ui/v2.5/src/components/List/Filters/FilterSidebar.tsx
  ui/v2.5/src/components/List/util.ts
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Scenes/styles.scss
  ui/v2.5/src/index.scss
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/utils/focus.ts
Labels: improvement, ui

#6077 Add separate sidebar toggle button
  ui/v2.5/src/components/List/FilterTags.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Scenes/styles.scss
Labels: improvement, ui

#6102 Refactor issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/discussion---request-for-commentary--rfc-.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: chore

#6101 Wall item height fix
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/components/Images/ImageWallItem.tsx
  ui/v2.5/src/components/Scenes/SceneMarkerWallPanel.tsx
  ui/v2.5/src/components/Scenes/SceneWallPanel.tsx
Labels: bug
