Repository stashapp/stash, pull requests merged in 2025-03, with the labels that each got.

#5691 Fix code comment in config.go [skip-ci]
  pkg/scraper/config.go
Labels: chore

#5695 Add FileSize component and refactor file size rendering in various components
  ui/v2.5/src/components/Images/ImageDetails/ImageFileInfoPanel.tsx
  ui/v2.5/src/components/Images/ImageList.tsx
  ui/v2.5/src/components/SceneDuplicateChecker/SceneDuplicateChecker.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneFileInfoPanel.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Scenes/SceneListTable.tsx
  ui/v2.5/src/components/Shared/FileSize.tsx
  ui/v2.5/src/components/Stats.tsx
Labels: bug

#5697 Use existing formats for saved filters
  ui/v2.5/src/components/List/SavedFilterList.tsx
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
  ui/v2.5/src/models/list-filter/criteria/custom-fields.ts
  ui/v2.5/src/models/list-filter/criteria/rating.ts
  ui/v2.5/src/models/list-filter/criteria/stash-ids.ts
  ui/v2.5/src/models/list-filter/filter.ts
  ui/v2.5/src/models/list-filter/types.ts
Labels: bug

#5698 Weblate translation update
  ui/v2.5/src/locales/de-DE.json
  ui/v2.5/src/locales/et-EE.json
  ui/v2.5/src/locales/fa-IR.json
  ui/v2.5/src/locales/fi-FI.json
  ui/v2.5/src/locales/fr-FR.json
  ui/v2.5/src/locales/sv-SE.json
  ui/v2.5/src/locales/tr-TR.json
  ui/v2.5/src/locales/zh-CN.json
Labels: chore

#5110 Performer select calculated ages
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryEditPanel.tsx
  ui/v2.5/src/components/Galleries/GalleryDetails/GalleryScrapeDialog.tsx
  ui/v2.5/src/components/Images/ImageDetails/ImageEditPanel.tsx
  ui/v2.5/src/components/Performers/PerformerSelect.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneEditPanel.tsx
  ui/v2.5/src/components/Scenes/SceneDetails/SceneScrapeDialog.tsx
  ui/v2.5/src/components/Scenes/SceneMergeDialog.tsx
  ui/v2.5/src/components/Shared/ScrapeDialog/ScrapedObjectsRow.tsx
  ui/v2.5/src/components/Tagger/scenes/PerformerResult.tsx
  ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx
  ui/v2.5/src/components/Tagger/styles.scss
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#5712 Replace history when merging tag
  ui/v2.5/src/components/Tags/TagDetails/TagMergeDialog.tsx
Labels: bug

#5721 docker documentation update
  docker/production/README.md
  docker/production/docker-compose.yml
Labels: documentation

#5722 Stash scraper scene query
  pkg/scraper/stash.go
  ui/v2.5/src/docs/en/Manual/ScraperDevelopment.md
Labels: improvement

#5727 Patchable ExternalLinkButtons component
  ui/v2.5/src/components/Groups/GroupDetails/Group.tsx
  ui/v2.5/src/components/Shared/ExternalLinksButton.tsx
  ui/v2.5/src/docs/en/Manual/UIPluginApi.md
  ui/v2.5/src/pluginApi.d.ts
  ui/v2.5/src/pluginApi.tsx
Labels: improvement

#5708 Add sort by scene code option
  pkg/sqlite/scene.go
  ui/v2.5/src/models/list-filter/scenes.ts
Labels: improvement

#5732 Improve UI loadable components
  ui/v2.5/src/docs/en/Manual/UIPluginApi.md
  ui/v2.5/src/pluginApi.tsx
Labels: improvement

#5723 Fix various migration issues
  internal/manager/task/migrate.go
  pkg/sqlite/database.go
  pkg/sqlite/migrate.go
Labels: bug

#5733 Remove duplicates from ScrapedTagsRow
  ui/v2.5/src/components/Shared/ScrapeDialog/ScrapedObjectsRow.tsx
Labels: bug

#5734 Update weblate translations
  ui/v2.5/src/locales/ca-ES.json
  ui/v2.5/src/locales/cs-CZ.json
  ui/v2.5/src/locales/es-ES.json
  ui/v2.5/src/locales/fi-FI.json
  ui/v2.5/src/locales/fr-FR.json
  ui/v2.5/src/locales/ja-JP.json
  ui/v2.5/src/locales/nb-NO.json
  ui/v2.5/src/locales/nl-NL.json
  ui/v2.5/src/locales/ro-RO.json
  ui/v2.5/src/locales/ru-RU.json
  ui/v2.5/src/locales/sv-SE.json
  ui/v2.5/src/locales/uk-UA.json
  ui/v2.5/src/locales/zh-CN.json
Labels: chore

#5742 Fix setFromSavedCriterion for TimestampCriterion
  ui/v2.5/src/models/list-filter/criteria/criterion.ts
Labels: bug

#5744 Parse scene t value as number not int
  ui/v2.5/src/components/Scenes/SceneDetails/Scene.tsx
Labels: bug

#5747 Refactor login page to not include in history
  internal/api/session.go
  ui/login/login.html
Labels: bug

#5713 Optimise card width calculation
  ui/v2.5/src/components/Galleries/GalleryCard.tsx
  ui/v2.5/src/components/Galleries/GalleryGridCard.tsx
  ui/v2.5/src/components/Groups/GroupCard.tsx
  ui/v2.5/src/components/Groups/GroupCardGrid.tsx
  ui/v2.5/src/components/Images/ImageCard.tsx
  ui/v2.5/src/components/Images/ImageGridCard.tsx
  ui/v2.5/src/components/Performers/PerformerCard.tsx
  ui/v2.5/src/components/Performers/PerformerCardGrid.tsx
  ui/v2.5/src/components/Scenes/SceneCard.tsx
  ui/v2.5/src/components/Scenes/SceneCardsGrid.tsx
  ui/v2.5/src/components/Scenes/SceneMarkerCard.tsx
  ui/v2.5/src/components/Scenes/SceneMarkerCardsGrid.tsx
  ui/v2.5/src/components/Shared/GridCard/GridCard.tsx
  ui/v2.5/src/components/Studios/StudioCard.tsx
  ui/v2.5/src/components/Studios/StudioCardGrid.tsx
  ui/v2.5/src/components/Tags/TagCard.tsx
  ui/v2.5/src/components/Tags/TagCardGrid.tsx
Labels: chore

#5699 Refactor stashbox package
  gqlgen.yml
  internal/api/resolver.go
  internal/api/resolver_mutation_stash_box.go
  internal/api/resolver_query_scraper.go
  internal/api/scraped_content.go
  internal/api/stash_box.go
  internal/identify/identify.go
  internal/identify/identify_test.go
  internal/identify/scene_test.go
  internal/manager/repository.go
  internal/manager/task_identify.go
  internal/manager/task_stash_box_tag.go
  pkg/match/scraped.go
  pkg/models/fingerprint.go
  pkg/models/model_scraped_item.go
  pkg/scene/find.go
  pkg/scene/fingerprints.go
  pkg/scraper/action.go
  pkg/scraper/autotag.go
  pkg/scraper/gallery.go
  pkg/scraper/group.go
  pkg/scraper/image.go
  pkg/scraper/json.go
  pkg/scraper/mapped.go
  pkg/scraper/postprocessing.go
  pkg/scraper/query_url.go
  pkg/scraper/scene.go
  pkg/scraper/scraper.go
  pkg/scraper/script.go
  pkg/scraper/stash.go
  pkg/scraper/stashbox/client.go
  pkg/scraper/stashbox/models.go
  pkg/scraper/stashbox/scene.go
  pkg/scraper/xpath.go
  pkg/sliceutil/collections.go
  pkg/stashbox/client.go
  pkg/stashbox/draft.go
  pkg/stashbox/graphql/generated_client.go
  pkg/stashbox/graphql/generated_models.go
  pkg/stashbox/graphql/override.go
  pkg/stashbox/performer.go
  pkg/stashbox/scene.go
  pkg/stashbox/studio.go
Labels: chore

#5760 Add IP address to login errors
  internal/api/session.go
Labels: improvement

#5770 docs: update Configuration wording
  ui/v2.5/src/docs/en/Manual/Configuration.md
Labels: documentation

#5764 Add rate limit to stashbox connection
  go.mod
  go.sum
  graphql/schema/types/stash-box.graphql
  internal/api/stash_box.go
  internal/manager/config/config.go
  internal/manager/task_identify.go
  internal/manager/task_stash_box_tag.go
  pkg/models/stash_box.go
  pkg/stashbox/client.go
  ui/v2.5/graphql/data/config.graphql
  ui/v2.5/src/components/Settings/StashBoxConfiguration.tsx
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#5765 Login page internationalisation
  .gitignore
  Makefile
  docker/build/x86_64/Dockerfile
  docker/build/x86_64/Dockerfile-CUDA
  docker/build/x86_64/README.md
  internal/api/server.go
  internal/api/session.go
  scripts/generateLoginLocales.go
  ui/login/login.html
  ui/ui.go
  ui/v2.5/src/locales/en-GB.json
Labels: improvement

#5767 Refactor scene list to not use ItemList component
  ui/v2.5/src/components/Groups/GroupDetails/GroupScenesPanel.tsx
  ui/v2.5/src/components/List/EditFilterDialog.tsx
  ui/v2.5/src/components/List/FilteredListToolbar.tsx
  ui/v2.5/src/components/List/ItemList.tsx
  ui/v2.5/src/components/List/ListProvider.tsx
  ui/v2.5/src/components/List/util.ts
  ui/v2.5/src/components/Performers/PerformerDetails/PerformerScenesPanel.tsx
  ui/v2.5/src/components/Scenes/SceneList.tsx
  ui/v2.5/src/components/Studios/StudioDetails/StudioScenesPanel.tsx
  ui/v2.5/src/components/Tags/TagDetails/TagScenesPanel.tsx
Labels: chore

#5776 Add tag count to studio sort whitelist
  pkg/sqlite/studio.go
Labels: bug

#5777 Add marker end seconds import/export
  internal/manager/task_import.go
  pkg/models/jsonschema/scene.go
  pkg/scene/export.go
  pkg/scene/marker_import.go
Labels: bug
